### ISSUE TITLE
100% CPU from animation

### ISSUE THREAD

**Issue by KalisaFalzone** [Zamiell/hanabi-live#1003]
I was looking into the code a bit and it looks like the animation for "Your Turn" is reanimating constantly in the background even when it is hidden. 

I started looking into this when my computer got really hot playing hanabi a couple days ago. 

in this file: https://github.com/Zamiell/hanabi-live/blob/d78c5f6097746f4c132a230bf4e15252f970327f/public/js/src/game/ui/drawUI.ts#L1117-L1133

This check will always be true since `text` and `yourTurnTween` both always exist.

```js
      if (text && yourTurnTween)
```
 I'm not sure what variable you have that determines if it is someone's turn. Maybe `global.ourTurn`?

Hope this is helpful.

**Comment by Zamiell** [comment]
should be fixed now. maybe
4a561d198061fd5b0aff9254420693b5d6487e6c
reopen a new issue if it still gets 100% cpu or whatever

**Comment by KalisaFalzone** [comment]
Cool, will watch for it. Thank you!
