### ISSUE TITLE
Empathy broken in 	Light-Pink-Fives & Muddy Rainbow

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#1004]
my purple card was not touched by the yellow clue but the empathy shows it could be a muddy rainbow card

![e](https://user-images.githubusercontent.com/50160641/80961876-73caab80-8e3e-11ea-8699-f211da3f0329.png)

**Comment by padiwik** [comment]
We had the same issue here https://hanabi.live/replay/158643/34 . The blues were not touched by the  green clue earlier and should be known blue. Likewise, the green 5 was not touched by the blue clue and should be known green.

**Comment by Zamiell** [comment]
should be fixed now, reopen if not
