### ISSUE TITLE
nonexistent tables after restart

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1010]
every time the game restarts, i get the same message
![2020-05-05_22-55-38](https://user-images.githubusercontent.com/46625461/81111076-237a4900-8f25-11ea-93a1-09b6bea262b0.png)
<img width="959" alt="2020-05-05_00-21-29" src="https://user-images.githubusercontent.com/46625461/81111081-24ab7600-8f25-11ea-91d6-46dbe82b80bc.png">

**Comment by Zamiell** [comment]
i think this will be fixed after the next time the server restarts, i made a lot of changes

**Comment by Zamiell** [comment]
should be fixed now
