### ISSUE TITLE
Download the Data

### ISSUE THREAD

**Issue by gongzhitaao** [Zamiell/hanabi-live#1011]
Hey Zamiell,

Thank you for the server, it is a lot of fun.

I have two questions:
1. Is it possible to download the play data somehow? Or are you considering open-sourcing the *all* the replay as a dataset? It will be a really interesting dataset for RL.
2. If I want to hook a HanabiBot, i.e., a program, to interact with the game, is it possible?

Generally I'm thinking about training an RL agent to play the game.

**Comment by Zamiell** [comment]
1) no, the data is not available, i only provide it upon special request
2) see https://github.com/Zamiell/hanabi-live-bot
