### ISSUE TITLE
note popup does not disappear when card is played

### ISSUE THREAD

**Issue by tyrcho** [Zamiell/hanabi-live#1012]
![image](https://user-images.githubusercontent.com/700260/81120589-56283f80-8f2d-11ea-9c69-4296fc39ca97.png)

**Comment by tyrcho** [comment]
I think it disappeared when I used the replay, not a big deal

**Comment by Zamiell** [comment]
if your computer lags note popups might stay on the screen when they are not supposed to. you can press esc to fix it usually
