### ISSUE TITLE
special mix: broken empathy

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1013]
both m3 are visible
![2020-05-06_20-41-48](https://user-images.githubusercontent.com/46625461/81210414-85e15100-8fda-11ea-9e20-06a0de13493b.png)

**Comment by Zamiell** [comment]
what exactly is broken in this screenshot

**Comment by padiwik** [comment]
The marked 3s in Valetta's hand cannot be multi because she sees both multi 3s. The multi color should be crossed off with a black X, probably.

**Comment by Aigul9** [comment]
the same thing in light pink & gray: 5 cannot be green or blue
![2020-05-07_23-46-07](https://user-images.githubusercontent.com/46625461/81370232-4e1efa00-90fd-11ea-933a-708fb5e9e1c3.png)

**Comment by Zamiell** [comment]
should be fixed now, reopen if not
