### ISSUE TITLE
friends do not highlight while they are spectating

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1023]
![image](https://user-images.githubusercontent.com/46625461/81479800-51fe6980-922e-11ea-8add-5bada9d143e3.png)

**Comment by Aigul9** [comment]
and this lobby is not above others

**Comment by Zamiell** [comment]
> and this lobby is not above others
what does this mean

**Comment by Aigul9** [comment]
>Games that contain one or more of your friends will be sorted at the top of the games list.
Should it apply to the games which my friends spectate?

**Comment by Zamiell** [comment]
yes

you should see this on next server restart
(tomorrow sometime)
