### ISSUE TITLE
Escape key does not close warnings/errors

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1026]
When a warning/error pops up on the screen, it should be possible to close it with the keyboard like other elements of the UI. However, it is not focused which means the Enter key will act on the chat rather than the warning/error. The Escape key reverts the dimming of the background but does not close the warning/error.

**Comment by Zamiell** [comment]
done

**Comment by Zamiell** [comment]
you can close warnings but not errors, because we want to force the user to refresh the page

**Comment by padiwik** [comment]
needs to be fixed in game as well

**Comment by padiwik** [comment]
in-game, the warning closes but the dimming shade does not with "esc" key

in a shared replay, the "esc" key also brings you to the lobby which is probably undesired when a warning is up

---

also, possibly related, to investigate: warnings from the Create Game tooltip have a weird flicker effect in the dimming background
