### ISSUE TITLE
Game didn't finish when all playable cards were discarded

### ISSUE THREAD

**Issue by Ten0** [Zamiell/hanabi-live#1030]
Game #160445 didn't finish when all left playable cards were discarded.
Note that there was a server restart during the game, where we reconnected to the game, and I suspect that's what caused the issue.

**Comment by Zamiell** [comment]
do you remember at what exact turn the server restarted?

**Comment by Zamiell** [comment]
it doesn't seem to happen when the server doesn't restart

**Comment by Ten0** [comment]
Unfortunately no but I would imagine this can be reproduced by restarting after having discarded the second 4.

**Comment by Zamiell** [comment]
can't reproduce, even after killing the server and rejoining on turn 59. if you can reproduce it, let me know. I will close for now since it seems to be a minor thing
