### ISSUE TITLE
Broken empathy: White-ones and Cocoa Rainbow

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1033]
https://hanabi.live/replay/161965/11
red 2 and 5 in my hand could be only red (they weren't touched by green t2)
g4 - only green (purple t18)
b24 in fireheart's - only blue (red t19)
y34 - only yellow (green and blue t33, 39)

**Comment by padiwik** [comment]
Dupe of #1004 which I already have the fix for

**Comment by Zamiell** [comment]
should be fixed now, reopen if not
