### ISSUE TITLE
add table id to NotifyYourTurn

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#1040]
Currently the "yourTurn" command that is sent to the client contains no data. For normal users this is currently fine because they are only allowed to be in 1 game at a time, but bots need to know which table they can react to.

**Comment by Zamiell** [comment]
thats not necessary because bots can already tell it is their turn from the turn command

**Comment by RaKXeR** [comment]
for posterity, here's the commit that adds the table id to NotifyYourTurn https://github.com/Zamiell/hanabi-live/commit/18a8488c8c6f6a6dc9a1307f2007ccb44c1cf967
