### ISSUE TITLE
Was wondering about the orange borders

### ISSUE THREAD

**Issue by hauntsaninja** [Zamiell/hanabi-live#1047]
Hello! Thank you so much for hanabi.live and for all the things you've done to help share and promote the game :-)

While playing today we noticed that the border colour for clued cards was changed from orange to black, and were wondering why, since it seems to be a much less prominent visual cue.

**Comment by Zamiell** [comment]
im testing to see if black is easier to see

**Comment by iamwhoiamhahaha** [comment]
how about black for old clued cards and orange/yellow for new-introduced cards

**Comment by Zamiell** [comment]
i think i would prefer to keep it simple

**Comment by iamwhoiamhahaha** [comment]
that would be nice if we have two colors so that we can easily see which card is the focus without checking the replay

**Comment by Zamiell** [comment]
you can already tell which card is the focus by looking at the arrows

**Comment by iamwhoiamhahaha** [comment]
no sometimes the clue touches old cards (slot 5, for example) and new cards (slot 1, for example) at the same time. by looking at the arrows the focus is on slot 5. however, the real focus is on slot 1, which is the brand-new card.

that would be nice if the border remains the same on slot 5 (black border) and the brand-new card has yellow border in this case

**Comment by Zamiell** [comment]
> no sometimes the clue touches old cards (slot 5, for example) and new cards (slot 1, for example) at the same time. by looking at the arrows the focus is on slot 5. however, the real focus is on slot 1, which is the brand-new card.

no, this is not true. look at the arrows more closely

**Comment by iamwhoiamhahaha** [comment]
ohh i see. gray arrows and white arrows

**Comment by Zamiell** [comment]
honestly im surprised you have been playing for a year and never noticed this

**Comment by iamwhoiamhahaha** [comment]
i'm also surprised i haven't noticed that until now lmao. (but i've noticed that in duck, it's clear though)

**Comment by Zamiell** [comment]
yeah maybe we should come up for a design for different arrows. i thought about it before though and not many things look good. e.g. i tried white and black arrows and its disgusting

**Comment by Zamiell** [comment]
you can use mspaint and do a mockup of something

**Comment by iamwhoiamhahaha** [comment]
the arrows are fine but maybe we can change the border to make it clearer.

(honestly i feel i'm so stupid that i haven't notice that. i guess i'm totally blind... sometimes i needs to check in the replay to make sure which cards are new introduced... but tbh, probably it is not a very good feature, since it is not clear. but probably only i have this problem)

**Comment by padiwik** [comment]
I've noticed it sometimes, said "huh cool", and still always check in the replay

**Comment by NoAnni** [comment]
What about having 2/3 different colours for clued cards? (let's say orange for colour clues, black for numbers, green for both). It would be useful when you want to give a finesse and don't notice that there's a card that would be prompted instead.

**Comment by Zamiell** [comment]
what colors though. every color overlaps with a suit, except for black and orange.

**Comment by Zamiell** [comment]
gonna make them Halloween borders in the next update
