### ISSUE TITLE
#25 Synesthetic

### ISSUE THREAD

**Issue by Worteltwee** [Zamiell/hanabi-live#1048]
In Detrimental Characters, the character #25 Synesthetic seems to be quite bugged. We played 2 games. In the first game someone clued 1 but there were no red cards to be clued, which breaks the game since that player cannot do anything anymore. In the second game, after this character gave a clue, he was forced to give clues for the rest of the game, also obviously breaking the game.

I recommend just deleting this character, I don't even think it is actually detrimental.

**Comment by Zamiell** [comment]
agreed, i deleted it. thanks
