### ISSUE TITLE
Colorless

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#1060]
it happens when the card got all the negative color information (except its own color clue)

before receiving red clue
![before](https://user-images.githubusercontent.com/50160641/82134270-ccc81580-9828-11ea-9ba2-680093d645e2.png)

after receiving red clue
![after](https://user-images.githubusercontent.com/50160641/82134272-ce91d900-9828-11ea-9884-beb606a66ec5.png)

**Comment by Zamiell** [comment]
should be fixed after next restart
