### ISSUE TITLE
Global parameters for Special-Ones/Fives

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1062]
Currently, the logic is hard-coded based on the variant name. This is bad. We should have some parameters defined in variants.json that give the properties of the special rank:

* `specialRank` - should be 1 or 5 depending on which rank is special, and some other value (UNKNOWN_CARD_RANK ?) for normal variant
* `specialAllClueRanks` - boolean, analogous to `suit.allClueRanks` but it applies to the special-ones/fives
* `specialNoClueRanks`, `specialAllClueColors`, `specialNoClueColors` analogously

**Comment by Zamiell** [comment]
done
