### ISSUE TITLE
Notes can look weird on high resolution screens

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1064]
In this game https://hanabi.live/replay/170433 , when my window is close to full size the note on Livia's g2 looks empty and has scroll bars all around it, as if the element is too zoomed in. The note on the navy 3 is normal.

![note](https://user-images.githubusercontent.com/24983586/82162976-1723b380-9876-11ea-8717-f639f65c9c0c.png)

When i shrink down the window, it looks like a normal note with `5pull?` written on it.

**Comment by Zamiell** [comment]
i dont have a 4K monitor or whatever so i dont really know how to fix this
try to investigate and submit a pull request

**Comment by Zamiell** [comment]
i can't reproduce, and i don't plan to do anything to fix this, it is probably just a limitation of the tooltip library on linux. feel free to submit a PR
