### ISSUE TITLE
Error when drawing start cards

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1066]
> Uncaught Error: The image "card-Unknown-7" was not generated.

because START_CARD_RANK = 7 ....

This breaks basically the entire game. Happens when a start card in Up or Down receives negative all ranks 1 to 5, which granted is very edge-case.

**Comment by Zamiell** [comment]
oh nice find!

**Comment by Zamiell** [comment]
i will just draw that card image then

**Comment by Zamiell** [comment]
can you test on master now and see if it is fixed

**Comment by padiwik** [comment]
Nope, not fixed. It's fine when drawing a fully known start card but not an unknown-suit start card

**Comment by padiwik** [comment]
Fixed
