### ISSUE TITLE
game #14221 fails at index 54

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1069]

**Comment by Zamiell** [comment]
its because misplays were counted as discards for some reason.
just going to delete the game because im too lazy to load old versions of the database and program a programmatic solution

**Comment by rogers-j** [comment]
It wasn't nonsense; a misplay is a strike + the action of putting the card in the discard pile instead of getting a clue + putting it in the discard pile

**Comment by Zamiell** [comment]
right, the discard action has a field of `"failed": true`, and i thought i correctly integrated this over to the new format when i made a script to convert all of the old games, but apparently i missed some edge case

**Comment by padiwik** [comment]
yeah, it's because old games didn't have this `"failed"` field

**Comment by Zamiell** [comment]
oh, that makes sense then, so that is the cause of the bug
