### ISSUE TITLE
if I have a note, say "Y3" on a card, and then I get a "3" clue on some other card (thus getting negative 3 on the card with the note), the card is still displayed as Y3

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1070]

**Comment by SashaIr** [comment]
Notice that it is not the case if I add the note *after* getting the clue: in that case, I get a popup saying "This card cannot possibly be a 3" and even if I keep the note, the card is not displayed as Y3, as expected.

**Comment by Zamiell** [comment]
unable to reproduce, provide steps to reproduce

**Comment by SashaIr** [comment]
I literally opened a game, marked a non-5 as a 5, got a 5 clue, the other card is still marked as a 5.

**Comment by Zamiell** [comment]
> I literally opened a game, marked a non-5 as a 5, got a 5 clue, the other card is still marked as a 5.

i do the same thing and it works as expected

**Comment by Zamiell** [comment]
can you try again now that ive rebooted the server?

**Comment by Zamiell** [comment]
oh i see it only happens if you mark it as 5 without g5

**Comment by Zamiell** [comment]
so your original description of the issue was inaccurate =p

**Comment by SashaIr** [comment]
Sorry about that, I assumed it worked the same way. "Y3" and "3Y" seem to work properly, but "3" and "Y" do not.

**Comment by Zamiell** [comment]
fixed, refresh the page 3 minutes from now
