### ISSUE TITLE
go through variants script and add special suits to every subvariant that is missing

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1074]

**Comment by jakestiles** [comment]
Not sure if this is related enough, but (thank you for adding Reversed and) I would like to see it implemented in combination with other variants such as Black Reversed and Rainbow Reversed and White Reversed (doesn't have to be all the variants but these more basic ones would be a great addition).

**Comment by robertos** [comment]
@jakestiles That is #1119

**Comment by Zamiell** [comment]
done
