### ISSUE TITLE
Empathy Glitch

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1075]
![2020-05-18_1754](https://user-images.githubusercontent.com/48993588/82273036-359ab500-9931-11ea-9742-069328c271d2.png)
![2020-05-18_1754_001](https://user-images.githubusercontent.com/48993588/82273038-37647880-9931-11ea-9faa-db1282839719.png)

Ok empathy glitch, the cards are pink and it shows the pink icon during game.  Idk why it isn't showing the pink icon in the review. 

Anyways the Gui is showing i1 directly by highlighting it in pink

**Comment by Dr-Kakashi** [comment]
![2020-05-18_1906_001](https://user-images.githubusercontent.com/48993588/82276732-efe2ea00-993a-11ea-8b66-f95b8b194ae6.png)
![2020-05-18_1906](https://user-images.githubusercontent.com/48993588/82276736-f2454400-993a-11ea-8852-331aa1a1b816.png)

Situation where no clues given to i1

**Comment by Dr-Kakashi** [comment]
![2020-05-19_1429](https://user-images.githubusercontent.com/48993588/82380391-3be66b00-99dd-11ea-8d76-483d9d252db3.png)

It's happening to null cards as well

**Comment by Zamiell** [comment]
should be fixed after next server restart
