### ISSUE TITLE
Small typo in 2-player conventions

### ISSUE THREAD

**Issue by katalystar** [Zamiell/hanabi-live#1081]
Hi! I think I noticed a small typo in the 2-player conventions guide: "give a" is repeated in the sentence (see below).

https://github.com/Zamiell/hanabi-conventions/blob/master/misc/2-Player.md

Second Turn Stalls
If a Save Clue was given to a chop card on the first turn of the game, then the next player is not allowed to discard. They must instead **give a give a** stall clue. (Otherwise, they are allowed to discard.)

**Comment by Zamiell** [comment]
this is the repository for the website, please reopen the issue in the correct repository
