### ISSUE TITLE
Page showing abbreviations

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1084]
Any chance we can get a page that says what all the abbreviations for the colors are?

R - Red
B - Blue
G - Green
N - Brown
....etc?

For example what is cocoa rainbow?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/blob/master/public/js/src/data/colors.json
https://github.com/Zamiell/hanabi-live/blob/master/public/js/src/data/suits.json

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/3f7584489204b96d2ca4f7ae987cf581104b9391
