### ISSUE TITLE
Vindictive (detrimental character) bug

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1086]
game 172704: I have been clued only once in the whole game, and gave 8-9 clues in a row after that, but when I was left with 0 clues we still lost. Given that an instant loss happened to me unexpectedly with a different detrimental character at 0 clues, is it possible that the game checks only for 0 clues, and not for whether or not the character is forced to clue on that turn?

**Comment by Zamiell** [comment]
this is already fixed, i will restart the server so that it has the latest code, and it shouldn't happen anymore
