### ISSUE TITLE
Empathy bug in light pink & dark brown

### ISSUE THREAD

**Issue by zsole2** [Zamiell/hanabi-live#1087]
![Screenshot from 2020-05-21 21-57-17](https://user-images.githubusercontent.com/11209960/82600647-83702100-9bae-11ea-9e2a-95bde6c98c55.png)

The missing dark brown card is the 5, but slot 5 shows possibilities of 1, 2, and 5.

**Comment by padiwik** [comment]
Could you go to endpoint /export/1983 and paste the json data for this game? I would like to test whether this was fixed in recent commits.

**Comment by Zamiell** [comment]
you're asking me?

**Comment by padiwik** [comment]
No, I'm asking @zsole2 since this game seems to have been played on a private server

**Comment by Zamiell** [comment]
oh

**Comment by zsole2** [comment]
I should have thought about this, sorry.
Here it is:

```{"id":1983,"players":["zsole2","Ercsi"],"deck":[{"suit":3,"rank":1},{"suit":1,"rank":2},{"suit":1,"rank":5},{"suit":0,"rank":2},{"suit":2,"rank":5},{"suit":3,"rank":4},{"suit":0,"rank":1},{"suit":2,"rank":1},{"suit":3,"rank":4},{"suit":3,"rank":2},{"suit":2,"rank":4},{"suit":1,"rank":1},{"suit":4,"rank":4},{"suit":5,"rank":2},{"suit":1,"rank":1},{"suit":5,"rank":5},{"suit":4,"rank":1},{"suit":3,"rank":5},{"suit":1,"rank":4},{"suit":2,"rank":2},{"suit":1,"rank":3},{"suit":2,"rank":2},{"suit":5,"rank":3},{"suit":2,"rank":4},{"suit":4,"rank":3},{"suit":4,"rank":3},{"suit":3,"rank":3},{"suit":2,"rank":1},{"suit":0,"rank":5},{"suit":0,"rank":1},{"suit":0,"rank":1},{"suit":5,"rank":1},{"suit":3,"rank":3},{"suit":4,"rank":5},{"suit":1,"rank":1},{"suit":0,"rank":2},{"suit":3,"rank":2},{"suit":0,"rank":4},{"suit":4,"rank":1},{"suit":4,"rank":2},{"suit":4,"rank":1},{"suit":0,"rank":4},{"suit":2,"rank":1},{"suit":2,"rank":3},{"suit":3,"rank":1},{"suit":2,"rank":3},{"suit":5,"rank":4},{"suit":1,"rank":2},{"suit":4,"rank":2},{"suit":0,"rank":3},{"suit":4,"rank":4},{"suit":1,"rank":3},{"suit":3,"rank":1},{"suit":1,"rank":4},{"suit":0,"rank":3}],"actions":[{"type":3,"target":1,"value":1},{"type":2,"target":0,"value":3},{"type":0,"target":0,"value":0},{"type":3,"target":0,"value":2},{"type":3,"target":1,"value":2},{"type":3,"target":0,"value":5},{"type":1,"target":10,"value":0},{"type":2,"target":0,"value":1},{"type":0,"target":11,"value":0},{"type":0,"target":6,"value":0},{"type":0,"target":1,"value":0},{"type":0,"target":7,"value":0},{"type":0,"target":3,"value":0},{"type":0,"target":9,"value":0},{"type":2,"target":1,"value":3},{"type":0,"target":5,"value":0},{"type":2,"target":1,"value":4},{"type":1,"target":18,"value":0},{"type":2,"target":1,"value":2},{"type":0,"target":19,"value":0},{"type":2,"target":1,"value":1},{"type":0,"target":20,"value":0},{"type":1,"target":12,"value":0},{"type":1,"target":21,"value":0},{"type":3,"target":1,"value":4},{"type":0,"target":17,"value":0},{"type":1,"target":14,"value":0},{"type":1,"target":24,"value":0},{"type":2,"target":1,"value":3},{"type":3,"target":0,"value":1},{"type":0,"target":16,"value":0},{"type":2,"target":0,"value":4},{"type":1,"target":27,"value":0},{"type":0,"target":26,"value":0},{"type":1,"target":28,"value":0},{"type":0,"target":8,"value":0},{"type":2,"target":1,"value":4},{"type":0,"target":31,"value":0},{"type":2,"target":1,"value":4},{"type":0,"target":13,"value":0},{"type":1,"target":30,"value":0},{"type":2,"target":0,"value":4},{"type":0,"target":22,"value":0},{"type":1,"target":29,"value":0},{"type":1,"target":34,"value":0},{"type":1,"target":32,"value":0},{"type":3,"target":1,"value":5},{"type":1,"target":36,"value":0},{"type":3,"target":1,"value":2},{"type":0,"target":39,"value":0},{"type":1,"target":35,"value":0},{"type":3,"target":0,"value":3},{"type":0,"target":25,"value":0},{"type":1,"target":40,"value":0},{"type":2,"target":1,"value":2},{"type":0,"target":43,"value":0},{"type":1,"target":37,"value":0},{"type":3,"target":0,"value":4},{"type":1,"target":42,"value":0},{"type":0,"target":23,"value":0},{"type":0,"target":4,"value":0},{"type":2,"target":0,"value":4},{"type":0,"target":46,"value":0},{"type":2,"target":0,"value":0},{"type":0,"target":49,"value":0},{"type":0,"target":15,"value":0},{"type":0,"target":41,"value":0},{"type":3,"target":0,"value":4},{"type":0,"target":50,"value":0},{"type":2,"target":0,"value":1},{"type":0,"target":53,"value":0},{"type":0,"target":33,"value":0},{"type":0,"target":2,"value":0}],"options":{"variant":"Light Pink \u0026 Dark Brown (6 Suits)"}}```

**Comment by padiwik** [comment]
Thanks, this was indeed fixed by #1149

**Comment by zsole2** [comment]
Thanks, I'll do an update  soon and check this.

**Comment by Zamiell** [comment]
ok, gonna close this now then
