### ISSUE TITLE
some older replays are unable to replay the actions

### ISSUE THREAD

**Issue by hauntsaninja** [Zamiell/hanabi-live#1104]
While attempting to view Game ID 2974, I get the following error:
`The action at index 67 was not valid. Skipping all subsequent actions. Please report this error to an administrator.`

**Comment by Zamiell** [comment]
there's a bunch of old games that are apparently bugged, ill try to fix it at some point

(this shouldn't happen with any newer games)

**Comment by Zamiell** [comment]
also happens in 2935 (deck play)

**Comment by padiwik** [comment]
For the very old games, could the problem be the hands are in the wrong order? When I open the examples given here (https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-certain-discard-duplication-promise), I see some highly illegal clues which also don't match the notes on the cards. These seem like good games to figure out what exactly went wrong.

**Comment by padiwik** [comment]
* 2974 and 2935 are deck misplays. 2935 is funny because the game didn't end when no more cards could play, i guess it wasn't coded back then
* 21606 hard crashes on the old code (Mar 31 2020):
```main.min.js:283 Uncaught TypeError: Cannot read property 'length' of undefined
    at main.min.js:283
    at e.a (main.min.js:283)
    at Object.f (main.min.js:7)
    at main.min.js:2392
    at Object.notifyList (main.min.js:2392)
    at n.onMessage (main.min.js:2392)```
* The games I linked (6817, 6799) are other examples of suits swapping order, which I'm trying to fix now

**Comment by Zamiell** [comment]
padi also copypaste the git commit hash that you are testing on

**Comment by padiwik** [comment]
bd3bfd6c

**Comment by padiwik** [comment]
game 21606:
```
| 5039811 |   21606 | {"type":"clue","clue":{"type":1,"value":5},"giver":5,"list":[19],"target":4,"turn":0}        |
| 5039812 |   21606 | {"type":"text","text":"Razgovor tells Libster about one Orange"}
```
card 19 does not exist on the first turn cuz only 18 cards are doled out. Was 6p was initially implemented with the wrong num cards per hand? anyways don't delete the game yet pls

**Comment by Zamiell** [comment]
yes, 6 player was originally implemented with 4 cards per hand.
after we beat it a few times, i wanted to make it more reasonable, so i changed it to 3 cards.
thus, i propose we should delete all of the old games

**Comment by padiwik** [comment]
isn't it somewhat easy to add the option in now that it exists?

**Comment by Zamiell** [comment]
oh, yeah i guess you could specify that all of those games should have the "one extra card" option set to true

**Comment by padiwik** [comment]
The last such game is 27152, 39 games in total

**Comment by Zamiell** [comment]
this is being worked on by padi and tracked in #1416

**Comment by Zamiell** [comment]
this should be mostly fixed now outside of a few odds and ends that will be tracked in issue #1416
thanks to padi
