### ISSUE TITLE
Hypothetical in Clue Starved Bug

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1106]
So, going into the hypothetical in Clue Starved is fine.  However, when players discard or play cards the clue count....bugs.....like discarding and/or playing cards makes it tick up and down by 0.2 clues.

So I tried starting a game in hypothetical....the first clue drops the clue count from 8 to 3.5 clues.  Playing a card drops it to 1.7 clues.  

Game ID: 179612

**Comment by Zamiell** [comment]
fixed
