### ISSUE TITLE
Word list for random game names includes sexual words

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1114]
For example

https://github.com/Zamiell/hanabi-live/blob/a8e2b6802829b15ca869eb911aec3a174232d3c8/src/assets/word_list.txt#L26430

or

https://github.com/Zamiell/hanabi-live/blob/a8e2b6802829b15ca869eb911aec3a174232d3c8/src/assets/word_list.txt#L50823

**Comment by Zamiell** [comment]
whats wrong with masturbation

**Comment by timotree3** [comment]
I work with kids and don't want to be embarrassed by these coming up if I introduce any to the site

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/faaa4df4db991f6191b40a79d285e5752083f836

**Comment by timotree3** [comment]
thank you for bearing with me. It's actually not a big deal to me personally for what it's worth. I'm just playing a scripted role.
