### ISSUE TITLE
Changing variants with command

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1117]
no one can seem to get /changevariant to work for Black & Rainbow (6 Suits).
I can change it to variants such as Black or Rainbow without problems, but I suspect there is some issue with the & doing some weird escapey things?

**Comment by Zamiell** [comment]
should be fixed after the next server restart

**Comment by padiwik** [comment]
I can't get any variant to work with the command now, even No Variant
