### ISSUE TITLE
add latest games

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1120]
show somewhere at least only friends' latest games (in lobby, if possible for every user, or make an another tab). i like watching replays, and using history for this purpose is highly inconvenient: i have to choose a player, open his profile, click on full history button - it requires so many actions. If i want to switch to another friend's game who was playing parallelly, then i need to do everything again.

**Comment by Zamiell** [comment]
oh, how about it does old announce functionality but only for friends?

**Comment by Aigul9** [comment]
fine

**Comment by Zamiell** [comment]
you will now get announcements for friends games
