### ISSUE TITLE
add filter

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1121]
how about adding a filter into full game history table, 'other players' column?
e.g. my games:
Sucubis, Valetta6789, bulbasaur
Dr_Kakashi, Floriman, Valetta6789
and by clicking on the header i get the list, in which i can see all the users i played with and filter history according to the selected criteria:
bulbasaur
Dr_Kakashi
Floriman
Sucubis

**Comment by Zamiell** [comment]
so you want "Sucubis, Valetta6789, bulbasaur" to be a link to a new page that shows all games with these 3 players?

**Comment by Aigul9** [comment]
just how it works in excel, for example, check the players and update the table view

**Comment by Zamiell** [comment]
i have no idea how it works in excel, you'll need to explain

**Comment by Aigul9** [comment]
weeell, i click here:
![image](https://user-images.githubusercontent.com/46625461/83157162-f2e49400-a10b-11ea-93c7-037d49fb38b3.png)
some window appears:
![image](https://user-images.githubusercontent.com/46625461/83158461-7b176900-a10d-11ea-94c4-082890e4b5c0.png)
i choose players and click 'ok' (let's say schark):
![image](https://user-images.githubusercontent.com/46625461/83158914-10b2f880-a10e-11ea-9744-959db72814f0.png)
I don't want to see other games except for those that I played with him.
Question: if i choose multiple players, should 'or'/'and' apply to them?

**Comment by Zamiell** [comment]
this is a good feature, i will add this

**Comment by Zamiell** [comment]
done, you will see it after the next server restart
