### ISSUE TITLE
table does not exist

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1126]
this error occurs when i try to watch the game from other players' point (even if i click on my name)

**Comment by Zamiell** [comment]
i dont understand what this means

**Comment by Zamiell** [comment]
provide steps to reproduce / video

**Comment by Aigul9** [comment]
works now

**Comment by Aigul9** [comment]
1. open a replay
2. make sure, you are the only person
3. right-click on any username
in shared replay it says:
![image](https://user-images.githubusercontent.com/46625461/83378095-51499500-a3e0-11ea-9719-15af156683f6.png)
in non-shared:
![image](https://user-images.githubusercontent.com/46625461/83378262-df258000-a3e0-11ea-9770-18cba928420c.png)

**Comment by Zamiell** [comment]
i see, thanks for reporting.

i recoded this now so that shifting perspectives will always work, regardless of how many people are in the replay.

so this bug shouldn't happen anymore
