### ISSUE TITLE
Maximum score issue in up or down variant

### ISSUE THREAD

**Issue by bfichera** [Zamiell/hanabi-live#1129]
Haven't had time to do any extensive testing, but the up or down variant seems to be miscalculating the maximum score.

My understanding is that the game below should have continued and the maximum score is still 30. 

![Screenshot from 2020-05-28 16-47-50](https://user-images.githubusercontent.com/22375789/83197952-fbd16780-a103-11ea-9deb-bc283302fec1.png)

I should note that the "womp womp" sound played every time we discarded 1s or 5s, independent of whether those cards were required to finish the game.

**Comment by Zamiell** [comment]
@robertos looks like a regression

**Comment by robertos** [comment]
Will look into it tonight

**Comment by Zamiell** [comment]
should be fixed now
