### ISSUE TITLE
Normal suits in reversed games are showing "Reversed" when finished

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1130]
See comments 
https://github.com/Zamiell/hanabi-live/commit/d893a622dffc9699357f8f108bbcfbb3ae683230#commitcomment-39514692
https://github.com/Zamiell/hanabi-live/commit/6d2c8f2c18379570c9cb6216e594e6679d997736#commitcomment-39514619

**Comment by Zamiell** [comment]
should be fixed now in the latest commit
