### ISSUE TITLE
Show positive clues on the cards

### ISSUE THREAD

**Issue by sephirothx** [Zamiell/hanabi-live#1140]
Right now the interface only directly shows touched cards, the clues (positive and negative) are only highlighted in the list on top-right when hovering the desired card. It would be very useful to have positive clues shown direcly on the card.
An idea:

![suggestion](https://user-images.githubusercontent.com/1510856/83310351-04ad6080-a20c-11ea-88f3-7e23c2ea37fc.png)

**Comment by Zamiell** [comment]
probably duplicate of #864

**Comment by Zamiell** [comment]
in this mockup, it overlaps with the critical indicator

**Comment by Zamiell** [comment]
are you still working on this or should i close it?

**Comment by Zamiell** [comment]
gonna close since he isn't responding
