### ISSUE TITLE
each game length is the same

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1157]
![image](https://user-images.githubusercontent.com/46625461/83389683-494a1f00-a3f9-11ea-9c0b-8013c3a5fddd.png)
it shows actual time only in the shared replay when the game was just finished

**Comment by Zamiell** [comment]
i dont understand this, provide steps to reproduce

**Comment by Aigul9** [comment]
open a replay, hover a mouse over game info

**Comment by Zamiell** [comment]
oh i see

**Comment by Zamiell** [comment]
should be fixed after next server restart
