### ISSUE TITLE
Replaying a game works from ID but not json

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1164]
Try using the json data for game 98745 . You get error "action at index 0 is invalid" (cannot give clue to yourself). But it works fine when viewing it by the database id.

Are there certain checks that are ignored when viewing from a database id or something?

**Comment by Zamiell** [comment]
its because "starting_player" is sometimes non-0 for games prior before ID 109740

**Comment by Zamiell** [comment]
fixed in https://github.com/Zamiell/hanabi-live/commit/e64895c2e82b9148fcefd4253a351e37d55ae1a5
