### ISSUE TITLE
change client to not use fractional clues for clue starved

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1169]

**Comment by robertos** [comment]
What's the plan here? Start with 2x clues and lose 2 on clue like the server?

**Comment by Zamiell** [comment]
originally the server worked like the client, but we got weird bugs, relating to floating point numbers.

when i talked to libster about this, he mentioned that as a general programming practice, you should always avoid working with floats if possible, because it introduces a whole new class of bugs. (e.g. for storing the value of "$123.45", you should use "12345"  instead of "123.45")

so, i changed the server to just work in integers and used logic to double it when appropriate, which worked well.

however, i never went back and gave the same treatment to the client, because

1) javascript is better at handling floats, and
2) i was lazy

the goal of this issue is to just copy the server logic and make the client work in the same way, then this issue can be closed

**Comment by robertos** [comment]
Sure. I do agree that ints are more stable than floats and you need to be careful comparing floats. JS is not that better at handling floats, in fact there's a class of sneaky bugs in JS because a number is anything in JS

**Comment by Zamiell** [comment]
done
