### ISSUE TITLE
remove "Action" button in table list, just click on row instead

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1176]

**Comment by DrAnax** [comment]
I'd like to fix this one

**Comment by Zamiell** [comment]
ok but make sure it is clear what is happening

**Comment by Zamiell** [comment]
like the entire row should light up / change color when you mouse over it

**Comment by Zamiell** [comment]
also, maybe a tooltip should appear that says "join" or "spectate", depending on if the game is started or not

**Comment by DrAnax** [comment]
I think i'll implement row color change on hover, a mouse curse change and show a dim 'view' or 'join' icon

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
done thanks to dranax
