### ISSUE TITLE
Help tooltips don't behave properly

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1179]
Using Chrome and Linux: Go to create a new game, and click one of the blue question mark tooltips. The first click merely resizes the option screen by a bit, and only the second click opens the proper github link. It works fine on Firefox.

**Comment by Zamiell** [comment]
works fine for me in chrome on windows

**Comment by Zamiell** [comment]
this is a dead simple link <a href="poop">poop</a>, i dont know how to fix this
