### ISSUE TITLE
Preplayed cards don't disappear into the stacks on the last turn of the game

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1180]

**Comment by padiwik** [comment]
this might be fixed now, i'd like to see some more games to confirm

**Comment by Zamiell** [comment]
well i reverted all the recent state changes so this is probably fixed now

**Comment by padiwik** [comment]
this has been an issue since i've turned on preplays, so i'm not sure it relates to the recent state changes

**Comment by Zamiell** [comment]
its related because the "state" bug is where you play a card and nothing happens, then you draw a card, and you get N+1 cards in the hand

**Comment by padiwik** [comment]
ok so actually the issue is when the card can't actually play (the game ends or gets terminated before it can play)

**Comment by Zamiell** [comment]
@padiwik can you test to see if this still happens

**Comment by Zamiell** [comment]
dupe issue
