### ISSUE TITLE
number of clues is broken

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#1184]
as reported on Discord, the number of clues you have is frequently broken in a game. It happened on average multiple times in a game, but I don't know exactly how to reproduce it. I've noticed sometimes receiving 2 clues back after a discard (or was it losing 2 clues after a clue?)

**Comment by robertos** [comment]
Should be fixed with #1183

**Comment by Zamiell** [comment]
k, will close
