### ISSUE TITLE
one extra card

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1190]
this feature looks like broken replay:
![2020-06-04_13-19-27](https://user-images.githubusercontent.com/46625461/83746305-93d0d300-a667-11ea-9c06-6fb55276d036.png)
![2020-06-04_13-27-48](https://user-images.githubusercontent.com/46625461/83746308-96332d00-a667-11ea-9fc2-04c134c47319.png)

**Comment by Zamiell** [comment]
whats broken about it

**Comment by Aigul9** [comment]
was the overlap intended?

**Comment by Zamiell** [comment]
yes, a slight overlap is intended

**Comment by Aigul9** [comment]
it's quite difficult to play up & down with this feature

**Comment by Zamiell** [comment]
fixed
