### ISSUE TITLE
time mismatch

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1191]
time before shutdown in discord and on the site do not match
typo: The server is shutting down **in in** 44 minutes.

**Comment by Zamiell** [comment]
> typo: The server is shutting down in in 44 minutes.

fixed, thank you

> time before shutdown in discord and on the site do not match

what does this mean

**Comment by Aigul9** [comment]
announcement in discord says in 1 min. if i try to create a game, then in 36 min.

**Comment by Zamiell** [comment]
fixed, thank you
