### ISSUE TITLE
Feature request: /games command

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1195]
When you're spectating a game with players you don't know, it's useful to quickly estimate their experience by looking up the number of games they've played. So, `/games padi` would return `padi has played 601 games` or something. Are you open to this existing if I submit a PR for it? Is this a good name for the command?

**Comment by robertos** [comment]
Maybe /stats or /playerstats or /playerinfo? "xyz has played 999 games since 1/2/1995, with 157 total max scores"

**Comment by padiwik** [comment]
I like the idea of total max scores. I just thought /stats might be misleading since it doesn't match the information in the scores endpoint. Perhaps we should add total max scores in the game lobby as another metric of experience?

**Comment by robertos** [comment]
I tried to summarize the info from the scores endpoint, which currently is (example below is my own)

Date joined: March 13th, 2020
Games played (in non-speedruns): 59
Time spent playing (in non-speedruns): 1 day, 2 hours, and 23 minutes
Games played (in speedruns): 0
Time spent playing (in speedruns): -
Total max scores: 5  (0.1%)

**Comment by Zamiell** [comment]
wouldnt it be better to just `/stats padi` and have that open "https://hanabi.live/scores/padi" in a new tab?

**Comment by padiwik** [comment]
Maybe the summarized stats should include the link. But opening a new tab is somewhat annoying when you're just looking for a fast way to check everyone's experience while watching their game.

**Comment by robertos** [comment]
Another option for the same effect is a mouseover tooltip on people's names

**Comment by Zamiell** [comment]
i dont think opening a link is particularly annoying. however, it would be annoying to have to type it for all 3 players in the game though. so maybe doing `/stats` should pop up a new window (similar to the chat window) with the stats for all 3 players in it.

**Comment by padiwik** [comment]
Good idea, it can easily be done that `/stats` with no arguments defaults to this. But I'm wondering how to make a useful window popup that fits the screen? that sounds even more annoying than just opening new tabs, or having a stats summary printed in chat

**Comment by Zamiell** [comment]
it doesn't have to fit the screen, it can just be a default width and height. and then, when you done reviewing the stats, you can click the x button to close it in exactly the same way that you can click on the x button to close the chat when you are done reading the chat

**Comment by padiwik** [comment]
Maybe my setup is weird but I keep chat permanently open in the top right, so I'm not a big fan of windows that need to get closed

**Comment by padiwik** [comment]
But also, I don't think a window the size of the default chat box is enough to fit all player's stats without scrolling or condensing them

**Comment by Zamiell** [comment]
> Maybe my setup is weird but I keep chat permanently open in the top right, so I'm not a big fan of windows that need to get closed

when considering this feature or the website more generally, we need to assume the default resolution of 1920×1080. in this resolution, there is not any room for keeping the chat permanently open in the top right.

> But also, I don't think a window the size of the default chat box is enough to fit all player's stats without scrolling or condensing them

im not proposing that the hypothetical window is the same size as the chat window. it can be as arbitrarily big as you need it to be. we don't have to worry about it blocking gameplay because the user will manually close it when they are done reviewing the stats.

alternatively, if you don't like the sound of that, you can go with robertos' idea of greatly increasing the size of the player tooltips. the disadvantage of that is that you can't see all the stats at once, of course.

**Comment by padiwik** [comment]
Well I hide the clue log in the top right... probably not advisable

I guess I would need to create a mockup of these new windows? But I still believe the cleanest or easiest solution is a chat reply when all you care about is the info robertos represented in the second comment. You can open the /scores endpoint in a new tab if you want more. Do you think a chat reply is too condensed and difficult to read?

**Comment by Zamiell** [comment]
a chat replay containing just the number of games is fine.

a chat reply containing this would probably be too difficult to read:

```
Date joined: March 13th, 2020
Games played (in non-speedruns): 59
Time spent playing (in non-speedruns): 1 day, 2 hours, and 23 minutes
Games played (in speedruns): 0
Time spent playing (in speedruns): -
Total max scores: 5 (0.1%)
```

**Comment by padiwik** [comment]
Done #1218
