### ISSUE TITLE
Replay display error in a few games.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#1201]
![image](https://user-images.githubusercontent.com/49693470/83940089-a9223a80-a7ea-11ea-8863-9d787389626d.png)

Console says: 
"The scores from client and server don't match. Client = 2, Server = 0
(anonymous) @ LineToLine.js:7"

Game id 194484.

**Comment by robertos** [comment]
LineToLine is Phaser code. No idea what this is @Zamiell

**Comment by Zamiell** [comment]
no idea

**Comment by Zamiell** [comment]
@robertos do we close this now with the new state changes?

**Comment by robertos** [comment]
This is a server-side error. Unrelated to state changes - the logged warning is due to a desync but it doesn't cause a pop up.

**Comment by robertos** [comment]
@hanabirnoob Seems like this doesn't repro anymore. Please reopen if you see it again.

**Comment by Zamiell** [comment]
its related to padi's fixes
