### ISSUE TITLE
Detrimental Characters: "Stubborn" Character Bug

### ISSUE THREAD

**Issue by dhd2788** [Zamiell/hanabi-live#1204]
Stubborn description: "Must perform a different action type than the player that came before them"

In the linked replay, I was able to give a clue when the player playing immediately before me also gave a clue (turns 26&27) [https://hanabi.live/replay/197301](https://hanabi.live/replay/197301). I did not experiment with other action types or other scenarios so I'm not entirely certain when this bug does and does not occur.

**Comment by padiwik** [comment]
Yeah it's because rank clues and color clues are now considered different action types in the code. I'm not sure if all clues should count as the same type for the Stubborn character... probably?

**Comment by Zamiell** [comment]
should be fixed now, reopen if not
