### ISSUE TITLE
Detrimental Characters: Oblivious+Quacker Bug

### ISSUE THREAD

**Issue by dhd2788** [Zamiell/hanabi-live#1205]
In a 3-player game ([https://hanabi.live/replay/197505](https://hanabi.live/replay/197505)), I had the Oblivious trait and the player whose hand I was _not_ Oblivious to was the Quacker. Whenever he quacked at the player's hand who I couldn't see, I received information about what specific clue type it was (so, if he quacked all blue cards, I would see it as a blue clue, but I should only see quacks and not the clue type). Attached is an image of my point of view (the Oblivious one) on turns 4 and 21 where quacks were given and I was able to see the type of clue that was given:
t4: [https://i.imgur.com/E6mnOn3.png](https://i.imgur.com/E6mnOn3.png)
t21: [https://i.imgur.com/AK8889H.png](https://i.imgur.com/AK8889H.png)

Additionally, on turn 21 when this quack happened, I (KiwiSquawks) saw incorrect numbers on the arrows and the clued player (Axineld) also saw incorrect numbers but they were different from mine. The player giving the quack (rfrank27) did not see numbers.
KiwiSquawks PoV: [https://i.imgur.com/AK8889H.png](https://i.imgur.com/AK8889H.png) (same image as linked above)
Axineld PoV: [https://i.imgur.com/KieEhmq.png](https://i.imgur.com/KieEhmq.png)

**Comment by Zamiell** [comment]
should be fixed now, reopen if not the case
