### ISSUE TITLE
add column "number of cards"

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1207]
since we have new options, allowing to alter amount of cards in the hand, i suggest adding a column "# of cards" in this table:
<img width="710" alt="2020-06-07_13-56-47" src="https://user-images.githubusercontent.com/46625461/83967131-697d5080-a8c7-11ea-9713-dfda2b8c8fb7.png">
otherwise, it seems like one team got perfect score and played better than another which scored 0, while the deck was much harder/easier with fewer/more cards

**Comment by padiwik** [comment]
It should probably also include Empty Clues and Bottom deck blind plays etc. Maybe the best option is a tooltip like with max scores to avoid having too many columns

**Comment by Zamiell** [comment]
done
