### ISSUE TITLE
shred replay leader can't right click score/eff/etc

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1210]

**Comment by robertos** [comment]
That one was because of my opportunistic MouseEvent.which -> button change. Actually the enums are not the same :( :( :(
To solve, move it back to be evt.which = 3 or evt.button = 2.

**Comment by robertos** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

Button is better, since it's the standard

**Comment by robertos** [comment]
(or the more robust buttons, that supports multiple buttons https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons)

**Comment by Zamiell** [comment]
u just wanna do a PR for it?
