### ISSUE TITLE
Mouse event handlers are using deprecated property MouseEvent.which

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1212]
The [which](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which) property is non-standard and deprecated. Should replace with [button](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) or [buttons](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons)

**Comment by Zamiell** [comment]
fixed
