### ISSUE TITLE
Spectating a game initially loads with wrong cards remaining

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1213]
Go to any game in progress as a spectator. The number of cards remaining in the deck loads with a much lesser value than it should be, which also gives a very negative pace. Entering replay fixes the issue.

**Comment by padiwik** [comment]
i can't repro consistently, but it happened to me a couple days ago as well

**Comment by Zamiell** [comment]
reopen if it happens on the "new" client
