### ISSUE TITLE
Send private replies to commands in the pregame chat to that chat

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1217]
Currently it sends to the main lobby chat

**Comment by padiwik** [comment]
Ok this seems intentional at least for normal PMs

>     // If this is a PM that we are receiving,
>    // we want it to always go to either the lobby chat or the game chat

is this because the pre-game chat is ephemeral? Personally I think it makes more sense to send to the pregame chat, since it's more likely you'll start the game and want to see such chat than leave the pre-game and lose it.

**Comment by Zamiell** [comment]
maybe it should send to all chats at once, or pop up a new window

**Comment by Zamiell** [comment]
maybe i should delete this feature

**Comment by padiwik** [comment]
all chats is weird, why is it better? it feels more confusing

new window seems annoying when you want to have a conversation

by "delete the feature" do u mean delete the exception for pre-game PMs?

**Comment by padiwik** [comment]
oh do you mean like a chat pop up for each person youre messaging? that's interesting

**Comment by Zamiell** [comment]
done for now
