### ISSUE TITLE
Efficiency in clue starved variant

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1219]
Whenever a card bombs, the in-game efficiency counter increases the denominator by 1 (as discarding it would give back a clue, so effectively bombing wastes a clue).
In clue starved, it also seems to increase the denominator by 1; it should do something sensible, like increase it by 0.5, or better yet by 0/1 depending on the total number of clues: if the total number of clues (including discards and all but one 5) is an integer, increase the denominator for the first bomb but not the second, and if it is a half-integer increase it by 1 for the second bomb but not the first.

**Comment by padiwik** [comment]
Are you also suggesting that discards should only update efficiency if it gives an actual full clue back?

**Comment by Zamiell** [comment]
should i close this

**Comment by robertos** [comment]
I believe so. Double check on a clue starved replay?

**Comment by Zamiell** [comment]
thanks dani, this will be fixed in an upcoming DLC

**Comment by Zamiell** [comment]
tests for this are in gameStateReducer.test.ts
