### ISSUE TITLE
add a filter to each column in history table

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1220]
sometimes i want to recall my previous games, and it would be quite useful if i could select number of players, score and variant. now i have to sort the table, click ctrl+F, type text, scroll for years until i find appropriate rows, try asking my eyes to ignore scores or players that i don't need.
btw, other players do not work as i proposed: i still can't see the whole list of players (i don't know with whom i played since i joined) and choose specific player(s).

**Comment by Zamiell** [comment]
happy birthday
