### ISSUE TITLE
Use notes to refine efficiency?

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1222]
Here's an interesting idea. If we mark a card as [f]inessed, this should count as a clued card for efficiency purposes. And likewise a card marked as trash should count as an unclued card. Would be useful when there's say a 5 for 1 finesse so you know you can give 1 for 1 clues afterwards.

**Comment by robertos** [comment]
Does that mean different people would see different efficiency values? What about spectators?

**Comment by padiwik** [comment]
Yes. Spectators should write their own notes if they want the more accurate efficiency

**Comment by Zamiell** [comment]
closing in favor of #774
