### ISSUE TITLE
Notes visual effects

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1225]
I like the visual effects from notes for things like r4/f/cm/fixme/trash; can these visual effects be made to remain even if more notes are added?
For example, I'd like to be able to write cm | probably r3 and still have a white border to remind me to not discard, or f | g1 to have a blue border but also note down that I'm trying to play g1.

**Comment by robertos** [comment]
Use brackets :) "[cm] something else" will keep the border

**Comment by robertos** [comment]
cm | probably r3 -> [cm] | probably r3
  f | g1 -> [f] | [g1]

**Comment by padiwik** [comment]
Which involves retyping the note, which is annoying. I understand zam wants piping something to a note to remove the border, but imo it's more likely we want to add information to a cm/finesse than turn off the cm/finesse

**Comment by robertos** [comment]
i see | as a "replace"/update symbol. what's left of it is just for history. Maybe a different symbol like "+"? 
e.g., "cm + r1" = add all visual effects from cm and r1
and "cm | f + r1" = only f and r1 effects, cm is history

**Comment by Zamiell** [comment]
> Which involves retyping the note, which is annoying.

no, it doesn't. just put brackets around the existing note
