### ISSUE TITLE
if stack is decided up, it shows up in replay before it is decided

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1229]

**Comment by robertos** [comment]
Since stackdirections are part of state, this should be fixed as part of making replays use state instead of actions

**Comment by Zamiell** [comment]
i think this is a regression from the state code you added, because this is a newish bug

**Comment by robertos** [comment]
The code I added doesn't touch the UI, and doesn't have anything to do with stack directions yet. Likely it was there already

**Comment by Zamiell** [comment]
oh, my bad then

**Comment by Zamiell** [comment]
shouldn't stack directions be part of state? currently, they are not
https://github.com/Zamiell/hanabi-live/blob/master/client/src/game/ui/HanabiCard.ts#L343

**Comment by Zamiell** [comment]
anyways, it is fixed now
