### ISSUE TITLE
Joining a hypo in progress doesn't play through past hypo actions

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1231]

**Comment by Dr-Kakashi** [comment]
If the game is in a hypothetical and a player refreshes the page. The game state will default to the starting position of the hypothetical, while the other players who didn't refresh are still seeing the proper hypothetical.

**Comment by padiwik** [comment]
Ok I fixed it, will submit PR as soon as I fix the hypoRevealed bug for new joiners
