### ISSUE TITLE
Refreshing Bug 

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1233]
If the game is in a hypothetical and a player refreshes the page.  The game state will default to the starting position of the hypothetical, while the other players who didn't refresh are still seeing the proper hypothetical.

**Comment by padiwik** [comment]
Same as #1231

**Comment by Dr-Kakashi** [comment]
Oh shoot, I'm going to close this and copy and paste my comment to your post
