### ISSUE TITLE
disable hypo toggle button if revealed card is clued, played, discarded

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1243]
@padiwik

**Comment by Zamiell** [comment]
currently, clicking on the button does nothing.

the button should be grayed out so that it looks like a "disabled" state

**Comment by padiwik** [comment]
oh that's smart

**Comment by Zamiell** [comment]
copy the "disabled" code from button.ts to button2.ts, then do `setEnabled(false)`

**Comment by Zamiell** [comment]
seems to work now, thanks padi
