### ISSUE TITLE
Replace all instances of checking a variant by string comparison with proper methods

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1252]
E.g.  `globals.variant.name.startsWith('Clue Starved') ` should be `isClueStarved(variant)`

Also consider taking this opportunity to replace specific variant checks with rule checks (e.g. instead of checking isThrowItInAHole(variant) you can check for playStacksHidden(variant), which initially returns the same things)

**Comment by padiwik** [comment]
Why not just use variant properties? I don't see the need for a function.

See https://github.com/Zamiell/hanabi-live/commit/e3b7655cdf47ce413f382675abd72a6d3f118252

**Comment by Zamiell** [comment]
done
