### ISSUE TITLE
Going back in a replay doesn't always update cards

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1254]
Sometimes cards that should be faded are not faded. And critical indicators aren't there when they should be.

**Comment by Zamiell** [comment]
provide steps to reproduce

**Comment by padiwik** [comment]
Sure, for example in this game https://hanabi.live/export/207624 go to turn 25. Then go back a turn. The b4 loses its critical indicator while the y1 and b1 in seph's hand aren't faded but they should be.

The code seems to work completely fine when you step forward in a replay, so i think it's an issue in the function that plays through past actions

**Comment by padiwik** [comment]
This is caused by fast animation
