### ISSUE TITLE
Efficiency formula missing strikes

### ISSUE THREAD

**Issue by mokesmoe** [Zamiell/hanabi-live#1255]
The efficiency formula shown in the efficiency tooltip and on the features page doesn't include strikes.

**Comment by Zamiell** [comment]
why would it?

**Comment by mokesmoe** [comment]
when you gain a strike the efficiency changes to reflect the clue you lost, but the formula only mentions "number of clues given" and not clues lost

**Comment by mokesmoe** [comment]
Mentioning clues lost instead of strikes directly may be more clear (and make things simpler for clue starved). It would also cover the case of playing a 5 at 8 clues.

**Comment by Zamiell** [comment]
you are right, i changed "number of clues given" --> "number of clues given or lost"

**Comment by Zamiell** [comment]
this will be fixed in an upcoming update, thanks
