### ISSUE TITLE
Played 5 at 8 clues doesn't reduce efficiency

### ISSUE THREAD

**Issue by mokesmoe** [Zamiell/hanabi-live#1256]
Playing a 5 while at 8 clues costs the team a clue, similar to a strike, but unlike a strike it doesn't change the efficiency.

 See this turn for an example: https://hanabi.live/replay/205765/36

**Comment by robertos** [comment]
This is fixed since we moved efficiency to the state machine

**Comment by Zamiell** [comment]
woot

mokes it will be fixed on live soon

**Comment by robertos** [comment]
It's actually fixed on live already :)

**Comment by Zamiell** [comment]
oh
