### ISSUE TITLE
showing empty table

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#126]
When creating a table, sometimes the list of players disappears for a short period, see screenshot below.

I don't know exactly when it happens, but it happened most of the times when I created a table today. It seems to happen often when someone joins a table. After a second it seems to display the table normally again.

I haven't seen it before today.

![image](https://user-images.githubusercontent.com/7376012/44118866-ba797672-a017-11e8-8004-4e4c1c6fdc92.png)

**Comment by Zamiell** [comment]
ctrl + f5 and let me know if it happens again
