### ISSUE TITLE
change replay leader should be an interactive tooltip where you click on the player to pass lead to instead of using an alert()

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1263]
@padiwik

**Comment by padiwik** [comment]
So like the current alert but with buttons for each player instead of typing a number? You can't just do players since you want to be able to give lead to any spectator

**Comment by Zamiell** [comment]
yeah i meant spectator

**Comment by DrAnax** [comment]
Closed by #2290
