### ISSUE TITLE
Up or Down: s on notes should denote start cards instead of 7 (e.g. sg = start of green)

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1264]

**Comment by Zamiell** [comment]
conventionally we use r0, s0, etc.
but that doesn't work either currently so yeah this issue needs to remain open

**Comment by padiwik** [comment]
Is there any suit that has the "s" abbreviation?

**Comment by robertos** [comment]
We can use 0 if there is/was/could be

**Comment by Zamiell** [comment]
sky, sapphire

**Comment by padiwik** [comment]
so the ambiguous suits, and those will most likely not be up or down

**Comment by Zamiell** [comment]
for reference, it looks like padi is currently working on this

**Comment by Zamiell** [comment]
seems to be fixed now thanks to padi
