### ISSUE TITLE
On non-timed games, the mouse over tooltip for player names still shows time remaining

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1265]

**Comment by Zamiell** [comment]
thats intended, but only if you have the setting checked

**Comment by robertos** [comment]
What setting?

**Comment by Zamiell** [comment]
"Show turn timers in untimed games"

**Comment by robertos** [comment]
Sure, but it should show the time elapsed not remaining?

**Comment by Zamiell** [comment]
oh, ya, that sounds correct

**Comment by robertos** [comment]
Also BTW the setting was off for me

**Comment by Zamiell** [comment]
can't reproduce, can you elaborate further

**Comment by robertos** [comment]
I haven't seen this in a while, will reopen if needed
