### ISSUE TITLE
Native URLs for tables

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1271]
This will allow e.g. sharing a link to your current table, and proper back button support for jumping between games and tables and the lobby.

Could use anchors (`hanabi.live/#table-1234`) or a format like `hanabi.live/table/1234`

**Comment by timotree3** [comment]
Ideally this would work for games with password and could redirect users after they log in.

**Comment by timotree3** [comment]
Could I implement this? I would love a sense of what's involved from someone experienced.

**Comment by Zamiell** [comment]
sure

**Comment by Zamiell** [comment]
just copy the code that opens a new table from a url

**Comment by Zamiell** [comment]
this is mostly implemented now, but there is no proper back button support, because that would entail reloading the page, which would never be desired
