### ISSUE TITLE
Going back to a particular turn can reset the game state

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1272]
![image](https://user-images.githubusercontent.com/24983586/85034829-7d8b4280-b150-11ea-8ba9-410a6f6e7928.png)

I'm spectating an active game, and this happens consistently but only if I go back to turn 16. No errors in console, how to debug?

**Comment by padiwik** [comment]
Oh I think I know. Kyle gave the same clue to the same person. And the replay thinks we're at the first instance of the action for whatever reason

**Comment by Zamiell** [comment]
@robertos

**Comment by Zamiell** [comment]
going to close this for now, with all the changes in card-reducer it will almost certainly not repro once we move it to master
