### ISSUE TITLE
notes misaligned in dual-color game #211032

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1276]

**Comment by padiwik** [comment]
i don't think it's just dual-color but i might be misremembering

**Comment by padiwik** [comment]
Oh my bug was the notes popup is too much to the right instead of centered, idk if that's the same bug you saw

**Comment by Zamiell** [comment]
yes, it must be something in a recent commit, or maybe something to do with dual color variant

**Comment by padiwik** [comment]
i think it happens because of the clue arrows?

**Comment by robertos** [comment]
There was some code to move the note on ambiguous that was not doing anything (because types). In the big type swoop i fixed that, but it seems like the original behavior was unintended.

**Comment by robertos** [comment]
notes.ts

@@ -325,7 +325,7 @@ export const show = (card: HanabiCard) => {
  // If there is an clue arrow showing, it will overlap with the tooltip arrow,
  // so move it over to the right a little bit
  for (const arrow of globals.elements.arrows) {
    if (arrow.pointingTo === card.state.order) {

**Comment by robertos** [comment]
You might want to just remove that code entirely

**Comment by Zamiell** [comment]
oh! yes, fantastic find, i remember writing that a long time ago.
i will delete that code block i guess, thanks rob
