### ISSUE TITLE
Spectator replay occasionally broken when moving backwards

### ISSUE THREAD

**Issue by jeep** [Zamiell/hanabi-live#128]
This happened last night as well as today when I hit the replay button or the back button in replay... going forward through the replay seems to always work
![image](https://user-images.githubusercontent.com/89500/44238272-ce9f0980-a168-11e8-9dc6-81e10b1422f4.png)

**Comment by Zamiell** [comment]
Reproduce bug, open dev console, copy paste lines

**Comment by Zamiell** [comment]
jeepLast Friday at 5:04 PM
no, intermittent and only when going back or first hitting the replay button.... going forward works fine, but when it is bad, going back again will make it empty
it has happened 4-5 times out of 10-15 attempts

**Comment by Zamiell** [comment]
@jeep unable to reproduce, provide more detailed steps

**Comment by Zamiell** [comment]
will likely be fixed during the client rewrite

**Comment by Zamiell** [comment]
found the bug and fixed it im pretty sure, reopen if it still happens
