### ISSUE TITLE
Same stats for different players

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1280]
![image](https://user-images.githubusercontent.com/15525142/85091045-8dd50900-b1b4-11ea-92af-374582dca090.png)

**Comment by TheDaniMan** [comment]
I think it's a bug, Derek says he has fewer games, and there's no way we have the exact same stats over that many games

**Comment by padiwik** [comment]
Yeah it's a bug https://hanabi.live/scores/derekcheah
