### ISSUE TITLE
Catch TouchEvent as well as MouseEvent

### ISSUE THREAD

**Issue by sholsyjy** [Zamiell/hanabi-live#1285]
I see it only catch `mousedown` and `mouseup` to show the 'empathy'. Maybe we can also catch `touchstart` and `touchend` and make them same as mouseEvent so we can play hanabi on iPad.

I've found part of code of this function, and it's OK if there is need a PR. Or maybe do it yourself?

**Comment by Zamiell** [comment]
does it not currently work on ipad?

**Comment by padiwik** [comment]
i was actually planning on doing this fix next. basically no touch events are supported currently except the dragging function and some of the button taps

**Comment by padiwik** [comment]
I should tag the PR #1292

**Comment by Zamiell** [comment]
should be fixed now thanks to padi
