### ISSUE TITLE
Null ones / fives interaction with other suits

### ISSUE THREAD

**Issue by florian-5f3759df** [Zamiell/hanabi-live#1293]
Example: A game of null-ones and rainbow, https://hanabi.live/replay/212976/8.

Expected behavior: The rainbow 1 is uncluable, since null-ones overrides the normal behavior of the suits.

Actual behavior: The rainbow 1 responds to color clues.

**Comment by Zamiell** [comment]
wrong. the suit property overrides the special property, as requested by valetta

**Comment by padiwik** [comment]
Link: https://github.com/Zamiell/hanabi-live/blob/master/docs/VARIANTS.md#suit-ones-or-suit-fives-with-another-special-suit

**Comment by Zamiell** [comment]
link is fixed now

**Comment by Zamiell** [comment]
when i flipped how the properties work i never went back and updated the documentation, which probably led to some confusion
