### ISSUE TITLE
State gets borked when spectating from a replay link

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1295]
Open Hanabi Live using a replay link with the turn number, like https://hanabi.live/replay/213235/2

Then go to lobby and try to spectate a game in progress. On the initial load, the cards and even the play stacks are all out of place, and there's duplicated actions in the action log:
![image](https://user-images.githubusercontent.com/24983586/85211908-a6136800-b31b-11ea-8182-4bac2fe22afe.png)

Related to #1213 probably?

**Comment by Zamiell** [comment]
can you test to see if this still works on card-reducer

**Comment by padiwik** [comment]
this seems fixed, possibly because we remove the /replay url when clicking the Lobby button

**Comment by Zamiell** [comment]
horray
