### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1301]
add tag commands (/tagsearchdeletewhatelse) in commands file. can we see the full list of tags somehow? like /mytags:
mytag1 - gameID1
mytag2 - gameID2, gameID3

**Comment by Zamiell** [comment]
35a817ec632b72ed51f2e7e53d302c76fae7384a

**Comment by Zamiell** [comment]
ill add /mytags

**Comment by Zamiell** [comment]
actually i changed my mind, im going to add `/tags/[username]` http endpoint instead

**Comment by Zamiell** [comment]
done
