### ISSUE TITLE
Missing number exclusions when viewing other player knowledge.

### ISSUE THREAD

**Issue by StereoPythonics** [Zamiell/hanabi-live#1302]
![image](https://user-images.githubusercontent.com/31551174/85226844-7e7ed700-b3d1-11ea-9e45-7dc55e590658.png)

Here player Bwitney Parells is viewing the hand knowledge of player mcgarc.

The value 3 is shown as a possibility for the mcgarcs third (purple) card, however both other purple threes are publicly visible so we know mcgarc's third card cannot be a purple three.

The game id was 214130 (p4v0s3 no variant

Hope it helps,
StereoPythonics

**Comment by padiwik** [comment]
Thanks for reporting. It seems I introduced this bug in one of my recent PRs, will fix.

Btw this feature of viewing what other people know about their hand is called "empathy".

**Comment by rogers-j** [comment]
(It's technically not _supposed_ to be called empathy, so I you will get no complaints from me 😉)

**Comment by padiwik** [comment]
oh then what is it _supposed_ to be called?
