### ISSUE TITLE
tab is outside the border

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1314]
![49305DEA-DD8F-4E61-874B-FC0852C620A1](https://user-images.githubusercontent.com/46625461/85302368-b8bfa580-b4b1-11ea-8728-ffe7de026db1.jpeg)

**Comment by padiwik** [comment]
Do you want them to just be icons? Smaller buttons?

**Comment by Aigul9** [comment]
no icons, please(

**Comment by Aigul9** [comment]
smaller font, margins, in 2 lines maybe

**Comment by Zamiell** [comment]
looks like this is only a problem on mobile at the smallest resolution
