### ISSUE TITLE
Rebind double tap in replays

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1315]
Since the edit note action is useless.. a double tap should probably display an arrow.

And then maybe a button for mobile users only that they can click to choose a card to morph?

**Comment by Zamiell** [comment]
why is the edit note action useless

**Comment by padiwik** [comment]
I mean shared/solo replays

**Comment by Zamiell** [comment]
> maybe a button for mobile users only that they can click to choose a card to morph?

i dont really want to clutter the codebase with mobile-only features

**Comment by padiwik** [comment]
Right, this is why it might be best to just not bother implementing leader actions for mobile users

**Comment by Zamiell** [comment]
ok, should we close this?

**Comment by padiwik** [comment]
i don't really care either way

**Comment by Zamiell** [comment]
mobile users probably wouldn't be the replay leader anyway i would imagine
