### ISSUE TITLE
Disallow restarting the game if the leader wasn't in the original game

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1319]
Alice Bob and Cathy were playing a game. They passed lead to Donald, and Donald remade the game. The new game had Alice, Bob, Cathy, and Donald but they couldn't play because Donald was actually spectating. Either it should force the leader to become a player, or the restart feature should ban Donald from restarting.

**Comment by Zamiell** [comment]
you just want the button to be grayed out?

**Comment by padiwik** [comment]
That could work yeah

**Comment by Zamiell** [comment]
that seems like a worse UX because the user won't know why the button is grayed out

**Comment by padiwik** [comment]
Well originally I was thinking for it to pop up a warning, just like there's warnings for people being away from the table etc

**Comment by Zamiell** [comment]
what do you mean

**Comment by padiwik** [comment]
yknow like all of these https://github.com/Zamiell/hanabi-live/blob/85687a0a47a88b6254056dcc802e095eb52c20bf/server/src/command_table_restart.go#L86

**Comment by padiwik** [comment]
can i just make the pr

**Comment by Zamiell** [comment]
fixed
