### ISSUE TITLE
Can see played card animation in Throw It in a Hole

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1328]
cheats!

**Comment by Zamiell** [comment]
what does this mean

**Comment by padiwik** [comment]
Start a game of Throw it in a Hole variant. Blind play a card. You can see which card it is by the faded image during the animation

**Comment by padiwik** [comment]
Well at least if you play a known red card, it shows for r1. Idk if it shows for pure blind plays, but it's bugged regardless

**Comment by Zamiell** [comment]
i think this must be a new bug, or we would have noticed it before

**Comment by Zamiell** [comment]
it sounds related to your changing of the "revealed" function, can you look into this?

**Comment by padiwik** [comment]
Can I change the server to not send card identities for plays in this variant?

**Comment by Zamiell** [comment]
sure, is that easy to do
