### ISSUE TITLE
Max score calculation bug

### ISSUE THREAD

**Issue by jeep** [Zamiell/hanabi-live#133]
When the same suit is killed multiple times, the max score is decreased too much.
Player.go (around line 253)
	if c.IsCritical(g) && !c.IsDead(g) {
		// Decrease the maximum score possible for this game
		g.MaxScore -= 6 - c.Rank

If the 5 is discarded, the max score is decreased by 1.
If the 4 is then discarded, the max score is decreased by 2 instead of just the 1 it should be decreased.

**Comment by Zamiell** [comment]
should be fixed now
