### ISSUE TITLE
write some efficiency/pace tests for 1 less card, 1 more card

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1332]

**Comment by Zamiell** [comment]
too lazy

**Comment by robertos** [comment]
Lazy is one thing, but these variants are actually bugged. We don't account for the hand/deck size correctly

**Comment by Zamiell** [comment]
what is bugged about them?

**Comment by robertos** [comment]
At least last time I checked, the efficiency / pace formulas didn't take into account alternate hand sizes. that might not be the case anymore.

**Comment by Zamiell** [comment]
they seem to work just fine
