### ISSUE TITLE
No possibility will be shown in a number blind variant in some situation.

### ISSUE THREAD

**Issue by victorywys** [Zamiell/hanabi-live#1338]
Game ID: #217910 
Turn: 45

In a number blind variant, when a card is clued with a color clue and has all the rank negative clue(since no rank clues will touch cards), it will be shown as having no possibility to be any card.

![image](https://user-images.githubusercontent.com/17527376/85654740-a80f5b00-b67c-11ea-8c53-fe0d266b5d9c.png)

**Comment by padiwik** [comment]
Thanks, fixed in #1341
