### ISSUE TITLE
Score is always 0/30 at endgame

### ISSUE THREAD

**Issue by martintb** [Zamiell/hanabi-live#1343]
Score shows as 0/30 at game finish regardless of actual score. This has been happening for ~1 week on every game played. 

Example Game ID: 219037

![image](https://user-images.githubusercontent.com/6588826/85816818-51685680-b73a-11ea-9e4b-8f784c8a55e2.png)

**Comment by Zamiell** [comment]
does it show correctly if you load up the review afterward?

**Comment by martintb** [comment]
Yup. If you immediately start reviewing the game, or look the game up in history, the score is correctly shown. 

After looking at the image above again, it appears that the scorebox has simply jumped back to the first turn while the rest of the UI is still showing the state at the end of the game.
