### ISSUE TITLE
# of players is wrong for shared replays

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1346]
In the lobby, the # of players column counts the number of spectators. It should count the number of the players in the original game, right? Because for games in progress, it doesn't care about the spectators. And a player is not a spectator.

**Comment by Zamiell** [comment]
i guess

**Comment by Zamiell** [comment]
you could also make the opposite argument, that a shared replay isn't a game

**Comment by padiwik** [comment]
In 99% of cases, a shared replay is the continuation of a game. In fact I even wonder if it should keep the table name, but that's a different issue

**Comment by Zamiell** [comment]
fixed
