### ISSUE TITLE
Accept touch events in place of mouse

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-live#135]
Currently, touch events can't be used instead of the mouse (e.g. to hover a card and see notes in a replay, or to add notes). It would be a nice feature to add.

**Comment by Zamiell** [comment]
submit a PR, i dont care about touch events

**Comment by Zamiell** [comment]
we can do this as part of the client rewrite

**Comment by padiwik** [comment]
Oh hey we fixed this

**Comment by Zamiell** [comment]
before i close this, are *all* UI elements touchable, or did you just do a pass on the major ones?

**Comment by padiwik** [comment]
Pretty much, except for some things like Ctrl + click for a local replay arrow that there's simply no way to bind nicely when we need to view empathy and edit notes.

The one thing I didn't bother to implement is double tap for shared arrows when you're the replay leader, perhaps I should.

**Comment by Zamiell** [comment]
sure, open a new issue for that then
