### ISSUE TITLE
ending hypothetical doesn't reset morphed cards anymore, probably because of recent changes

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1351]

**Comment by padiwik** [comment]
like how recent? cuz it might be from me functionizing the card.reveal() function

**Comment by padiwik** [comment]
it also doesnt unblank cards, but going into empathy fixes it. so maybe it is the fault of not calling setBareImage()

**Comment by padiwik** [comment]
yeah cuz when you're following a shared replay, people can draw completely blank cards. so it seems like `globals.turn` is mismatched or something. it's probably a different value for the shared turn as opposed to the local turn shuttle.

**Comment by Zamiell** [comment]
also we found a bug where cards were blanked out after we ended the hypo, which is probably just a different manifestation of the same bug

**Comment by padiwik** [comment]
also toggling hypoRevealed doesn't redraw the cards anymore

**Comment by Zamiell** [comment]
padi should i close this now?

**Comment by padiwik** [comment]
sure, ill submit the other PR as well one sec

**Comment by padiwik** [comment]
ok, don't close this. at least two issues still exist:

* doesn't reset morphed cards on hypo end
* enter a replay, go to some intermediate turn, hold empathy on a card. then go back a turn. it seems to blank out some of the card information

Both of which are caused by the `setBareImage()` optimization and can be fixed by toggling empathy. But I can't figure out a good fix.

**Comment by padiwik** [comment]
I've got the fix for the second bug with calling `resetActiveHover()`. But what's the best way to fix the first bug? Either we need to redraw all the cards drawn up to the current turn, which seems inefficient, or keep track of which cards were morphed and redraw all of them.

**Comment by padiwik** [comment]
Oh yknow, the first version shouldn't be any less efficient because they need to be drawn anyways

**Comment by Zamiell** [comment]
i vote first version

**Comment by Zamiell** [comment]
closing now, seems to be fixed on card-reducer too
