### ISSUE TITLE
If you aren't using shared turns, and leader enters a hypothetical, you start off on the wrong turn

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1354]

**Comment by Zamiell** [comment]
can you test to see if this still happens on card-reducer?

**Comment by padiwik** [comment]
This is fixed, however there's a related graphical bug that's unfixed:

* Lead a shared replay
* Pause shared turns
* Go to some other turn
* Enter hypothetical
* Leave hypothetical

The gray "solo turn" shuttle will still show, even though you're actually on shared turns.

**Comment by Zamiell** [comment]
ok, can you verify that this is fixed now?

**Comment by padiwik** [comment]
good job
