### ISSUE TITLE
Detrimental Characters :  starting contrarian leads to some UI problems on player order

### ISSUE THREAD

**Issue by Lesbre** [Zamiell/hanabi-live#1356]
When the first player is contrarian, the white bold underline under current player goes downwards while the black background box goes upward (turn goes upward). 
The bold white underline will continue going downwards (never upwards) while the black box changes direction as expected.

**Comment by robertos** [comment]
@Zamiell Fixed on card-reducer?

**Comment by Zamiell** [comment]
yeah its fixed on card reducer

lesbre, you will see it fixed on live the next time i restart the server
