### ISSUE TITLE
replay starts at random turn

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1369]
If you open the URL https://hanabi.live/replay/(some number)/(turn number), exit replay, press watch replay and type any replay number, it'll start you at (turn number) rather than at turn 1.
(for reproducibility I used https://hanabi.live/replay/226729/43 , left, and opened replay for game 226459)

**Comment by padiwik** [comment]
Well that's not a random turn, that's a specific turn! But yeah, this bug is consistent and reproducable. Fixing this will probably fix #1295

**Comment by TheDaniMan** [comment]
oh tru, that's the same one. I should just close?

**Comment by padiwik** [comment]
they manifest differently, idk

**Comment by Zamiell** [comment]
this is fixed in card-reducer, you will see it fixed on master in a week or so
