### ISSUE TITLE
card-reducer branch: make throw it in a hole work

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1385]

**Comment by Zamiell** [comment]
i did some work on this, all that is left is for rob to fix the `onHoleChanged()` function

**Comment by robertos** [comment]
done?

**Comment by Zamiell** [comment]
i tested it and experienced the following bug:

- clue some 1s
- play some 1s
- terminate
- the play stacks glitch out - some of the 1s are completely hidden, some of the 1s slowly animate from the center of the screen to their proper stacks.
  - after the slow animation is finished, the rest of the 1s appear

**Comment by Zamiell** [comment]
furthermore:

>the empathy in "throw it in a hole" is wrong.
we assume that other players know the cards they played.
(one small issue is the call to "revealCard" using the information we know, but the main problem is cards that will be drawn later)

**Comment by Zamiell** [comment]
actually i guess this isn't a very safe assumption, because it could be wrong

**Comment by Zamiell** [comment]
looks like it is fixed now thanks to rob

**Comment by Zamiell** [comment]
not fixed, still bugs out after refreshing and then terminating the game

**Comment by Zamiell** [comment]
any misplay animations also happen, which is buggy

**Comment by Zamiell** [comment]
i guess misplay animations to the discard pile are expected? not sure how it should work

**Comment by robertos** [comment]
There's two consistent options:
1. no animations for anything, animate fast
2. misplays and playstacks animate (current)
and one less consistent option
3. playstacks animate, misplays don't (add a fade/teleport)

**Comment by robertos** [comment]
There's also a funky, more complete change which is to make the reveal slower and more tense, by revealing the cards one by one and animating to the playstack or misplay. It would take much longer, but it would be a suspense reveal :) -- definitely not for this issue, but can be added as another issue if desired (P3)

**Comment by robertos** [comment]
I might go with option 1. (no anims) since that's what's currently on H.L

**Comment by Zamiell** [comment]
im fine with option 1

**Comment by Zamiell** [comment]
looks fixed, thanks
