### ISSUE TITLE
Show History of Friends

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1393]
If you go to show history, then show history of friends, it lists game history of friends, but all the games are missing a name. So for exmaple, the top one for me says # of players 3, and lists the players as melwen, qbphoenix.
I don't think it's very consistent about which player it excludes.

**Comment by robertos** [comment]
Dupe #1163

**Comment by TheDaniMan** [comment]
I even tried searching "friend" and didn't find the dupe :(

**Comment by padiwik** [comment]
Search "friends" lol, apparently github cares about plurals
