### ISSUE TITLE
card-reducer branch: animations should not happen for drawn cards on turn 0

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1399]

**Comment by robertos** [comment]
but i like the deal out :D

**Comment by Zamiell** [comment]
really? i think it is kind of annoying. it distracts from reading all the cards when starting to make your first move

**Comment by robertos** [comment]
I'm half joking. But think Windows Solitaire

**Comment by Zamiell** [comment]
fixed
