### ISSUE TITLE
Memory leak in tables

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1407]
Run the code in debug.go, the games remain in memory even when they are unattended by everyone. Zam thinks it's due to timer?

**Comment by Zamiell** [comment]
it must be due to the timer because it is stuck in a sleep.
the solution is to somehow use a sleep and a signal at the same time, i'll have to google that probably

**Comment by Zamiell** [comment]
something like this https://stackoverflow.com/questions/23331370/interrupt-a-sleeping-goroutine

**Comment by Zamiell** [comment]
probably isn't worth the extra complexity since it only matters when doing the massive game bullshit that padi is doing

**Comment by padiwik** [comment]
how is what I'm doing different from live, where people slowly create and leave more and more tables over time?

**Comment by padiwik** [comment]
Oh yeah it is timer, that explains all these messages when the script ends
```
Thu Jul 09 11:22:14 EDT 2020 - INFO - session.go:45 - Warning - Table 12896 does not exist. - Asddsa76
Thu Jul 09 11:22:21 EDT 2020 - INFO - game.go:173 - Table #17247 (Solo replay for game #21105) - Turn 0 - Time ran out for "Zamiel".
```

**Comment by Zamiell** [comment]
the following code is in the checktimer function:

```
	// Check to see if the game ended already
	if g.EndCondition > EndConditionInProgress {
		return
	}
```

padi why isn't this hitting? is the game ending without setting EndCondition?

**Comment by padiwik** [comment]
well, better question, why is the timer running at all in a replay? i tried adding `&& !t.Replay` in a couple places and it didn't help

**Comment by Zamiell** [comment]
i guess CheckTimer should never even be entered in replays in the first place, since noone can run out of time in a replay

**Comment by Zamiell** [comment]
padi can you confirm that memory still grows with this change?

**Comment by padiwik** [comment]
yes, i think the bug is in command_actions.go#153 i'll try fixing and report back

**Comment by padiwik** [comment]
oh nevermind that's a bad place for a fix

**Comment by padiwik** [comment]
Why it's bugged:
1. command_replay_create.go runs commandTableStart()
2. commandTableStart() begins the timer functions, starting a cycle of sleep death
3. command_replay_create.go sets t.Replay = true

so, timer has no way of knowing it shouldnt be running.

possible solution 1: add t.Replay as part of commandData on game creation??

what i did (hacky):
* add `t.Replay = true` right when table is made
* comment out https://github.com/Zamiell/hanabi-live/blob/master/server/src/command_action.go#L62-L67

I think a memory leak might still exist, but it seems less? not sure, will see when running the big script

**Comment by padiwik** [comment]
lol my hack breaks the terminate action, i think

**Comment by Zamiell** [comment]
> possible solution 1: add t.Replay as part of commandData on game creation??

we can already using ExtraOptions.Replay actually

**Comment by padiwik** [comment]
Oh i thought that was just for the `!replay` command, can it be overloaded?

**Comment by Zamiell** [comment]
fixed on master now

**Comment by Zamiell** [comment]
will leave this open until you test

**Comment by padiwik** [comment]
i don't think i see timers, but it's still leaky somewhere

**Comment by Zamiell** [comment]
oh i think i know why

**Comment by Zamiell** [comment]
its because CheckIdle is doing the same thing that CheckTimer previously was

**Comment by Zamiell** [comment]
cd306c0e7c199e74288dcc45b90c472d14124bb1

**Comment by padiwik** [comment]
nice, it's eating *much* less memory now

**Comment by Zamiell** [comment]
ok, will close
