### ISSUE TITLE
Note arrays are mismatched on old games

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1408]

**Comment by padiwik** [comment]
Next thing is notes, they're fucked for some reason. Consider for example https://hanabi.live/replay/13725 . The notes are obviously wrong.

```
hanabi=# select * from game_participant_notes where game_participant_id in (3590, 81329, 94135, 119229) order by card_order asc;
 game_participant_id | card_order |                           note    
                        
---------------------+------------+-----------------------------------
------------------------
                3590 |          0 | the 1s reclue means invert focus
               81329 |          0 | cm, p5...maybe this is p3? Ok this
 is p5 
               94135 |          0 | chop move
              119229 |          0 | locked hand :( --- should've clued
 green
                3590 |          1 | c
              119229 |          1 | cm
               81329 |          1 | b2
               81329 |          2 | b3/y3, assda will gentleman's if y
3
                3590 |          2 | y1
              119229 |          2 | f
                3590 |          3 | g1>
              119229 |          3 | 4: Yeesh tried to play finessed y3
 and DC'd, lol
                3590 |          4 | why burn tho
              119229 |          4 | f
                3590 |          5 | y5; not sure what yeesh thought I 
was cluing
              119229 |          5 | 35 --- Why did Yeesh clue me this 
when he had y3 himself?
                3590 |          6 | b4
              119229 |          6 | f
              119229 |          7 | f
                3590 |          7 | f
              119229 |          8 | blind?
              119229 |          9 | f
(22 rows)
```

Why? The true note card_order got ignored, and instead each game_participant_id has their notes stored in sequential card_order *ignoring empty notes*. For example, Yeesh's notes in that game should be on cards 12, 14, 29 but in the db they are recorded as 0, 1, 2.

So I'm gonna need the old db to fix, if it's even possible

**Comment by padiwik** [comment]
yeah i'm gonna need a backup from before you deleted the notes row in game_participants in d7aec386ff5f5a0f5744f058e8c08e132c4e79d8

**Comment by padiwik** [comment]
migrate script was this: https://github.com/Zamiell/hanabi-live/blob/fce5eded33ac3c8c21275f794dde7080d52b58d3/scripts/python/migrate_db_notes_field.py

**Comment by padiwik** [comment]
```SELECT (SELECT game_id FROM game_participants WHERE game_participant_id = game_participants.id) FROM game_participant_notes GROUP BY game_participant_id HAVING COUNT(*) < MAX(card_order);```

first non-bugged game seems to be 103429

**Comment by padiwik** [comment]
Since zam can't find a relevant backup newer than December 2018, it seems we need to just delete old notes:
```
DELETE FROM game_participant_notes WHERE game_participant_id < 283710;
```

**Comment by Zamiell** [comment]
```
hanabi=> DELETE FROM game_participant_notes WHERE game_participant_id < 283710;
DELETE 467114
```
