### ISSUE TITLE
right click cards in the trash to make arrows

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#141]
The arrows should go away once a turn is changed.

**Comment by rogers-j** [comment]
![image](https://user-images.githubusercontent.com/5349111/45194075-52975f00-b206-11e8-8f61-fe862e82ecf1.png)
I'm undecided on this one.

**Comment by rogers-j** [comment]
The key to this change is that ui.js `showClueMatch` currently iterates over `playerHands[i].children[j]` for all `i` and `j` to remove the arrows. I suspect this could instead iterate over all cards in `ui.deck`. There's also a question of what the performance impact that would have.

The safest thing might be to do that first, see if people have worse performance problems, then try the rest.
If that goes fine, then in function `handleReplayIndicator` it would be fine to relax the condition `isInPlayerHand`.

**Comment by rogers-j** [comment]
And then 99a5e86 secretly does half of this.

**Comment by Zamiell** [comment]
fixed
