### ISSUE TITLE
card-reducer branch - in an ongoing game, pressing "home" and then "down" results in own hand being not draggable

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1410]

**Comment by robertos** [comment]
I couldn't repro this after the fix for #1413 . Can you try again pls?

**Comment by Zamiell** [comment]
ok

**Comment by Zamiell** [comment]
still happens, you actually dont have to use the replay, all you have to do is take some turns

**Comment by Zamiell** [comment]
so the handSetDraggable() function or whatever is not being called

**Comment by Zamiell** [comment]
can't repro now, /shrug
