### ISSUE TITLE
Pips aren't removed in certain Special-Ones

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1411]
Example https://hanabi.live/replay/231192/10 the y2 should have the red pip removed, because a negative 1 clue and a positive yellow clue must give negative red...

Also check if fixed on card-reducer

**Comment by asaelr** [comment]
In attempt to solve this type of bugs, I refactored the applyClue mechanism.
(The current logic separates colors from ranks, and this is the root of evil here)
It probably doesn't match the card-reducer.

Also, if you want to include that, probably have a look at it before - I have never touch any typescript before...

[hanabi.diff.txt](https://github.com/Zamiell/hanabi-live/files/4891381/hanabi.diff.txt)

**Comment by padiwik** [comment]
Also positive brown doesn't remove black and pink in special mix??

**Comment by Zamiell** [comment]
make sure to double check that asael's pr gets both of these bugs

**Comment by padiwik** [comment]
asaelr's pr is on prod right? There are still places where pips get crossed out when they should be removed entirely in the special variants, such as the first example and this brown 5 here https://hanab.live/replay/250770/42

**Comment by Zamiell** [comment]
> asaelr's pr is on prod right?

no, rob still has to accept this pr

**Comment by robertos** [comment]
That's my next priority after we get through the cr bugs

**Comment by Zamiell** [comment]
thanks to rob and asael, this can be closed now
