### ISSUE TITLE
card-reducer branch - regression, cards now show animations during the initial setup

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1413]
i fixed it in 11d897a747f3a2995ccfc4b6dea788f65ab9d072
but i think it regressed in f8c44df74930bc82bd5f20adfe66acca23327b02

**Comment by Zamiell** [comment]
nice, this is fixed now
additionally, the UI seems to load a lot faster!

**Comment by robertos** [comment]
It's all psychological but i'll take it :)
