### ISSUE TITLE
card-reducer branch: server should accept JSONs with 'suit' or 'suitIndex' 

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1415]
To make it easier to test, and to allow for people with saved JSONs to see their games without having to make changes

**Comment by Zamiell** [comment]
done

**Comment by robertos** [comment]
Nope, still bugged

**Comment by Zamiell** [comment]
I tried this, and it didn't work: https://stackoverflow.com/questions/18635671/how-to-define-multiple-name-tags-in-a-struct
not sure how to proceed

**Comment by Zamiell** [comment]
this won't work: https://stackoverflow.com/questions/38809137/golang-multiple-json-tag-names-for-one-field
because suitIndex is not a pointer and 0 is a valid suit index

**Comment by robertos** [comment]
People don't seem to be complaining, close this and move on? @Zamiell
