### ISSUE TITLE
try making black box slide around

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1421]

**Comment by Zamiell** [comment]
changed my mind

**Comment by robertos** [comment]
This would be pretty easy to do, if you wanted to. not sure if it's a desirable effect

**Comment by Zamiell** [comment]
i think it would look dumb in keldon mode
and it would look dumb in bga mode in the case where it has to animate from the bottom player to the top player

**Comment by Zamiell** [comment]
because it has to bypass all the other players

**Comment by robertos** [comment]
You could have a special case where it goes down fading, then shows from the top fading in (on bga). on keldon i agree it might be a bit extreme

**Comment by robertos** [comment]
but it's true that it's a common mistake for people not to realize it's their turn even though there are at least 5 visible signs

**Comment by Zamiell** [comment]
i'll leave it for you to test out

**Comment by robertos** [comment]
added to the infinite to do list :)

**Comment by Zamiell** [comment]
closing this
