### ISSUE TITLE
card-reducer branch: holding down left click should be released upon a new action happening

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1433]
otherwise you can trigger a bug like the following:

1) hold down left click to empathy a non-clued card
2) press right arrow
3) press left arrow

(results in bugged card images)

**Comment by padiwik** [comment]
probably cuz this isn't running anymore https://github.com/Zamiell/hanabi-live/blob/5af44118f2dae12a2a6491dd3da1bb7dcc734f95/client/src/game/ui/replay.ts#L155

solution, put that in the goto() function? i really hope that keeps the active hover pressed when a normal action happens in-game, if that doesn't cause bugs

**Comment by robertos** [comment]
make a selector.... :) subscribe to the things that should cancel the active hover

**Comment by Zamiell** [comment]
not fixed yet on card-reducer

**Comment by Zamiell** [comment]
thanks padi this is fixed now
