### ISSUE TITLE
card-reducer branch - in a reply, cards can be removed twice

### ISSUE THREAD

**Issue by asaelr** [Zamiell/hanabi-live#1446]
steps to reproduce (for example):
Watch the replay in the attached file
Go to turn 4
Check the empathy for the clued p4
It has an X over the '2' pip, even though only a single p2 is seen.

I'm pretty sure that the reason for that is line 114 of cardsReducer.ts , combined with the fact that in a replay, _ourPlayerIndex_ is a valid player index.
[buggyGameJSON.txt](https://github.com/Zamiell/hanabi-live/files/4908168/buggyGameJSON.txt)

**Comment by robertos** [comment]
Thanks Asael, does it repro on live?

**Comment by robertos** [comment]
Also I think it might have been recently introduced by Zamiel adding ourPlayerIndex...

**Comment by robertos** [comment]
I.e. #1439

**Comment by asaelr** [comment]
> Thanks Asael, does it repro on live?

no. only on card-reducer.

**Comment by robertos** [comment]
Should be fixed by #1452

**Comment by Zamiell** [comment]
closing then, thanks rob
