### ISSUE TITLE
disconnection in mobile version

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1453]
I always get this message after opening a replay in a new tab:
![7CB6C665-E907-4E20-BED6-FF8CA3C8CCDB](https://user-images.githubusercontent.com/46625461/87281188-a3abc480-c4fb-11ea-8eb8-5fad4293eea2.jpeg)

**Comment by padiwik** [comment]
so like close the other tab?

**Comment by Aigul9** [comment]
well, i don't have to close it on a computer. why does it work differently?

**Comment by padiwik** [comment]
does it work if you refresh the new tab that you're looking at? it's possible the mobile browser aggressively loads multiple tabs or something

**Comment by Aigul9** [comment]
it works after refreshing, but it's so annoying

**Comment by padiwik** [comment]
like this?
1. have hanabi.live open on web browser
2. go to discord
3. open a /replay link
4. the link loads with that error

sadly, i can't reproduce it on my phone

**Comment by Aigul9** [comment]
usually, I do this way:
1. Open hanabi.live 
2. Open history in another tab
3. Open previous games in separate tabs
ERROR

**Comment by padiwik** [comment]
i just got this once on a computer, weird

**Comment by Aigul9** [comment]
i don’t remember such messages or i got used to them
