### ISSUE TITLE
Fix/add breakpoints for header in History screen

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1455]
it probably changed because we added the logo

**Comment by robertos** [comment]
@padiwik I don't see the issue, can you please describe in more detail? (Also do you wanna go ahead and fix it? :) )

**Comment by padiwik** [comment]
slowly shrink the window width, at some point the new logo overlaps with the text to the left of the buttons

**Comment by robertos** [comment]
Over here (on c-r) the break that makes the text disappear happens much before the text hits. Do you have a screenshot?

**Comment by padiwik** [comment]
oh maybe someone added very conservative limits

**Comment by padiwik** [comment]
It's when you have friends 
![image](https://user-images.githubusercontent.com/24983586/88470690-7b45a200-cecd-11ea-962d-1dc1751f0e2b.png)

**Comment by robertos** [comment]
Gotcha. Yeah, gotta tweak them breakpoints, or make some icons a "pri2". Feel free to go for it, or it will stay in the backlog for now

**Comment by Zamiell** [comment]
tfw no friends FeelsBadMan

**Comment by padiwik** [comment]
Now we also need to fix them in pregame because of the new Change Variant button

**Comment by DrAnax** [comment]
I think this is no longer valid after #2000 and it should be closed

**Comment by Zamiell** [comment]
ok
