### ISSUE TITLE
When converting a game to a shared replay, players aren't synced with the leader

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1457]
* You need to actually toggle the Pause Shared Turns button twice to sync with the leader's shared turns
* I had this on hanabi.live multiple games in a row
* rob says it's probably not fixed in card-reducer
* Idk if it's reproducable by others

**Comment by Zamiell** [comment]
padi can you test to see if it happens on card-reducer

**Comment by padiwik** [comment]
I think this only happened when someone timed out. And it looks like you fixed that?

**Comment by Zamiell** [comment]
i dont know what fix you are referring to

**Comment by padiwik** [comment]
oh nevermind i was thinking of https://github.com/Zamiell/hanabi-live/commit/c576b1f9f265fe4b0443df9b34320855f4c4c127

**Comment by Zamiell** [comment]
paid does this still happen on card-reducer?

**Comment by padiwik** [comment]
was fixed in the ways i tested, so i guess i'll close

**Comment by Zamiell** [comment]
hooray
