### ISSUE TITLE
card-reducer branch - bug with rob's animate() function - strike constantly animates when clicking the back button

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1466]

**Comment by Zamiell** [comment]
(it should only animate the first time a strike happens, and even then, only if you are not in an in-game replay)

**Comment by Zamiell** [comment]
i think we need to add more args to it or something? not sure

**Comment by robertos** [comment]
I've seen the issue. In this case, it's because strikes are not in a reactive view, so the animation runs every turn (we replay all turns)

**Comment by Zamiell** [comment]
ill work on strike stuff then

**Comment by Zamiell** [comment]
i fixed this one!
