### ISSUE TITLE
broken empathy in pink-ones

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1467]
card's appearance doesn't change after crossing out all 1s
![image](https://user-images.githubusercontent.com/46625461/87463166-adc3e500-c619-11ea-848e-2bc1c41835eb.png)

**Comment by padiwik** [comment]
Why would it? This is information from cards you see, not from clues

**Comment by robertos** [comment]
+1 what padi said, the current design is to only change the card visual when you know only from clues (= it's 100% public information) that a card is determined

**Comment by Aigul9** [comment]
okay, thanks for clarification))
