### ISSUE TITLE
Start commands are confusing

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1468]
![image](https://user-images.githubusercontent.com/24983586/87470061-36c32800-c5ea-11ea-9580-2afce4bd7b6d.png)

I think it's weird to have them as 7 separate commands, right? Seems to make more sense to have `/s next` and `/s [2|3|4|5|6]` because they all do the same thing, so they should be one command.

Or at least, overload `/s` with the numerical arguments, or make it throw an error when invoked with arguments to avoid this confusion. Presumably you want to keep the `/s3` syntax for backward compatibility, so we would need to allow both with a space and without.

**Comment by Zamiell** [comment]
fixed

**Comment by padiwik** [comment]
on card-reducer :disappointed:
