### ISSUE TITLE
delete all Forgetful games from DB after card-reducer merge + server reboot

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1472]
in games with Compulsive + Forgetful, sometimes the server complains of invalid actions but sometimes it doesn't. Happens on both live, master, and card-reducer. Check for yourself with game IDs 150278 and 203671. In game 150278 for example, the invalid action can occur at turn 24, turn 33, or nowhere.

**Comment by padiwik** [comment]
(this also means we might be able to undelete 150316)

**Comment by padiwik** [comment]
Ok, well now we gotta delete I guess, nonexistent character is illegal
```
DELETE FROM games USING game_participants WHERE games.id = game_participants.game_id AND game_participants.character_assignment = 32;
```

**Comment by Zamiell** [comment]
ill wait until i reboot the server before running this

**Comment by Zamiell** [comment]
```
hanabi=> DELETE FROM games USING game_participants WHERE games.id = game_participants.game_id AND game_participants.character_assignment = 32;
DELETE 140
```

**Comment by Zamiell** [comment]
thanks padi
