### ISSUE TITLE
card-reducer: If you mouse over a clued card and then put it back, it will no longer be raised

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1474]
at least in a hypo, i didn't try in game

**Comment by Zamiell** [comment]
in a game, it immediately stops the raising as soon as you mouse over the card

**Comment by Zamiell** [comment]
this is a regression from 604ba77eac0ab4553e26a85ced8fc34d260d3284

**Comment by Zamiell** [comment]
the game lags out when beginning to drag a card, rob is this because of the shadows?

**Comment by padiwik** [comment]
> in a game, it immediately stops the raising as soon as you mouse over the card

yeah exactly, that's a better way to put it

**Comment by Zamiell** [comment]
confirmed fixed, thanks rob
