### ISSUE TITLE
card-reducer branch: rob should fix case 'cardidentities' in stateReducer.ts

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1475]

**Comment by robertos** [comment]
Did that regress recently?

**Comment by Zamiell** [comment]
yes, i had to comment out your code because it crashed terminated games

**Comment by Zamiell** [comment]
oh maybe its because terminated games dont send the full action list.
i'll rewrite some stuff on the server such that the termination code flows through the command_action.go function like the other things

**Comment by Zamiell** [comment]
todo - test to see if the commented code works now with the new server

**Comment by Zamiell** [comment]
seems to be fixed now, thanks rob
