### ISSUE TITLE
card-reducer branch: after morphing a card, subsequent clues do not touch it

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1480]

**Comment by robertos** [comment]
Morphing right now is only visual, because the rules can't really be enforced when cards can be illegal (e.g. 3 red 5's). So touching clues, playing/misplaying, etc will follow the original card's rule - feel free to change how that works.

**Comment by Zamiell** [comment]
for parity, morphing needs to not be visual, so one of us needs to start investigating/working on this

**Comment by robertos** [comment]
See that toast on the Assignees list? :) ==>

**Comment by Zamiell** [comment]
will close this now, thanks rob

should we open a new issue for morphed card identities / any other bugs?
