### ISSUE TITLE
prevent bombing at 3 strikes

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1492]

**Comment by padiwik** [comment]
isn't the game over by then? idk if an extra check is a good idea, since it would hide other issues

**Comment by robertos** [comment]
What does this one mean? There's already an alert when you're trying to play a known unplayable card right?

**Comment by Zamiell** [comment]
not for preplays

**Comment by padiwik** [comment]
so, any end of a game (e.g. timeout) should turn off all preplays, right? it's not due to the 3 strikes

**Comment by Zamiell** [comment]
done

**Comment by padiwik** [comment]
is this why i can't preplay with 2 strikes, or is that a different bug?

**Comment by padiwik** [comment]
edit: a known unplayable at the time of preplay

**Comment by Zamiell** [comment]
huh?
