### ISSUE TITLE
Feature request: /missing-scores for multiple people

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1496]
Currently, the recommended way is to spam /findvariant . But what if you're only looking for certain kinds of variants? It would be nice for us to have https://hanabi.live/missing-scores/padi/eljobe just like there exists https://hanabi.live/history/padi/eljobe

**Comment by Zamiell** [comment]
done

**Comment by padiwik** [comment]
it's not working for > 2 people

**Comment by Zamiell** [comment]
it works just fine for > 2 people if you use the correct url endpoint

**Comment by padiwik** [comment]
It's not https://hanab.live/missing-scores/padi/eljobe/Zamiel ? then what is it?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/blob/master/docs/FEATURES.md#website-endpoints

**Comment by padiwik** [comment]
but why. /history works fine when shared

**Comment by Zamiell** [comment]
because it is valid for usernames to be numbers

**Comment by padiwik** [comment]
Feels like the syntax should be `https://hanab.live/missing-scores/padi?players=2` then?

**Comment by padiwik** [comment]
i guess that's too much typing and doesn't happen anywhere else in the codebase

**Comment by Zamiell** [comment]
we could do that but it is a bit nicer to type theurl / edit the url when it is shorter
