### ISSUE TITLE
card-reducer branch: direction arrows should be in state

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1503]

**Comment by robertos** [comment]
I don't think so. We already have the states and actions for each segment in state, we have more than enough information to know if the arrows are shown

**Comment by Zamiell** [comment]
```
    // TODO: direction arrow should be in state,
    // or calculated from state
    globals.deck
      .filter((c) => c.state?.suitIndex === i)
      .forEach((c) => c.setDirectionArrow(i, direction));
```
you wrote this, right?

**Comment by robertos** [comment]
The code actually changed in #1514 , and I removed that comment, since the direction arrow is actually a UI only thing (i.e. you could be morphed, or have a note)

**Comment by robertos** [comment]
If this is not clear, I'm suggesting to close this.

**Comment by Zamiell** [comment]
ok
