### ISSUE TITLE
BUG: start a replay from JSON, crash

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1513]
gameCommands.ts:520 Uncaught TypeError: Cannot read property '0' of undefined
    at gameCommands.ts:520
    at Object.spectators (websocketInit.ts:96)
    at Connection.onMessage (Connection.ts:52)
(anonymous) @ gameCommands.ts:520
(anonymous) @ websocketInit.ts:96
onMessage @ Connection.ts:52

**Comment by robertos** [comment]
And the spectators label is empty because the crash was before writing the contents

**Comment by Zamiell** [comment]
can't repro. did you forget to reboot the server?

**Comment by robertos** [comment]
I was pretty sure I had rebooted, but couldn't repro today. Will reopen if I see it again
