### ISSUE TITLE
game "meters" are buggy

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1517]
![B83D08D7-02E3-423A-9239-4F695CD5D09A](https://user-images.githubusercontent.com/46625461/87973163-c5dfac80-cad0-11ea-9e6a-16f885be08c3.jpeg)
turns, score, clues, efficiency and pace are the same as on turn 1, taken time is undefined. it happens not always, so I can't reproduce it.

**Comment by padiwik** [comment]
Is this when you first enter a replay? i.e. #1362

**Comment by Aigul9** [comment]
mm, i can't tell. going back and forth or reloading the page (if the link contains a game id) doesn't help. i doubt that i'll be able to catch it on pc

**Comment by Zamiell** [comment]
reopen the issue if it still happens after the big patch next week
