### ISSUE TITLE
card-reducer branch: Cards can get stuck showing the backs.

### ISSUE THREAD

**Issue by eljobe** [Zamiell/hanabi-live#1522]
Steps to reproduce:
1. Mouse-down on a card.
2. Drag the card to the discard pile.
3. Very quickly Mouse-up, Mouse-down

Observed behavior: The card back continues to be shown to the user.
Expected behavior: The card face is shown to the user.

![image](https://user-images.githubusercontent.com/679924/88255692-62fd3980-ccb9-11ea-851a-d02dc664d4ef.png)

In this image the card you can see the back of in pepper_test's slot 3 is a yellow 4. But, it got stuck looking like this.

I'm on:
MacOS: 10.15.5
Chrome: Version 84.0.4147.89 (Official Build) beta (64-bit)

Let me know if you need a video of the reproduction steps.

**Comment by Zamiell** [comment]
im able to reproduce, thanks for the detailed report!

**Comment by Zamiell** [comment]
fixed, thanks
