### ISSUE TITLE
favicon change

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1527]
try:
- white card background
- black fireworks, or green fireworks

**Comment by Zamiell** [comment]
also, don't tilt the card, it looks weird

**Comment by padiwik** [comment]
can we use the discord one, but transparent background? it's nice and symmetricish

**Comment by Zamiell** [comment]
it doesn't look good at 16x16 pixels

**Comment by padiwik** [comment]
does it look like a jumbled mess of blue? cuz the discord cards should be the same size as the current favicon...

**Comment by Zamiell** [comment]
https://cdn.discordapp.com/attachments/187748727971119105/736730876318318663/favicon.png

**Comment by padiwik** [comment]
Perhaps with a light-colored border?

**Comment by Zamiell** [comment]
i have no idea how to make favicons or do any graphic design whatsoever, feel free to experiment yourself and find a better favicon

**Comment by robertos** [comment]
https://realfavicongenerator.net/
Have fun

**Comment by Zamiell** [comment]
closing this for now
