### ISSUE TITLE
Reentering a paused game shows as unpaused in the client

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1534]
* Start a game
* Pause it
* Have a player refresh the page, or a spectator join

Expected behavior:
The game appears paused

Actual behavior:
The pause screen is not shown, and instead the timer runs down client-side (does this also mean the client and server-side timers might not match? That seems bad; I've had people who ran out of time on live due to a laggy internet connection)

**Comment by Zamiell** [comment]
is this on c-r or master

**Comment by padiwik** [comment]
i tested on c-r, do you want me to check on live ?

**Comment by Zamiell** [comment]
nah

**Comment by Zamiell** [comment]
fixed, thanks
