### ISSUE TITLE
Up or Down 5 suit Piles being labeled Erroneously

### ISSUE THREAD

**Issue by MicahSE** [Zamiell/hanabi-live#1540]
In up or down 5 suit(This was occurring in 2 player, have not tested with more players), when playing a card from your own hand to start a pile(1/5/S) it will label the pile incorrectly.  For 1s/5s it does the opposite(down/up respectively) and for S's it auto labels them Down even before a 2 or 4 is played.  This is only seen by the player playing the card, and the labels are correct for other teammates.

This is not just a visual bug.  I.e. when playing a known Red 2 onto a Red 1 up stack(labeled down) it gives the 'This card is known unplayable, are you sure you want to play it' error.

**Comment by MicahSE** [comment]
A few more notes: Refreshing the page does not help.  It removes the wrong label, but the arrows on piles still point the wrong way.

Additionally, it messes up things like critical cards(if Red is going up, because it assumes going down, it will grey out the R5 as if it is trash, instead of giving it the exclamation mark)

**Comment by Zamiell** [comment]
fixed
