### ISSUE TITLE
Why is it my turn, I am not even in the game

### ISSUE THREAD

**Issue by TheDaniMan** [Zamiell/hanabi-live#1541]
![image](https://user-images.githubusercontent.com/15525142/88610055-a823c180-d053-11ea-87a1-080f807d71eb.png)

**Comment by Zamiell** [comment]
are you spectating?

**Comment by TheDaniMan** [comment]
Yes, if I go into replay and come out again it becomes my turn.

**Comment by Zamiell** [comment]
ok.
in the future, if you are opening a bug report, remember to post steps to reproduce, as opposed to just a vague question and a screenshot.

**Comment by TheDaniMan** [comment]
Right.
I'm not sure exactly how it works, but it seems that if I join any active game, open replay, go back and forth a bunch of times and exit replay then eventually it becomes my turn. I can't get it consistently yet but I got it to work after a few tries in 3 different games. Just try hitting all the buttons a few times?

**Comment by Zamiell** [comment]
was able to repro, is fixed now
