### ISSUE TITLE
Blind Play Sounds

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1543]
Please bring back the blind play sounds.  It's just nice to have sounds to differentiate between the two plays.  We just lost a game from this because one of the players thought it was a normal play when it was a blind play.

**Comment by robertos** [comment]
I don't think that was changed at all? @Zamiell

**Comment by padiwik** [comment]
looks like you forgot to add back blind sounds here https://github.com/Zamiell/hanabi-live/commit/3a96a90e7f04cecf13c49603da3451f02575c661#diff-7e2c3e38fc3ee7f1e51a2bcce4e34ef9 ?

**Comment by Zamiell** [comment]
fixed
