### ISSUE TITLE
Fix incorrect database entry code

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#155]
https://github.com/Zamiell/hanabi-live/blob/f0270343c4f7bd0caaa19e1c9d9ba86aec766790/src/gameEnd.go#L99

The code that inserts the game into the database after it is finished doesn't give a crap about whether the game was timed or not. The "timed" field is unused (always 0) and the other 2 time fields are filled with whatever the creator of the table had in the base time and time per turn boxes, regardless of whether or not the time checkbox was checked or not.

**Comment by Zamiell** [comment]
fixed
