### ISSUE TITLE
Throw it in a Hole: cards don't get played

### ISSUE THREAD

**Issue by sephirothx** [Zamiell/hanabi-live#1552]
When a card is played in a Throw it in a Hole variant game, it doesn't leave the player's hand. Screenshot after theandrewni attempts to play one of his ones:
![image](https://user-images.githubusercontent.com/1510856/88647570-6aac4c00-d0c6-11ea-811f-e83b3989bdc3.png)

Refreshing the page breaks the interface:
![image](https://user-images.githubusercontent.com/1510856/88647585-6f710000-d0c6-11ea-95bb-379c51146314.png)

**Comment by Zamiell** [comment]
fixed
