### ISSUE TITLE
Touch actions no longer work on cards

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1553]
on cards

**Comment by Zamiell** [comment]
not sure what could have done this, padi do you wanna investigate since this is kinda your thing

**Comment by padiwik** [comment]
yeah, my bet is when you disabled actions on tweening cards they didn't get re-enabled or something

**Comment by robertos** [comment]
I disabled listening, which is all actions, nothing related to specific events

**Comment by padiwik** [comment]
it got killed here https://github.com/Zamiell/hanabi-live/commit/79760aca3cc099e7cd9782bda33dbfbc40a29a04 (search for `touchstart`)

**Comment by padiwik** [comment]
after loading HanabiCardInit diff
