### ISSUE TITLE
Server updates timestamp for Discord at-here that did not send a notification

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#156]
Undesired behavior:

1. A user types `@here` into the channel by any means. Because they do not have the appropriate *Discord* permission, the notification does not exist.
2. The server [reads the inbound message](https://github.com/Zamiell/hanabi-live/blob/master/src/discord.go#L106) and updates the last time the message was sent. This resets the notification timer to the full two hours.
3. The user then types `/here`, but is blocked by the timer.

Suggested fix:
Remove (2). The server does not need to scan user messages for `@here`. This is contrary to the Discord permission model.

Alternative:
Check if the API property `MentionEveryone` works for `@here` and, if so, check that instead of parsing the string.

Users with permission to create a conventional `@here` notification can *bypass* the server's two-hour timer, but by default have no reason to do this instead of the expected `/here`.

**Comment by Zamiell** [comment]
fixed
