### ISSUE TITLE
get rid of shade in keldon mode and make black lines yellow

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1562]

**Comment by rogers-j** [comment]
Needs refinement for 5p:

![image](https://user-images.githubusercontent.com/5349111/89109538-ebd14f00-d3f6-11ea-9c12-cd439c6084fd.png)

**Comment by rogers-j** [comment]
Needs refinement for 5p:
![image](https://user-images.githubusercontent.com/5349111/89109557-115e5880-d3f7-11ea-91e9-08fee5130af1.png)
![image](https://user-images.githubusercontent.com/5349111/89109560-18856680-d3f7-11ea-91eb-b84a9ce63a44.png)

**Comment by Zamiell** [comment]
propose something specific

**Comment by rogers-j** [comment]
The stripe shouldn't go out of its box into the adjacent nameframe?

**Comment by Zamiell** [comment]
then where are you proposing that it goes

**Comment by rogers-j** [comment]
Goes? It just needs to stay inside the box. Maybe that means all the cards need to be slightly smaller.
