### ISSUE TITLE
Hand cursors should allow for configurable skin color

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1563]
Diversity is important

**Comment by marcmagus** [comment]
Thank you for addressing this. A WONTFIX would have been a serious issue for my group.

**Comment by robertos** [comment]
@marcmagus Let us know what you think of the current solutions (use the OS cursors, which are independently configurable)

**Comment by marcmagus** [comment]
We think it's a good solution. It takes it off your plate, the default will generally not be visually jarring (since people are used to it), and it's configurable.

**Comment by robertos** [comment]
This is currently live. Let us know if you have more feedback on it
