### ISSUE TITLE
Sometimes finesse/clued/cm borders disappear after/during replays

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1566]
Don't have a good repro yet

**Comment by padiwik** [comment]
are these cards that get played recently? like by clicking through the replay arrows real quick

**Comment by robertos** [comment]
I see the borders disappearing on cards on my hand/other people's hands. Yes clicking on arrows quickly seems to be related

**Comment by robertos** [comment]
Got a repro. during a game, draw a card, put "f" on slot 1, back one turn, forward one turn, finesse border is gone.
@Zamiell can you please take a look?
