### ISSUE TITLE
Site chat bypasses restrictions on server-wide notifications

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#157]
Repro step:

As any user, type `@here` into the website chat.

Per `src/commandChat.go`, this string will be sent to the Discord channel as the bot account, which (intentionally) has permission to create a message that notifies everyone.

(This also applies to `@everyone`. This is not recommended for testing.)

**Comment by Zamiell** [comment]
pretty sure i fixed this a while back but forgot to close this issue, please reproduce and see if the bug still exists

**Comment by Zamiell** [comment]
ok should be fixed now
