### ISSUE TITLE
Invalid chat commands shouldn't be broadcasted

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1576]
If you type /wrongcommand it should eat the message and show the error to the user, privately, and not to the world. See how twitch (or IRC) does it

**Comment by Zamiell** [comment]
i kind of like it because then i can add useful aliases

**Comment by robertos** [comment]
You can get it as telemetry, but we don't have to spam discord or the game chat

**Comment by Zamiell** [comment]
done
