### ISSUE TITLE
Played cards remain shifted up (as though clued) when played on the stacks

### ISSUE THREAD

**Issue by EhDrone** [Zamiell/hanabi-live#1578]
[Raised Card Bug.txt](https://github.com/Zamiell/hanabi-live/files/5009468/Raised.Card.Bug.txt)

Associated screenshot:
![image](https://user-images.githubusercontent.com/40768367/89089914-50dc6480-d365-11ea-8d00-fe5c4aff4df9.png)

**Comment by padiwik** [comment]
see #1567 , looks like rob fixed it and the bugfix should be on live soon?

**Comment by Zamiell** [comment]
its already on live

**Comment by padiwik** [comment]
ive noticed this tends to happen when you were looking at replay, exit replay, and immediately play your own card

**Comment by robertos** [comment]
I reproed this without looking at replay. Don't have a good repro

**Comment by Zamiell** [comment]
rob says that this should be fixed now, reopen if not
