### ISSUE TITLE
notes appear on cards in BGA layout

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#158]
In the BGA layout, if I hover over a card with a note in the top hand, the note appears on the card, instead of below it. This is only a problem in the BGA layout, in the normal layout, the note appears below the card. 

On BGA layout the notes should also appear below the card if there is no room above the card.

![note](https://user-images.githubusercontent.com/7376012/47608156-7d788500-d9f7-11e8-9ddb-0063026c0f9d.png)

**Comment by Zamiell** [comment]
oh i see its because it assumes your hand the note should appear above

**Comment by Zamiell** [comment]
fixed
