### ISSUE TITLE
Keyboard command for empathy

### ISSUE THREAD

**Issue by beri2** [Zamiell/hanabi-live#1580]
A key that, when pressed, activates the empathy mode (on all hands?) would be nice.
Thx

**Comment by rogers-j** [comment]
Toggle, or press-and-hold?

**Comment by padiwik** [comment]
This seems it would be especially useful in speedrun. Maybe Ctrl key, since Ctrl click is already mapped to empathy? but this is unintuitive for normal games

**Comment by rogers-j** [comment]
How does Ctrl interact with empathy?

**Comment by robertos** [comment]
I think holding ctrl or space to do empathy would be good

**Comment by Zamiell** [comment]
can't be control, i will use space

**Comment by padiwik** [comment]
oh true, control clashes with regular keyboard shortcuts

**Comment by beri2** [comment]
> Toggle, or press-and-hold?
Press-and-hold might be more convenient (on PC at least)

And how about, if your mouse is over a hand, empathy is only for that hand, and if it’s not empathy is for all hands?

**Comment by beri2** [comment]
> Toggle, or press-and-hold?

Press-and-hold might be more convenient (on PC at least)

And how about, if your mouse is over a hand, empathy is only for that hand, and if it’s not empathy is for all hands?

**Comment by Zamiell** [comment]
done
