### ISSUE TITLE
hypo bugs

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1585]
sometimes show or hide button after a couple of turns gets disabled:
![DE4F59F1-245A-4C2F-9CC2-C48F1154DFB6](https://user-images.githubusercontent.com/46625461/89152508-ef3a1700-d56b-11ea-91a7-e468030b1648.jpeg)
"back" works only for 1 turn, and then it's impossible to cancel more previous turns

**Comment by Zamiell** [comment]
> sometimes show or hide button after a couple of turns gets disabled

that's intended.
it gets disabled if you clue a hidden card. because then hiding it would make the clue invalid, if that makes sense

> "back" works only for 1 turn, and then it's impossible to cancel more previous turns

thats a bug, i will fix it

**Comment by Zamiell** [comment]
fixed
