### ISSUE TITLE
Timer starts when player is not yet loaded in

### ISSUE THREAD

**Issue by efaust** [Zamiell/hanabi-live#1586]
Had a game tonight where a player failed to load in. The client properly showed their name as red, as they had not yet synched, but started the timer anyway. On a particularly bad connection (like we had), a player may time out before ever getting to see the board.

**Comment by robertos** [comment]
I think this issue is related to Florrat's bad restart. This was a restart

**Comment by Zamiell** [comment]
- timer starts server side when the game starts, not when a player finishes loading
- i think its going to be pretty rare that loading takes more than 5 seconds, even on the slowest connections

**Comment by robertos** [comment]
I got permanently stuck until refresh

**Comment by Zamiell** [comment]
can you repro?

**Comment by Zamiell** [comment]
done
