### ISSUE TITLE
If you clue a card, then play it, then rewind (hold left arrow), card can stay raised on turn before it was clued

### ISSUE THREAD

**Issue by robertos** [Zamiell/hanabi-live#1598]
It's related to the "unclue" happening before the animation where it goes back to the hand finishes.
E.g.
Clue a card on turn 2
Play it on turn 5
Hold left
If the animation of the card moving back from the playstack is still happening when the replay goes from turn 2 to 1, then the card stays raised.

Also repros on post game / JSON replays.

**Comment by Zamiell** [comment]
261882

**Comment by robertos** [comment]
+ repros on pretty much any game :)
