### ISSUE TITLE
Create Forum or Message Board

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1603]
Any way we can have some sort of Forum or Message Board for Hanabi topics?

**Comment by robertos** [comment]
Is Discord not enough? :P

**Comment by Zamiell** [comment]
I think discord serves this purpose just fine for the current level of engagement. Discord doesn't have threads, but the traffic isn't high enough to warrant anything more complicated. As for conventions, we already have a message board - GitHub issues.
