### ISSUE TITLE
Duck variant doesn't quack anymore

### ISSUE THREAD

**Issue by iwantthequackback** [Zamiell/hanabi-live#1607]
While playing the duck variant, when cluing cards, instead of going *quack* the games plays the normal sound.

**Comment by fpvandoorn** [comment]
Someone found this important enough to create a Github account for it :)

**Comment by robertos** [comment]
🦆

**Comment by padiwik** [comment]
🦆🦆

**Comment by NoMercyO** [comment]
This person Ducks

**Comment by robertos** [comment]
I think this might be the case for Moo and Oink as well

**Comment by robertos** [comment]
Here is the death of the quack, oink and moo: https://github.com/Zamiell/hanabi-live/commit/bed003f33e7ee55da76f0a274907e13e22d9f5f4#diff-7e2c3e38fc3ee7f1e51a2bcce4e34ef9L124-L137
Solution is likely to do it client side :)

**Comment by robertos** [comment]
Pri-1 because regression and Quacker character getting action

**Comment by Zamiell** [comment]
fixed
