### ISSUE TITLE
detrimental character, empathy on slow-witted

### ISSUE THREAD

**Issue by florian-5f3759df** [Zamiell/hanabi-live#1617]
https://hanab.live/replay/270021

When clicking scharkbite's hand I saw his slot 2 and 3 as perfectly known, even thought it was not.

(Additionally there was a gamebreaking bug at the end, but that is already found as #1615)

**Comment by Zamiell** [comment]
what about his slot 4?

**Comment by florian-5f3759df** [comment]
When I go into the replay now:
On turn 1 empathy reveals slot 2,3,4
On turn 2-4 empathy is as expected
On turn 5-8 empathy reveals slot 2
On turn 9-14 empathy reveals slot 2,3

I'm not sure if this is identical for other players watching the replay, since I was of course part of the game, which might change things (like reorder the players).

**Comment by Zamiell** [comment]
fixed
