### ISSUE TITLE
Orange Card Numbers

### ISSUE THREAD

**Issue by MicahSE** [Zamiell/hanabi-live#1621]
For reference, this is what I mean: ![image](https://user-images.githubusercontent.com/50384292/90277986-9d7b7180-de34-11ea-9cc1-d0aafbe90594.png)

(I believe these kinds of numbers are used in variants like pink? where number clues don't give 100% information to cards, but this was just a dark rainbow game).

This occurred after being in game, server restarted, and then the numbers changed color.  This occurred for all players in the game.  The issue has persisted after:
-Refreshing the page
-Restarting the game
-Creating a new lobby

**Comment by Zamiell** [comment]
@robertos is this related to your PR?

**Comment by Zamiell** [comment]
@MicahSE provide steps to reproduce

**Comment by padiwik** [comment]
For example: plus, DMoney, scharkbite just created a fresh Omni (6 Suits) game. I started spectating at the turn when 2 was clued to DMoney, touching a y2. Now, all cards newer in the deck than the y2 have an orange 2 in empathy, which remains when going back and forth in replay regardless of any new clues that invalidate the 2

I don't think the variant matters at all here

**Comment by robertos** [comment]
@Zamiell not sure, maybe. I need to check

**Comment by robertos** [comment]
It might be related to Asael's

**Comment by rggallison** [comment]
my teammates and I are also seeing this.

**Comment by timotree3** [comment]
https://hanab.live/replay/270831/17 empathy on timotree you can see orange card pip

**Comment by timotree3** [comment]
It looks like every time a number is clued, all future cards drawn will have an orange mark for that number
