### ISSUE TITLE
Blind Play Last Card fail

### ISSUE THREAD

**Issue by FearfulFred** [Zamiell/hanabi-live#1626]
Game #271283.  Selected "blind play last card" as option.
In the critical moment, a player was warned "can't play a card not in your hand".  
Difference between 29 points and 30!

p.s.  Hanab.live is our favorite family hangout.  Thanks!

**Comment by jasonnoble** [comment]
This happens both when the blind play card is playable and not playable.

![image (26)](https://user-images.githubusercontent.com/22501/90435148-d5302680-e08b-11ea-8a77-53f91b0231ba.png)

**Comment by Zamiell** [comment]
fixed

**Comment by FearfulFred** [comment]
Thank you!Fear{less|ful} Fred
    On Monday, August 17, 2020, 04:51:11 PM PDT, James <notifications@github.com> wrote:  
 
 


fixed
