### ISSUE TITLE
strikeout crosses behave bonkers when the gambler character is in the game

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#163]
sometimes a strike appears in the 0th position (outside the strike box), sometimes in the middle (2nd position). Strange stuff.

**Comment by RaKXeR** [comment]
My guess is that the position of the ghost strike icon depends on how many strikes have happened before the gambler "fails to play" a card that doesn't cost a strike

**Comment by Zamiell** [comment]
im just going to delete gambler because it is a stupid character
