### ISSUE TITLE
Timer continues to run for paused, spectated game

### ISSUE THREAD

**Issue by Rasmoh** [Zamiell/hanabi-live#1635]
1. Start a new timed game
2. Pause game
3. Spectator joins game

Expected: No timer shows in game for spectator
Actual: Timer is displayed behind pause modal and runs down to zero for spectator

**Comment by Rasmoh** [comment]
It also seems like if a player of the paused game refreshes the page they'll see the same behavior.

**Comment by Zamiell** [comment]
how can you even see it behind the thing?

**Comment by Zamiell** [comment]
fixed
