### ISSUE TITLE
keyboard shortcuts work only partially in hypothetical

### ISSUE THREAD

**Issue by chmallon** [Zamiell/hanabi-live#1636]
* 12345, QWERTY and Ctrl+Enter work fine,
* Tab does not, i.e. nothing happens.
* A and D work half, i.e. you get the dialog for the slot input, but then you get the error message "You cannot perform a game action in a shared replay."

**Comment by chmallon** [comment]
> * A and D work half, i.e. you get the dialog for the slot input, but then you get the error message "You cannot perform a game action in a shared replay."
1. If you leave the replay by clicking on lobby while this error message dialog is shown, then the dialog does not vanish.
2. If you leave the replay by pressing Esc and then create another shared replay, then the whole game screen is darkened.

**Comment by padiwik** [comment]
On newest version of master, ctrl+enter works but 12345 / QWERTY / Tab / A and D don't work, both in hypo and in game

The second issue you describe is tracked in / related to #1026

**Comment by padiwik** [comment]
Now it looks like just Tab is broken

**Comment by Zamiell** [comment]
fixed now
