### ISSUE TITLE
Play turn_us after any other turn sound

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1639]
* This makes it consistent so that the sound on your turn is always different from someone else's turn. It doesn't really make sense for the sound to be distinct only for clue actions and normal discards.
* Should help the perennial issue of people not noticing it's their turn
* Perhaps change the sound so it's distinct from the piano. Could use a bell. CM reports that they have never noticed turn_us is a distinct sound

**Comment by Zamiell** [comment]
i dont want two sounds to play in a row
