### ISSUE TITLE
don't ping the table creator if he's in the waiting list (stop pinging yourself)

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#164]
if someone on the waiting list creates a table, the bot pings them. Since the bot does have the ability to "link" people between the server and discord when they have the same name, it is a bit unusual for this to happen. Obviously the ideal behaviour is the bot simply omitting the ping to that person as if they weren't in the waiting list.

**Comment by Zamiell** [comment]
i'd rather not since it signifies that they are being taken off the waiting list. otherwise you will get on the waiting list and then never know that you are taken off the waiting list
