### ISSUE TITLE
bug: Graphic glitch while pre-playing during turn start

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1645]
![Screenshot from 2020-08-17 15-24-16](https://user-images.githubusercontent.com/6473438/90438125-87beb400-e0a1-11ea-8140-96baa704944b.png)
I pre-played blue 3 as my turn started and this happened

**Comment by Zamiell** [comment]
1) can you reproduce it in a test game
2) are there any errors in the javascript console

**Comment by timotree3** [comment]
my only idea to reproduce it was to open hanab live in two seperate browser windows but I couldn't move fast enough to play at the same time on both windows

**Comment by Zamiell** [comment]
i dont understand. isn't that the point of preplay, e.g. you dont have to do 2 things at once?

**Comment by timotree3** [comment]
this has happened one time. it happened when I pre-played a card exactly at the same time as my turn started

**Comment by timotree3** [comment]
if it was a normal pre-play I wouldn't have to do two things at once but it's not. I have to set the preplay at the same time as I start my turn which means doing two things at the same time

**Comment by timotree3** [comment]
steps to reproduce:

1. enter a game
2. as the player going first, enter into your JS console
```
globals.store.dispatch({
      type: 'premove',
      premove: {type: 0, target: 0}}
);
```
3. see the first weird behavior:
![Screenshot from 2020-08-20 13-20-20](https://user-images.githubusercontent.com/6473438/90804295-0016b680-e2e8-11ea-947f-a28e3732119e.png)
4. click cancel pre-play
5. see the mentioned behavior in the issue description
![Screenshot from 2020-08-20 13-20-42](https://user-images.githubusercontent.com/6473438/90804331-1755a400-e2e8-11ea-80de-116c73ab6f36.png)

**Comment by Zamiell** [comment]
> as the player going first, enter into your JS console
globals.store.dispatch({
      type: 'premove',
      premove: {type: 0, target: 0}}
);

that doesn't make any sense, how would you be able to premove if it is currently your turn

**Comment by timotree3** [comment]
Well when I caused it naturally it happened because I premoved at the same time as my turn started. There is lag involved with these things. I think the fix would be to put a check somewhere in the premove workflow for whether it's still not your turn.

**Comment by Zamiell** [comment]
ok, i put some more turn validation on the pregame, it should be fixed now
