### ISSUE TITLE
When Discord messages get replicated in the lobby, the usernames in @-mentions do not match Discord.

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1653]
For example, in Discord:
![Discord Mention](https://user-images.githubusercontent.com/6473438/90783877-a48bff00-e2ce-11ea-8797-f755512f77f4.png)

Replicated to lobby:
![Lobby Mention](https://user-images.githubusercontent.com/6473438/90784057-d309da00-e2ce-11ea-80b0-47e7652a76c1.png)

The desired behavior would be to put the server-wide discord nickname of the mentioned user in the lobby, not their discord username.

**Comment by timotree3** [comment]
I'm working on this now and should have a PR in the next hours.

**Comment by timotree3** [comment]
Hmm. Actually it looks like we already replace all @-mentions with calls to `discordGetNickname`. It seems like what's really happening then is that `discordGetNickname` is failing to get the server-wide nickname and is falling back to the username.

**Comment by Zamiell** [comment]
oh its probably a regression because i updated the version of discordgo recently

**Comment by Zamiell** [comment]
do you wanna see if it works on the version from 30 days ago

**Comment by Zamiell** [comment]
no, i meant test to see if it works on the commit from 30 days ago

**Comment by timotree3** [comment]
For that I'm needing to create a test discord server and bot token of my own. While creating the bot I noticed that there's a setting for whether or not the bot intends to query the set of guild members
![Screenshot from 2020-08-20 11-12-18](https://user-images.githubusercontent.com/6473438/90790436-0dc34080-e2d6-11ea-964b-371936cfae4f.png)

Is this set for your bot?

**Comment by Zamiell** [comment]
you wont be using my username and password, you will need to create your own
