### ISSUE TITLE
Add DISCORD_GUILD_ID as its own variable in .env

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1655]
Currently the code just reads the first Channel ID. It is no longer the case that #general channel ID matches the guild ID

https://discord.com/developers/docs/change-log#breaking-change-default-channels

**Comment by timotree3** [comment]
I'm pretty sure that we no longer ever use the guild ID after my PR

**Comment by padiwik** [comment]
don't you use it to query guild members?

**Comment by timotree3** [comment]
oh yeah good point

**Comment by timotree3** [comment]
alternative: make the bot multiple-guild compatible by not requiring this to be configured at all. I'm working on a PR for that now.

**Comment by Zamiell** [comment]
why would we want the bot to be multiple-guild compatible

**Comment by padiwik** [comment]
why are you closing the issue though?

**Comment by Zamiell** [comment]
what else do you want to do

**Comment by timotree3** [comment]
he pushed a commit that addresses it
