### ISSUE TITLE
greedy error causes clue options to vanish

### ISSUE THREAD

**Issue by samweiler** [Zamiell/hanabi-live#166]
When 'greedy' gives a bad clue (touching only one card), an error appears.  Click it away, and the boxes for gives clues go away entirely - or don't redraw.

**Comment by samweiler** [comment]
I'm also seeing the problem intermittently with 'conservative'.

**Comment by fpvandoorn** [comment]
This is a problem with all characters. The workaround is to either refresh or go back to the lobby and return to the game. Zamiel said that he was not interested in fixing this bug.

**Comment by Zamiell** [comment]
wont fix, just refresh or be smart enough to not give illegal clues
