### ISSUE TITLE
Shared Missing Scores List Bug

### ISSUE THREAD

**Issue by Bonja97** [Zamiell/hanabi-live#1666]
If a player for the shared list has an illegitimate maximum score, the respective variant appears in the missing scores list even if another player has a legitimate maximum score for it.

Example: 3-Player Rainbow (6 Suits) for Bonja97, melwen, and joelwool. Bonja97 has 30/30 with bottom-deck blind-play; melwen has the same score with no handicap options, but the variant still appears on the list.

https://hanab.live/scores/Bonja97
https://hanab.live/scores/melwen
https://hanab.live/shared-missing-scores/Bonja97/joelwool/melwen

**Comment by timotree3** [comment]
The problem on the linked page hasn't disappeared.

**Comment by Zamiell** [comment]
because the server hasnt restarted yet
