### ISSUE TITLE
Contrarian character needs debuff

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#167]
I really love the contrarian character, but currently it is a advantageous character (if played well), not a detrimental one. It would be nice if it is debuffed.

The best debuff I can think of is `end-game lasts for 2 turns`. Here end-game means the period after the last card is drawn. This is seemingly unrelated, but
* Contrarian makes the end-game ambiguous anyway. My rulebook states "each player plays one more time" which suggests that each player plays *exactly* one more time, which is not possible without ignoring contrarian in the last round.
* Contrarian makes this debuff interesting in that the team can always guarantee that a bottom-decked 5 is still playable (assuming no other constraints) . 

This is a significant debuff: if anyone other than contrarian has a playable card, there is 1 card in the deck and that is a 5, then it is not possible to play both those cards. But if someone thinks of a better debuff, I'm all for that.

**Comment by Zamiell** [comment]
done
