### ISSUE TITLE
Not recognizing what turn it is

### ISSUE THREAD

**Issue by MicahSE** [Zamiell/hanabi-live#1674]
Currently in a game, and sometimes it will display as being my friend's turns when in reality I'm supposed to play, or sometimes the "Your turn" thing sticks around when it's their turn.  Either way, all of us have had to refresh on almost all of our turns in order to get replay/notes/playing cards to work

Example of it being my turn, but DJ is still highlighted, and his clued cards don't have the border(experienced after he played a card): 
![image](https://user-images.githubusercontent.com/50384292/90987157-e333ea80-e556-11ea-93ec-7b693c596bfd.png)
NOTE: Also unable to enter replay mode in this state, until refresh

**Comment by MicahSE** [comment]
Example of my turn having just ended, but the your turn button sticking around for the next person's turn: 
![image](https://user-images.githubusercontent.com/50384292/90987266-a4526480-e557-11ea-9781-27c78a8398c4.png)

**Comment by Zamiell** [comment]
are there any errors in the javascript console

**Comment by jasonnoble** [comment]
![Screen Shot 2020-08-24 at 12 18 24 PM](https://user-images.githubusercontent.com/22501/91081190-f51f9700-e603-11ea-94d3-d54886a3a089.png)

**Comment by Zamiell** [comment]
try now

**Comment by jasonnoble** [comment]
Better for me.  Thanks @Zamiell !

**Comment by Zamiell** [comment]
ok sounds like this is fixed then
