### ISSUE TITLE
Timer weird bug when right clicking

### ISSUE THREAD

**Issue by iwantthequackback** [Zamiell/hanabi-live#1678]
I right clicked my timer so it would stop at my turn. Another used said it pause at their turn, thus unpaused the timer. I was AFK (hence the pause) so I ran out of time and the timer got stuck at 0:00. We could play 1 more turn but then it was over. Here's a screenshot.
![timersweird](https://user-images.githubusercontent.com/69444436/90993579-708d3400-e583-11ea-967a-dc9af4592f23.jpg)

**Comment by Zamiell** [comment]
should be fixed now
