### ISSUE TITLE
Cluing trash doesn't make it opaque

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1681]
https://hanab.live/replay/279627/39 the fill should reload to opacity 1 as soon as the clue happens

**Comment by padiwik** [comment]
(actually to repro you need to move back a bit so the card starts off faded)

**Comment by timotree3** [comment]
Notably, entering and leaving empathy on the card while it's clued and faded makes it opaque again. I suspect that setStatus is not being called when it should be

**Comment by Zamiell** [comment]
sounds like you are close to a PR? ; )

**Comment by timotree3** [comment]
The problem is that `onCardStatusChanged` is only called when the CardStatus changes for a card, and that only changes when a card is discarded or played, not clued.

Solutions I see:
- Change CardStatus to include an enum variant `CluedTrash` or similar.
- Change `onCardStatusChanged` to run also whenever `GameState.clues` changes.

Which do you think I should implement?

**Comment by timotree3** [comment]
Actually option one doesn't make sense because CardStatus is determined based on card suit and rank combinations not based on individual cards.

**Comment by robertos** [comment]
Neither - you should figure out if the clues on the card changed, not GameState.clued.

**Comment by timotree3** [comment]
I don't follow. `onCardStatusChanged` does that. It's just not running often enough

**Comment by robertos** [comment]
Yes, you just have to change the subscription to include any cases where the clues on that card change

**Comment by timotree3** [comment]
"that card" doesn't make sense. `onCardStatusChanged` iterates over every card

**Comment by timotree3** [comment]
ooh. are you suggesting an entirely different callback? one that checks the latest clue given and updates the fading for newly touched cards when necessary?

**Comment by robertos** [comment]
Eventually, yes. But for now, subscribing to GameState.clues is fine.
