### ISSUE TITLE
Entering a password game maintains the password on the next Create Game

### ISSUE THREAD

**Issue by sephirothx** [Zamiell/hanabi-live#1688]
Repro steps:
1. Enter (or attempt to enter) a password game
2. Create Game
3. The field 'password' will contain the password used on step 1

**Comment by Zamiell** [comment]
thats intended

**Comment by sephirothx** [comment]
Is it the intended behaviour to force the same password you used to enter another player's lobby, the next time you create your own lobby?

**Comment by Zamiell** [comment]
what do you mean force. you can use any password you like

**Comment by sephirothx** [comment]
maybe my repro steps are not clearly explaining the problem. I will make it clearer:
1. Player A creates a game with password 'asd'
2. Player B joins the game inputting 'asd' as password
3. Player B leaves the lobby
4. Player B attempts to create a new game. 'asd' will be set as default password after clicking on Create Game

**Comment by Zamiell** [comment]
thats intended because the same group of friends is likely going to use the same shared password

**Comment by sephirothx** [comment]
I see, nevermind then. I didn't think about it because i have no friends

**Comment by Zamiell** [comment]
FeelsBadMan

**Comment by padiwik** [comment]
unfortunately this means that after entering a password game once, you need to manually clear the password when you want to create a non-password game. I'm not sure if it's obvious that leaving the password field blank is equivalent to not having a password

**Comment by timotree3** [comment]
Maybe a good solution would be to have a checkbox that enables password or not next to the password field and while the password field gets overwritten by games you join, the checkbox state matches the last game that you created. also for UX the checkbox would enable as soon as you typed something into the password field and would disable as soon as you cleared it

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/c189564bc09622a55caa2dee89077650a973b639
