### ISSUE TITLE
softlock with Insistent or Vindictive at 0 clues

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#169]
The Insistent and Vindictive are sometimes required to clue, and the game softlocks if they are at 0 clues. The game should probably end with a score of 0 when this happens. Forcing the previous player to generate a clue is not a possibility (they try to play a card that they think is a playable 5, and then an error message gives a channel of information. Even harder is the interaction with other characters, which might be forced to clue or play themselves).

**Comment by Zamiell** [comment]
fixed
