### ISSUE TITLE
watching game replay from JSON borked

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1696]
I opened the replay from JSON data of game `#279627` and all the cards were either red or yellow when in the real game there were tons of other suits. Due to the lack of green cards in the opening hand of the replay, the rest of the replay is borked because the first clue of the game (greens) is "empty".

Steps to reproduce:
1. go to https://hanab.live/export/279627
2. watch a JSON replay with that data

**Comment by Zamiell** [comment]
fixed
