### ISSUE TITLE
Mark notes as read on touch

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1700]
Currently tapping a card will rotate its note 15 deg as if it's unread, but we want to mark it as read

**Comment by Zamiell** [comment]
should i assign it to you?

**Comment by padiwik** [comment]
if you don't want to fix it, i'll get around to it eventually

**Comment by Zamiell** [comment]
i dont care about mobile so its all you

**Comment by padiwik** [comment]
looks like this got fixed somehow

**Comment by Zamiell** [comment]
maybe by the mouse refactor
