### ISSUE TITLE
Timer Issue

### ISSUE THREAD

**Issue by iwantthequackback** [Zamiell/hanabi-live#1702]
I created a game with 2.5 minutes each + 30 sec each turn, but the game started with 2:28 instead of 2:30.

I did do a /pause function at the beginning of the game, but it was never my turn, and I still had 2:28 time left.

![timer issue](https://user-images.githubusercontent.com/69444436/91503542-b8b89900-e898-11ea-8476-ecb2b3f1b3f0.png)

**Comment by DrAnax** [comment]
This must have been fixed via #2324 and #2301

**Comment by Zamiell** [comment]
well the /pause command was removed, so i guess this would no longer be an issue
