### ISSUE TITLE
Hypothetical says No clues incorrectly

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1703]
Steps to reproduce:

1. Create a shared replay with game ID `282088`
2. Enter hypothetical

Errors in console: none

Screenshot:
![Screenshot from 2020-08-27 19-59-18](https://user-images.githubusercontent.com/6473438/91506307-d0475000-e89f-11ea-9c54-31a1228535f8.png)

**Comment by Zamiell** [comment]
fixed
