### ISSUE TITLE
Prism START should not be yellow (leaking "rank 7")

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1705]
https://hanab.live/replay/282269/38 use empathy on timotree

**Comment by Zamiell** [comment]
i think because it only has "positive" prism logic but not "negative" prism logic
do you want to look into this

**Comment by timotree3** [comment]
Yeah I'll take a look

**Comment by timotree3** [comment]
... wow.. In this case it was correct to display as possibly prism. The prism START is yellow and was not visible

**Comment by robertos** [comment]
The underlying bug is, Prism START should not be yellow

**Comment by timotree3** [comment]
What color should Prism START be?

**Comment by robertos** [comment]
Either no color (white) or all colors (rainbow)

**Comment by timotree3** [comment]
Another good candidate it dual-color with whatever colors prism 1 and 5 are

**Comment by Aigul9** [comment]
I think, prism should be more confusing. 1, 5, start: r/p, 2/4: y/b, 3: green for no variant

**Comment by Zamiell** [comment]
start card is rank 0, thus it should be `len(colors) - 1`

**Comment by padiwik** [comment]
note this change may break some old games where people clue a single START with the wrong color, but hopefully not

**Comment by robertos** [comment]
I don't think Start is rank 0. Otherwise it should be written zero, shown in the pips...

**Comment by Zamiell** [comment]
its not shown in the pips because there is no room for it

**Comment by padiwik** [comment]
is START explained as rank 0 in any doc? or is it just the logical convention

**Comment by Zamiell** [comment]
convention

**Comment by robertos** [comment]
If it's not visible, there's no "logical convention" for prism. It could be rank 0, 1/5, 6, 3 (1 + 5 / 2), or 999

**Comment by Zamiell** [comment]
i didn't say it was logical, i said it was a convention

**Comment by Zamiell** [comment]
fixed now, will push to master when the stats update is done
