### ISSUE TITLE
Insistent charcter doesn't work

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#171]
It currently allows you to give clues not touching the same cards, I think even to different players. I do not know if you are also allowed to discard. I think there is a bug here where `name2` should be `name`, but I don't know if that will fix everything:
https://github.com/Zamiell/hanabi-live/blob/55ec7c1a5a745214b8b75c4e6b1cd50ec283f591/src/character.go#L626

**Comment by Zamiell** [comment]
it is already set that way, can you verify?

**Comment by Zamiell** [comment]
reopen if still bugged
