### ISSUE TITLE
Difficult to see X on black suit

### ISSUE THREAD

**Issue by english5040** [Zamiell/hanabi-live#1712]
It's difficult to tell if there's an X on the black suit or not. Maybe the X should be colored white if it's on the black suit?

**Comment by timotree3** [comment]
I'm misplayed black cards 3 times so far because of this

**Comment by timotree3** [comment]
For me, I skip over the black pip with my eyes because it looks crossed out, so the white X solution wouldn't help me. Should we just change the black pip? Anyone wanna design a new one?

**Comment by Zamiell** [comment]
zamiel from the future here:
we use the katakana he symbol now for the black pip, which solves the problem.
