### ISSUE TITLE
Self-identified member of Hyphen-ated group

### ISSUE THREAD

**Issue by beri2** [Zamiell/hanabi-live#1714]
As I’m using the hyphen-ated features, I’m tagged as self-id’d member of the Hyphen-ated group. I believe I’m not (won’t be) the only one using these features despite not playing with H conventions and therefore not being part of the Hyphen-ated group.
So it may be(come) confusing for some people.

My suggestion would be:
- make it possible to use the features without being tagged "H"
- create categories that players can identify to depending on what playstyle they use, so that you can easily spot players willing to play the same style as you (such as "H") – ideally checkboxes so you can pick more than one playstyle

**Comment by Zamiell** [comment]
that sounds too complicated for now. 99% of people who check that checkbox are actually members of the hyphen-ated group
