### ISSUE TITLE
Fractional seconds should be hidden

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1718]
![image](https://user-images.githubusercontent.com/24983586/91743850-789e3280-eb86-11ea-9d3f-0836496e78ce.png)
looks weird

**Comment by Zamiell** [comment]
what is this a screenshot of

**Comment by padiwik** [comment]
some /seed page, but the issue appears in other places too

**Comment by Zamiell** [comment]
which page

**Comment by Zamiell** [comment]
what other places

**Comment by padiwik** [comment]
https://hanab.live/history/bonja97
https://hanab.live/seed/p3v0s123

**Comment by padiwik** [comment]
also the variant pages, which i think use a different model https://hanab.live/variant/4

**Comment by Zamiell** [comment]
fixed
