### ISSUE TITLE
Filters are extremely slow/broken on large history pages

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1719]
https://hanab.live/history/florrat2

**Comment by Zamiell** [comment]
define broken. it works for me just fine.
but yes, it is slow. feel free to submit a PR if you can think of a better/faster way to do it.

**Comment by padiwik** [comment]
i define broken as I went to florrat's page, changed the players to 2, and nothing changes

**Comment by Zamiell** [comment]
did you let the page finish loading first?

**Comment by padiwik** [comment]
i let it load fully (which seems necessary) and now the page is frozen lmao

**Comment by Zamiell** [comment]
its not frozen, its just updating the dom

**Comment by padiwik** [comment]
are the row colors supposed to be alternating even after sorting? they aren't 
![image](https://user-images.githubusercontent.com/24983586/91754963-57ded880-eb98-11ea-8e65-4d69a925db36.png)

**Comment by Zamiell** [comment]
i added code to manually set the colors.
however, this is making the code even slower than it already is.
