### ISSUE TITLE
A Blind Spot/Oblivious character can clue the hand he can't see, but only if it's a color clue

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#172]
It's not forbidden server-side for a Blind Spot/Oblivious (BS/O) character to clue the hand he can't see. The client code currently allows them to do this, but only with color clues, and only if another player has a card of that color.

We should determine if we want this functionality. A broader question is how we want these characters to differ from Spiteful/Insolent; being able to clue the hidden hand may be a nice differentiator. Furthermore, we may want to conditionally allow empty clues like we used to do for philosopher, or else the BS/O player can gain information from server errors, or something like that.

**Comment by Zamiell** [comment]
what do you want me to do exactly?

**Comment by aliblong** [comment]
Like I explain in the post, fix the bug where BS/O characters can sometimes clue color to the hand they can't see, either by making it so they can *always* or *never* clue the hand they can't see.

**Comment by Zamiell** [comment]
which is it, always or never?

**Comment by aliblong** [comment]
Well, I vote for always, and since nobody else has weighed in, we can probably just go with that.

**Comment by Zamiell** [comment]
so then it is only a client side fix right?

**Comment by aliblong** [comment]
I think the server would have to exceptionally allow empty clues from BS/O, even if empty clues were disabled globally. Otherwise, BS/O could gain extra information by trying to give clues which end up being empty and are therefore rejected by the server.

**Comment by Zamiell** [comment]
ok, I added the following logic to both server and client:

```
            // By default, disable the "Give Clue" button if
            // the clue will "touch" no cards in the hand
            const enabled = match
                // Make an exception if they have the optional setting for "Empty Clues" turned on
                || globals.emptyClues
                // Make an exception for the "Color Blind" variants (color clues touch no cards)
                || (globals.variant.name.startsWith('Color Blind')
                    && clueButton.clue.type === CLUE_TYPE.COLOR)
                // Make an exception for certain characters
                || (globals.characterAssignments[globals.playerUs] === 'Blind Spot'
                    && who === (globals.playerUs + 1) % globals.playerNames.length)
                || (globals.characterAssignments[globals.playerUs] === 'Oblivious'
                    && who === (globals.playerUs - 1 + globals.playerNames.length)
                    % globals.playerNames.length);
```
