### ISSUE TITLE
Variant idea: Prism-Ones

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1723]
In this variant, all 1's are:

- Touched normally by color clues
- Touched only by number clues corresponding to their suit
  - The red 1 is touched by 2's clues
  - The yellow 1 is touched by 3's clues
  - The green 1 is touched by 4's clues
  - And so on, wrapping around if necessary

**Comment by timotree3** [comment]
This is the number analog of the Prism variant

**Comment by timotree3** [comment]
I can try implementing this. It needs a better name though, I think

**Comment by Zamiell** [comment]
indeed, prism is the wrong word

**Comment by Zamiell** [comment]
i presume that you would simultaneously implemented prism-ones and prism-fives

**Comment by timotree3** [comment]
yes

**Comment by Zamiell** [comment]
Irregular-Ones?
Surreal-Ones?
Crazy-Ones?
Phantom-Ones?
Deceptive-Ones?

**Comment by Zamiell** [comment]
i like Deceptive-Ones
