### ISSUE TITLE
Match Database ID to Variant ID page

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1730]
For example:
The page for:
Global Statistics for Black & Dark Prism (6 Suits)
https://hanabi.live/variant/1472
The database id is 1472

On here:
https://github.com/Zamiell/hanabi-live/blob/master/data/variants.txt
the variant is listed as #87

**Comment by padiwik** [comment]
That's just a text file that happens to have line numbers. The correct way to "get" a variant is https://hanabi.live/stats . Changing it in the db is annoying if not impossible (need to change all the seeds too, for one) and I don't see what's wrong with the current ID system that's based loosely off of day added

**Comment by Dr-Kakashi** [comment]
Oh, I didn't realize it's going to cause a big issue to all the seeds and whatnot.  Thank you for the link to the stats page.  I'll close this.

**Comment by Zamiell** [comment]
fixed
