### ISSUE TITLE
Efficiency Calculator Bug

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1734]
![2020-09-08_14-22-40 (efficiency drop)](https://user-images.githubusercontent.com/48993588/92529190-eda0e600-f1de-11ea-9012-724e3226885b.png)

We didn't notice this bug until the replay
When kimbi plays R4 efficiency drops from 2.10 to 2.00
Can we have it set so that the efficiency is recalculated once the game ends?

Additionally I believe the efficiency calculations have changed? 
I've noticed that when trash is clued during games, the efficiency drops.  Is the formula updated?  If so, can the new formula be reflected in the doc?

**Comment by IQubic** [comment]
I'm not sure how helpful this will be, but here's the exact moment when the efficiency drops from 2.10 to 2.00.
https://hanab.live/replay/292758/31

**Comment by Zamiell** [comment]
> When kimbi plays R4 efficiency drops from 2.10 to 2.00

thats not a bug, the other red card is now globally known trash, so it doesn't count as going towards efficiency

**Comment by Zamiell** [comment]
> If so, can the new formula be reflected in the doc?

its already reflected??
