### ISSUE TITLE
Game is confused about whose turn it is and no one can go

### ISSUE THREAD

**Issue by erinboyle** [Zamiell/hanabi-live#1735]
Playing with detriments and rainbows. devolving alley agency. The last thing that happened was me bombing. I think what happened then is that the game auto-discarded my bomb card, and maybe one part of the logic therefore thinks I need to discard again since that's my detriment. But another part thinks it's not my turn so won't let me go. 

![image](https://user-images.githubusercontent.com/12789116/92677365-86fff300-f2d8-11ea-82aa-2edf3e3c7ba6.png)

**Comment by padiwik** [comment]
This is with the Panicky (26) character

**Comment by muyjohno** [comment]
+1 Had the same issue and came to the same conclusion (it occurred after a panicky misplay)
