### ISSUE TITLE
feature: Show future needed efficiency in-game

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1737]
Currently we show two efficiencies:

Current efficiency = Cards gotten / Clues spent
Total efficiency = Maximum score / Total clues possibly usable

I propose we show a third and in my opinion more useful efficiency:

Future efficiency = Cards not gotten / Clues not spent

In other words: (Maximum score - Cards gotten) / (Total clues possibly usable - Clues spent)

**Comment by timotree3** [comment]
Okay I'm gonna work on this feature. Any ideas for how to present this number? Should I label it?

It also seems useful to display its numerator and denominator. I'll make a strawman that shows too much unlabelled information and we can go from there

**Comment by Zamiell** [comment]
> Any ideas for how to present this number?

i dont know if there is any room for additional numbers

**Comment by Zamiell** [comment]
could probably just delete current eff

**Comment by Zamiell** [comment]
status on this?

**Comment by timotree3** [comment]
Couldn't compile the client on my new computer. Giving up for now


~Timo

**Comment by Zamiell** [comment]
are you on linux? if you follow the instructions it should be able to compile

**Comment by timotree3** [comment]
> on linux?
yes
```text
+ npm install
npm ERR! Cannot read property 'matches' of undefined
```
online advice says to delete `node_modules` / `.package_lock.json` but neither thing exists in my filesystem

**Comment by Zamiell** [comment]
ok. all `npm install` does is install all of the dependences that are located in the `dependencies` + `devDependencies` sections of the package.json file

* in package.json, delete everything out of those sections
* and add the first thing back, e.g. `"@sentry/browser": "^5.21.1",`

do an npm install and see if it works. if it does, add more shit, until you find the line that is breaking

**Comment by Zamiell** [comment]
from the log, looks like it might be jest?

**Comment by Zamiell** [comment]
timo what is the formula for future effiicency?

**Comment by padiwik** [comment]
isn't it in the first post?

**Comment by Zamiell** [comment]
oh nevermind

**Comment by Zamiell** [comment]
how do i calculate Total clues possibly usable

**Comment by Zamiell** [comment]
oh i guess its just (8 + floor((starting pace + number of suits - unusable clues) / discards per clue)) ?

**Comment by timotree3** [comment]
So Zam are you already working on this? If not, would you accept a PR that just changes the efficiency counter to show future needed efficiency instead?

**Comment by Zamiell** [comment]
i almost have it done

**Comment by Zamiell** [comment]
i dont know if it works, do you wanna write some tests

**Comment by timotree3** [comment]
Sure. Also it might be good if you defined minEfficiency in terms of futureEfficiency. i.e.
```ts
const minEfficiency = (<args>) => futureEfficiency(variant.suits.length * 5, totalPossibleClues(<args>));
```

**Comment by Zamiell** [comment]
done now
