### ISSUE TITLE
feature: Identity list notes affect pips

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1739]
Parse notes that are a comma separated series of identities and show them in the UI.

For example, if a card had the note `y4,m4` it should morph into a 4 and it's color pips should be yellow and multi.

I believe that just like identity notes, these should be ignored in empathy.

**Comment by timotree3** [comment]
Bonus would be to parse the common shorthand for identity lists that would make `r234` expand to `r2,r3,r4` and `ry23` expand to `r2,r3,m2,m3`

**Comment by timotree3** [comment]
I want to work on this tomorrow

**Comment by padiwik** [comment]
personally i like the shorthand `rm23` because it's quicker to parse in my head. I also think it's a good compromise to keep it for the people who don't like note morphing cards.

**Comment by timotree3** [comment]
> personally i like the shorthand `rm23` because it's quicker to parse in my head.

Me too. To be clear, I mean that we would parse that shorthand as though it expanded to the comma-separated list, I don't actually want it to expand that way in the note. 

> I also think it's a good compromise to keep it for the people who don't like note morphing cards.

Are you saying that you know people that would prefer not to have this feature?

**Comment by Zamiell** [comment]
> Are you saying that you know people that would prefer not to have this feature?

i think that is the case

you are trying to combine two disparate features, which actually removes information from the player.
meaning - a player can hover over a note to see the possibilities from the note, and they can look at the pips to see the explicit information / clues.
in your implementation, if they want to see the latter, they would have to delete the note and then readd the note, which probably isn't desired behavior.

**Comment by timotree3** [comment]
> in your implementation, if they want to see the latter, they would have to delete the note and then readd the note, which probably isn't desired behavior.
No they wouldn't. I think it would work like identity notes do. As soon as you hold left-click on the card or drag a card it would show the card with notes ignored

**Comment by Zamiell** [comment]
oh, then that is probably okay

**Comment by Zamiell** [comment]
status on this?

**Comment by timotree3** [comment]
will resume work once I have a working dev environment.

**Comment by timotree3** [comment]
I'll work on this today
