### ISSUE TITLE
Hypothetical Mode Discarding Bug

### ISSUE THREAD

**Issue by MBarber00** [Zamiell/hanabi-live#1749]
![image](https://user-images.githubusercontent.com/68383899/93214506-2bf95080-f75d-11ea-825f-8d784ed94a61.png)

In this hypothetical, sushi is unable to discard. A sound is played and the number of clues is enlarged and changes colour in an animation, as though the team were on 8 clues.

**Comment by TheDaniMan** [comment]
I get this bug on replay 307773, if I try to give a clue on turn 44 and then discard.

**Comment by padiwik** [comment]
it's because the game ends at 8 clues, making the state have 8 clues and the dragging be not allowed
