### ISSUE TITLE
Discrepancy with Efficiency Calculations

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1753]
I have some games for example:
Game ID: 282416
The end game efficiency is shown as 1.47 /   1.39
When I count the # of turns which is 16 then divide by the number of played cards 25 I get 1.563, which is the true ending efficiency.

I also noticed that the efficiency tanks when trash cards are clued.  Has the efficiency formula been changed?  

I assume there's no real way to have an "accurate" efficiency during gameplay, due to trash cards being clued and whatnot.  What do you guys think about having the ending efficiency be recalculated to the true value once the game ends?

**Comment by Dr-Kakashi** [comment]
I'm not saying the formula is completely broken
Game ID: 74926
22 clue's used, 30 cards, 1.364 calculated.  1.36 / 1.20 shown

**Comment by Zamiell** [comment]
> When I count the # of turns which is 16 then divide by the number of played cards 25 I get 1.563, which is the true ending efficiency.

no, it is not, because you are forgetting about the "clues lost" part of the formula.

the formula for efficiency is here: https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Efficiency.md#efficiency

so, in this example, its 25 / (16 + 0.5 + 0.5)
