### ISSUE TITLE
Show # of clues

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1754]
It would be nice if the top right clue box showed the # of clues used along with total clues given.  

![Turns](https://user-images.githubusercontent.com/48993588/93382305-d08b9900-f816-11ea-9e0e-31a0566b1886.png)

Something along the lines of this?
Maybe the total turns display at the end is redundant since you can just look at the list.

**Comment by padiwik** [comment]
who cares about the number of a particular clue? if it was turn number, that might have some use

**Comment by Zamiell** [comment]
we have to remember that any extra information that we add comes at the cost of making the ui appear more cluttered, so we need to be careful and make sure the tradeoff is worth it

in this case, it doesn't seem very clear that it would be worth it
