### ISSUE TITLE
Shared Replay Hypothetical won't let me discard

### ISSUE THREAD

**Issue by MicahSE** [Zamiell/hanabi-live#1755]
When trying to discard in a shared replay hypothetical, the number of clues just enlarges and grows red like so:

![image](https://user-images.githubusercontent.com/50384292/93528633-9e5a6400-f908-11ea-8948-79e8cb1a48ab.png)

I'm almost positive this issue arises when looking at a hypothetical for a game that was terminated immediately(i.e. there was never a turn 1 to begin with), as my other replays work fine, and that's the defining feature of this one

**Comment by padiwik** [comment]
dupe #1749

**Comment by MBarber00** [comment]
This issue doesn't only arise when looking at a shared replay for a game that was terminated immediately. I have seen it on replays of a game that was played until the end.

**Comment by Zamiell** [comment]
fixed thanks to padi
