### ISSUE TITLE
Bug Report: OCM Sound

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#1757]
Gave a 1 clue that picked up 1 on slot 1 and 1 on slot 5 (the chop)
The chop focus 1 played then the OCM sound played.  

https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#playing-multiple-1s---the-chop-focus-exception-part-3

**Comment by Zamiell** [comment]
this is technically not a bug because i intentionally didn't program part 3 into the webpage logic

i guess i could try programming a chop determination logic, but it will fail whenever a card is chop moved (which is probably okay)

**Comment by Aigul9** [comment]
Also it happened in this game, although kyle already discarded: https://hanab.live/replay/329361/13.

**Comment by Zamiell** [comment]
valetta, i dont think i can reliably program logic for the server to know when a card is stale, so this specific "bug" will probably never be fixed
