### ISSUE TITLE
Text log shows internal suit names instead of displayName

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1763]
![image](https://user-images.githubusercontent.com/24983586/93928783-dd156300-fce8-11ea-94f0-2faac077674d.png)

**Comment by rogers-j** [comment]
https://github.com/Zamiell/hanabi-live/blob/59aee5c91eee38a05604d8d4c62f694189347310/client/src/game/rules/card.ts#L12 ?

**Comment by padiwik** [comment]
there are other places too with bad `].name` such as in the detrimental characters random color code, just search that string i guess

**Comment by padiwik** [comment]
although that code is unused by any characters atm

**Comment by rogers-j** [comment]
https://github.com/Zamiell/hanabi-live/blob/5bccc1c28580db661272bb1912cfbafdaf0964a8/client/src/game/rules/clues.ts#L27

https://github.com/Zamiell/hanabi-live/blob/5bccc1c28580db661272bb1912cfbafdaf0964a8/client/src/game/rules/clues.ts#L98

https://github.com/Zamiell/hanabi-live/blob/5bccc1c28580db661272bb1912cfbafdaf0964a8/client/src/game/ui/drawHands.ts#L504

https://github.com/Zamiell/hanabi-live/blob/5bccc1c28580db661272bb1912cfbafdaf0964a8/client/src/game/ui/drawHands.ts#L516

https://github.com/Zamiell/hanabi-live/blob/5bccc1c28580db661272bb1912cfbafdaf0964a8/client/src/game/ui/notes.ts#L253

**Comment by padiwik** [comment]
yes and I believe there's no such thing as a displayColorName

**Comment by rogers-j** [comment]
But if all of the color names are in practice "friendly" I suppose that's fine.

**Comment by Zamiell** [comment]
> if all of the color names are in practice "friendly" I suppose that's fine

yes they are

**Comment by rogers-j** [comment]
https://github.com/Zamiell/hanabi-live/commit/7f23cdadeeb5f6b7104acf4b3ebcab73816223c7

**Comment by Zamiell** [comment]
the commit was already linked
