### ISSUE TITLE
number pips don't appear for me

### ISSUE THREAD

**Issue by ParadoxicallyAiriest** [Zamiell/hanabi-live#1767]
Background: Hanabi Live displays color and number pips on cards in players' hands. When the player knows a card can't be a specific color/number because of the cards they can see, a cross appears over the pip. When the player knows a card can't be a specific color/number because of a clue they received, the pip disappears.

The number pips don't show up for me.

![screenshot of empathy mode](https://i.imgur.com/T6daaGO.png)

I do see color pips, and they disappear and are crossed as expected. I can also see crosses over where the number pips should be, but not the number pips themselves.

Real life mode is off. Turning on Hyphen-ated group features and "make numbers on cards match the art style" didn't help. There are no errors or warnings in the javascript console. This happens in completely fresh installs of Chromium 78.0.3904.97 and Firefox 70.0. It actually took me a long time of playing and watching streams to realize that my gui was missing something.

**Comment by Zamiell** [comment]
are you on linux

**Comment by padiwik** [comment]
slightly related (i think), can we make the website specify a default font?

**Comment by Zamiell** [comment]
it does specify a default font

**Comment by ParadoxicallyAiriest** [comment]
> are you on linux

yeah

**Comment by Zamiell** [comment]
try on windows

**Comment by padiwik** [comment]
Could you load up a game, enter console, and give me the output of `globals.deck[4].rankPips.children[0].attrs` ? Also `globals.deck[4].rankPips.children[0].isVisible()` to check that it is trying to appear.

**Comment by ParadoxicallyAiriest** [comment]
I used game 306586, at the end of the review, looking at the final state.

`attrs`:

```
align: "center"
fill: "white"
fontFamily: "Arial"
fontSize: 63
fontStyle: "bold"
height: 40
listening: false
shadowColor: "black"
shadowEnabled: true
shadowForStrokeEnabled: true
shadowOffsetX: 5
shadowOffsetY: 5
shadowOpacity: 0.4
stroke: "black"
strokeWidth: 3
text: "1"
visible: false
width: 40
x: 14
y: 0
```

`isVisible()`: `false`

**Comment by padiwik** [comment]
oops go to the beginning of the review and check the isVisible

**Comment by padiwik** [comment]
my theory is whatever font your system substitutes for Arial refuses to render that small

**Comment by ParadoxicallyAiriest** [comment]
Not sure how to test that.

I think the font is DejaVu Sans (made a simple HTML page and tried to set the font to Arial, dev tools says the actual rendered font is DejaVu Sans). I don't think the font itself has issues being rendered small? It's a very commonly-used font.

**Comment by padiwik** [comment]
strange, i tried using DejaVu Sans and it looks normal. How about https://hanab.live/replay/167360 , a speedrun game where the text doesn't have shadows?

**Comment by ParadoxicallyAiriest** [comment]
I clicked through while holding down the spacebar and didn't see any number pips at all.

**Comment by ParadoxicallyAiriest** [comment]
> my theory is whatever font your system substitutes for Arial refuses to render that small

The whole UI uses the same font, right? There are smaller numbers than the pips in the pace/efficiency and the clue history.

**Comment by padiwik** [comment]
nah the text and stuff is Verdana. i believe only card numerals are Arial, although there may be some elements where no font is specified in the code

**Comment by Zamiell** [comment]
AFAIK the game works fine in ubuntu, so this guy must be using some other version of linux

i dont really care about random flavors of linux or operating systems that can't use basic fonts, so i will close this as a wontfix

feel free to submit a PR yourself though if you would like it fixed

**Comment by padiwik** [comment]
> AFAIK the game works fine in ubuntu, so this guy must be using some other version of linux

Well... no, he could still be using ubuntu with some weird settings. For example, the site is proven to work fine on Windows 10 + Chrome but last night AshleyBridge for some reason couldn't use the chat in the website.

Still, your main point is valid that it looks like a system issue.
