### ISSUE TITLE
speedruns should end on negative pace

### ISSUE THREAD

**Issue by asaelr** [Zamiell/hanabi-live#1786]
as basically it's the same as losing a critical card

**Comment by Zamiell** [comment]
the server doesn't know what pace is

**Comment by timotree3** [comment]
1, Pace is incredibly easy to calculate.
2. This feature could be implemented in the client

**Comment by Zamiell** [comment]
speedrunners have already decided that the game should not end with negative pace

**Comment by padiwik** [comment]
oh yeah #602

**Comment by Zamiell** [comment]
yes, that

**Comment by padiwik** [comment]
perhaps conditions/opinions have changed since then?
