### ISSUE TITLE
[Variant] Number 6, Number 4 and Diminished 4

### ISSUE THREAD

**Issue by Tiramisu1th** [Zamiell/hanabi-live#1789]
Number 6
The 6th rank is added to each suit. All the 6's cards are critical just like the 5's.
This post are mostly about introducing the variants and comparing the difficulty and playability(e.g. possible conventions) of Number 6 and what we already have in the game

----------------------------------------------------------------------------------------------------------------------------------------

-Pace and Efficiency calculations:
Pace means the maximum amount of discard possible without losing perfect score, so we can get the value by considering cards that will not ever be going to trash bin(cards that needs to be played + total cards remaining in players' hands at the end) and total cards in a deck. For example, for a Special Mix (5 Suits) game with 5 players, there are 45 cards available, 25 needs to be played, and at least 15 cards will be stuck in players' hands. 45-25-15=5, so the efficiency for that game is +5

Efficiency means the minimum average no. of cards that each clue needs to get in order to get every playable cards. We can get this by dividing cards that need to be played by clues available in that game. Let's take Special Mix (5 Suits) game with 5 players again as example, we start with 8 clues, and we can get 5 more from the 5 discards(without going to negative pace) and 4 clues from playing 4 suits(The game ends immediately once the last suit has completed, thus no clue will be awarded for completing the 5th suit), which adds up to 17 clues. Efficiency = 25/(8+5+4) = 1.47

After going through such calculations, we can estimate the difficulty of playing Special Mix (5 Suits) with 5 players by considering the Pace and Efficiency, which are +5 and 1.47 respectively.

Please be noted that all paces and efficiencies listed are for 5 players(because 5 players will result in the most amount of cards stuck in hand in the end of each game, resulting in the least pace and thus the highest difficulty for same variant in terms of pace and efficiency), and the number in brackets are the same stats for 3,4 or 6 players(all 3 of them has same amount of cards stuck in hand in the end of each game, which is 12). Also, as long as the the suit is not darkened, the actual color doesn't affect pace and efficiency, which means Null (4 Suits) is technically as easy/difficult as Omni (4 Suits))

-------------------------------------------------------------------------------------------------------------------------------------------

For the sake of estimating the difficulties of Number 6 variant and the combinations with other playstyles, here are the difficulties of some expected common variants that hanab.live players will play with Number 6 variant:
Number 6 (5 Suits): +10/1.36(+13/1.2)                                            Compare: No Variant: +10/1.13(+13/1.00)
Number 6 (6 Suits): +15/1.29(+18/1.16)                                          Compare: 6 Suits: +15/1.07(+18/0.97)
Number 6 (4 Suits): +5/1.50(+8/1.26)                                              Compare: 4 Suits: +5/1.25(+8/1.09)
Number 6 & Black (6 Suits): +10/1.57(+13/1.38)                             Compare: Black (6 Suits): +10/1.30(+13/1.15)
Number 6 & Black (5 Suits): +5/1.76(+8/1.50)                                 Compare: Black (5 Suits): +5/1.47(+8/1.25)
Number 6 & Throw It In a Hole (5 Suits): +10/1.67(+13/1.43)         Compare: Throw It in a Hole (5 Suits): +10/1.39(+13/1.19)
Number 6 & Throw It In a Hole (6 Suits): +15/1.57(+18/1.38)         Compare: Throw It in a Hole (6 Suits): +15/1.30(+18/1.15)

For advanced players who wants to challenge themselves:
Number 6 (3 Suits): +0/1.80(+3/1.38)                                              Compare: 3 Suits: +0/1.50(+3/1.15)
Number 6 & Up or Down (5 Suits): +5/1.76(+8/1.50)                      Compare: Up or Down (5 Suits): +5/1.47(+8/1.25)
Number 6 & Up or Down (6 Suits): +10/1.56(+13/1.38)                  Compare: Up or Down (6 Suits): +10/1.30(+13/1.15)
Number 6 & Clue Starved (5 Suits): +10/2.00(+13/1.88)                 Compare: Clue Starved (5 Suits): +10/1.67(+13/1.56)
Number 6 & Clue Starved (6 Suits): +15/2.00(+18/1.89)                 Compare: Clue Starved (5 Suits): +15/1.67(+18/1.58)
Number 6 & Black (4 Suits): +0/2.18(+3/1.71)                                 Compare: Black (4 Suits): Not available, +0/1.81(+3/1.43)

From the above data, we can see that Number 6 variant considerably raised the efficiency while maintaining the same pace. Thus, it would be difficult and tricky variant that raises the max. difficulty of the same.
Another good comparisons are Number 6 (5 Suits) and Black (6 Suits). In practical, the newly-added r6, y6, g6, b6 and p6 are almost equivalent to k1-k5 in dark variants, and they can reduce the RNG factor of the deck as bottom deck k1-k3(although bottom deck 5's in Number 6 are still similar to bottom deck k4 and it is more likely as the chance is 5/55 comparing to 1/55, but we can always get rid of it with bottom deck blind play option on while it is impossible to get rid of bottom deck k1-k3 even with that option on).
Number 6 variants can also bring significant improvement to the criteria of competitive hanabi. First, it is more consistent to score higher score(at least you can avoid getting 26-28/30 because of bottom deck k1-k3) because the RNG factor is reduced. Moreover, Number 6 (6 Suits) increased the max. score from 30 to 36, and the addition of 6's opens up to a lot of convention possibilities(for example, 6 pull, 6ce, 6nd, 6cm, 6bcme, stalling with 5 clue instead of 6 clue to signal something juicy, etc., depending on creativity of the community), which is definitely going to demand even better performance by the candidates and push the skill cap even higher for hanabi enthusiasts

-------------------------------------------------------------------------------------------------------------------------------------------

Number 4 is basically removing the second copy of 4's and 5's. Diminished Number 4 is removing the third copy of 1's on top of Number 4. Please do the calculations yourself if you are interested in investigating on them. I don't want to make another list or to do anymore calculations for today :)

P.s. This is my first time submitting an issue, please don't flame me too hard if I did or said something wrong. I hope the community(at least Zamiel) would consider implementing these variants to the game in the future

**Comment by Zamiell** [comment]
this has been proposed before and we've decided against it. arbitrarily adding more critical cards doesn't really make the game more interesting or fun (which is why clue starved was invented, to try and address this).
