### ISSUE TITLE
Let users compose/customize their own variants

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#179]
With the rise of many many special variants and different variants that are simply the same variants but with less stacks, the next natural step would be to, instead of making the user pick 1 of a big list of variants and variations of variants, they would be presented with a list of templates, and be allowed to modify them by removing/adding specific stacks, etc.
Lots of different ways of implementing this exists, but I think almost any would be better than the current giant list of variants.

**Comment by RaKXeR** [comment]
the score system is already kinda bullshit since the modifiers have no effect on them whatsoever, and with all these variants it's actually more clogged than it would be if you reduced the amount of variants displayed on the score. If you don't want to group custom variant scores with the chosen template they could either a. not count, b. be grouped into a single "custom variant" score, c. be listed in a "x variant - custom" after the score information from "x variant".

It also doesn't seem that hard to program from the way the variant code is already structured, maybe the other random patch lines added throughout the code would need some changing.

Anyway I'm making this issue for later consideration because I honestly can't see us not implementing something like this in the future.

**Comment by Zamiell** [comment]
if im understanding you correctly, you're proposing that the max score is tracked for the "White Suit" variant, but not tracked for the "White Suit (5 Suits)" variant, as you want that behind a custom gate, with the intent that no custom scores are tracked

I agree that the server should not track scores for random custom shit like "Navy + Sky + Green + Purple + White". However, I **do** want to track scores for _White Suit (5 Suits)_. So how do propose that is resolved.

**Comment by RaKXeR** [comment]
Well I see what you mean, only way I can think is to give users an option to track or not track the score of a certain game (either as a setting for the table or for each player) and then only display scores of variants the user has played.

**Comment by Zamiell** [comment]
but then users could check the box to track the score for "Navy + Sky + Green + Purple + White", and then the server would permanently remember their score, which I don't want
