### ISSUE TITLE
off-screen chatbox

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1790]
sometimes chat goes off the screen, and i receive a hundred yellow notifications in console:
Konva warning: Pointer position is missing and not registered by the stage. Looks like it is outside of the stage container. You can set it manually from event: stage.setPointersPositions(event);
(this is the right edge of the screen)
<img width="230" alt="2020-10-10_21-41-46" src="https://user-images.githubusercontent.com/46625461/95666110-6210d100-0b5f-11eb-87a4-7e66403207cf.png">

**Comment by Zamiell** [comment]
just ignore the yellow notifications

**Comment by Aigul9** [comment]
so why does this window disappear

**Comment by Zamiell** [comment]
what disappears, the chat window?

**Comment by Aigul9** [comment]
yes

**Comment by Aigul9** [comment]
it rides outside of the screen

**Comment by Zamiell** [comment]
i just tried, and i am not able to drag the chat off the screen from any of the 4 sides

provide steps to reproduce

**Comment by Aigul9** [comment]
and might disappear if i move the mouse too fast

**Comment by Aigul9** [comment]
i don’t know how to reproduce it yet

**Comment by Zamiell** [comment]
if you can find reproducible steps, then feel free to reopen the issue

**Comment by padiwik** [comment]
is it undesired to allow chat box to be outside the main canvas?

**Comment by Zamiell** [comment]
it is currently programmed to not allow that
the idea is that we do not want x y coordinates to be saved to be offscreen coordinates, which renders the chat inaccessible

**Comment by padiwik** [comment]
This seems to happen when attempting to resize the chat box smaller than the enforced min dimensions, at least on mobile. Of note, the default dimensions (based on percentage?) can be smaller than the min dimensions

**Comment by padiwik** [comment]
oh i see, it's allowed to go into the already-rendered dark green background area, but shouldn't go past that?
