### ISSUE TITLE
Hanabi bot pinging

### ISSUE THREAD

**Issue by dxl540** [Zamiell/hanabi-live#1793]
You can ping people through hanab.live by using \@ pings. For example, putting \<@688593453487358106> in lobby chat will ping me. (Please don't spam this) You can also ping roles this way (I think)

**Comment by padiwik** [comment]
It looks like Discord has an "allowed mentions" feature that will prevent any pings from the bot https://godoc.org/github.com/bwmarrin/discordgo#MessageAllowedMentions
This will also let us remove the sketchy AtEveryone/AtHere sanitization.
