### ISSUE TITLE
Warning before game timeout?

### ISSUE THREAD

**Issue by haileyhultquist** [Zamiell/hanabi-live#1795]
In our most recent game, my partner and I spent quite a while (probably 20-30 min) thinking about the optimal endgame sequence in a particularly close game. But finally, as my partner went to play it, the game terminated with the message "Players were idle for too long." We continued the game offline and confirmed our "victory" but it was rather disappointing anyway. Could there maybe be some "Are you still playing?" warning before the game just ends?

By the way, this is an incredible website. Thank you for creating it!

**Comment by Zamiell** [comment]
> probably 20-30 min
well the idle limit is 30 mins, so you must have not made a move for exactly 30 minutes

i think the easiest fix would be to send a chat message from the server 5 mins before (e.g. at the 25 minute mark) to let them know that it is about to be terminated. and hopefully the players would be reading the chat

we wouldnt want to implement anything more complicated than that, as this is the first request i've heard for players needing longer than 30 minutes for a move, which means this situation is incredibly rare

**Comment by Zamiell** [comment]
and for the record, assuming that you are getting really good at hanabi, I would highly recommend playing timed games as an additional challenge.
the standard time control is 2 mins + 20 seconds per move.
in most cases, giving players unlimited time (e.g. 30 minutes to think about a move) trivializes the game, as experienced players will almost always be able to find the near-optimal move in that time frame

**Comment by haileyhultquist** [comment]
Thanks for the information! We're still pretty new to this so we haven't tried any timed games yet.
I looked through the code and I think for us, it is good enough just to know that we can start a replay to reset the idle timer the next time my partner thinks for half an hour!
