### ISSUE TITLE
Buffer before clue is actually sent

### ISSUE THREAD

**Issue by iwantthequackback** [Zamiell/hanabi-live#1796]
Hello,

It's more of a feature request than an issue. I was wondering if it would be possible to have optional delay before sending a clue to the rest of the team? My issue is the vast majority of the time when I realize I made a mistake, it's within the second I send the clue, see the clue card and hear the musical notes. If I could press escape or another key to cancel, I could avoid many in game mistakes.

Maybe having an option in the setting to tick a box and set timer before sending clue to 2 or 3 seconds, or even let the user choose.

**Comment by Zamiell** [comment]
nope
