### ISSUE TITLE
Variant Request - Full of Fours

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#1800]
2 of each 1, 3 of each 4, Possibly adjust starting clue count.

**Comment by Zamiell** [comment]
possibly adjust your brain

**Comment by jakestiles** [comment]
Zam would you accept a PR for this or other distribution variants? Such as 4s become critical in exchange for extra 1s or 2s?

**Comment by Zamiell** [comment]
they are not interesting enough to warrant being variants, so no

**Comment by Zamiell** [comment]
i thought we had discussed this previously

**Comment by jakestiles** [comment]
You hadn’t closed the issue so it seemed worth asking.

**Comment by Zamiell** [comment]
my bad, i will close it now
