### ISSUE TITLE
Should be able to make notes about what a card isn't and it gets crossed off on the card

### ISSUE THREAD

**Issue by djnarayanan** [Zamiell/hanabi-live#1801]
something like !2g and makes the card visually not green 2

**Comment by Zamiell** [comment]
we've decided against this in the past

**Comment by Zamiell** [comment]
tim do you want to do this?

**Comment by timotree3** [comment]
Why did we decide against it in the past?

**Comment by Zamiell** [comment]
because we didn't have notes affect the affirmative, so why would they affect the negative

**Comment by Zamiell** [comment]
but now we have them affect the affirmative, so it should naturally also affect the negative

**Comment by marcmagus** [comment]
Semantics question: should [!2g] mean "this card is not the green 2" or "this card is not green AND this card is not a 2"?
It seems desirable to allow [!bg] rather than requiring [!b][!g] which suggests one should also be able to do [!bg12] and cross off all 4 values, but this may create some confusion if people expect to be able to note "!g2" to mean that this card isn't the green 2 with no additional implications (the most straightforward read for that note)

**Comment by Zamiell** [comment]
> Semantics question: should [!2g] mean "this card is not the green 2" or "this card is not green AND this card is not a 2"?

the former, for the reasons you described

**Comment by timotree3** [comment]
It should interpret the part after the `!` as a list of impossibilities in exactly the same way that it currently parses possibilities, and make sure that they are all removed from the possible identities shown on the card. `!g2` is one impossibility, `!g,2` is nine impossibilities, `!g,b` is ten. and `!g2,b2` is two.

**Comment by Zamiell** [comment]
so it sounds like we agree then

**Comment by Zamiell** [comment]
> !g2 is one impossibility, !g,2 is nine impossibilities, !g,b is ten. and !g2,b2 is two.

i think you meant to type:
`!g2` is one impossibility, `!g,!2` is nine impossibilities, `!g,!b` is ten. and `!g2,!b2` is two

**Comment by marcmagus** [comment]
"!g2 is one impossibility, !(g,2) is nine impossibilities, !(g,b) is ten. and !(g2,b2) is two."
might be feel desirable to the end-user but could increase parser complexity perhaps beyond what you want to support.

**Comment by timotree3** [comment]
!g,2 meaning (any card that is NOT green OR any 2) would be equivalent to saying (any 2). therefore that interpretation is useless and we should prefer !g,2 meaning (any card that is NOT green AND is NOT a 2) or equivalently (any card that is not (green OR a 2))

**Comment by timotree3** [comment]
oh wait. 

> !g,2 meaning (any card that is NOT green OR any 2) would be equivalent to saying (any 2)
Actually this is nonsense. It would mean (any card that is NOT (green 1, green 3, green 4, OR green 5))

Maybe I changed my mind

**Comment by Zamiell** [comment]
> It would mean (any card that is NOT (green 1, green 3, green 4, OR green 5))

that is correct, which is why i prefer the syntax that i typed out above

**Comment by timotree3** [comment]
comma means OR, right? so your syntax should mean (any card that is either (NOT green 2) or (NOT blue 2)) which is the same as saying (any card)

**Comment by Zamiell** [comment]
`!g, !2` is not green and not a 2, r.g. r1, rr3, r4, r5, b1, b3, etc.

`!g, 2` is not green and a 2, e.g. r2, b2, y2, p2
