### ISSUE TITLE
[Variant] Pure

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#1803]
Hi, feel free to change the name.
It's a suit where the special rules of the variant doesn't apply:

Dual Color/Ambiguous: this suit would just get clue by one color
Color Blind/Number blind/Totally blind: this suit are still clued by number and color.
Clue Starved: each discard of a card of that suit gave 1 clue back.
Cow & Pig/Duck: clues given are shown if that touch one card of that suit. That would make lots of information given.
Throw It in a Hole: when a card of that suit is played (correctly or badly), it's shown.
Up or Down: it's a normal suit with three 1, and one 5 (and which need to be played in normal order).

I believe that could make some really hard variant way more affordable when you want to discover them or want them slightly easier.

Alternating Clues seems the variant where this suit can't fit.

**Comment by Zamiell** [comment]
its not the worst idea, but i dont like it enough to make it a reality
