### ISSUE TITLE
It would be nice to display the component numbers of efficiency in-game

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1811]
With a score of 20 and 18 clues spent in a 2-player game

e.g. Efficiency: 0.45 (5/11) | 0.86

**Comment by Zamiell** [comment]
sure, on tooltip?

**Comment by timotree3** [comment]
I would suggest always visible actually as it may help make it less jarring to see such a low efficiency number. What if on tooltip it showed (5 cards left to clue / 11 total clues available)? 

Also what if we used emojis? 

Efficiency: 0.45 (5 🃏 / 11 🕛) | 0.86

**Comment by Zamiell** [comment]
there's not enough room for that

keep in mind we are adding `+N` to the right of it for modified eff

**Comment by timotree3** [comment]
hmm. I feel like there might be enough room. especially if we decreased the margins

**Comment by Zamiell** [comment]
i dont want it to be crowded

**Comment by timotree3** [comment]
fair
