### ISSUE TITLE
Detrimental : impossible to win with hesitant (question/bug)

### ISSUE THREAD

**Issue by laurst** [Zamiell/hanabi-live#1819]
https://hanab.live/replay/334411

We discarded the fist null 2 on turn 12, then a hesitant player picks the second null 2 on turn 52. Since that player is hesitant, there's no way for them to play that card.

I'm not sure this should be a bug because in that situation I guess we could have clued the player to discard, therefore moving the null 2 to the second slot. But I feel like when the deck is empty, a hesitant player could be allowed to play from slot 1. I can see some situations where a defeat would be unavoidable.

If you agree that this should change, I can try and submit a PR.

**Comment by padiwik** [comment]
The point of detrimental characters is to make it harder to win, so you have to do weird stuff like forcing Hesitant to discard. Equally it is possible for a critical card like k4 to be on the bottom of the deck, preventing a win with the default options, or a player to have too many critical cards in their hand, etc. We don't change the rules of the game to prevent those situations but instead we challenge ourselves to give better clues and play more efficiently. With bottom deck blind plays enabled, Hesitant can still play the card on the bottom of the deck and everything is fine. I don't think changing Hesitant behavior is necessary to make it "fun" or winnable.

**Comment by Zamiell** [comment]
hello laurst. i haven't seen you around yet personally, but welcome to hanabi live.
have you been playing with the hyphen-ated group, or are you playing with your own set of friends?

with respect to your issue, characters aren't really intended to be balanced in the way that you are describing.
they are a throwaway feature that i programmed in a day that isn't meant to be taken seriously.
thus, their design is focused on simplicity - we don't want to add exceptions and complex mechanics to any characters.

if you want to help with the website, there are plenty of other productive things that need to be done =)

**Comment by laurst** [comment]
@padiwik 
That's fair, I can see that. Thinking again, I think my complaint really is about how hesitant interacts with the `all or nothing` setting in this case (which we always play with : my group does not focus efficiency), but it's definitely true that there are (almost) always things you can do in order to avoid painting yourself in a corner. Thank you for your perspective and answer !

@Zamiell 
Thanks ! I'm playing with my friends : we simply took our in-person hanabi games online due to the situation. Despite having seen this name around, I'm not exactly sure what the hyphen-ated group is.

Point taken, I agree that detrimentals are not supposed to be balanced (which they are definitely not ; some combinations are straight up impossible). For us it's mostly a way to keep the game fresh once in a while by forcing us to adapt to the detrimentals instead of relying purely on the same set of conventions.

No promises about helping on the website, but I'll have a look. Thank you so much for creating it !
