### ISSUE TITLE
Joining game / viewing game results in blank green screen

### ISSUE THREAD

**Issue by jasonnoble** [Zamiell/hanabi-live#1822]
Created a game, when the game started, I get a blank green background (normal game background).  No cards show up.

```
globals.ts:101 Uncaught TypeError: Cannot read property 'getState' of null
    at Object.get state [as state] (globals.ts:101)
    at Object.get options [as options] (globals.ts:114)
    at gameCommands.ts:443
    at gameCommands.ts:151
    at Object.init (websocketInit.ts:100)
    at i.onMessage (Connection.ts:52)
```

![Screen Shot 2020-11-04 at 11 49 43 AM](https://user-images.githubusercontent.com/22501/98155710-f129b400-1e93-11eb-817c-a4e80d3c23d8.png)

Tried multiple browsers and accounts.  Seeing the same issue.

**Comment by padiwik** [comment]
What are the options and variant of the game?

**Comment by jasonnoble** [comment]
Dark Brown (6 suits), timed with password.  `shenanigan commando effrontery`

**Comment by jasonnoble** [comment]
Same error with different account, No Variant.

**Comment by Zamiell** [comment]
hard-reload and try again

**Comment by Zamiell** [comment]
fixed
