### ISSUE TITLE
feature: statistic showing max rounds left

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1825]
This would be useful in the endgame for determining whether someone has enough time to play all their cards or needs a tempo clue.

Formula is: cluesStillUsable + pace + missing score = max turns left
max rounds left = max turns left / numPlayers

**Comment by timotree3** [comment]
Zam, would you accept a PR for this? Where should it go?

**Comment by Zamiell** [comment]
i guess

put it in a mouseover tooltip on turn

**Comment by timotree3** [comment]
What if it showed as a denominator under the turn number?

e.g. Turn 23/71
In 2p no variant.

**Comment by Zamiell** [comment]
thats confusing because it implies that there will be 71 total turns in the game

**Comment by timotree3** [comment]
Which would be approximately true

**Comment by timotree3** [comment]
The score says 7/25 even though you might not get a score of 25. Maybe the number behind a slash represents the max in this context.

**Comment by Zamiell** [comment]
it sounds like you are proposing two separate things

**Comment by Zamiell** [comment]
why dont you make an issue for that

**Comment by timotree3** [comment]
I wonder if it should show how many cards need to be played per round moving forward. Kind of like "future tempo"
