### ISSUE TITLE
"Forest" identity note conflicts with finessed note

### ISSUE THREAD

**Issue by jack67889** [Zamiell/hanabi-live#1826]
The abbreviation of the Forest suit in Ambiguous is "f", thus a finessed note also morphs a card into Forest. Resulting in conflicts, especially if the card is known to be not Forest. Could the abbreviation for Forest identity notes be changed to "r" or "o" (I don't think the Forest suit is used in other Ambiguous variants)?

**Comment by Zamiell** [comment]
fixed
