### ISSUE TITLE
Feature Request - cards gotten modifier reads notes

### ISSUE THREAD

**Issue by glassbead0** [Zamiell/hanabi-live#1832]
Certain notes on un-clued cards automatically increments the "cards gotten modifier" and thus the efficiency modifier. Which kinds of notes should trigger this is certainly up for debate.

Also decrement the cards gotten modifier for clued cards with a `kt` or `trash` note.

Maybe only be turned on if the Hyphenated Conventions are enabled. Everyone might not want this turned on.

Suggested notes that cause the increment:

`f`
`cm`
any identity note: (`b3`, `y2`)
identity noes separated by commas (or commas space?): (`r4, y4`, `g2, g3`, `3,4`)
maybe any partial identity note: (`4`, `b`)
...

**Comment by Zamiell** [comment]
submit pull request

**Comment by Zamiell** [comment]
cm wouldn't cause cards gotten to increase because you have to clue cm cards to get them to play

**Comment by Zamiell** [comment]
@vEnhance should i close this now?

**Comment by vEnhance** [comment]
Yep.

**Comment by Zamiell** [comment]
ok thanks
