### ISSUE TITLE
private messages

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1841]
here is a little experiment😄
![9735228B-25BA-4223-ACCD-345B5D8AC0DC](https://user-images.githubusercontent.com/46625461/99152086-b9e7ae00-26b0-11eb-824a-fc5bb174e6f0.jpeg)
![3836113A-2FF1-4C95-988A-62D984AD9AB1](https://user-images.githubusercontent.com/46625461/99152089-bc4a0800-26b0-11eb-91a0-512b578f7111.jpeg)
messages sent while player is in the non-shared replay just disappear. also when we go back from the game to lobby or vica versa, they aren’t saved anywhere.
desired behaviour: messages should be stored somewhere until the page refresh

**Comment by Zamiell** [comment]
its a lot of work to program private messages. why can't everyone just use discord?

**Comment by Aigul9** [comment]
messages acted as i described when you implemented them
