### ISSUE TITLE
New Variant Proposal: All-Specials

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#1842]
### Rename these Special Variants to "All-Specials"
* Color Blind -> All-Rainbows
  * Color clues touch no suits = All-Rainbow cards are touched by all color clues
* Number Blind -> All-Pinks
  * Rank clues touch no suits = All-Pink cards are touched by all rank clues
* Totally Blind -> All-Omnis
  * Color clues and rank clues touch no suits = All-Omni cards are touched by all color clues and all rank clues
* Color Mute -> All-Whites
  * Color clues cannot be given = All-White cards cannot be touched by color clues
* Number Mute -> All-Browns
  * Rank clues cannot be given = All-Brown cards cannot be touched by rank clues

### New All-Specials Variants
* Number Blind + Color Mute -> All-Light-Pinks
  * Rank clues touch no suits = All-Light-Pink cards are touched by all rank clues
  * Color clues cannot be given = All-Light-Pink cards cannot be touched by color clues
* Color Blind + Number Mute -> All-Muddy-Rainbows
  * Color clues touch no suits = All-Muddy-Rainbow cards are touched by all color clues
  * Rank clues cannot be given = All-Muddy-Rainbow cards cannot be touched by rank clues
* Totally Mute -> All-Nulls
  * Color clues and rank clues cannot be given = All-Null cards cannot be touched by color clues and rank clues
  * *Probably not a good idea to implement this variant lol*

### All-Specials with Another Special Suit
* Example 1: All-Whites & Brown (6 Suits)
  * Suits:
    *  All-White-Red
    *  All-White-Yellow
    *  All-White-Green
    *  All-White-Blue
    *  All-White-Purple
    *  Brown
  * Type of clues: 
    *  Rank clues: 1, 2, 3, 4, 5
    *  Color clues: brown (red, yellow, green, blue and purple clues cannot be given)
  * All-White cards cannot be touched by color clues
  * Brown cards cannot be touched by rank clues
* Example 2: All-Pinks & Rainbow (6 Suits)
  * Suits:
    *  All-Pink-Red
    *  All-Pink-Yellow
    *  All-Pink-Green
    *  All-Pink-Blue
    *  All-Pink-Purple
    *  Rainbow
  * Type of clues: 
    *  Rank clues: 1, 2, 3, 4, 5
    *  Color clues: red, yellow, green, blue, purple
  * All-Pink cards are touched by all rank clues
  * All-Pink cards are touched by specific color clues (e.g. All-Pink-Blue cards are touched by blue clues)
  * Rainbow cards are touched by all color clues
* Example 3: All-Muddy-Rainbows & Omni (6 Suits)
  * Suits:
    *  All-Muddy-Rainbow-Red
    *  All-Muddy-Rainbow-Yellow
    *  All-Muddy-Rainbow-Green
    *  All-Muddy-Rainbow-Blue
    *  All-Muddy-Rainbow-Purple
    *  Rainbow
  * Type of clues: 
    *  Rank clues: 1, 2, 3, 4, 5
    *  Color clues: red, yellow, green, blue, purple
  * All-Muddy-Rainbow cards are touched by all color clues
  * All-Muddy-Rainbow cards cannot be touched by rank clues
  * Omni cards are touched by all color clues and all rank clues

### Dark All-Specials
* *One of the All-Special suits is replaced with an **All-Special-Dark** suit*
* Example 4: Dark All-Rainbows (6 Suits)
  * Suits:
    *  All-Rainbow-Red
    *  All-Rainbow-Yellow
    *  All-Rainbow-Green
    *  All-Rainbow-Blue
    *  All-Rainbow-Purple
    *  All-Rainbow-Dark
  * Type of clues: 
    *  Rank clues: 1, 2, 3, 4, 5
    *  Color clues: red, yellow, green, blue, purple, dark (black)
  * All-Rainbow cards are touched by all color clues
  * There is only one of each All-Rainbow-Dark card in the deck
* Example 5: Dark All-Light-Pinks & Black (6 Suits)
  * Suits:
    *  All-Light-Pink-Red
    *  All-Light-Pink-Yellow
    *  All-Light-Pink-Green
    *  All-Light-Pink-Blue
    *  All-Light-Pink-Dark
    *  Black
  * Type of clues: 
    *  Rank clues: 1, 2, 3, 4, 5
    *  Color clues: black
  * All-Light-Pink cards are touched by all rank clues
  * All-Light-Pink cards cannot be touched by color clues
  * There is only one of each All-Light-Pink-Dark card in the deck
  * There is only one of each black card in the deck

 #### Do not add these Variants
* All-Rainbows & Rainbow
* All-Pinks & Pink
* All-Omnis & Omni
* All-Whites & White
* All-Browns & Brown
* All-Light-Pinks & Light Pink
* All-Muddy-Rainbows & Muddy Rainbow
* All-Nulls & Null
* And their dark variants

**Comment by Zamiell** [comment]
> Rename these Special Variants to "All-Specials"

we had it that way before but we changed it because the ui was confusing

**Comment by Zamiell** [comment]
> New All-Specials Variants

no, these sound terrible

**Comment by Zamiell** [comment]
> All-Specials with Another Special Suit

not a fan

**Comment by Zamiell** [comment]
> Dark All-Specials

a black version of color blind might be okay but a black version of number mute would not be
overall, seems kind of superfluous
