### ISSUE TITLE
feature: show max turns left next to turn count

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1846]
e.g. Turn 23/71
in 2p No Variant

**Comment by Zamiell** [comment]
sure

**Comment by Zamiell** [comment]
its kind of confusing because in a shared replay, the max turn count implies the total count of turns in the replay, which is not the case

**Comment by timotree3** [comment]
Yeah. It may not be ideal.

**Comment by Zamiell** [comment]
should we close this now

**Comment by timotree3** [comment]
well it can still be implemented as a replacement for that line of the tooltip. if you think the feature is undesired then close it. personally I think I would like it but I imagine it would bother many people

**Comment by Zamiell** [comment]
ok then lets close it for now. having the information in a tooltip is a nice compromise
