### ISSUE TITLE
refactor notes.ts

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1853]
@timotree3 

a request regarding notes.ts:
1) why are there two separate functions that are both named `getPossibilitiesFromKeyword`? that's really confusing. can we rename one of them to be more descriptive?
2) the file is almost 500 lines long. can we refactor the note identity stuff out of the file and into a new file called `noteIdentity.ts`?

**Comment by timotree3** [comment]
one of them has an `s` on the end. `getPossibilitiesFromKeywords` meaning that it takes all of the keywords from a note and produces a list of card possibilities

**Comment by timotree3** [comment]
the other one only examines a single `Keyword`

**Comment by Zamiell** [comment]
oh ok, i missed that
