### ISSUE TITLE
proxy revoked error

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1855]
both 084d0f4a3dda903d2657525181ff0ae227510480 and ab3a91fac50462ba4e91912470a744d6bfbff5dc cause the proxy revoked error when the game ends

steps to reproduce:
- start a 2p game
- give a number 1 clue
- terminate

these commits have been reverted for now

**Comment by Zamiell** [comment]
@timotree3

**Comment by timotree3** [comment]
The error occurs in resolving the selector for `onNewSoundEffect` after the game has ended. 

```ts
  subAfterInit(
    (s) => ({
      soundType: s.ongoingGame.stats.soundTypeForLastAction,
      currentPlayerIndex: s.ongoingGame.turn.currentPlayerIndex,
      turn: s.ongoingGame.turn.turnNum,
      lastAction: s.ongoingGame.stats.lastAction,
    }),
    soundView.onNewSoundEffect,
  ),
```

My theory was that the error was caused by the `lastAction` field again, and since `onNewSoundEffect` doesn't actually use that field, I tried deleting it from the selector, which fixed the error.

**Comment by Zamiell** [comment]
ok, do you want to do another PR, or should i revert the commits, or what

**Comment by Zamiell** [comment]
ok, timo did a PR, will close this
