### ISSUE TITLE
Add Clue Starved (3 Suits) and (4 Suits)

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1858]
I believe that these have a lower efficiency requirement than Clue Starved with higher suits, so I don't see why they shouldn't exist.

**Comment by Zamiell** [comment]
they have a higher eff req https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Efficiency.md

**Comment by timotree3** [comment]
they have lower starting pace but lower efficiency req. look at the table you linked me

**Comment by Zamiell** [comment]
on the table i linked you, the number of "1.82" and the number of "1.88" is higher than the number of "1.79"

**Comment by timotree3** [comment]
Ah. but that's only true for 5p. for all the others it's easier. Adding a clue starved suit adds 5 cards to play, 0.5 clues from suits, and 2.5 clues from discards. 5 > 3 so adding a clue starved suit increases the difference between cards to play and clues usable. I guess what's happening here is that 25 / 14.5 is less than 20 / 12 even though the difference is bigger.

**Comment by Zamiell** [comment]
> Ah. but that's only true for 5p. for all the others it's easier

the algorithm that is currently in use is as follows:
if a variant has a higher req eff than X in **any** amount of players, then the variant won't be added.
X is currently equal to 1.79

**Comment by timotree3** [comment]
right but the fact that we're dividing the two numbers instead of subtracting them is making you think that Clue Starved (4 Suits) 5p is actually harder than Clue Starved (5 Suits) 5p. I'm not sure it even is. You can win a game of Clue Starved (4 Suits) 5p by giving 8 2-for-1 clues and 4 1-for-1 clues. In 5 Suits it's 11 2-for-1 clues and 3 1-for-1 clues.

**Comment by Zamiell** [comment]
ultimately, it would be nice to have code for players to "create their own variant", which has been requested many times and discussed previously.
when such code is in place, the plan would be to use a custom metric to determine which variant and player combinations are eligible for the server to track, score wise.
my proposed metric is as follows:
`pace > 0 && eff < 1.7`
(not particularly relevant here, but including it for completeness)

using this new "create game" UI, players would be free to play any variant and player combination that they would like.
but if they decided to play a very difficult variant (e.g. Clue Starved 4 Suits), the max score would not be tracked by the server.
(as opposed to the current system, where players can only play variant and player combinations that can be tracked by the server.)

it is unclear whether or not we will ever get to this state.
so in the meantime, i have been using relying on the algorithm discussed in my previous post.
putting aside the flaws of the efficiency calculation, it is a pretty good schelling point for determining which variants should be added to the website and which should not be added to the website.

generally speaking, i don't care that much if we want to add clue starved 3 suits and 4 suits.
but we should note that it does break the algorithm that I have put in place.
so the onus would be on you to propose a new algorithm and then come up with some argument or logic to defend it.
for example, we probably don't want the server to be tracking scores for variants with 3 dark suits.

alternatively, we can start to work towards the create your own variant solution.

**Comment by timotree3** [comment]
fair enough
