### ISSUE TITLE
Fix mobile lobby

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#1870]
Quick and _very_ dirty lobby proposal, paste before the `</head>` on live site.

The css doesn't take into account other screens (such as login, tutorial etc)

```
<style>
@media only screen and (max-width:760px){#lobby-chat-bottom-half{margin:0!important;padding:0!important;width:auto!important;height:auto!important}#lobby-chat,.lobby-users-box-container{height:80vh!important;margin:10px 1px 0!important;width:100%!important}#lobby-bottom-half,#lobby-bottom-half div,#lobby-top-half,#lobby-top-half div{margin-left:0!important;padding-left:0!important}#lobby-chat-container{width:auto!important}body{overflow:auto!important}#lobby-games{padding:1px!important}#lobby>div>div{height:auto}#lobby>div>div>section{height:auto}.lobby-table-container{height:auto}.box{overflow:auto}.lobby-half{height:auto}#lobby{height:auto;margin:10px 5px!important;width:auto!important}table#lobby-games-table,table#lobby-games-table tbody,table#lobby-games-table td,table#lobby-games-table th,table#lobby-games-table thead,table#lobby-games-table tr{display:block}table#lobby-games-table thead tr{display:none}table#lobby-games-table tr{border:1px solid #333}table#lobby-games-table td{border:none;border-bottom:1px solid #eee;position:relative;padding-left:50%;background-color:#fefefe;padding-top:30px!important;padding-left:30px!important}table#lobby-games-table td:first-child{background-color:inherit;border-top:3px solid #000!important}table#lobby-games-table td:before{position:absolute;top:6px;left:6px;width:45%;padding-right:10px;white-space:nowrap}table#lobby-games-table td:nth-of-type(1):before{font-weight:700;content:"Table Name"}table#lobby-games-table td:nth-of-type(2):before{font-weight:700;content:"# Players"}table#lobby-games-table td:nth-of-type(3):before{font-weight:700;content:"Variant"}table#lobby-games-table td:nth-of-type(4):before{font-weight:700;content:"Timed"}table#lobby-games-table td:nth-of-type(5):before{font-weight:700;content:"Status"}table#lobby-games-table td:nth-of-type(6):before{font-weight:700;content:"Players"}table#lobby-games-table td:nth-of-type(7):before{font-weight:700;content:"Spectators"}}
</style>
```

**Comment by Zamiell** [comment]
@padiwik approve this

**Comment by padiwik** [comment]
screenshots pls? also you should probably make it readable, search for @media rules in existing css and put it there

**Comment by Zamiell** [comment]
we use prettier to format CSS

**Comment by Zamiell** [comment]
or we should

**Comment by padiwik** [comment]
i think it's called hanabi.css or main.css; don't edit alpha.css

**Comment by Zamiell** [comment]
main.css is compiled by grunt, only edit hanabi.css

**Comment by Zamiell** [comment]
and add comments
/* Overwriting this media query because it does X and Y for the purposes of Z */

**Comment by DrAnax** [comment]
It's a first try, to see the looks, not intended as a real fix. If you like the approach I can work on it

![image](https://user-images.githubusercontent.com/2622043/99883660-9af99680-2c31-11eb-8763-fb943905f3ea.png)

Lobby chat has max height:

![image](https://user-images.githubusercontent.com/2622043/99883681-b5337480-2c31-11eb-8333-196f28c367a3.png)

Users box left as is (for now)

![image](https://user-images.githubusercontent.com/2622043/99883701-c8464480-2c31-11eb-9609-bfad058cd658.png)

**Comment by Zamiell** [comment]
seems good

for reference on how it is "supposed" to look on mobile, use this:

https://html5up.net/alpha

and select "Elements" from the menu

**Comment by padiwik** [comment]
Oh that's an interesting implementation. I like it better than the current site. Can you make the table boxes like a 2 by x table, so that e.g. the status is directly to the right of the text Status?

**Comment by DrAnax** [comment]
I'll get back on the subject in a couple of days with mockup screens

Στις Σάβ, 21 Νοε 2020, 7:50 μ.μ. ο χρήστης padiwik <notifications@github.com>
έγραψε:

**Comment by Zamiell** [comment]
any updates on this @DrAnax ?

**Comment by DrAnax** [comment]
I'm still on it, need some more time

>

**Comment by Zamiell** [comment]
ok was just wondering = )

**Comment by DrAnax** [comment]
I'm seeing various media breakpoints; is there a reason for this or just an effort to make things pretty?

@media screen and (max-width: 290px)
@media screen and (max-width: 400px)
@media screen and (max-width: 490px)
@media screen and (max-width: 650px)
@media screen and (max-width: 736px)
@media screen and (max-width: 830px)
@media screen and (max-width: 840px)
@media screen and (max-width: 970px)
@media screen and (max-width: 1220px)
@media screen and (min-width: 1280px)
@media screen and (min-width: 1440px)

Are there any standard breakpoints we would like to use?


Also, I'm thinking of keeping the logo even on mobile, replace the top bar with a hamburger menu on mobile and replace topbar icon-buttons with text on desktop, is it ok?

**Comment by Zamiell** [comment]
> I'm seeing various media breakpoints; is there a reason for this

if you're referred to hanabi.css line 869, then that is to keep all the navbar buttons visible as you drag the window smaller

**Comment by Zamiell** [comment]
> I'm thinking of keeping the logo even on mobile, replace the top bar with a hamburger menu on mobile and replace topbar icon-buttons with text on desktop, is it ok?

a hamburger menu might be difficult because you will have to completely reimplement:
1) the create game tooltip
2) the watch specific replay tooltip
3) the resources tooltip
4) the settings tooltip
and that is probably not ideal, because any code change to the create game tooltip will have to be copied to the mobile reimplementation version too

**Comment by DrAnax** [comment]
Work in progress, please tell me what you like/dislike:

**1. Main nav on various screen sizes:**

![image](https://user-images.githubusercontent.com/2622043/101529178-eaadc100-3998-11eb-9904-23db83a8b5ce.png)


**2. List of tables, lobby**

![image](https://user-images.githubusercontent.com/2622043/101530362-78d67700-399a-11eb-8926-93aa8673c323.png)

**3. Lobby, max-width: 620px (or smaller) OR max-height: 520 (or smaller)**

Bottom half gone, can be toggle with the bottom screen buttons. User status gone

![image](https://user-images.githubusercontent.com/2622043/101530772-0619cb80-399b-11eb-965c-7a3ba707ae14.png)

**4. Lobby, max-width: 520px**

Users panel gone, user indication next to chat title

![image](https://user-images.githubusercontent.com/2622043/101530935-40836880-399b-11eb-8cb0-3d63f3ed66d8.png)

**Comment by DrAnax** [comment]
In the case of the narrowest nav, 'help' is gone, not 'settings' (text is wrong, image is correct)

**Comment by Zamiell** [comment]
so you are getting rid of the icons for desktop users?
that seems bad because now non-native english speakers will have a more difficult time using the website.
each button has an appropriate icon as a hint as to what the button does, which can help you use the website even if you don't know any english.

is the intent of removing the buttons to save horizontal space?
the current nav works well all the way down to 395 px wide.
according to [this website](http://www.javascriptkit.com/dhtmltutors/cssmediaqueries2.shtml#:~:text=Most%20mobile%20phones%20have%20a,CSS%20pixel%20on%20the%20screen.), phones can have a width of 320, so the fact that our current nav doesn't work on 320 is probably a bug.

**Comment by Zamiell** [comment]
the tables/chat changes all seem great

**Comment by DrAnax** [comment]
I didn't remove them in order to save space, just my personal view of a navbar. I can always bring them back. But, as you say, not all buttons fit in smaller resolutions. Are you ok with the order of button removal?

**Comment by DrAnax** [comment]
In any case the designs are based on the assumption that users will use landscape mode on mobiles

**Comment by Zamiell** [comment]
> Are you ok with the order of button removal?

yes sir, with 1 exception:
"watch" is less important than "history"

> In any case the designs are based on the assumption that users will use landscape mode on mobiles

that seems fine to me

**Comment by padiwik** [comment]
Isn't it weird to covertly remove information just because the screen is smaller? I imagine a scenario where someone says "check the Spectators column" yet they don't see any Spectators column

**Comment by padiwik** [comment]
If Play = Create Table and Watch = view lobby or join a table, that seems unclear. I'm not sure what those buttons are intended to do though.

**Comment by DrAnax** [comment]
> Isn't it weird to covertly remove information just because the screen is smaller? I imagine a scenario where someone says "check the Spectators column" yet they don't see any Spectators column

It is, in a sense; but the alternative design (presented initially) produces a very long scrolling screen of tables.



> If Play = Create Table and Watch = view lobby or join a table, that seems unclear. I'm not sure what those buttons are intended to do though.

Both links show the relevant tooltip; I dont think there will be an issue imo

**Comment by padiwik** [comment]
Oh it's the Watch Replay button, i see. I still feel like Play should be named Create or New because if you want to play by joining an already-made table, you shouldn't be pressing this button. But when it's called "Play" you might be misled to do so.

**Comment by DrAnax** [comment]
New is indeed better; can be done 'new game' on wider screens and just new on tight space

**Comment by padiwik** [comment]
(Watch, similarly, reads like Spectate but I guess there isn't really a better way to do it)

**Comment by padiwik** [comment]
probably Replay makes more sense?

**Comment by DrAnax** [comment]
I think so

**Comment by Zamiell** [comment]
should i close this now?

**Comment by DrAnax** [comment]
Yes please
