### ISSUE TITLE
feature request: display game id in chat

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1878]
add phrase "The game №${gameId} was terminated/finished". when players do not review their games/do quick reviews/immediately restart/played it long time ago and i just came back, then i don't have time to copy the link, and it would be quite useful to display it in chat. now i have to open the scores, history and find the game. aren't there so many actions for a user?

**Comment by Zamiell** [comment]
when you say game id do you mean table id or database id

**Comment by Aigul9** [comment]
six-digit number

**Comment by Zamiell** [comment]
done

**Comment by Aigul9** [comment]
omg, this is perfect
