### ISSUE TITLE
Effeciency false in Throw it in a Hole

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#1888]
The effeciency required is sometimes shown (during a whole turn) while it shouldn't (but the number shown is really high, things like 3.00/x in a normal game).

**Comment by Zamiell** [comment]
the req eff is always shown as the 2nd number

provide steps to reproduce

**Comment by Romain672** [comment]
I dunno, but it's pretty commun.
https://www.zupimages.net/up/20/48/9vmv.jpg

Play one game and you will see at least twice.

**Comment by Zamiell** [comment]
provide a specific replay and a specific turn, and then say what you think the efficiency should be

**Comment by Romain672** [comment]
Game 353886
During the whole first half (about).
Effeciency should be - | 1.00 but it goes from things like 1.57 | 1.00 to 0.00 | 1.00.

**Comment by Zamiell** [comment]
i repeat myself:
provide a specific turn, and then say what you think the efficiency should be

**Comment by Romain672** [comment]
Game 353894
Effeciency shown during game was:
turn 18: 1.14 | 1.00
turn 22: 1.75 | 1.00
turn 23: 2.33 | 1.00
turn 24: 3.00 | 1.00
turn 25: 5.00 | 1.00
turn 26: 5.00 | 1.00
turn 27+: - | 1.00

On the replay, effeciency is normal.
For all these turns, effeciency should be - | 1.00.
If you miss the title, it's 'thow it in a hole'.

**Comment by timotree3** [comment]
> For all these turns, effeciency should be - | 1.00.
That is not how we intend it to work. It is possible to display a reasonable value for future efficiency in a game of Throw-It-In-A-Hole. It's supposed to count the number of cards that players have tried to play over the course of the game, and treat that as the current score, and do the rest of the calculation as normal

**Comment by Romain672** [comment]
It was my pov if that's matter.

**Comment by Zamiell** [comment]
tim should i close this then?

**Comment by Romain672** [comment]
No, these numbers are still weird, they seem way too high.

**Comment by Romain672** [comment]
and the '- | 1.00' doesn't seem normal too.

**Comment by timotree3** [comment]
@Romain672 I believe I fixed this in my PR #1896. After it is accepted, let me know if you encounter the problem again.
