### ISSUE TITLE
Morph UI Proposal

### ISSUE THREAD

**Issue by Hyphen-ated** [Zamiell/hanabi-live#1889]
while in hypo, the "give clue" button is 3/4 as wide as normal, and the extra space contains a button labeled "edit cards". when you click it, it modally turns from black to gray in the same way that the clue ui buttons do. it also changes your cursor to a pencil. when you left click on a card while in this mode, it opens the existing morph dialog. exit the mode by left clicking on anything that's not a card.

**Comment by Hyphen-ated** [comment]
rough mockups
![editcards](https://user-images.githubusercontent.com/1559801/100316389-46c31f00-2f6f-11eb-94ea-7bd543e45e66.jpg)
![noclues](https://user-images.githubusercontent.com/1559801/100316396-49257900-2f6f-11eb-9258-a7e4e52d12c6.jpg)

**Comment by Zamiell** [comment]
put it on the right side

**Comment by Zamiell** [comment]
because the leftmost option should be the default option

**Comment by Hyphen-ated** [comment]
i think that logic only applies to dialogs. but i don't see any reason to prefer left over right, so sure

**Comment by padiwik** [comment]
It's weird either way, is there any way to fit it into the "hypo region" of buttons?

**Comment by Hyphen-ated** [comment]
you mean above "end hypo" in the lower left? that's the only hypo region while you're actually in hypo. that seems worse to me, the  lower left corner feels more like "changing where you are" whereas the middle fits better with manipulating game objects

**Comment by padiwik** [comment]
In BGA mode at least there was a proposal to put all the hypo buttons next to each other (show drawn cards, back 1, etc)

**Comment by Hyphen-ated** [comment]
ok if there's other necessary hypo buttons maybe the whole clue ui should slide left a bit and a collection of buttons goes in next to it

**Comment by Zamiell** [comment]
you could do:

1) when a hypo is active, instead of being centered, clue UI is moved to the left
2) all 3 hypo buttons go to the right of the clue ui, e.g.
  - end hypo
  - show drawn cards
  - back 1 turn
3) this would be done on both keldon mode and BGA, and the UI is identical between the two (so it would be nice code wise and for consistency purposes)

remaining problems:
1) there's not enough room for a 4th button of "edit cards", you would have to make all the other shit smaller
2) even without a 4th button, there's not even enough room for the existing 3 buttons, because shown drawn cards is 2 lines long

**Comment by Zamiell** [comment]
hyphen, can you do a mockup of the following (as a stress test to see if there is room):

- BGA mode
- 6 players
- 6 suits
- clue UI moved to the left
- 4 hypo UI buttons showing to the right of the clue UI:

1) "Back 1 Turn"
2) "Edit Cards"
3) "Show Drawn Cards"
4) "End Hypothetical"

**Comment by padiwik** [comment]
Why BGA mode?

**Comment by Zamiell** [comment]
because there is less room to the right of the clue UI in BGA mode, so it is the limiting mode

**Comment by padiwik** [comment]
The space to the right seems the same, but in Keldon mode there is less vertical space

**Comment by Zamiell** [comment]
im not considering the vertical space at the moment because presumably you wouldn't put any of the hypo buttons below the y axis of the existing clue UI

**Comment by Zamiell** [comment]
but you are right in that it is possible to cram some buttons below the clue UI (but only in BGA mode, so it doesn't help us that mode)

**Comment by Hyphen-ated** [comment]
![hypomock](https://user-images.githubusercontent.com/1559801/100321576-c0f7a180-2f77-11eb-9372-759669e4051f.jpg)

**Comment by Zamiell** [comment]
hmmm, probably an improvement over what we have right now
but looks a bit messy =(
padi what do u think

**Comment by Zamiell** [comment]
it is also kinda dumb how the player buttons are over the hypo buttons

**Comment by padiwik** [comment]
I think the pencil icon is kinda silly, and all the buttons can be one line if you just say "End Hypo". Though perhaps abbreviations are bad design?

About the people buttons, I was wondering if changing to the more natural workflow of click a number/color and then click on a player's hand is a good idea. I believe every other place does it like this.

**Comment by padiwik** [comment]
unfortunately that makes clue previews difficult on mobile

**Comment by Zamiell** [comment]
> I was wondering if changing to the more natural workflow of click a number/color and then click on a player's hand is a good idea.

that might piss off a lot of people ><

**Comment by Hyphen-ated** [comment]
i think "end hypothetical" is preferable to "end hypo", all else equal. it's not really a standard abbreviation, so it's kind of an avoidable "huh?" moment.

if the other three buttons could all be approximately that same number of characters, i would prefer "end hypo", to be consistent. 
but i'm not sure "show drawn cards" is ever getting down that low, so given that constraint, "end hypothetical" seems better

**Comment by Zamiell** [comment]
ok, since no-one has any better ideas, lets move forward with the implementation of this mockup

hyphen, do you want to do a pull request? in order to move the clue UI to the left, you can copy-paste the same code that moves the "Toggle Shared Turns" button to the left

**Comment by Hyphen-ated** [comment]
so far I have implemented the following.
I rearranged which one is on top because "show drawn cards" is sometimes not visible, so it looks better to have it at the periphery of the button cluster instead of the middle.
it seemed neater to have them all the same width so I made them the same width.
this made it necessary to shorten the text, so I'm trying it out with "end hypo" and with "show drawn/hide drawn". on the theory that the "cards" part is inferrable. not really sure if this is a good idea.
![hypoui](https://user-images.githubusercontent.com/1559801/101197202-a7f58d00-3616-11eb-8a96-6810c1003ef4.png)

**Comment by timotree3** [comment]
Looks great!

**Comment by Zamiell** [comment]
looks excellent, thank you

> I rearranged which one is on top because "show drawn cards" is sometimes not visible

Can we change the behavior of this such that it is always visible, but disabled (e.g. will have faded text) when it is supposed to be hidden?
Then, you could put it in the middle again.
("Edit Cards" seems like a more important option than "Show Drawn Cards", so it should probably be at the top, but I guess that is debatable.)

**Comment by Zamiell** [comment]
(For reference, the "Give Clue" button is a good example of a disabled button. You just call `button.setEnabled(true)`).

**Comment by Hyphen-ated** [comment]
it feels to me like the bottom row is actually the most prominent row, kinda because it's lined up with the huge "give clue" button, and because the lower right corner juts out into empty space.

both of the bottom buttons are more important than either of the top buttons. i think the hierarchy of importance is consistent when edit cards is in the middle

**Comment by Zamiell** [comment]
> i think the hierarchy of importance is consistent when edit cards is in the middle

ok, sure.

can we still change the invisible --> disabled though? i think invisible buttons are probably bad, since it is less clear what is going on

**Comment by Hyphen-ated** [comment]
okay sure

**Comment by Zamiell** [comment]
another idea for consideration:
alice tries to click on the disabled "Show Cards Button", and it doesn't work, and she thinks to herself "I wonder why this is disabled"
so maybe we could a tooltip on the disabled button: "You cannot hide drawn cards right now because one or more cards drawn cards have been touched by a clue."

**Comment by Zamiell** [comment]
@timotree3 do you remember off hand what all the conditions specifically are for the button being visible/hidden currently?

**Comment by timotree3** [comment]
> @timotree3 do you remember off hand what all the conditions specifically are for the button being visible/hidden currently?
It's shown if we're in a hypothetical and I'm the leader and we're in a shared replay. It should be shown if we're in a hypothetical and I'm the leader and the game is finished. Working on a PR for that

**Comment by Zamiell** [comment]
ohh, so i misunderstood how it worked then.
it **is** already disabled most of the time in the correct way

**Comment by Hyphen-ated** [comment]
is "Exit Hypo" a better label than "End Hypo"?
exit is a more standard word

**Comment by timotree3** [comment]
> is "Exit Hypo" a better label than "End Hypo"?
I think so

**Comment by Zamiell** [comment]
i guess

**Comment by padiwik** [comment]
> add a tooltip on the disabled button: "You cannot hide drawn cards right now because one or more cards drawn cards have been touched by a clue."

This isn't exactly accurate, it should be something like "one or more drawn cards have been clued or played or discarded". Additionally, I think there should be a tooltip to explain what "Show Drawn" means because it seems very unclear to someone new to the site.
