### ISSUE TITLE
Change icons of game's options in the history

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#1907]
Title.

The 'empty clue' option and 'one more card' look the same in the 'show history'.

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/100496188-2ab2af80-3120-11eb-99d3-789080029510.png)

looks fine to me

**Comment by Romain672** [comment]
Oh mb. I though each option was shown inside, but not it's always a '+'.
Sorry :(

**Comment by padiwik** [comment]
I want it to show the icon of the option if it's just one option

**Comment by Zamiell** [comment]
open a new issue
