### ISSUE TITLE
Clearer options icon in games history

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1908]
In "show history", if a game has only one additional option (e.g. speedrun) that icon should be displayed instead of a generic "+"

**Comment by Zamiell** [comment]
what do you want to show if there are two or more options

**Comment by padiwik** [comment]
same as now is ok, but i do think there is room to put two icons

**Comment by Zamiell** [comment]
the current icon looks like "One More Card"

**Comment by Zamiell** [comment]
maybe this https://fontawesome.com/icons/ellipsis-h?style=solid

**Comment by padiwik** [comment]
That means the current icon is bad design (see Romain's confusion). I was also thinking an ellipsis.

**Comment by Zamiell** [comment]
ok, do PR
