### ISSUE TITLE
Timer wrong first turn

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#1914]
The timer of the first player is sometimes wrong at the start of the game.
It is display like: '153722867:xx'.

It seem to happen a part of the time when you start a game. Not sure how to reproduce it.

**Comment by Romain672** [comment]
Now that I think to it, it's possible that both game were because of the server which restarted. I don't believe so but maybe.
So if no one report that bug again in the following days, it seem to be that.

**Comment by Romain672** [comment]
It happen again, but it's pretty rare.
Could be because of Firefox/lag.

**Comment by DrAnax** [comment]
Fixed by #2301
