### ISSUE TITLE
Post-game hypo: hide the hand of the player who chooses the line

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1918]
Similar to the rationale for hiding drawn cards, it might make sense to hide the other cards that are not known to the person making the decision: the cards in their hand.

Then again, it can be pretty easy to ignore their hand through willpower, and that is a skill you need in order to predict player's actions in Hanabi in general.

**Comment by Zamiell** [comment]
agree with this, make it togglable with the "Shown Drawn Cards" button

**Comment by timotree3** [comment]
If we were to implement this it should show the empathy on their hand rather than making every card "blank", right?

**Comment by Zamiell** [comment]
oh ya

**Comment by Zamiell** [comment]
thats weird

**Comment by Zamiell** [comment]
because then empathy on the hand would show the real card, instead of showing the empathy

**Comment by timotree3** [comment]
> because then empathy on the hand would show the real card, instead of showing the empathy
maybe that should be the case for hidden drawn cards too then

**Comment by Zamiell** [comment]
meh, sounds complicated

**Comment by Zamiell** [comment]
this feature/suggestion sounds like it would add a lot of complexity for not a lot of gain

**Comment by Zamiell** [comment]
i want empathy to always show empathy, not the opposite of empathy

**Comment by Zamiell** [comment]
so basically to do this feature, you would want to add some code to the `setBareImage()` function, to make it ignore `globals.state.cardIdentities` (line 334) iff
1) you are in a hypothetical
2) and started the hypo
3) and the card was in your hand at the beginning of the hypo

**Comment by Zamiell** [comment]
and then hitting the "Shown Drawn Cards" should already recalculate all cards I think, so thats it

**Comment by DrAnax** [comment]
Is this still valid?

**Comment by Zamiell** [comment]
oh interesting, we had a duplicate issue for this from 2 years ago.
yes, you implemented this feature, so minus the discussion about "empathy showing the reverse of what it normally shows", this can be considered closed, thank you
