### ISSUE TITLE
rejoining a shared replay

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1930]
Steps to reproduce:
1. Play the game.
2. Leave the shared replay
3. Try to join this replay again

**Comment by NoMercyO** [comment]
Myself and Florrat independently experienced this bug last night as well. Error that occurs (as soon as you log in to the website) was roughly to the effect of "you cannot rejoin a game while you are still playing" suggesting the error is related to the server designating you as an active player despite the lobby changing to a replay. 

Rehosting a replay is a current viable workaround.

**Comment by Zamiell** [comment]
fixed thanks
