### ISSUE TITLE
Contrarian only grants 1 turn after deck runs out

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#1933]
Game ID 360103

**Comment by Zamiell** [comment]
that isn't a bug.
jake doesn't have any playable cards, so why would you want him to have a turn?

**Comment by jakestiles** [comment]
But wump did. Does contrarian not reverse in end game?

**Comment by Zamiell** [comment]
oh i see, nevermind what i said

**Comment by timotree3** [comment]
Looks like bug in on `command_action.go` line 148. It needs to account for contrarian turn order
