### ISSUE TITLE
Make it more easier to answer a private message

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#1937]
Is it possible to either:
 - add a ' [Answer]' to the end of a private message, and if it is clicked, it automatiquely write '/w personwhosendthepm ' (to be exact, it would replace the current message writed by that)
 - or, if you type '/w[tab]' or '/w  [tab]' it automatiquely choose the last person pm?

Or both? :D

**Comment by Zamiell** [comment]
are you aware that /r exists

**Comment by Romain672** [comment]
Ok it's what i wanted, nvm then, sorry for this one :(
