### ISSUE TITLE
Player´s turn skipped

### ISSUE THREAD

**Issue by RealToDie** [Zamiell/hanabi-live#1938]
Game-ID: 360620

Player 1 plays the last card from the bottom of the deck. Then the turn of player 2 is kind of skipped. The game says that it is the turn of player 3, but the message "It is not your turn, so you cannot perform an action" appears when player 3 tries to play a card. Player 2 cannot do anything at all. Maybe an issue with detrimental characters (panicky, spiteful, miser)?

**Comment by willwin4sure** [comment]
My guess is that Panicky interacted with the bottom deck blind play badly
