### ISSUE TITLE
Refresh page in shared replay opens new copy of shared replay instead of remaining in current one

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1947]

**Comment by Zamiell** [comment]
provide steps to reproduce

**Comment by timotree3** [comment]
1. open shared replay with a second player
2. eyeballs = 2
3. refresh the page
4. both see eyeballs = 1

**Comment by Zamiell** [comment]
i did those steps and the problem does not reproduce
provide better steps to reproduce

**Comment by timotree3** [comment]
I don't believe you. try again.

**Comment by timotree3** [comment]
works every time for me. presumably because of the change to shared replay urls

**Comment by timotree3** [comment]
just tested those steps on prod to be sure and it reproduced.

**Comment by timotree3** [comment]
weirdly, I can't reproduce on master

**Comment by timotree3** [comment]
maybe you already fixed this?

**Comment by Zamiell** [comment]
well prod is on master so if you reproduce on prod then no?

**Comment by Zamiell** [comment]
The server has successfully started at: Fri Dec 04 21:39:59 UTC 2020 (27ff9a0cf44fb8d3f115f746e8f64fdf515f300f)

**Comment by timotree3** [comment]
well last time it happened on my main account what I did was:

1. play a game of hanab with real people
2. finish it and enter shared review
3. refresh the page.
4. oops! no longer in the same shared review

**Comment by Zamiell** [comment]
should be fixed automatically by the new functionality

**Comment by Zamiell** [comment]
for fun, see if you can reproduce on master now
