### ISSUE TITLE
Ambigious & Rainbow (3 Suits) and Ambigious & Prism (3 Suits) are the same

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#1951]

**Comment by Zamiell** [comment]
intended

**Comment by padiwik** [comment]
you intend to have the "same" variant with different names? seems odd

**Comment by Zamiell** [comment]
its just a consequence of variant combinations that are valid

**Comment by padiwik** [comment]
Yet pink and brown reversed got removed

**Comment by Zamiell** [comment]
indeed. however, the heuristic for not generating pink reversed is much less specific than the one required to fix this problem, so i dont think it is perfectly analogous.
in the case of reverse pink, normal pink naturally takes precedence.
in the case of Ambigious & Rainbow (3 Suits) and Ambigious & Prism (3 Suits), which takes precedence and why?

**Comment by padiwik** [comment]
Rainbow because it comes first in the variants listing, and in particular is a default variant
