### ISSUE TITLE
Clicking end hypo is really laggy

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#1962]

**Comment by timotree3** [comment]
can't reproduce locally. I think it may have to do with the round-trip time for the `endHypo` action

**Comment by Zamiell** [comment]
you should be able to confirm that pretty easily by just having the javascript console open and watching it for when the green message is sent out and the black message comes back

**Comment by timotree3** [comment]
I can't reproduce it at all, actually. Closing for now
