### ISSUE TITLE
split into subpackages

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#1972]
- tables
- http
- github
- models

**Comment by DrAnax** [comment]
Have you tried starting VSC with the provided workspace file (`code hanab.code-workspace`)? VSC behaves correctly even when using subpackages.

If so, this is issue still valid?

**Comment by Zamiell** [comment]
this is a duplicate of the "channels server refactor" issue, which we have decided against and will instead write the server in typescript with redis transactions
