### ISSUE TITLE
Esc key in in-game hypo doesn't fix the button interface

### ISSUE THREAD

**Issue by padiwik** [Zamiell/hanabi-live#1982]
Also do you think Esc should exit hypo but keep you in the replay, in general?

**Comment by timotree3** [comment]
what do you mean fix the button interface?

**Comment by padiwik** [comment]
![image](https://user-images.githubusercontent.com/24983586/101414768-b8c32e80-38b4-11eb-91b0-75a08edeb757.png)
It should remove the clue UI and add back a button to enter in-game replay

**Comment by Zamiell** [comment]
> do you think Esc should exit hypo but keep you in the replay, in general?

sure

**Comment by padiwik** [comment]
should be fixed in #1983
