### ISSUE TITLE
window width in a game

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1993]
change sizes of elements according to window width during the game without refreshing the page

**Comment by Zamiell** [comment]
too difficult for now, maybe in a year or two when we have a better state of affairs with the graphics library

**Comment by padiwik** [comment]
didn't rob do this at some point? what happened to it

**Comment by Zamiell** [comment]
it was super buggy so we reverted it

**Comment by Aigul9** [comment]
you said the same words some time ago, like half a year back or more

**Comment by Zamiell** [comment]
well, its not easy to redesign the entire UI.
if you want complicated things then pay money to hire a coder to help us, otherwise do not complain
