### ISSUE TITLE
fix ui in mobile version

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2023]
![7BB245F6-63BA-433A-A2B0-B5CDAEC26A37](https://user-images.githubusercontent.com/46625461/103386098-425dc900-4b0e-11eb-8918-4aaafd55fa98.png)
arrows point in empty space in portrait orientation.
also this form remains in the same place regardless of the orientation.
portrait -> landscape. in another direction it is off screen
![8642DEC8-21E3-4942-9C66-4B5040DD5CC4](https://user-images.githubusercontent.com/46625461/103386183-bef0a780-4b0e-11eb-967d-a3bd6a96af78.png)

**Comment by padiwik** [comment]
If you initially load the page while in landscape mode, is it normal?

**Comment by Aigul9** [comment]
arrows - yes

**Comment by DrAnax** [comment]
This has been fixed by the new modals
