### ISSUE TITLE
Variant Request: Reversed + Other

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#2026]
Reversed + Black
Reversed + Pink
Reversed + Rainbow
Reversed + White
Reversed + Brown

**Comment by Zamiell** [comment]
already exists

**Comment by jakestiles** [comment]
Reversed Black exists. A variant with one Reversed suit + another Black suit does not exist. Which was my proposal.

**Comment by Zamiell** [comment]
nothing else gets this treatment, so nah

**Comment by jakestiles** [comment]
You mean there isn’t a variant that has a Black suit and a separate Rainbow suit. Or a variant with a White suit and a separate Pink suit? Etc.

**Comment by Zamiell** [comment]
no, i mean that each variant modifier gets every special suit and no more, no less

**Comment by jakestiles** [comment]
Ok. And it not having been done before is sufficient reason not to do it? Do you also think it’d be uninteresting or too hard or too hard to code?

I like Reversed and think the additional variants would be interesting.

**Comment by Zamiell** [comment]
it is an arbitrary rule to limit the number of variants, otherwise we would have 100,000 variants instead of 1841
if/when choose-your-own-variant is implemented, then it will alleviate the issue
until then this is a good metric with which to decide how variants are combined
