### ISSUE TITLE
Finesse border takes precedence over clued border

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#2032]
Use case: In hat guessing, I end up writing `[unclued] [f]` on any clued card that has been given a play instruction, and I would rather just write `f`.

**Comment by Zamiell** [comment]
should cm also take precedence over clued border?
if not, thats introducing inconsistent behavior.
besides, its very confusing to change these defaults now, and hat guessing is an edge-case that we don't care about optimizing for

**Comment by timotree3** [comment]
> should cm also take precedence over clued border?
actually that would be helpful for hat guessing too. might be annoying for hyphen-ated players who use keldon mode though (no raised clued cards)

**Comment by Zamiell** [comment]
i think the current behavior is better + i dont care about hat guessing
