### ISSUE TITLE
Critical-four variant

### ISSUE THREAD

**Issue by Pimak** [Zamiell/hanabi-live#2037]
I propose a variant where every 4 is critical.
This might be very hard to win especially in 2/3 players games with so many saved cards.
In a critical-four variant, each suit looks like this :
111
22
33
4
5

**Comment by Zamiell** [comment]
its been proposed before and doesn't sound very fun

**Comment by Pimak** [comment]
Well, I like it :smile: 
Thanks @bhamrick for #2168
