### ISSUE TITLE
Feature Request: Set maximum player count on table creation

### ISSUE THREAD

**Issue by eskolnik** [Zamiell/hanabi-live#2053]
In the current implementation, any public table will allow 6 players to join, which can lead to either unenjoyable games (as many folks prefer 3-5p to 6p) or the group needing to coordinate to split into separate lobbies. The simplest solution to this would be to cap lobbies at 5, but for the sake of people who do enjoy 6p games, it would be nice to leave those available. To that end, I propose that we have newly created tables default to a 5-player cap, but provide an option in the table creation UI for the host to set an arbitrary player cap (2-6). 

Example UI
![image](https://user-images.githubusercontent.com/1791642/105071070-1e790d80-5a52-11eb-9483-9063b2d04fa6.png)

**Comment by DrAnax** [comment]
Fixed via #2314
