### ISSUE TITLE
/pause doesn't work, /setleader doesn't work on pregame

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-live#2062]
/pause doesn't work, /setleader doesn't work on pregame

pause is very important because real life things happen, like a doorbell or a phonecall we cannot kill all games because someone needs 1 min to do something else. I would like to be able to open a door, without playing untimed games because I find them boring

**Comment by Zamiell** [comment]
/pause was removed
you can (still) pause by right clicking on the timer though

**Comment by padiwik** [comment]
Why remove useful chat commands?

**Comment by Zamiell** [comment]
how is it useful

**Comment by padiwik** [comment]
Some people prefer using chat commands rather than an obscure feature of "right click the timer"

**Comment by Zamiell** [comment]
it is much faster to right click the timer, so i dont care about that preference

**Comment by Zamiell** [comment]
furthermore, i dont think a documented chat command is any more "obscure" than a documented right click

**Comment by padiwik** [comment]
> it is much faster to right click the timer

No if you're already in chat (perhaps you tell your teammate "brb someone's at the door") then it's significantly faster to type out a pause.

**Comment by Zamiell** [comment]
thats more of an argument to make a ctrl+p hotkey for pause rather than typing 7 keystrokes

**Comment by Zamiell** [comment]
mel see if you can find a reliable way to do the /setleader bug
closing for now since i can't reproduce
