### ISSUE TITLE
Prism & Dual Color

### ISSUE THREAD

**Issue by Pimak** [Zamiell/hanabi-live#2063]
Dual Color & Prism don't work together as intended.
For example, in 4 suits : 
The suits are as follow : 
Orange, touched by Red and Yellow
Purple, touched by Red and Blue
Green, touched by Yellow and Blue

However, for the prism cards, they are :
Prism 1 touched by Red
Prism 2 touched by Yellow
Prism 3 touched by Blue
Prism 4 touched by Red
Prism 5 touched by Yellow

**Comment by padiwik** [comment]
Prism cards are based on the _colors_ in the game, not the suits. Similarly, in Prism & Rainbow there is no "rainbow" Prism card touched by all the colors.

**Comment by Zamiell** [comment]
padi is right

**Comment by rogers-j** [comment]
See also: #2061
