### ISSUE TITLE
Prism stack color indicator

### ISSUE THREAD

**Issue by Pimak** [Zamiell/hanabi-live#2064]
As I said in #2063 , Prism can be confusing when using some weird variants.
If we had an indicator under the suit, it would be easier to know at a glance what a clue means.
Right now, in these weird variants, to know what prism card it could be, we can :
- Remember every single cards
- List them in chat, and then use it as a reference
- Wait for your turn to see the colors used in this game
- Enter hypothetical and see the colors in the clues
None of these are practical.

The indicator could be 5 squares just under the stack 
Or at the top of the suit like how it look like for dual-color suit (the corner has 2 colors)

**Comment by padiwik** [comment]
* The color of the prism cardback of a particular suit matches the color that touches it
* Empathy would work if it is known Prism
* I believe every variant has the colors in the logical order if you just look at the suits, and it's not hard to figure it out from there
Is this not enough?

**Comment by Zamiell** [comment]
i find myself agreeing with padi

padi why so based lately

**Comment by Pimak** [comment]
When the stacks look like this, it's hard to know the colors of each prism cards
![image](https://user-images.githubusercontent.com/37274338/106103352-1a7b7880-6141-11eb-8810-bb4536eb6b70.png)

**Comment by Zamiell** [comment]
from left to right its red yellow blue, right?

**Comment by Pimak** [comment]
Yes. I wasn't even sure and had to check back the [replay](https://hanab.live/replay/415411#1) to confirm

**Comment by Zamiell** [comment]
yeah so you can just look at the triangles from left to right

**Comment by DrAnax** [comment]
@Zamiell close

**Comment by Zamiell** [comment]
i guess this exists now in the mouseover tooltip, so i will close
