### ISSUE TITLE
history table

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2072]
1) could we sort the table on /history not by max score, but max possible score? it seems illogical to have 4 suits after 21/30 6 suits.
2) isn’t it more intuitive to sort in desc order by default?

**Comment by Zamiell** [comment]
1) its just sorted by alphabetical, i dont know how to sort it any better
2) what do you mean

**Comment by Aigul9** [comment]
if you click on “score” column, it will be sorted by score, date... and 30 > than any other number, but i think that max scores for 3/4/5 suits should be shown alongside them.

so by clicking once, it will show 0s first, which is not really useful

**Comment by rogers-j** [comment]
You'd rather sort it by `maximum score - actual score`, so that 30/30 and 25/25 and 20/20 are all sorted before 29/30, 24/24, and 19/20? Seems reasonable.

**Comment by DrAnax** [comment]
> You'd rather sort it by `maximum score - actual score`, so that 30/30 and 25/25 and 20/20 are all sorted before 29/30, 24/25, and 19/20? Seems reasonable. Then we would need to invert the sort order, so that the 'difference from perfect' is instead ascending.

I the end I used `actual / maximum` instead; 10 / 15 and 15 / 30 seem equal to me.

**Comment by Zamiell** [comment]
takis did this, it should sort properly now

> I the end I used actual / maximum instead

this algorithm seems really good imo
