### ISSUE TITLE
In-game explanation of the used variant

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2073]
If I'm a new player, and started e.g. spectating a game of some variant, then I'll have no idea what is this "light pink" or "muddy rainbow" suit is. So I'd move the mouse to that suit, and there would be a tooltip that explains that "light pink is ...."

And such tooltip should mention which letter I should use in the notes to mark my card as of that suit, like "3y" (yellow 3) but for some other suit. Such letter is currently only visible in the colorblind mode.

**Comment by rogers-j** [comment]
Does that include hovering over a play stack with zero cards?

**Comment by DarthGandalf** [comment]
Of course. There should be no need to play at least one card on the stack to learn how that suit works.

**Comment by Zamiell** [comment]
good idea
