### ISSUE TITLE
Make Empathy discoverable

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2074]
Empathy should be available as a clickable button somewhere. I had no idea there is this feature until I was told to hit spacebar.

I just want the feature to be discoverable intuitively, without someone who already knows about it mentioning it to you, and you asking "empathy? what's that?"

Slightly related to #864

**Comment by Zamiell** [comment]
there's no room to put another button though.
so suggest something a little more specific

**Comment by rogers-j** [comment]
You are supposed to discover this when your mouse cursor changes while hovering over a card in another player's hand.

**Comment by DarthGandalf** [comment]
I saw the cursor change, but I thought it's an indication to look at the top right corner which has a list of hints about the card under cursor. Also the effect is a bit different: the spacebar toggles empathy for every player, not for one.

P.S. before your comment I did not know I can click on those cards to show the partial empathy for that specific player

**Comment by rogers-j** [comment]
"Partial" empathy is the real one, and the spacebar does it for all hands for lack of a separate hotkey per player.

**Comment by rogers-j** [comment]
> I saw the cursor change, but I thought it's an indication to look at the top right corner which has a list of hints about the card under cursor.

The two features are meant to work together; you hover over a player's card, causing the hint list to highlight the clues to that card and especially who gave the clues. The highlights stay in place even while seeing the cards from that player's perspective.

This is why I think adding a button would be a bad idea; it would be a detour from the correct workflow.

**Comment by DarthGandalf** [comment]
Yes, I see...

I'll think how can this be improved without adding new buttons.

**Comment by Zamiell** [comment]
will close for now unless anyone has any better ideas
