### ISSUE TITLE
Confusing UI of terminating the game

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2076]
I saw the skull in the 3rd bomb, but it's not obvious that the skull is a button. The skull looks like just a reminder that the game is lost if the 3rd misplay happens.

**Comment by Zamiell** [comment]
provide an actionable suggestion

**Comment by Zamiell** [comment]
will close since darth did not provide an actionable suggestion

**Comment by dartharaknus** [comment]
I think we should add a tooltip. I didn't realize what it was either until someone else told me.

**Comment by Zamiell** [comment]
i think the skulls already have a tooltip right?
