### ISSUE TITLE
Clue-giving keyboard shortcuts rely on QWERTY layout

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2077]
I use Colemak instead of Qwerty, and the keys don't quite match.

Such positional keys should be handled in JS via [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead of [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

**Comment by Zamiell** [comment]
submit a pr

**Comment by DrAnax** [comment]
Closed by #2137
