### ISSUE TITLE
Chat doesn't auto-scroll

### ISSUE THREAD

**Issue by mdavidson29** [Zamiell/hanabi-live#2078]
![image](https://user-images.githubusercontent.com/30240608/106394104-b4e0f380-63af-11eb-8150-d20d2594a693.png)

The chat doesn't auto-scroll if it is already open. 

- Closing the chat and reopening it brings it to the bottom
- If new messages are sent while the chat is open, it does not auto-scroll down to show new messages

**Comment by Zamiell** [comment]
the chat won't auto scroll if it isn't already set to be at the bottom-most line.
try scrolling all the way up and then scroll all the way to the bottom

**Comment by mdavidson29** [comment]
Even if I scroll all the way to the bottom, it only auto-scrolls for 1 message.  After that, it doesn't auto-scroll.

**Comment by mdavidson29** [comment]
We are doing a text review and I have to be constantly scrolling down.

**Comment by Zamiell** [comment]
try on version 4966
