### ISSUE TITLE
Link to Convention Document in Lobby needs update

### ISSUE THREAD

**Issue by Hari3** [Zamiell/hanabi-live#2088]
From the Lobby, Clicking on Resources opens a Pop-Up
![image](https://user-images.githubusercontent.com/10483303/107128036-906da580-68e0-11eb-91f7-0c7e78a65fb1.png)

Clicking on "Strategies and Conventions" should lead to the new website, https://zamiell.github.io/hanabi-conventions/.

**Comment by Zamiell** [comment]
done
