### ISSUE TITLE
scrolling bar

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2090]
couple of days ago i noticed this:
![2021-02-08_00-07-09](https://user-images.githubusercontent.com/46625461/107159596-37fedc80-69a2-11eb-8c35-d78166db6303.png)
also when note or variant description is too long:
![2021-02-08_00-07-38](https://user-images.githubusercontent.com/46625461/107159615-5664d800-69a2-11eb-8a1b-a83cc09c47a9.png)

**Comment by DrAnax** [comment]
Any steps to reproduce? Browser, screen size etc

**Comment by Zamiell** [comment]
closing since she didn't provide steps to reproduce

**Comment by Aigul9** [comment]
I am using chrome, 100% screen size.
This problem still exists. In pre-game it applies to long variants, I think in the game it appears when no extra feature (bdbp, all or nothing, etc) is chosen.

**Comment by Aigul9** [comment]
How to reopen an issue?
