### ISSUE TITLE
Impossible Notes

### ISSUE THREAD

**Issue by Smandon1** [Zamiell/hanabi-live#2098]
When playing 'Throw It in a Hole', I often put notes on the play piles to keep track of what I think happened.  Sometimes during the game I am unable to enter notes for a play pile, typically the green play pile (I'm not sure if any other piles are affected).  Refreshing fixes the issue.

To reproduce:
1) Start a 'Throw It in a Hole' game.
2) Play a card.
3) Right click on the green pile, in a (oftentimes) feeble attempt to leave a note.  It will not pop up with the note input box.

This doesn't always happen for all players after playing a card, but it does seem to be happen > 50% of the time, from limited testing.

**Comment by DrAnax** [comment]
Closed via #2110

**Comment by Zamiell** [comment]
ok thanks
