### ISSUE TITLE
Throw it in a Hole: you can sometimes hear the "critical card is misplayed/discarded" sound when a partner misplays or discards a critical card

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#2100]
I have been able to repro this 2/2 times when misplaying a 5.

**Comment by jack67889** [comment]
So it's only the decreased max score sound (https://raw.githubusercontent.com/Zamiell/hanabi-live/master/public/sounds/turn_sad.mp3) that the other players can hear when you misplay a critical.

**Comment by Zamiell** [comment]
should be fixed now
