### ISSUE TITLE
Sorting games by Date & Time not working (when viewing all games with certain seed)

### ISSUE THREAD

**Issue by nikolockenvitz** [Zamiell/hanabi-live#2130]
I noticed that sorting games (when viewing all games with certain seed) does not work as expected for Date & Time.

Steps to reproduce:
* go to https://hanab.live/seed/p3v16s14
* sort column `Date & Time` by clicking on it (I just assume that this should be possible as it works for all the other columns)
* table is not sorted by date & time, e.g. there are some games from 2019, 2020, 2021 but then again some from 2020 and 2019
* I would expect it to be sorted by timestamps

btw, really nice game/implementation ;)

**Comment by Zamiell** [comment]
do you wanna submit a pr?

**Comment by nikolockenvitz** [comment]
Sure, can do this. I would look into it next week. But I also need to setup everything locally and get familiar with the code base. However, fix should be pretty straight forward I guess.

**Comment by Zamiell** [comment]
ok thx
