### ISSUE TITLE
"change variant" btn doesn't work as expected

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2131]
Steps to reproduce:
1. Create a game
2. Join from another acc
3. Try to change a variant from that acc

Non-leaders didn't have this button enabled before. Why was it changed?

**Comment by newduke** [comment]
Hey @Aigul9 , I added this because it is hard as a nonleader to select and suggest variants.  It just pastes the variant name in chat.

**Comment by Aigul9** [comment]
i think it should work like suggestion for turns, so that table owner can accept or decline it
