### ISSUE TITLE
Feature request: Ability to point to cards during play/spectating

### ISSUE THREAD

**Issue by bhamrick** [Zamiell/hanabi-live#2147]
Similar to using arrows to point to things during review, it would be awesome to be able to point during play for commentating purposes (like while streaming).

**Comment by timotree3** [comment]
Are you aware that you can Control+Right-Click on cards in game to point an arrow at them?

**Comment by bhamrick** [comment]
I am not. That sounds like a sufficient resolution.

**Comment by bhamrick** [comment]
(I don't see it documented on https://github.com/Zamiell/hanabi-live/blob/master/docs/FEATURES.md if you want to take this as a signal that it should be better documented)

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/60033bcb4845d7037e5c5f54db7298c83e57e400
