### ISSUE TITLE
in-game and shared hypos overlap each other

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2150]
Steps to reproduce:
1. Start a game
2. Enter to hypo mode
3. Terminate the game
So far the only option to get in sync is pause shared turns - use again - enter hypo - leave hypo.
It's been discarded in one hypo and clued in another:
![2021-03-21_19-36-12](https://user-images.githubusercontent.com/46625461/111913175-0471a080-8a7e-11eb-838b-49887d73367a.png)

Also new cards with "show drawn cards" on remain "uncolored" until you check this field one more time.

**Comment by timotree3** [comment]
is the person who enters in-game hypothetical also the shared replay leader?

**Comment by Aigul9** [comment]
i tried with non-leader
