### ISSUE TITLE
request: add /tagsdelete

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2152]
Add command which will remove all tags at once without typing each of them

**Comment by Aigul9** [comment]
will someone else be able to delete tags created by other users?

**Comment by DrAnax** [comment]
You will be able to delete all the tags of that game; that's how a single tag delete works

**Comment by Aigul9** [comment]
this sounds like incorrect behaviour

**Comment by DrAnax** [comment]
You want to delete all your tags in a specific game or all your tags in general?

**Comment by Zamiell** [comment]
end-users should only be able to delete the tags that they themselves create

**Comment by DrAnax** [comment]
Ok, incoming fix
