### ISSUE TITLE
Games Played

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-live#2166]
I believe that in games played that kinda count the experience of the players, we shouldn't count the terminated and the bombed out.

**Comment by timotree3** [comment]
I would be quite interested in seeing a Games Completed statistic that doesn't count terminations. Not sure if it should replace games played or not.

**Comment by mmelwen** [comment]
Replace it to "punish" the serial killers that live among us

**Comment by Zamiell** [comment]
> we shouldn't count the terminated and the bombed out

i agree with this

**Comment by Zamiell** [comment]
fixed by #2330

**Comment by mmelwen** [comment]
Shouldn't be the same number at score and statistics maybe there we should have something like:
Date joined: March 17th, 2020
Games played (in non-speedruns): __no of compeated not 2p games __
2p games: 
Terminated:
Time spent playing (in non-speedruns): 103 days, 6 hours, and 52 minutes
Games played (in speedruns): 42
Time spent playing (in speedruns): 43 minutes
Total max scores: 1271  (13.8%)

**Comment by Zamiell** [comment]
oh yeah, that's a good point, i guess these two numbers are no longer consistent

mel can you open a separate issue for this so that it can be tracked
