### ISSUE TITLE
Request: remove the ability to play cards from rewind when speedrun mode is disabled

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#2172]
The only real gain from being able to play cards from within a rewind is in time-sensitive modes (although typically one does not even use rewind in speedrun); otherwise, simply writing a note on the card and then playing it in the normal game view is a perfect substitute. I would argue that whatever benefit is gained by being able to play a card quickly from rewind in a timed game is not worth the channel it creates for user errors - for example:
1. User plays a card, believing themselves to be in the normal game view, when really they are in rewind mode.
2. User is playing cards in a hypothetical, and accidentally hits back one too many times, causing a return to the rewind. A subsequent play would cause a play in the actual game.

**Comment by timotree3** [comment]
Alternatively, to address the first bullet point, maybe it could exit the replay as soon as you start dragging a card, so that you see the real position in your hand.

**Comment by aliblong** [comment]
Sounds like potentially bad UX to have your hand jumping around like that, and maybe harder to implement than just removing the ability to play from rewind

**Comment by aliblong** [comment]
Closed with 2cb646b
