### ISSUE TITLE
allow writing notes on cards when game is paused

### ISSUE THREAD

**Issue by rz-1** [Zamiell/hanabi-live#2193]
I'd like to see the ability to write notes on cards when the game is paused. Often someone has auto-pause enabled and I want to see the board and write notes on cards during this time. Maybe move the pause screen to the side?

**Comment by Zamiell** [comment]
that's cheating, you aren't supposed to do anything when the game is paused

**Comment by rz-1** [comment]
I don't think it's cheating if it is not the player's turn, but I see how it could be if it is the player's turn.
