### ISSUE TITLE
line overlaps variant name on mobile

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2200]
i don’t know how it looks on pc screen, but separatory line is apparently overlapping variant name
![4499AD8F-5E47-4EB0-8E40-7A89D9412C59](https://user-images.githubusercontent.com/46625461/121813015-ec6f7e80-cc72-11eb-8610-9722575c0333.jpeg)

**Comment by Zamiell** [comment]
@DarthGandalf do you wanna take a look

**Comment by DarthGandalf** [comment]
Yeah, on desktop it looks much better than that

![Выделение_378](https://user-images.githubusercontent.com/325092/121813782-85979880-cc65-11eb-8e49-15f485f8fa15.png)

**Comment by DarthGandalf** [comment]
@Aigul9 I cannot reproduce it. On my various mobile devices it doesn't overlap

**Comment by DarthGandalf** [comment]
What browser and device is this?

**Comment by Aigul9** [comment]
Safari 14, IPhone @DarthGandalf

**Comment by Zamiell** [comment]
will close now because safari sucks and i dont care about safari, use chrome
