### ISSUE TITLE
Up or Down: Show on the backs of cards whether a card could be a Start card

### ISSUE THREAD

**Issue by jim-hays-root** [Zamiell/hanabi-live#2202]
In Up or Down, show on the backs of cards whether the card could be a Start card, for example, by showing an S to the left of the 1:
![image](https://user-images.githubusercontent.com/54556994/123523193-2a679c00-d690-11eb-9380-260287f5537c.png)

Even though users cannot directly clue Start cards, they would still be `X`'d out if the user can deduce that the card is not a Start card because they can see all the Start cards matching the possible suits

With this change, in the screenshot above the rightmost card is clearly the Green Five. Without this, the user has to remember to check whether it could also be the Green Start.

**Comment by Zamiell** [comment]
thats a nightmare to program, feel free to submit a pull request if you want that to happen
