### ISSUE TITLE
Limit the amount of results per page to reduce loading times

### ISSUE THREAD

**Issue by jack67889** [Zamiell/hanabi-live#2203]
Sadly, I'm totally incapable of submitting a pull request for this myself. But could the amount of results (for example, for a player's history or the scores for a seed) be split to like a 1000 results per page, so it won't take forever to load.

**Comment by Zamiell** [comment]
ok so this is partially complete now due to takis' work with nice javascript UI that sorts the results by page
however, the client-side stuff doesn't reduce the loading time at all.
so the real solution is to create an API to get partial results.
