### ISSUE TITLE
[proposal] Add optional level to game creation

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#2214]
Game creator could fill in the optional game level during creation. When doing this, the game's title on the main screen has a badge with the game's level.

There's no need for an additional database entry; this can be added as html into the game's title:

game title -> clean up html -> prepend with `'<span class="badge">' + game_level + '</span>'`

(which is also easily cleaned, if needed)

Using:

```
span.badge {
    background: gray;
    padding: 0 5px;
    border: 1px solid black;
    margin-right: 5px;
    border-radius: 2px;
    color: white;
}

```

this could look like this on the main lobby screen:

![image](https://user-images.githubusercontent.com/2622043/125275988-5afa3780-e318-11eb-83f4-549fea75066e.png)

Edit: can also be implemented with client-side only changes; send `level + '#' + title` as game title, split the title if there's a hashtag during main lobby table creation.

**Comment by Zamiell** [comment]
i think i prefer to have it in the database as an "official" table value
