### ISSUE TITLE
New Variant Proposal: Repeat

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#2216]
Similar idea from https://github.com/Zamiell/hanabi-live/issues/2215

#### Number Repeat
- All types of number clues can only be given once and everything resets when each number clue has been given.
- All types of color clues are always able to give.
- Once the first reset is performed, the order of the number clues is fixed (as the order before the reset) and cannot be changed for the rest of the game.
#### Color Repeat
- All types of color clues can only be given once and everything resets when each color clue has been given.
- All types of number clues are always able to give.
- Once the first reset is performed, the order of the color clues is fixed (as the order before the reset) and cannot be changed for the rest of the game.
#### All Repeat
- All types of number clues can only be given once and everything resets when each number clue has been given.
- All types of color clues can only be given once and everything resets when each color clue has been given.
- Once the first number reset is performed, the order of the number clues is fixed (as the order before the reset) and cannot be changed for the rest of the game.
- Once the first color reset is performed, the order of the color clues is fixed (as the order before the reset) and cannot be changed for the rest of the game.

**Comment by Zamiell** [comment]
sounds not fun and too similar to #2215
