### ISSUE TITLE
New Variant Proposal: Flying Six

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#2218]
### Name Origin
- *Flying Six* in *One Piece* manga

### Preparation
- Flying-SIX components: one of each [specific-color]-Six cards and `n` Blank-Six cards (for n is the number of players)
- Prepare a Flying-SIX pile before the start of the game:
  1. Shuffle the [specific-color]-Six cards and draw a random one and place it on the table face-down.
  2. Place the rest of the cards in the box. They are not used for the rest of the game.
  3. Shuffle `n` Blank-Six cards with the [specific-color]-Six card which was placed on the table in step 1. This is a Flying-SIX pile.
- At the beginning of the game, deal a card (from the Flying-SIX pile) to each player and place the last card into the box.
- Players can now see their Flying-SIX card in secret and place it in front of them face-down.

### Rules
- The player who draws the [specific-color]-Six card cannot give the [specific-color] clue nor discard the [specific-color] 5 during the entire game; while nothing apply to the players if they draw a Blank-Six card.
- The game lost immediately if someone plays the [specific-color] 5.
- To win the maximum score, in the last round, the last player has to choose one of the Flying-SIX cards among the players and play it as the [specific-color] 5.

**Comment by iamwhoiamhahaha** [comment]
> Dr_Kakashi — Today at 1:53 PM
I probably would change the rule on The game lost immediately if someone plays the [specific-color] 5.
probably would delete that
you want the last player to guess right?
pretty easy guess if a 5 hasn't been played
IAMJEFF — Today at 1:54 PM
o true
Dr_Kakashi — Today at 1:55 PM
also I would ban rank

how about Flying-SIX cards cannot be played in the last round?

**Comment by Zamiell** [comment]
too hard to code
