### ISSUE TITLE
json endpoints do not provide tags content

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2219]
tags field is empty for each game
![image](https://user-images.githubusercontent.com/46625461/125819387-dbecda69-c770-484b-9733-784f7d1b9787.png)
![image](https://user-images.githubusercontent.com/46625461/125819196-a4b5f9d6-e2b5-455d-b4c3-97583d1a4d69.png)

**Comment by Aigul9** [comment]
is this gonna be fixed

**Comment by Zamiell** [comment]
submit a PR yourself

**Comment by Aigul9** [comment]
it would be better to provide them in notes format, so that different tags are separated from each other and grouped by users
