### ISSUE TITLE
Use replay while in hypothetical

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#2224]
It would be nice to be able to check context by rewinding in order to make a move in the current turn of a hypo. There is not a lot of space for hypo controls last I heard, but perhaps we can add a small "Forward 1" button.

**Comment by Zamiell** [comment]
its a bit confusing to be in a hypo and in a replay at the same time, so im not sure how good of an idea this is

**Comment by Zamiell** [comment]
will close this for now
