### ISSUE TITLE
Replay controls get hidden in shared replay if keyboard is used to scroll to end

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#2232]
![image](https://user-images.githubusercontent.com/6473438/127231644-a0ad4c4e-11e0-4506-9712-ebeadfa21d1f.png)

1. Open a shared replay
2. Click the arrow to go to the end
3. Press the left arrow key
4. Press the right arrow key

**Comment by Zamiell** [comment]
probably a new bug relating to the recent PR about automatically closing the replay

**Comment by timotree3** [comment]
Ya. I'm on it
