### ISSUE TITLE
[Character] Explorer

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#2233]
"25% of the cards he sees are hidden."

Alternatively (easier to code), cards 'ranked' 4n+1 (1/5/9/13/17/21/...) in the deck are hidden.
Alternatively, cards of numbers 2&3 are hidden.

**Comment by timotree3** [comment]
Can you try to make sure he draws every fourth card and then he will be a normal player?

**Comment by Romain672** [comment]
On that second idea yes.
On that first, since it's random, that change nothing.

**Comment by Zamiell** [comment]
i dont like this idea because its not clear to other players which cards are hidden and which are not

**Comment by Romain672** [comment]
@Zamiell I added a third idea which resolve that problem ('Cards of numbers 2&3 are hidden' ).
But that 25% seems interresting to me.

**Comment by Zamiell** [comment]
just hiding 2's and 3's isn't that interesting
