### ISSUE TITLE
When starting a game with !replay, it carries over the original game options as well

### ISSUE THREAD

**Issue by Lel0uch-H** [Zamiell/hanabi-live#2244]
This behavior certainly does not seem intentional. The idea behind !replay seems to be playing the same deck that was played in the original game, not taking into account the additional game options used (timer, bottom deck blind plays, etc.).

First observed while starting this game from a !replay: https://hanab.live/replay/601480

**Comment by Zamiell** [comment]
replay is a debugging tool, so yes this is intended
