### ISSUE TITLE
Throw in hole: notes on stacks are hidden

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2245]
Specs see the actual cards, no the bases, so can't see what players are thinking.

Same during review - whenever 1 is played, the notes are hidden behind it.

**Comment by Zamiell** [comment]
what do you propose is the solution

**Comment by DarthGandalf** [comment]
Maybe somehow combine the notes of the visible card with the notes of the stack base?

**Comment by Zamiell** [comment]
that could work, sure

**Comment by Zamiell** [comment]
seems like a complicated feature for little gain, so i will close for now
