### ISSUE TITLE
DIfferent website behavior in different accounts

### ISSUE THREAD

**Issue by Lel0uch-H** [Zamiell/hanabi-live#2246]
Despite having exactly same settings in 2 accounts, I observe 2 different behaviors:

1. On hitting terminate, it shows a pop-up "Are you sure ..." while it doesn't in the other account.
2. Running games/reviews in the lobby have a %age completion in the UI that shows up in one of the accounts but not in the other.

**Comment by Zamiell** [comment]
1) will happen until you play N games
2) the % only shows for people you are your friends
