### ISSUE TITLE
Show restriction notes in empathy mode.

### ISSUE THREAD

**Issue by xelepart** [Zamiell/hanabi-live#2249]
I want the [3,4], [t] or [!5] types of notes to work on *other player's cards* when they I am in empathy mode.

Use Case: I (A) clue "you have one red" to C, and B plays a blind blue 1.

32 turns later, I am trying to figure out what C knows about their hand. I do empathy, and see that they know they have a red card and it could be a 2,3,4. I've forgotten that I bluffed them. I forget to look at my note 'cause I am a bad person. My note says [2,3] because when I bluffed, those were the only valid bluffs. And now I make a bad play 'cause I think they think 4 is valid.

I think empathy should use my notes, and only show 2,3, just like it does for my own cards.

**Comment by newduke** [comment]
👍

**Comment by DarthGandalf** [comment]
Empathy on your own cards ignores your notes. You can see that e.g. when holding the card

I also miss this feature, but I'd like it to be a separate mode; no idea how to switch between these 2 empathy modes though

**Comment by Zamiell** [comment]
sorry, but the website has a strong distinction between notes and real negative information.
the primary point of empathy is to always show the latter, for the exact purposes of distinguishing between the two.
by removing that distinction, players would have no way to easily check for this

> 32 turns later, I am trying to figure out what C knows about their hand.

you should have been keeping track of this using notes that evolve using pipes.
here is a common example of a note for a hypothetical red 3 that was bluffed:

`t34 bluff [r2, r3, m2, m3] | r2, r3 | r3`
