### ISSUE TITLE
Modify the second suit pip of double almost same suit variants

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2251]
E.g. "Light Pink and Pink", or "Muddy Rainbow and Cocoa Rainbow" have this problem: the cards look very similar, and can be confused. One workaround is colorblind mode, because it always shows the letter in corner.

My proposal which works for non-colorblind mode too is to change the pip in some way to make it distinguishable form the base pip. Maybe add some pattern around the pip.

**Comment by Zamiell** [comment]
good idea

**Comment by DarthGandalf** [comment]
Here's a prototype

![Selection_092](https://user-images.githubusercontent.com/325092/132100880-88285aa9-a072-4fde-b464-8fe5e8cbcf2b.png)
![Selection_091](https://user-images.githubusercontent.com/325092/132100883-cbbd4beb-0237-404a-adc5-8d99a8e7cb57.png)

**Comment by Zamiell** [comment]
don't really like that
i was thinking something more simple, like a circle around the pip and thats it

**Comment by DarthGandalf** [comment]
Like this?

![Selection_094](https://user-images.githubusercontent.com/325092/132101419-5bd3cca1-f3eb-480d-a7e6-45507a23c0a0.png)
![Selection_093](https://user-images.githubusercontent.com/325092/132101420-71e7a39b-4e82-450f-8706-75f186aa620d.png)

**Comment by Zamiell** [comment]
i was actually thinking just a circle line, no filling in of the background

**Comment by DarthGandalf** [comment]
![Selection_096](https://user-images.githubusercontent.com/325092/132103990-806484c0-f139-4210-9d57-59198d7aec06.png)
![Selection_097](https://user-images.githubusercontent.com/325092/132104047-61106da0-fb7d-4778-b8f2-52cecdb253fa.png)

**Comment by Zamiell** [comment]
lgtm

**Comment by Zamiell** [comment]
can you make the circle pip a bit smaller to account for the fact that the circle makes it better?

**Comment by DarthGandalf** [comment]
You mean, the pip inside the circle?

**Comment by Zamiell** [comment]
yes, so that the total size of the pips remains consistent
