### ISSUE TITLE
Improve the reclue arrow

### ISSUE THREAD

**Issue by DarthGandalf** [Zamiell/hanabi-live#2252]
The switch from white to gray is very subtle, so many people don't notice that something is different about the arrow

Embrace my terrible image editing skills for the alternative design:
![изображение](https://user-images.githubusercontent.com/325092/132096985-dbfeb50a-abb6-4112-a8e9-7660a748e39c.png)

(he double arrow can stay gray, of course)

If someone has some better idea how to make the difference for the reclue more obvious, please say

**Comment by Zamiell** [comment]
i agree that the gray arrow is subtle, and i am open to other possibilities

however, the double arrow in the proposed screenshot is off-putting and not an improvement imo

**Comment by rogers-j** [comment]
Perhaps some additional symbol like 🔄?
(Cluing new cards is the common case, and so for aesthetic reasons I do not think we want to add complexity there, such as 🆕)

**Comment by Zamiell** [comment]
well unless we have any other better ideas i will close this

**Comment by DrAnax** [comment]
Double vertical arrows? (left and right of the central circle clue)

**Comment by Zamiell** [comment]
maybe, show a mockup

**Comment by DrAnax** [comment]
![image](https://user-images.githubusercontent.com/2622043/145715285-dfbda099-f0df-485c-b669-21dca9b51672.png)

**Comment by Zamiell** [comment]
- imagine if you get clued about 2 new cards, and it also retouches 3 other cards
- the total amount of arrows would be 8
- this is quite noisy - there would be a lot of clutter on the screen

thus, i dont know if this is an improvement

**Comment by DrAnax** [comment]
It would be if the engine can detect the focus of the clue; if it's already clued only then the double arrows would appear. But maybe that's going too far

**Comment by Zamiell** [comment]
there is no possible way that a computer can determine the focus of a clue

**Comment by DrAnax** [comment]
Then close the issue, I agree that the screen will be cluttered
