### ISSUE TITLE
Mouse cursor changing to image makes server requests

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#2263]
/client/src/game/ui/cursor.ts:32-57 is responsible for mouse cursor changes.

When the cursor changes to an image (look.png, edit.png) this makes each time a new server request for the image.

**Comment by Zamiell** [comment]
it should be cached by the browser right?
meaning that it shouldn't actually result in any bandwidth being wasted, as long as you have requested that image on the same page load before

**Comment by DrAnax** [comment]
yes, but it isn't. maybe it can be cached like the cards images

**Comment by Zamiell** [comment]
it needs to be looked into then and changed so it is cached i guess

**Comment by DrAnax** [comment]
Closed by #2331

**Comment by Zamiell** [comment]
thanks
