### ISSUE TITLE
'Who's online' mobile button not working

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#2267]

**Comment by DrAnax** [comment]
On local dev it does though

**Comment by DrAnax** [comment]
Is critical.min.css built automatically? I think the problem lies there.

**Comment by Zamiell** [comment]
no its not built automatically

**Comment by DrAnax** [comment]
Can you rebuild it?

**Comment by Zamiell** [comment]
doing so now

**Comment by Zamiell** [comment]
ok, it should be live now, should i close this?

**Comment by DrAnax** [comment]
No, still no functional; I'll have to investigate further.

**Comment by DrAnax** [comment]
Ok, it works; it just needs a hard cache refresh, thanks.

**Comment by DrAnax** [comment]
Works on narrow desktop window, but it doesn't on chrome mobile.

**Comment by DrAnax** [comment]
Ok this is weird; I downloaded Opera and it works fine; it also works fine on chrome icognito mode. I emptied the cache, closed all tabs, even restarted the phone, but in chrome the who's online button was not functional.

I ended up removing all application data from settings and now it works fine.
