### ISSUE TITLE
UI bugs in game options inside the lobby

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2271]
Extra space under the button and horizontal scrolling bar (play with the speedrun checkbox):
![2021-10-30_23-57-00](https://user-images.githubusercontent.com/46625461/139558324-d1582393-ef60-4258-b00e-850c84d784b1.png)
![2021-10-30_23-57-31](https://user-images.githubusercontent.com/46625461/139558328-4d6e0e8c-625d-4206-90c1-55ca3a35ea57.png)

**Comment by DrAnax** [comment]
Can you please elaborate so I can fix this? Thanks.

**Comment by DrAnax** [comment]
![image](https://user-images.githubusercontent.com/2622043/139560982-44209837-9756-46d5-85a7-3ff3f3033a92.png)

Ah, you mean this? Browser? OS?

**Comment by DrAnax** [comment]
This looks like an outdate CSS stored in cache; see if a hard cache reset fixes the problem.

**Comment by Aigul9** [comment]
Windows 10, Google Chrome latest version. ok, will check tomorrow

**Comment by Aigul9** [comment]
seems ok
