### ISSUE TITLE
throw it in a hole

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#228]
throw it in a hole (cards are played face-down into a single pile that nobody gets to look at. at the end of the game, look at the pile to see if you won)

**Comment by fpvandoorn** [comment]
That seems really hard, but interesting... I would suggest that the game immediately ends when you get 3 strikes though - no point in continuing a lost game, even if no player knows you have lost already.

**Comment by Zamiell** [comment]
agreed

**Comment by Zamiell** [comment]
done
