### ISSUE TITLE
[Variant] X-Suits & Light-X-Suits

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#2298]
So what I think follow those suits is that 'X-Suits': this a new suit which got touched by his color, his number, and the number X.
'Light-X-Suits' get touched by his number, and the number X.
So these suits are some baby pinks.

Per example for '4-Suit':
 - x1 got touched by x, 1 and 4
 - x2 by x, 2 and 4
 - x3 by x, 3 and 4
 - x4 by x and 4
 - x5 by x, 4 and 5 

And 'Light-2-Suit':
 - x1 got touched by 1 and 2
 - x2 by 2
 - x3 by 2 and 3
 - x4 by 2 and 4
 - x5 by 2 and 5 

Now the question is, how we determine X?
First solution is to add (2x)5 new suits.
Second solution is to roll a dice (if it's 6 you reroll).
Third solution is to said that X is equal to the first (leftmost) card of the first player.
Forth solution is to said that X is equal to the last card of the deck.
Fifth solution to make X equal to the first clue given this game. But I don't like it. Players could abuse it by always clueing 5 first per example.

**Comment by Zamiell** [comment]
doesn't sound very fun
