### ISSUE TITLE
Embedded hanab.live fails to establish the websocket

### ISSUE THREAD

**Issue by ikelos** [Zamiell/hanabi-live#2303]
Hi there,

I was tying to embed the hanab.live game in gather.town, since it seemed like a good collaborative game to be able to play in such an environment.  Gather.town handles this using an iframe, but for some reason every time I login (successfully) to Hanab.live the websocket connection fails and it returns an error message (offering to reload or sign out).

I don't know if there's some kind of a header or some value sent as part of establishing the wss connection that's causing this to fail.  I also don't know whether it's intentional or not, but it would be quite nice to get working if everyone would be ok with allowing it to be embedded?

I'm happy to help debug wherever possible, unfortunately I can't see more in chrome than the following event (which doesn't clearly explain why the websocket failed):

```
Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
isTrusted: true
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: WebSocket {url: 'wss://hanab.live/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
defaultPrevented: false
eventPhase: 0
path: []
returnValue: true
srcElement: WebSocket {url: 'wss://hanab.live/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
target: WebSocket {url: 'wss://hanab.live/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
timeStamp: 12345.59999999404
type: "error"
[[Prototype]]: Event
```

I can play hanab.live normally from the same browser, so it seems to be specific to being embedded.  The embedding is just through an iframe:
```
<iframe src="https://hanab.live" frameborder="0" allow="clipboard-write *; autoplay *; fullscreen *; picture-in-picture *;" style="width: 100%; height: 100%; background: white;"></iframe>
```

**Comment by Zamiell** [comment]
well the iframe isn't passing cookies then because you need a valid cookie in order to login to the websocket server and you need to post to /login to get a valid cookie

**Comment by ikelos** [comment]
You're quite right, both establish the login request, and are returned a suitable set-cookie header, but:

* In chrome the cookie appears to be set but doesn't appear to be transmitted
* In firefox, the cookie is never recorded (but if manually added, it allows login)

The strange thing is I set every exception I could find to allow cookies for both browsers?  I suspect the protocol is coming into play here somewhere, but the fact that the browsers appear not to be registering or sending the cookies suggests it's some kind of third party tracking protection.  I don't know that there'd be a way around it though, so happy for you to close this ticket off if you'd like.  Thanks for investigating...

**Comment by Zamiell** [comment]
i didn't really investigate anything but sure i'll close

**Comment by DrAnax** [comment]
Most probably SameSite cookie policy is enabled, therefore cookies cannot work inside an IFrame. Nowadays the only possible workaround is to explicitly disable the policy by setting SameSite=none and Secure=true

rel

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

https://blog.heroku.com/chrome-changes-samesite-cookie

**Comment by Zamiell** [comment]
yes, it is enabled, see: <https://github.com/Zamiell/hanabi-live/blob/master/server/src/http.go#L163-L178>

**Comment by Zamiell** [comment]
and no, this is not something i would ever turn off lol, its recommended by OWASP

**Comment by ikelos** [comment]
Thanks @DrAnax , I confirmed that setting SameSite on the cookie to None does allow the site to continue in the iframe.
