### ISSUE TITLE
Card not marked as critical

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#2318]
Up & Down

Red S has been played, Red 1 discarded. Shouldn't Red 5 be marked as critical?

![image](https://user-images.githubusercontent.com/2622043/145735822-ded4f2db-769a-4a57-baac-0a01b6cdb734.png)

**Comment by Zamiell** [comment]
i think so but i can't remember exactly how advanced the up or down logic is

**Comment by DrAnax** [comment]
After playing Red 2 though, the Red 5 was correctly marked
