### ISSUE TITLE
How to deal with max number of players changing in pregame?

### ISSUE THREAD

**Issue by DrAnax** [Zamiell/hanabi-live#2323]
- Can table owner change the number of players in pregame?
- Can guests propose a set of options including max number of players

If yes in either case:
- What if the new number of players is less than the present number of players?

**Comment by Zamiell** [comment]
> Can table owner change the number of players in pregame?

i guess

> Can guests propose a set of options including max number of players

i guess

> What if the new number of players is less than the present number of players?

boot the final player(s)

**Comment by DrAnax** [comment]
> boot the final player(s)

> don't allow changing the number of players in this case OR
> default to the current number of players

I need a final decision by tomorrow

**Comment by Zamiell** [comment]
what i said makes more sense because the table leader has the authority to boot people from the table with /kick anyway

**Comment by mangopie1** [comment]
Make sense. Otherwise owner have to manually kick them before making the change. And if someone join again in the meantime, owner have to kick again. So auto kick sounds better UX

**Comment by Zamiell** [comment]
fixed now
