### ISSUE TITLE
pressing home when editing a note does not actually go home

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#2335]
instead, it deletes the pipe, and i have to press home *again* to actually go home

**Comment by DrAnax** [comment]
Yes, it's one of the intercepted keys:

```
  const keysRemovingPipe = [
    "ArrowLeft",
    "ArrowRight",
    "ArrowUp",
    "ArrowDown",
    "Home",
    "End",
    "Backspace",
    "Delete",
    "Escape",
  ];
```

Want me to add/remove something there?

**Comment by Zamiell** [comment]
to be more specific, I think pressing home should remove the pipe
thus, it should probably still belong in an array called "keysRemovingPipe"
however, I as an end-user should not have to press the key twice to actually make it work.
instead, i should press home, and it should go home and delete the pipe at the same time.
is that possible?

**Comment by DrAnax** [comment]
Maybe; if so I'll PR

**Comment by Zamiell** [comment]
thank you :)
