### ISSUE TITLE
Editing a note that ends with a pipe still adds a pipe

### ISSUE THREAD

**Issue by timotree3** [Zamiell/hanabi-live#2353]
1. Have a note saying `r3 |`
2. Right-click it

Expected: There is a phantom ` ` at the end so the note looks like `r3 | ` and if I move the cursor the space disappears.
Actual: There is a phantom ` | ` at the end so note looks like `r3 | | `

**Comment by Zamiell** [comment]
i dont think this is a bug  because having a pipe at the end of the note in this way implies that a state transition has occurred, and thus if you remove it you would be removing information

**Comment by DrAnax** [comment]
Currently JS adds a `sp|sp` if the note is not empty. When the note closes, it removes the `sp|sp` if it is the last part of the value.

What you suggest is to add only a single space if the note ends with `sp|`. What should happen when your note closes? Should only the last space removed or the entire `sp|sp` string?

**Comment by timotree3** [comment]
Just the last space.

**Comment by timotree3** [comment]
What? There would be no note changes. It would add a space and then remove a space. The note would be same at the end and the beginning

**Comment by Zamiell** [comment]
ok, even if that were the case, its still not desired since it is deleting that a state transition occurred

**Comment by timotree3** [comment]
Note before: `r3 |`
Note while note is open: `r3 | `
Note after pressing enter/escape: `r3 |`

Nothing's being deleted.

You mean that you want notes to look like `r3 | | new note`? I would never put a double pipe in my notes willingly.

**Comment by Zamiell** [comment]
a typical state transition is:
`r3 | not r3 | g3`
this can be abbreviated to:
`r3 | not | g3`
which can be further abbreviated to:
`r3 | | g3`
if i am at the 2nd part of this note, tim's proposed change would make the 3rd part of the note `r3 | g3`, which would destroy the 2nd intermediary state

**Comment by Zamiell** [comment]
help me understand why you would ever willingly keep a note as `r3 |` without wanting to designate that a state transition has occurred.
isn't that the precise purpose of the pipe in this context?

**Comment by timotree3** [comment]
My assumption when opening this issue was that we don't want double pipes in our notes. If that's actually something you like, then fine.

**Comment by Zamiell** [comment]
i personally hate double pipes, and subsequently do not ever use the double-abbreviated form denoted above.
however, at least 1 person has said that they use this workflow (i.e. Gandalf, Nitrate1)
