### ISSUE TITLE
Gray rows on history table are out of bounds

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#2368]
Steps to reproduce:
1. Open history page.
2. Wait until it completely loads.

seems like it depends on the longest variant in the list

why does it take so long to update the history table if the query selecting 30k rows runs about 300ms?

![image](https://user-images.githubusercontent.com/46625461/146690425-ad0bb988-e12d-406d-83c7-8e0a4eb8b82f.png)

**Comment by DrAnax** [comment]
> why does it take so long to update the history table if the query selecting 30k rows runs about 300ms?

Because jQ tablesorter hides the rows when filtered. This takes a lot of time. All these problems will disappear ajax is used to feed the data in history, stats and scores

**Comment by DrAnax** [comment]
> Gray rows on history table are out of bounds

This depends on the resolution. Bellow 1024px the filters should be hidden. What's your screen width?
