### ISSUE TITLE
Restart 6p game kicks a player out

### ISSUE THREAD

**Issue by jack67889** [Zamiell/hanabi-live#2373]
If you restart a 6 player game, the last person that joined pre-game is automatically kicked out and the game starts again with only 5 players.

**Comment by DrAnax** [comment]
I can't reproduce this on test environment. Has someone managed to reproduce this unwanted behavior consistently?

**Comment by jack67889** [comment]
I've also heard it from other teams. As far as I can tell it happens every time.
