### ISSUE TITLE
Site really doesn't want you to create 6p games

### ISSUE THREAD

**Issue by jack67889** [Zamiell/hanabi-live#2374]
In the game creator window: if you remove the number of "max players", the site auto-fills a value of 5. When you use the arrows in the box (or on a keyboard) to increase this number, the value jumps from 5 to 2. (If you keep increasing the value another round, after it jumped to 2, you are able to reach 6.)

**Comment by DrAnax** [comment]
This sounds like a browser related bug regarding how the <input type="number"> with min/max values works. On client side no JS code intervenes to your actions, unless you enter an invalid input (non numeric) or a number out of bounds (<2 or >6).

In any case, when you select your prefered number of players, this is store as a setting to your profile. So, maybe the site likes 5p players more (being the default option) but it doesn't enforce it.

**Comment by DrAnax** [comment]
@Zamiell close
