### ISSUE TITLE
disable sad on up and down

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#238]

**Comment by Zamiell** [comment]
its not disabled but it should work now

**Comment by fpvandoorn** [comment]
As mentioned in #296 this doesn't work yet.
The function `NeedsToBePlayed`
https://github.com/Zamiell/hanabi-live/blob/master/src/card.go#L33
returns `!variantUpOrDownIsDead`
https://github.com/Zamiell/hanabi-live/blob/master/src/variantUpOrDown.go#L80

However, "have to be played" is not the same as "not being dead". At the start of an up&down game, all of the cards {1,5,S} are not dead, but none of them have to be played. If you lose a single one of them, you can still win. (similarly, if the S is down, then losing one of {1,5} is fine, but you cannot lose both).
