### ISSUE TITLE
hypo improvements for starting player

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#2387]
after the last PR, the starting player's hand is hidden

however, if this hand has been previously clued, it should appear partially clued to every player in the shared replay, as it would appear to the player at the time of the hypothetical

right now, it does not do this, and is just completely hidden with a yellow border to indicate that it is clued

**Comment by DrAnax** [comment]
Back to the drawing board then

**Comment by mmelwen** [comment]
The cards shouldn't be hidden in the hypo !!!! we are already in the replay of the game, the cards supposed to be globally known

**Comment by Zamiell** [comment]
> The cards shouldn't be hidden in the hypo !!!! we are already in the replay of the game, the cards supposed to be globally known
wrong.
the point of a hypo is to find the best move for turn N.
and on turn N, Alice cannot see her own hand.
therefore, the best move for Alice is independent of the identity of any cards in her hand
