### ISSUE TITLE
Change end-of-game text

### ISSUE THREAD

**Issue by mmelwen** [Zamiell/hanabi-live#2393]
Is even worse than before now, before the vtk someone wrote vtk on chat and when 50% wrote it as well someone killed the game, now the game is suddenly killed and you have no idea that people where even voting. 

I think when the first one presses the button we should at least know that by changing the color of the skull

**Comment by Zamiell** [comment]
the idea of the feature is that you can vote to kill without revealing any information to the team (e.g. that someone made a mistake, which might not be globally known yet)

**Comment by mmelwen** [comment]
At least after the game is over is good to know who voted in favor.  Before we could debate with people who frequently terminate games with no loss of a critical card because the didn't like a clue or something similar. Now you play for 30 min and suddenly the game ends, you dont even know who to avoid playing with again

**Comment by Eliclax** [comment]
I agree that we shouldn't know anything about people voting to kill during the game, but I also agree that we should be able to see who voted to kill after it's killed.

**Comment by DrAnax** [comment]
@Zamiell what's the status of the PR?

**Comment by Zamiell** [comment]
i think the correct code change is to change the text from "The players voted to terminate the game!" to "Alice, Bob, and Cathy voted to terminate the game!"

**Comment by Zamiell** [comment]
i will rename this issue accordingly

**Comment by DrAnax** [comment]
Ok, will do
