### ISSUE TITLE
In Hypo mode: "Show Drawn" checkbox should be reworded

### ISSUE THREAD

**Issue by mdavidson29** [Zamiell/hanabi-live#2396]
Right now, the "Show Drawn" checkbox controls both the visibility of newly drawn cards in hypo mode as well as the current player's hand (global visibility or empathy view).  

My recommendation would be to split these into two checkboxes, since they cover separate things:
1) Show Drawn
2) Empathy view

If you want to still keep these functions controlled by the same checkbox, maybe change the label to "View all cards" or something?

**Comment by mmelwen** [comment]
Since in all the reviews I have been the players always want to see the cards,
 I believe the most common behaviour should be the default one, and the checkbox should be called 
"hide unknown cards"

**Comment by Zamiell** [comment]
if the players want to see the cards, then they misunderstand what the point of a hypothetical is

**Comment by mmelwen** [comment]
Perhaps you are right but does it matter? if most of the users want them visible isn't right to be the default behaviour of the site?

**Comment by Zamiell** [comment]
if most of the users think 2+2=5, should I change how addition works?

**Comment by T-Hoodie** [comment]
In my experience people playing through hypotheticals try to figure out if different actions yield better results:
1. for the specific seed being played ("would this action have been better here?")
2. on average for any possible seed ("would this action usually have been better?")
3. in a potential worst case scenario ("would this action always have been better?")
Players often times ask those questions in this order, and try to answer them in the same order. Drawing placeholder cards over cards from the specfic seed is detrimental for the first question. and for the rest we have to consider a mutlitude of potential draws anyway. Being shown one of those possibilitites (the current seed) isn't really harmful in my opinion, so I agree with melwen here: The default option should be show drawn cards.

**Comment by T-Hoodie** [comment]
> if most of the users think 2+2=5, should I change how addition works?

poor analogy

**Comment by Zamiell** [comment]
the first question is an anti-goal.
for example, a common trap for poker players is to analyze whether or not their decisions made them win or lose their particular hand/deal.
doing this actively prevents them from improving at the game.

if players are asking questions in this order, then their brains are flawed, and they are seeking irrelevant information

**Comment by T-Hoodie** [comment]
Every poker player in the world analyzes whether or not their decision made them win or lose their particular hand/deal. The common mistake is not knowing that the answer to the first question doesn't always coincide with the other questions.
In the games that I play the usual approach from the players is to find an answer to the first question, and afterwards analyze whether or not (or to what extend) the solution can be generalized.
This approach has its pros and cons, but it is common and valid. Thats why I think the default option should reflect that. However I also dont believe its a particular important topic and if the default setting is different, then so be it.

**Comment by Zamiell** [comment]
> This approach has its pros and cons, but it is common and valid

no, it is not valid.
the answer to the first question is not relevant in any way for the purposes of determining what the best line for alice was on turn N

**Comment by T-Hoodie** [comment]
The approach obviously has to include the question of generalization, as i mentioned twice before. And then it is a valid approach.
The answer to the first question is strongly correlated to the second and third, and answering it is a promising attempt in order to find a generally optimal action.

**Comment by Zamiell** [comment]
if my goal is to find out X, and i know that Y is correlated to X, i could go investigate Y.
but if there is nothing stopping me from investigating X directly, then investigating Y is just a distracting waste of time, *especially* when X and Y are not strongly correlated (because in this case they are not)

**Comment by Eliclax** [comment]
> if most of the users think 2+2=5, should I change how addition works?

If this is your analogy, then your conclusion that "players misunderstand the point of a hypothetical" assumes several axioms, such as "players would like to improve in the most efficient way."  I'm not sure you understand that not all players have the same priorities as you.  Believe it or not, a significant portion of our community enjoys Hanabi more with table talk.  Note that I am not disagreeing with your assumptions or your conclusion — I am disagreeing with your dictatorial and normative approach.

It is true that "Being in a minority, even a minority of one, does not make you mad."  However, it does make you unpopular.  Perhaps you think it's worth sacrificing popularity to protect the truth, and on some level, I find that very respectable.  But popular opinion can't be reasoned with, and you shouldn't be surprised if people in our community think of you as oppressive and even unreasonable.  There are other ways to stand up for what you think is right, and frankly, your current approach only stifles the community spirit.

**Comment by Zamiell** [comment]
yes, when players enter a hypothetical, i assume they want to get better at the game, and i assume that they want to get better at the game in the most efficient way.
these are pretty reasonable assumptions to make, and are completely fine assumptions for deciding on what the default options should be.
if players are mentally deficient and actually want to see the cards, then they always have the option to show whatever cards that they want simply by clicking a button, so everybody gets what they want.

**Comment by Zamiell** [comment]
fixed in #2403
