### ISSUE TITLE
Time out should not kill the game

### ISSUE THREAD

**Issue by Romain672** [Zamiell/hanabi-live#2397]
Hi,
When a timer reach zero, just make it stay at 0:00 without killing the game.

If that player was disconnected/got a lag/got a complicated situation, let the others players be angry in chat or kill the game if timer hit zero if they want to.
(If that's really a problem to see if someone was out of time, just turn the timer red until the end of game, but imo it's not needed)

Personnally, if I hear the alarm at 10s, I will ~80% of the time just play immediately. ~80% of letover just play when there is 2/3 seconds left. And for the rare remaining cases, instead of doing a random move which can cost the game, I will try to not take more than 10 extra seconds, except if I really need it.
Only the fact to know I'm out of time would make me play so much faster.

With that suggestion done, players can be more aggressive by putting a lower time limit, so that would not change much the duration of games.

**Comment by Zamiell** [comment]
the timer is intended to work like it is in chess

**Comment by Romain672** [comment]
But why so? It's hard to change it?

If yes ok.
If not, that just look so bad for disconnection per example. You can expect the player to came back 2min later, and that just ruin the fun for most players. So I don't get the gain of it.

**Comment by Romain672** [comment]
Chess is a 1v1, so you can assume disconnection give a weird position for the opponent where he can be 'fair' and wait, or just can punish, which isn't great.
Hanabi is coop, so that's completely different imo.

**Comment by Eliclax** [comment]
As far as I understand, this point has been brought up multiple times. Long story short, Zamiel will not listen to what you have to say. He has made up his mind and that's the end of that.

**Comment by Zamiell** [comment]
these kind of remarks come off as really passive aggressive, please stop.
i have carefully considered what other people have to say in this case, and have decided against it for reasons discussed in previous threads / the discord.

**Comment by hakha3** [comment]
I can understand that some people may want chess like timer, but there are also a lot of people who would prefer not killing game cuz their teammate timed out, so maybe make addional checkmark which would make that timer doesnt kill game. So table creator can decide which timer he prefers. (Both timers would need to distinguish somehow between each other, so people dont mistake them)
