### ISSUE TITLE
hypothetical maker

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#25]
client needs to know the deck order for this to work, will need new variable to store this. 

step 1:

- new feature
- exists only in replays
- you click a button to toggle it on, similar to how you click the button in a shared replay to toggle off turn warping
- after feature is toggled, clue UI appears, and "return" button appears above the "Help" button in the bottom-left hand corner
- now you can give clues and drag cards
- after you give a clue or do a move, it becomes "your turn" again, as you assume the position of the next person, and this goes on forever
- during this whole process, you still retain full visibility of all of the cards

step 2:

- extend hypotheticals to be seen in shared replays

**Comment by Zamiell** [comment]
@aliblong should this be server or client side and why?

**Comment by aliblong** [comment]
The server should (does) send the full game info in a replay, and the client can do everything from there. Not sure what else the server would do relating to this feature.

**Comment by aliblong** [comment]
Of course, for shared replays, the new hypothetical moves would have to be disseminated by the server in a smart way.

**Comment by aliblong** [comment]
Right, so the server will have to send the deck order in replays

**Comment by Zamiell** [comment]
ok, it doesn't do that already

**Comment by Zamiell** [comment]
server now sends the full deck to the client at the end of the game

**Comment by Zamiell** [comment]
oldest issue complete pog
