### ISSUE TITLE
Game status should be clearer from the lobby

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#27]
Games that end and turn into shared replays are not obviously discernable from in-progress games from the lobby. Both in-progress games and shared replays have the "Running" status. When a new shared replay is started, the title of the table becomes "usernames's shared replay".

The "Status" entry should have a third state "Shared Replay" in addition to the existing two, "Running" and "Not Started".

**Comment by Zamiell** [comment]
done

**Comment by aliblong** [comment]
[Doesn't quite look right](https://user-images.githubusercontent.com/7608707/35069198-7f3889f0-fba7-11e7-9947-7b3c9076fc07.png)

**Comment by Zamiell** [comment]
done

**Comment by aliblong** [comment]
[Was it looking different on your test server?](https://user-images.githubusercontent.com/7608707/35071018-575aebfc-fbad-11e7-9266-52b791f3d827.png)
