### ISSUE TITLE
Let emotes work on pre-game and in-game chat

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#281]

**Comment by Zamiell** [comment]
discord emotes?

**Comment by RaKXeR** [comment]
yeah

**Comment by Zamiell** [comment]
https://www.npmjs.com/package/emoji-name-map
also emoji

**Comment by Zamiell** [comment]
done

**Comment by Zamiell** [comment]
sort of, doesn't handle discord emotes but only twitch emotes but i think i want it this way for now because the client doesn't have a way of getting the server's current emote list dynamically
