### ISSUE TITLE
up and down game ends to early

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#296]
see e.g. game #18635

**Comment by Zamiell** [comment]
```
// variantUpOrDownCheckAllDead returns true if no more cards can be played on the stacks
func variantUpOrDownCheckAllDead(g *Game) bool {
	for suit, stackRank := range g.Stacks {
		// Search through the deck
		neededRanks := make([]int, 0)
		if g.StackDirections[suit] == stackDirectionUndecided {
			if stackRank == 0 {
				// Nothing is played on the stack
				neededRanks = []int{1, 5, startCardRank}
			} else if stackRank == -1 {
				// The "START" card is played on the stack
				neededRanks = []int{2, 4}
			}
		} else if g.StackDirections[suit] == stackDirectionUp {
			neededRanks = append(neededRanks, stackRank+1)
		} else if g.StackDirections[suit] == stackDirectionDown {
			neededRanks = append(neededRanks, stackRank-1)
		} else if g.StackDirections[suit] == stackDirectionFinished {
			continue
		}

		for _, c := range g.Deck {
			for neededRank := range neededRanks {
				if c.Suit == suit &&
					c.Rank == neededRank &&
					!c.Discarded {

					return false
				}
			}
		}
	}

	// If we got this far, nothing can be played
	return true
}
```

see any bugs?

**Comment by RaKXeR** [comment]
Maybe I misunderstood the code, but isn't the last `for` that is going through `g.deck` also suppose to go through players' hands?

**Comment by Zamiell** [comment]
cards are not removed from the deck when they are dealt to players

**Comment by fpvandoorn** [comment]
One thing which confuses me in that code: is `stackRank` supposed to be `c.Rank` where `c` is the top card of the stack? If so, why are we comparing `stackRank` against `-1` instead of `startCardRank`?

The bug might be somewhere else. Actually, there were two other bugs during that game:
* When the orange S was discarded (turn 8) we got the sound of losing a critical card. I cannot find any code deciding whether a card is critical in `variantUpOrDown.go`, so how is that decided? (the only thing related is `variantUpOrDownIsDead`, but notice that in this variant it is **not** the case that being critical is equivalent to (not being dead and being the last undiscarded copy of that rank)).
* When the purple 2 was played on purple S, the stack didn't display that it was a stack going up.

**Comment by Zamiell** [comment]
startCardRank is rank 6, but when a start card is played, it makes the stack go to -1 instead of 6 as a special case.

**Comment by Zamiell** [comment]
> When the orange S was discarded (turn 8) we got the sound of losing a critical card. I cannot find any code deciding whether a card is critical in variantUpOrDown.go, so how is that decided?

https://github.com/Zamiell/hanabi-live/blob/master/src/player.go#L279-L292

**Comment by Zamiell** [comment]
> When the purple 2 was played on purple S, the stack didn't display that it was a stack going up.

yeah thats probably the bug

**Comment by Zamiell** [comment]
ok this should fix it, reopen it if there are still bugs

https://github.com/Zamiell/hanabi-live/commit/bc2c4630e7964562a44c16236398151dc37e8ee4

**Comment by Zamiell** [comment]
look over that and let me know if it is sufficient

maybe there is a bug here? https://github.com/Zamiell/hanabi-live/blob/master/src/variantUpOrDown.go#L112-L115

**Comment by fpvandoorn** [comment]
I think this comment (and the similar comments for 5/S) is false:
https://github.com/Zamiell/hanabi-live/blob/master/src/variantUpOrDown.go#L102-L103
If **one** of {1,5,S} is discarded, then **both** other cards need to be played.

Probably the simplest logic (after dealing with 2s, 3s, 4s) is:
- if the pile is going down, 1 needs to be played
- if the pile is going up, 5 needs to be played
- if the pile is undecided, look through discard pile for 1, 5, S. If you find one, the other two have to be played. (this is true independent of whether S has been played or not)
- in any other case, the card does not have to be played

**Comment by Zamiell** [comment]
does that logic account for the fact that the card is already marked to be `c.Discarded = true` before getting to this function?

**Comment by fpvandoorn** [comment]
No. In that case, you need to check that there are 2 cards of {1,5,S} in the discard pile.

I just realized it is actually more complicated. We want to hear the sad sound whenever the last move caused the maximum possible attainable score to decrease, right? (assuming you have enough time to play all cards not in the discard pile). Now suppose both blue 2s and the blue S have been discarded. The blue stack can still get 3 points. Discarding the 1 does not cause a sad sound, discarding the 5 does.

New logic, assuming that `c` is a card in the discard pile which has rank 1, 5 or S, and `c` is not dead:
* if the pile is going down, play sad sound iff `c.Rank == 1`
* if the pile is going up, play sad sound iff `c.Rank == 5`
* If both 2s are discarded, but there is an undiscarded 4, play sad sound iff both `5` and `S` are discarded (it doesn't matter whether `c.Rank` is 1, 5 or S)
* If both 4s are discarded, but there is an undiscarded 2, play sad sound iff both `1` and `S` are discarded
* If there is an undiscarded 2 and 4, play sad sound iff at least 2 of `1`, `5` and `S` are discarded
* If all 2s and 4s are discarded, play sad sound if all of `1`, `5` and `S` are discarded.

**Comment by fpvandoorn** [comment]
I think there is also a bug in `variantUpOrDownIsDead`. The following comment is false:
https://github.com/Zamiell/hanabi-live/blob/master/src/variantUpOrDown.go#L190-L192
The 3 is also dead if all 2s and all 4s are discarded.

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/f472413332e578f3dacefd8833869af71089c7b2

**Comment by Zamiell** [comment]
well the diff is horrible, just reread this file:
https://github.com/Zamiell/hanabi-live/blob/master/src/variantUpOrDown.go

**Comment by fpvandoorn** [comment]
I guess I don't know exactly what you mean by a dead card. Do you mean something different from a useless card? For example, I would return `true` here
```
	if g.StackDirections[c.Suit] == stackDirectionFinished {
		return false
	}
```
But if `variantUpOrDownIsDead` is only called by `variantUpOrDownNeedsToBePlayed` then that particular thing doesn't matter.

Things which do matter in `variantUpOrDownIsDead`:
* This should be `true`:
https://github.com/Zamiell/hanabi-live/blob/b14dbbd51db84e0107d4f97c952129f58dcd11b0/src/variantUpOrDown.go#L163
* This comment is still wrong:
https://github.com/Zamiell/hanabi-live/blob/b14dbbd51db84e0107d4f97c952129f58dcd11b0/src/variantUpOrDown.go#L136-L138
if `S` has been played, `1` and `5` are dead both 2s, both 3s, **or** both 4s have been discarded.
* Is it a problem that `variantUpOrDownIsDead` is called after `c.Discarded` has been set to `true`? If the 1 and 5 are already discarded, then I discard the `S`, I think it is considered a dead card (since the 1, 5 and S have been discarded).

**Comment by Zamiell** [comment]
handling the sad sound is now completely handled in getMaxScore()

**Comment by Zamiell** [comment]
new flow:

```
	// This could have been a discard (or misplay) or a card needed to get the maximum score
	newMaxScore := g.GetMaxScore()
	if newMaxScore != g.MaxScore {
		// Decrease the maximum score possible for this game
		g.MaxScore = newMaxScore

		// Play a sad sound
		// (don't play the custom sound on a misplay,
		// since the misplay sound will already indicate that an error has occurred)
		if !c.Failed {
			g.Sound = "sad"
		}
	}

	// This could be a double discard situation if there is only one other copy of this card
	// and it needs to be played
	total, discarded := g.GetSpecificCardNum(c.Suit, c.Rank)
	doubleDiscard := total == discarded+2 && c.NeedsToBePlayed(g)
	// (we add two because this card has not been marked as discarded yet)

	// Mark that the card is discarded
	c.Discarded = true

	// Return whether or not this is a "double discard" situation
	return doubleDiscard
```

**Comment by Zamiell** [comment]
note that:
1) c.Discarded is only set to true after we return from c.NeedsToBePlayed()
2) c.NeedsToBePlayed() is only ever entered for cards that have 2 or more copies in the deck

**Comment by Zamiell** [comment]
```
// variantUpOrDownNeedsToBePlayed returns true if this card still needs to be played
// in order to get the maximum score (taking into account the stack direction)
// (before getting here, we already checked to see if the card has already been played)
func variantUpOrDownNeedsToBePlayed(g *Game, c *Card) bool {
	// First, check to see if the stack is already finished
	if g.StackDirections[c.Suit] == stackDirectionFinished {
		return false
	}

	// Second, check to see if this card is dead
	// (meaning that all of a previous card in the suit have been discarded already)
	if variantUpOrDownIsDead(g, c) {
		return false
	}

	// All 2's, 3's, and 4's must be played
	if c.Rank == 2 || c.Rank == 3 || c.Rank == 4 {
		return true
	}

	// This card is either a 1, a 5, or a "START" card
	// The final card in an already-decided stack must be played
	if (g.StackDirections[c.Suit] == stackDirectionUp && c.Rank == 5) ||
		(g.StackDirections[c.Suit] == stackDirectionDown && c.Rank == 1) {

		return true
	}

	// For undecided stacks, between the 1, the 5, and the "START" card,
	// two of them have to be played
	if g.StackDirections[c.Suit] == stackDirectionUndecided {
		ranksToCheck := []int{1, 5, startCardRank}
		for i := range ranksToCheck {
			total, discarded := g.GetSpecificCardNum(c.Suit, i)
			if total == discarded {
				// At least one starting card has already been discarded, so we need the other two
				return true
			}
		}
	}

	// Default case; if the card does not meet the above conditions, it does not need to be played
	return false
}
```

**Comment by Zamiell** [comment]
```
// variantUpOrDownIsDead returns true if it is no longer possible to play this card by
// looking to see if all of the previous cards in the stack have been discarded
// (taking into account the stack direction)
func variantUpOrDownIsDead(g *Game, c *Card) bool {
	// Make a map that shows if all of some particular rank in this suit has been discarded
	ranks := []int{1, 2, 3, 4, 5, startCardRank}
	allDiscarded := make(map[int]bool)
	for _, rank := range ranks {
		total, discarded := g.GetSpecificCardNum(c.Suit, rank)
		allDiscarded[rank] = total == discarded
	}

	// Start by handling the easy cases of up and down
	if g.StackDirections[c.Suit] == stackDirectionUp {
		for i := 2; i < c.Rank; i++ {
			if allDiscarded[i] {
				return true
			}
		}
		return false
	} else if g.StackDirections[c.Suit] == stackDirectionDown {
		for i := 4; i > c.Rank; i-- {
			if allDiscarded[i] {
				return true
			}
		}
		return false
	}

	// If we got this far, the stack direction is undecided
	// (the previous function handles the case where the stack is finished)
	// Check to see if the entire suit is dead in the case where
	// all 3 of the start cards are discarded
	if allDiscarded[1] && allDiscarded[5] && allDiscarded[startCardRank] {
		return true
	}

	// If the "START" card is played on the stack,
	// then this card will be dead if all of the 2's and all of the 4's have been discarded
	// (this situation also applies to 3's when no cards have been played on the stack)
	if g.Stacks[c.Suit] == startCardRank || c.Rank == 3 {
		if allDiscarded[2] && allDiscarded[4] {
			return true
		}
	}

	return false
}
```

**Comment by Zamiell** [comment]
> No. In that case, you need to check that there are 2 cards of {1,5,S} in the discard pile.
> 
> I just realized it is actually more complicated. We want to hear the sad sound whenever the last move caused the maximum possible attainable score to decrease, right? (assuming you have enough time to play all cards not in the discard pile). Now suppose both blue 2s and the blue S have been discarded. The blue stack can still get 3 points. Discarding the 1 should not cause a sad sound, discarding the 5 should.
> 
> New logic, assuming that `c` is a card in the discard pile which has rank 1, 5 or S, and `c` is not dead:
> 
> * if the pile is going down, play sad sound iff `c.Rank == 1`
> * if the pile is going up, play sad sound iff `c.Rank == 5`
> * If the pile is undecided:
>   
>   * If both 2s are discarded, but there is an undiscarded 4, play sad sound iff both `5` and `S` are discarded (this is true whether `c.Rank` is 1, 5 or S and also true when S is already played)
>   * If both 4s are discarded, but there is an undiscarded 2, play sad sound iff both `1` and `S` are discarded
>   * If there is an undiscarded 2 and 4, play sad sound iff at least 2 of `1`, `5` and `S` are discarded
>   * If all 2s and 4s are discarded, play sad sound iff all of `1`, `5` and `S` are discarded.

so does any of this apply anymore with the sad sounds not being handled by this function?

**Comment by fpvandoorn** [comment]
Game #18738 still ended early

**Comment by Zamiell** [comment]
can you review the code that i wrote yesterday?

**Comment by fpvandoorn** [comment]
yes, I'll do that later

**Comment by Zamiell** [comment]
i moved c.Discarded back to the way it was because it was messing up non-upordown games

**Comment by Zamiell** [comment]
i dont think it affects anything now

**Comment by Zamiell** [comment]
with the new !replay feature i replayed game 18738 turn 33, looks like the bug still happens

**Comment by fpvandoorn** [comment]
I think games ending to early is caused by
https://github.com/Zamiell/hanabi-live/blob/0db325596e5e2aea77f0b420db745971d11b8089/src/variantUpOrDown.go#L240
That should be
```
for _, neededRank := range neededRanks {
```
right?

**Comment by fpvandoorn** [comment]
Also, this should probably be for a different variant:
https://github.com/Zamiell/hanabi-live/blob/0db325596e5e2aea77f0b420db745971d11b8089/src/player.go#L230-L231

**Comment by Zamiell** [comment]
oh ya u right on both counts

**Comment by Zamiell** [comment]
i guess ill close this now

**Comment by fpvandoorn** [comment]
Sounds good! The new solution to determine whether to play the sad sound is easier, indeed.
