### ISSUE TITLE
Feature: queue for games

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#3]
Nothing sophisticated, just click a button to get in queue. There will be a sentinel watching for table creation which pings users in queue on discord and/or client, as well as some way to make it obvious to the players making the table that the queued players want to play.

**Comment by Zamiell** [comment]
how about this:

user clicks "Queue for Next Game" button in the lobby, and then they get a browser notification when the next table opens ?

**Comment by aliblong** [comment]
Sounds good, but I think there should also be some kind of indicator to the players making/joining the table that someone is in queue. Maybe change the label on the "Create Game" button to "Create Game (n in queue)"? Also, I dunno if there's a better word than queue; players might expect from "queue" that they'll be autojoined to a table when it appears.

**Comment by Zamiell** [comment]
```
Minimum viable product: clientside subscribtion to the game, gets a desktop notification when the next table is created. Joining a table, closing the page, and entering a replay are all enough to cancel the notification.

Room to improve: Client passively cancels the desktop notification if the game starts without the subscriber
```

**Comment by aliblong** [comment]
We should call it a "waiting room" or just a "waiting" state rather than a "queue" in the current conception, since those waiting are not ordered.

**Comment by Zamiell** [comment]
> Joining a table, closing the page, and entering a replay are all enough to cancel the notification.

this sounds bad, lets just make it so that joining a table cancels the notification

**Comment by rogers-j** [comment]
On the contrary, they're all trivial if the work is client-side

**Comment by Zamiell** [comment]
the feature will be client side but i dont want to have 2 different features, see #5

**Comment by Zamiell** [comment]
implemented for now as /next
