### ISSUE TITLE
iPad problems

### ISSUE THREAD

**Issue by BraisGabin** [Zamiell/hanabi-live#316]
I invite a friend to try hanabi.live. We couldn't finish because the server drop him constantly. He always plays using his iPad and he was using Safari. Is there any known issue with iPad or Safari?

**Comment by Zamiell** [comment]
yes, there is. tell him to use chrome

**Comment by Zamiell** [comment]
actually, once i finish my grunt task for transpiling the javascript, it should work on older browsers

**Comment by Zamiell** [comment]
have him try now, i've transpiled all of the code with Babel
