### ISSUE TITLE
arrows get duped when cluing

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#318]
reproduce steps:
in 3 player game:
1) clue number 1 to left player
2) twitch to player 2, with player 2 have one or more 1s in their hand

**Comment by Zamiell** [comment]
cannot reproduce

**Comment by fpvandoorn** [comment]
I don't know exactly what causes it to happen, but I've definitely seen it plenty of times. I will try to see if I can reproduce it consistently.

**Comment by Zamiell** [comment]
i think i might have fixed this bug today, reopen this if you see it again
