### ISSUE TITLE
disable clicking on card while it is tweening

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#322]

**Comment by fpvandoorn** [comment]
Yes, that would be really nice! In BGA mode the "replay" area is in between the draw pile and the discard pile. It is therefore possible that in the middle of the replay, you accidentally click on a card in motion (which you drew) and drag it over a play pile, and this will be interpreted as your move. This actually happened to me, but I forgot to open an issue about it.

**Comment by Zamiell** [comment]
oh that is unrelated and would only happen if you have speedrun option turned on

**Comment by fpvandoorn** [comment]
Do you mean the option to preplay cards? I have that turned on, yes. But I was looking through the replay while it was my turn, so I'm not sure whether it counts as a preplay.

**Comment by Zamiell** [comment]
ok ive fixed click events on cards that are tweening

i've also fixed being able to drag cards that are tweening, which was different and much more complicated

**Comment by fpvandoorn** [comment]
Great, thanks!
