### ISSUE TITLE
cards sparkle if critical

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#333]

**Comment by hanabirnoob** [comment]
Would be nice if this was an option.

**Comment by Zamiell** [comment]
better to do this during the client rewrite

**Comment by robertos** [comment]
@Zamiell I took a stab at this here: https://github.com/robertos/hanabi-live/tree/critical-indicator

Here's what it looks like:
![image](https://user-images.githubusercontent.com/621574/83296337-7d2d0680-a1a5-11ea-8ae7-ee2cf696fdb2.png)

The placement and icon can be changed of course, I also added the SVG of the icon I made.

**Comment by Zamiell** [comment]
nice.

it overlaps with note symbol though?

**Comment by robertos** [comment]
Here are some mockups of other options (not implemented)

![image](https://user-images.githubusercontent.com/621574/83296745-1eb45800-a1a6-11ea-880e-be401ab05c1b.png)
(or reverse, critical right note left)

![image](https://user-images.githubusercontent.com/621574/83296799-3b509000-a1a6-11ea-9b85-b1fac85d6ffd.png)

![image](https://user-images.githubusercontent.com/621574/83296856-54594100-a1a6-11ea-97db-f15e5a068491.png)

(or reverse, critical on top, note on bottom)

**Comment by Zamiell** [comment]
maybe we put critical indicator in top right, and move note indicator to bottom left

**Comment by robertos** [comment]
One more. Not a fan, but for completeness
![image](https://user-images.githubusercontent.com/621574/83296968-8f5b7480-a1a6-11ea-979d-2f92f223c2b7.png)

![image](https://user-images.githubusercontent.com/621574/83297018-a306db00-a1a6-11ea-84f8-ecb6fb9c0c7f.png)

**Comment by robertos** [comment]
Mockup of your idea
![image](https://user-images.githubusercontent.com/621574/83297130-dc3f4b00-a1a6-11ea-8df1-40f3dbcb3ab1.png)

**Comment by Zamiell** [comment]
shrug, seems fine

**Comment by Zamiell** [comment]
btw this shouldn't show if the card is clued

**Comment by robertos** [comment]
> shrug, seems fine
Your choice of which

> btw this shouldn't show if the card is clued
Can be done, but why? The fact the card is clued doesn't make it less critical. I'm also showing it on replays and spectators for now, it can be disabled in those cases

**Comment by Zamiell** [comment]
well, it could always show, or it could only show if the card still needs to be saved, depending on what we think is better.

the reason i propose the latter is because i think that the icon could be distracting for players. it adds more noise to the overall game state.

**Comment by robertos** [comment]
Another option is to change the stroke of numbers/pips in critical cards. We can try a few options and see what people like

**Comment by Zamiell** [comment]
changing the stroke of the number could be good.
changing the number of pips seems more abstract, i like the other options better so far.

**Comment by robertos** [comment]
> changing the number of pips seems more abstract,
I was thinking stroke of pips. Basically the stroke of everything in the card

**Comment by Zamiell** [comment]
yeah maybe that would be good

**Comment by robertos** [comment]
Even with a pretty thick stroke it's still too subtle IMO

![image](https://user-images.githubusercontent.com/621574/83301510-a3a36f80-a1ae-11ea-8fd4-46a4a9e34af1.png)

**Comment by robertos** [comment]
The red border would probably be best, and I'd be OK to let it be overwritten by CM/F/clued borders

**Comment by Zamiell** [comment]
border on numbers looks pretty ugly

**Comment by robertos** [comment]
Agree 100%, which is why i wanted to try a red border on the card (that gets overwritten by F/CM/clued border). Color should be tweaked instead of this #ff0000 RED

![image](https://user-images.githubusercontent.com/621574/83303689-5c1ee280-a1b2-11ea-9350-91dbd5922597.png)

**Comment by robertos** [comment]
Optionally the card can show a tooltip (when it doesn't have a note) to explain it is critical

**Comment by Zamiell** [comment]
right now i prefer the ! icon to a red border, because a special border implies the number is clued.

(in the hyphen-ated conventions, a chop move is an "invisible clue", and a finessed card is also treated like it has a invisible clue on it as well.)

**Comment by robertos** [comment]
Got it. The red border would get overwritten by any of those, but the icon is less obtrusive to that for sure. I'm still don't have a strong preference of placement.

Here's an idea with a lighter icon (no circle), even more subtle

![image](https://user-images.githubusercontent.com/621574/83304355-92a92d00-a1b3-11ea-8c43-050c8a9a2f4d.png)

![image](https://user-images.githubusercontent.com/621574/83304407-a94f8400-a1b3-11ea-9bab-c93033cb242d.png)

**Comment by Zamiell** [comment]
well i want the icon to be clearly visible, and that might be too small to see clearly.

show a full screenshot of a 6 player game with some critical cards?

**Comment by Zamiell** [comment]
(6 player games have quite small hands)

**Comment by robertos** [comment]
Here's a mockup of a 6p game with a few different options

![image947](https://user-images.githubusercontent.com/621574/83305474-aa81b080-a1b5-11ea-8936-434c9e6fd0ce.png)

**Comment by Zamiell** [comment]
yeah the bang is too hard to see, lets just go right the circle ! thing in the top right?

**Comment by robertos** [comment]
Sounds good. What's your preference for note vs crit placement?
1. Crit should be replaced by notes
2. Crit should move out of the way for notes (left or below)
3. Notes move out of the way if card becomes Crit (left or below)
4. Notes go to bottom left

**Comment by robertos** [comment]
I think notes might need to stay on top because of the discards. If the note is on the bottom it might be covered by other cards

**Comment by Zamiell** [comment]
i thought just always put crit on top right and always put notes on bottom left.

you dont need to see notes on discarded cards so if the icon is covered, that isn't an issue

**Comment by robertos** [comment]
PR coming soon :)

**Comment by robertos** [comment]
This is what it looks like implemented:

![image](https://user-images.githubusercontent.com/621574/83309170-6b575d80-a1bd-11ea-8d31-33fb274b2251.png)

And on dual-color variants

![image](https://user-images.githubusercontent.com/621574/83308787-6e058300-a1bc-11ea-81c7-3105b272ecd4.png)

**Comment by Zamiell** [comment]
yeah seems fine, nice work
