### ISSUE TITLE
enable clicking on tweening cards in hand

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#390]
For speedruns, I often end up clicking on cards while they are moving in someone's hand (because they just played/discarded an older card from their hand).

Is it possible to:
* Enable clicking on moving cards, if both the start and endpoint of their movement was in their hand
* Disable clicking on all other moving cards.

**Comment by Zamiell** [comment]
> I often end up clicking on cards while they are moving in someone's hand

what happens when you do that

**Comment by fpvandoorn** [comment]
It just doesn't register the click

**Comment by Zamiell** [comment]
fixed
