### ISSUE TITLE
disable cannot clue error message

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#391]
I sometimes double click on a card in someone else's hand. This will preclue that card, and then next turn I (often) get the error message that the card is not in that player's hand anymore.

Preferred outcome: ignore the preclue without error message (at least in speedruns)

**Comment by Zamiell** [comment]
um what does double clicking have to do with this?

**Comment by Zamiell** [comment]
not able to reproduce

**Comment by fpvandoorn** [comment]
In a speedrun, if you double click a card in someone else's hand, this will be registered as "cluing that card" + "precluing that card next turn" (which is fine with me). However, the other player will often play that card in the meantime.

To reproduce:
* Start a speedrun
* On Bob's turn, Alice preclues Bob, by clicking Bob's slot 1
* Bob plays slot 1
* Alice (on her turn) gets an error message that she cannot clue the card, because it is not in Bob's hand

**Comment by Zamiell** [comment]
fixed
