### ISSUE TITLE
pop-up stays after button disappears

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#393]
Many in-game buttons show a pop-up if you hover over them. Sometimes this pop-up stays visible after the button disappears.

![popup](https://user-images.githubusercontent.com/7376012/54324605-c27f0b80-45d4-11e9-84c1-f1757d80ad00.png)

Steps to reproduce:
* spectate a game
* click the "Lobby button" without hovering your mouse over the button before clicking.
* The pop-up will then stay visible in the lobby (see screenshot)

**Comment by Zamiell** [comment]
fixed
