### ISSUE TITLE
text over text when prediscarding

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#398]
If Alice prediscards on Bob's turn, then on Cathy's turn Alice sees text on text

![text_over_text](https://user-images.githubusercontent.com/7376012/54460877-3b9b7180-4741-11e9-96ff-2605af8e4a1b.png)

**Comment by Zamiell** [comment]
i fixed this already, are you on the latest code

**Comment by fpvandoorn** [comment]
maybe not

**Comment by Zamiell** [comment]
test and reopen if so
