### ISSUE TITLE
Color indicator arrows depending on clue type

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#41]

**Comment by rogers-j** [comment]
I think a difference between rank and suit clues might be useful, even if colors don't work out.

**Comment by rogers-j** [comment]
This would probably be easier if the arrows were not text.

**Comment by Zamiell** [comment]
nope, it was easier since they were text

**Comment by rogers-j** [comment]
No I mean easier to make rank and suit clues different.

**Comment by Zamiell** [comment]
i thought about it and it doesn't seem necessary to put a "5" or whatever on top of the arrow

**Comment by rogers-j** [comment]
I'm not immediately thrilled with that implementation either, but new players mistaking one type of clue for the other is a real thing that happens.
