### ISSUE TITLE
pips should disappear if all copies are seen

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#427]

**Comment by NoMercyO** [comment]
This sounds kinda cheaty to me. There is a different between clear history information being present, and the game inferring things for you

**Comment by Zamiell** [comment]
lets give it a chance to see how it plays

**Comment by Dumbo14** [comment]
I have to agree with NoMercy on this one. It should be up to the players to infer things about their cards. The UI, in my opinion, should only show info resulting directly from clues.
