### ISSUE TITLE
Helper advising wrong info

### ISSUE THREAD

**Issue by NoMercyO** [Zamiell/hanabi-live#437]
![cap1](https://user-images.githubusercontent.com/48550025/55035943-6e155c00-4fd6-11e9-97f8-6aea51f566da.JPG)
![cap2](https://user-images.githubusercontent.com/48550025/55035947-6eadf280-4fd6-11e9-8212-1b0666b326eb.JPG)

It is playable

**Comment by Zamiell** [comment]
your mom is playable
every night

**Comment by Zamiell** [comment]
fixed

**Comment by Zamiell** [comment]
looks like this bug is still here but i have a separate issue for it now
