### ISSUE TITLE
Separate spectators from players in the list of participants visible from the lobby

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#44]
For ongoing games, the table entry in the lobby includes both players and spectators under the "Players" field. Spectators should be in a separate field. For shared replays, we could have one of the following: i) participants in the "Spectators" field, with the "Players" field remaining immutable as a list of those who *did* play the game; ii) everyone in the "Spectators" field; iii) the shared replay leader alone in the "Players" field, although this would make the field names confusing. I like i).

**Comment by rogers-j** [comment]
In favor of i

**Comment by Zamiell** [comment]
how about i just bold the players. more simple, less work

**Comment by rogers-j** [comment]
The formatting is secondary. If the player doesn't stick around for the replay, the name is not present.

Not that it isn't a good idea. I could imagine bolding the names for players in the review.

**Comment by Zamiell** [comment]
@aliblong 

> For ongoing games, the table entry in the lobby includes both players and spectators under the "Players" field.

i just tested and this doesn't seem to be the case

**Comment by aliblong** [comment]
Did it change some time in the intervening 5 months? It's good enough now for in-progress games, but I'd still like for shared review lobby entries to have the players of the game distinguished in some way.

**Comment by Zamiell** [comment]
it did not change, no

**Comment by Zamiell** [comment]
i think this works now
