### ISSUE TITLE
Clickable ID links 

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#443]
I noticed that when I go view My Profile > Full Game History, I see that it displays all the games I've done on the site.  

Would it be possible to set it so that the ID of the games are clickable, so that when you click the ID's it'll open another window of the replay?  Right now I have to copy and paste the ID to "watch specific replay" to see the replay.  

Not really important issue, just to make the site more user friendly.

**Comment by Zamiell** [comment]
done
