### ISSUE TITLE
Make extra UI info a lobby option

### ISSUE THREAD

**Issue by Dumbo14** [Zamiell/hanabi-live#444]
I feel the "potentially double discard"  and "hand locked" warnings should be optional because:
1) These aren't part of the base game but rather follow from the conventions set forth by the Hyphen-ated Group. Not everyone plays with these conventions.
2) It should be left up to the players to recognize these scenarios.

Similarly, the UI shouldn't show ruled out possibilities for cards because they are visible in other players hands (as mentioned in https://github.com/Zamiell/hanabi-live/issues/427)

I suggest making these features optional when creating a lobby.

**Comment by Zamiell** [comment]
what is your hanabi.live username?

**Comment by Dumbo14** [comment]
Ryno

**Comment by Zamiell** [comment]
```
These aren't part of the base game but rather follow from the conventions set forth by the Hyphen-ated Group.
```
I don't think this is quite right - a double discard situation is independent of conventions. Regardless of what conventions you play with, if two people discard in a row, and they discard the same card, a perfect score will be lost. Although I am aware that with some conventions, you are supposed to discard in a double discard situation. If a group does, then such a group can simply ignore the warning.

The "hand locked" is similarly convention-independent. It simply signifies that every card in a hand is clued. Regardless of what conventions you were playing with, if every card in the hand is clued, then it would display the same message.

In the future we can make a checkbox to make these things optional.

**Comment by fpvandoorn** [comment]
@Zamiell: by the same logic, the "chop movement" feature (I forgot the exact name, but the feature whether a hand was deterministically reordered after a discard) is convention-independent: if your group doesn't play with it, they can just ignore that the UI moved the card from slot 4 to slot 1 (obviously this is a much more extreme example).

**Comment by fpvandoorn** [comment]
I am in favor of making these things optional, and we should probably disable them during speedruns.

**Comment by Zamiell** [comment]
i fail to how those two examples are comparable. one is an extra ui element that can be safely ignored. one is... your hand.

**Comment by fpvandoorn** [comment]
Sure, the effects and how much effort it takes to ignore them are different. I'm just disagreeing with the statement

> a double discard situation is independent of conventions

On BGA players have to take preventative measures to avoid double discarding, so as a player you don't have to worry about double discarding after the previous player discarded. So the information is irrelevant.

Maybe a better example: suppose that a group plays with a rule that if your team is at 7 clues, given clues have a special meaning, so they request a feature that prominently displays when the team is at 7 clues (maybe an orange border around the discard pile). Would you consider that feature independent of conventions?

(Note: I'm not saying we shouldn't have these UI features. They are nice to have.)

**Comment by Zamiell** [comment]
yes, i would consider that feature independent of conventions, because 7 clues means 7 clues regardless of which conventions you play with!!

**Comment by fpvandoorn** [comment]
Ok, that's fair. Then we just use different definitions of "dependent on convention". 
I would say that if a UI feature is used in one convention, but irrelevant in another, then - even though the UI displays the same information in both cases - it depends on the convention. Maybe more precisely I should say "whether it is useful depends on the convention".

**Comment by Dumbo14** [comment]
> 7 clues means 7 clues regardless of which conventions you play with!

While this is true, by showing a special border on the discard pile the UI is implying to all players that there is something inherently unique to this state of the game and all players should be interpreting actions differently somehow, which isn't the case. This state is only special under certain conventions.


Coming back to the original issue;
> Regardless of what conventions you play with...

Just because you argue that any reasonable set of conventions would have special rules accounting for certain situations such as consecutive discards/locked hands/etc. (this is a bold claim that I don't think I agree with, but is besides the point), does not mean that the UI should acknowledge these situations. Although this could be useful for newer players as an additional feature.

**Comment by Zamiell** [comment]
>Just because you argue that any reasonable set of conventions would have special rules accounting for certain situations
To be clear, that is **not** what i was arguing.

I'll reopen the issue

**Comment by fpvandoorn** [comment]
The "you know you cannot play this card"-popup falls under the same category, and should be disabled with the same option (IMO)

**Comment by Zamiell** [comment]
this is implemented now
