### ISSUE TITLE
The latest feature that shows deduced card identity based on visible cards broke empathy in rewind mode

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#447]
present view:
![present view](https://user-images.githubusercontent.com/7608707/55130876-e07b5e80-50f2-11e9-9a84-774e39e0a45d.png)

past view (without clicking for empathy):
![past view, no click](https://user-images.githubusercontent.com/7608707/55130927-0ef93980-50f3-11e9-8488-5839067046c4.png)

before this feature, there were rank pips in past view; 2-5 would be faded

you can imagine how it looks after a color clue has been given, but I'll show it anyway:
![past view; a color clue has been given](https://user-images.githubusercontent.com/7608707/55131163-de65cf80-50f3-11e9-8be2-5b9e7a24ba6e.png)

**Comment by Zamiell** [comment]
should be fixed now
