### ISSUE TITLE
speedrunning world records

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#458]
The fact that hanabi.live keeps track of speedrunning WRs is really nice.

Two remarks
* Congradulations -> Congratulations
* It seems to get the time wrong sometimes. The 2p normal WR was 57 seconds, but here it counts it as ~1:01: https://www.youtube.com/watch?v=EEQ8sNYgNIA

**Comment by Zamiell** [comment]
wasnt that the game that got deleted from the database?

**Comment by fpvandoorn** [comment]
oh, you're right.
