### ISSUE TITLE
Pause Feature

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#460]
1.  Manual Pause 
Nice feature to have for various reasons. 

2.  Pause when a player becomes disconnected during gameplay.  
I've been having trouble with my internet connection and noticed how the games end when I  reconnect.  What I've noticed is that the timer is still counting down when it reaches my turn, even though I'm not connected to the game.  Would it be possible to implement a feature where the game will pause when it reaches the player's turn if they're not connected?  I know the game understands when a player is not connected when their username turns red.

**Comment by Zamiell** [comment]
done
