### ISSUE TITLE
Adding Move Count

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#461]
Proposal:  
1. In full game history, add a heading of "# of moves" or "# of turns" to each game
2. In Scores and Statistics, add a heading of "Average # of moves/turns"  
3. In Scores and Statistics, show how many times a max score has been achieved. 

In studying the conventions and learning the game, I highly suspect that skilled players on average have games with the least amount of turns.  Theoretically, the best games are the ones with no mistakes and have maximized the efficiency of clues on every turn.  So it's a shame that these games are hidden within the full game history profile with no way to directly see them.  Unless if you open the game in a replay and see for yourself.  It would be nice to show the game with the fewest amount of turns on your profile somewhere for each variant, or at least show the # of moves made in each game.  

For point number 3, the score table just indicates that a max score has been achieved.  However, I think it would be beneficial to show how many times a max score has been achieved.  I've seen some players with hundreds or even thousands of games in a category, but as it stands it only shows that they've "achieved" the max score.  You can see the issue when a new player who's played only a few games, but made the same achievements has a profile that's no different than a veteran player, since both profiles have achieved the same max scores.

**Comment by Zamiell** [comment]
doesn't really seem that important compared to how much work it would be to implement
