### ISSUE TITLE
Clarity in Six Color Variant

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#465]
I've noticed that the yellow and orange colors are quite hard to distinguish immediately at times in variants where both the yellow and orange are played together.  I like the dark yellow color for the yellow suits.  Is there a way to have the orange color be more vibrant/brighter orange than the dark orange it's currently at?  If not could the orange color be changed to a brownish or wooden style of color?

**Comment by Zamiell** [comment]
change the colors yourself, playtest it, and then send a pull request

**Comment by Ape** [comment]
I have suggestion for this. Replace orange with cyan. It has more distance to the other colors and to me it looks simply looks a bit better. Below is a quick mockup.

![cyan](https://user-images.githubusercontent.com/156318/55933320-a010fa00-5c35-11e9-8d86-8f64a12bc630.png)

**Comment by Zamiell** [comment]
@aliblong @fpvandoorn

**Comment by Ape** [comment]
Also, we could change 'Wild & Crazy' to have:

yellow = red + green
purple = red + blue
cyan = green + blue

This would allow us to completely remove the orange cards.

**Comment by aliblong** [comment]
Is cyan easier to distinguish from blue than orange from yellow? It's not immediately clear to me.

**Comment by Asddsa76** [comment]
I haev no problem distinguishing orange and yellow. Not in favour of changing orange, since it's eponymous to 6-suit.

**Comment by Ape** [comment]
> Is cyan easier to distinguish from blue than orange from yellow?

Yes, I think it definitely is, but the matter is highly subjective.

At least for me, yellow vs orange is noticeably harder to differentiate than any other color pair in the game. However, this is by no means preventing me from playing. It's just a slight annoyance.

Using cyan seems to be one way to solve the issue. Another way would be to tweak the colors without really changing them completely. For example by making the orange a bit more red or by changing the lightness of the colors in some way.

**Comment by Ape** [comment]
I think the main problem here is the similarity of the card fill colors (the background color behind the numbers and symbols on the cards):

![backgrounds](https://user-images.githubusercontent.com/156318/56015388-9359d800-5d01-11e9-84dd-66d19c09c4f7.png)

**Comment by fpvandoorn** [comment]
I have no strong opinion either way. During a game I'm focusing more in the symbol on the card anyway (I sometimes confuse burgundy for black because I associate the spades symbol on a dark card with black). 
The current orange and yellow do have a similar hue, so maybe we should change them.

**Comment by Zamiell** [comment]
what color are you using for cyan, #00FFFF?

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/56085003-2e3dd980-5e0a-11e9-9a3f-6b49b9039a1c.png)
looks pretty terrible tbh

**Comment by Zamiell** [comment]
compared to this:
![image](https://user-images.githubusercontent.com/5511220/56085024-b0c69900-5e0a-11e9-9e7e-b03d280be256.png)

**Comment by Ape** [comment]
@Zamiell, Obviously `#00ffff` is way too bright. I made my mockup by just hue shifting some other color so that it looks decent.

However, I now noticed that there is already a color 'Teal' that is very close to what I wanted. Maybe that could be used in the 6-suit variant.

https://github.com/Zamiell/hanabi-live/blob/master/public/js/src/constants.js#L67 (`#00b3b3`)

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/56102169-11cc9a80-5ef9-11e9-9aa0-b17bc234b4a6.png)

**Comment by Zamiell** [comment]
vs this:

![image](https://user-images.githubusercontent.com/5511220/56102187-49d3dd80-5ef9-11e9-8bbb-5f78fd074703.png)

**Comment by Zamiell** [comment]
done it is now teal

**Comment by Dr-Kakashi** [comment]
Good job guys! I've been really busy with things in real life, so I'm really liking the change!  Teal is my favorite color as well! =D
