### ISSUE TITLE
many buttons are broken

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#470]
* I cannot move forward or backward in a shared replay (I'm not leader)
* I cannot click on someone's name during the game to see their actions

there is probably more

**Comment by fpvandoorn** [comment]
* hovering over a username doesn't show their time
* hovering over eyes doesn't show spectators
* hovering over crown doesn't show leader
* hovering over pace/efficiency doesn't show tooltip
* cannot click "pause shared turns"
* reported in voice chat: cannot change leader during replay

**Comment by Zamiell** [comment]
fixed
