### ISSUE TITLE
Faded pips on later clued cards

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#494]
During in-game replay, it's hard to keep track of which cards are which, since they all appear as generic while they used to have faded pips. 

For example, a surprising card is clued, and I go back to check for focus inversion etc, but now I have to mark the card with a note first to keep track of it, while in the past it would be recognizable due to having faded pips.

**Comment by Zamiell** [comment]
i think what you meant is the learned suit drawing, not the actual faded pips. now that the learned suit bug is fixed, are you finding yourself actually using faded pips?

**Comment by Asddsa76** [comment]
I guess not
