### ISSUE TITLE
card is grey without being played yet

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#499]
![image](https://user-images.githubusercontent.com/5511220/56002871-29eeb080-5c92-11e9-93ef-58d0c119a82e.png)

**Comment by sjdrodge** [comment]
![image](https://user-images.githubusercontent.com/715409/56028800-f25e2380-5ce6-11e9-93be-52172e67c4c8.png)

**Comment by Zamiell** [comment]
ah that screenshot has a game ID, so it is much better than my screenshot, thanks

**Comment by Zamiell** [comment]
fixed
