### ISSUE TITLE
Cards stay in place in background

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#503]
![Hanabi background cards 2](https://user-images.githubusercontent.com/49531523/56011450-f3438500-5ce7-11e9-92e2-ca053d10c867.gif)
![Hanabi background cards](https://user-images.githubusercontent.com/49531523/56011451-f3438500-5ce7-11e9-9bcb-1747958c722e.gif)
![Background yellow border](https://user-images.githubusercontent.com/49531523/56011452-f3438500-5ce7-11e9-8c7d-a1edcfe66503.gif)
![Ghost cards](https://user-images.githubusercontent.com/49531523/56011453-f3dc1b80-5ce7-11e9-9820-110ed6cdb370.gif)
![image](https://user-images.githubusercontent.com/49531523/56011494-31d93f80-5ce8-11e9-9a30-4d0dfc94f1f2.png)

Errors say something about discord pictures?
![image](https://user-images.githubusercontent.com/49531523/56011465-048c9180-5ce8-11e9-8ee9-32441a5e2dcc.png)

**Comment by Zamiell** [comment]
the errors in that screenshot is not related to the bug, so I will need the actual corresponding error.
so, in the future:
1) always play on hanabi.live/dev
2) always play with the javascript console open on the right side (make sure it is on the "Console" tab)
3) when the bug randomly happens, you will immediately see errors pop up on the right side, and then you will know that they correspond to the bug that just happened

**Comment by Asddsa76** [comment]
![image](https://user-images.githubusercontent.com/49531523/56188634-5013a800-6026-11e9-96cc-cf7d0e3dc8a2.png)

**Comment by Zamiell** [comment]
those keyboard bugs are actually unrelated to the bug you are seeing. i've fixed the keyboard.js bug now, so repeat this process and let me know if you see any other error messages.

**Comment by Zamiell** [comment]
if it happens again and you dont have any error messages, its probably something to do with your graphics card / graphics driver, because this bug doesn't happen to anyone else. i would try running a different OS (temporarily as a troubleshooting measure) and see if it happens there

**Comment by Zamiell** [comment]
closing issue, reopen if you find actual javascript errors relating to the bug
