### ISSUE TITLE
Pips sometimes not crossed out for already played cards

### ISSUE THREAD

**Issue by sjdrodge** [Zamiell/hanabi-live#506]
Game 29480, Turn 51, snkylittleazn's slot 3 doesn't have the already played y5 and r5 eliminated. Apologies for the lack of screenshot.

**Comment by Asddsa76** [comment]
Crossed out yr for me, but not b

![image](https://user-images.githubusercontent.com/49531523/56068048-a7431f80-5d7d-11e9-9893-1246b8d7bfcd.png)

**Comment by sjdrodge** [comment]
Interesting that the possibilities that weren't eliminated are exactly the ones that were played from our own hands. Probably a good indication of the nature of the bug.

**Comment by Zamiell** [comment]
reopen if it still happens on the latest code

**Comment by sjdrodge** [comment]
Noticed it again during game 30412: iamwhoiamhahaha's g5 didn't get a crossed out blue pip after I played b5, but it works fine in the replay, so reproducing might be a real pain.

**Comment by Zamiell** [comment]
well reproducing games is fairly easy because the server has a !replay command. so from your perspective the pip didn't get crossed out or from his perspective?

**Comment by Zamiell** [comment]
ok i think i fixed it now, reopen if you still get the bug
