### ISSUE TITLE
Bug: In-game replay with later-known info

### ISSUE THREAD

**Issue by hunt0r** [Zamiell/hanabi-live#526]
ID# 29979

Turn 10 is Blues to Hunter. Upon receiving the clue, Hunter goes into the in-game replay, and back 2 turns, but both cards are now NOT showing blue. (The replay usually shows all now-known info as we look back in time, say at Turn 8 or something)

After Hunter plays the b5 on Turn 13, going back in the replay (say to Turn 8) correctly shows the b5, but still doesn't show the other blue card as known-blue, so the issue persists, and seems to be limited to un-played clued cards.

**Comment by Zamiell** [comment]
fixed
