### ISSUE TITLE
Keyboard hotkeys for making notes

### ISSUE THREAD

**Issue by Ape** [Zamiell/hanabi-live#528]
I would like to play the game with keyboard only. Currently it's not really possible, because there is no way to make notes without using mouse.

**Comment by Zamiell** [comment]
besides writing notes, what is missing?

**Comment by Zamiell** [comment]
also, propose functionality of how you want it to work

**Comment by Ape** [comment]
> besides writing notes, what is missing?

I think this is the only thing missing. However, I don't like the current hotkeys for playing or discarding cards, but I will need to do some testing and come back to these later.

> also, propose functionality of how you want it to work

There should be some hotkey for opening the same note prompt that you can open with right-clicking. I'm not yet sure what would be the best system for selecting which cards to note.

**Comment by Zamiell** [comment]
ok, reopen the issue when you have answers to these two questions
