### ISSUE TITLE
server doesn't verify if non-hosts try to terminate tables before the game starts

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#53]
Since the server uses the abandon command for abandoning both ongoing and unstarted games, any player that joins the table has the ability to kill the table. that means you can kill any table if you join before the game starts or the table gets full.
This is a very minor issue easily fixed with yet another verification in the commandGameAbandon.go file, just thought I'd mention it.

**Comment by RaKXeR** [comment]
After talking with instantiation a bit we realized that the optimal behavior for non-hosts abandoning tables would not be to stop them from sending the command all-together, but to simply make them leave the table. The solution is probably to just send commandGameAbandon to commandGameLeave if triggered when the game hasn't started.

**Comment by Zamiell** [comment]
ok done
