### ISSUE TITLE
replay un-visually-morphs cards from comments

### ISSUE THREAD

**Issue by hunt0r** [Zamiell/hanabi-live#539]
If I comment my own card (e.g. "p2") it visually becomes one. However, going back in replay, it un-visually-morphs. It stays un-morphed after I exit replay

**Comment by hunt0r** [comment]
Hrmm... later in same game, I don't observe this bug. So not sure what's different between the two...

**Comment by hunt0r** [comment]
But then the 2nd copy of the card (which I have marked in my hand) was drawn... and my card visually un-morphed. So still buggy, I think

**Comment by Zamiell** [comment]
can you provide steps to reproduce?

**Comment by Zamiell** [comment]
oh i think i found the bug, reopen the issue if you still experience this bug

**Comment by hanabirnoob** [comment]
I experienced the bug as well two times. First time brown 4 morphed into brown 3. Second time a multi card magically turned into a green one when it was clued green.

**Comment by Zamiell** [comment]
did you experience the bug since 40 minutes ago?

**Comment by hanabirnoob** [comment]
Yes. I even took the evidence.

**Comment by Zamiell** [comment]
can you provide steps to reproduce?

**Comment by hanabirnoob** [comment]
https://imgoat.com/uploads/534b76d325/211130.gif
I have only a gif.

**Comment by Zamiell** [comment]
ok, that's an unrelated bug due to something wrong on the server that I already fixed, so it shouldn't happen again
