### ISSUE TITLE
Refreshing page fades misplays

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#542]
![image](https://user-images.githubusercontent.com/49531523/56189704-e47f0a00-6028-11e9-88a1-59d56ed9bc1e.png)

**Comment by Zamiell** [comment]
i dont understand what the bug is. can you elaborate

**Comment by Asddsa76** [comment]
The screenshot is of the game, not in replay. The 2 red Xs are faded, as if they happen in future.

**Comment by Zamiell** [comment]
im not following. what exactly is a "red x"?

**Comment by Asddsa76** [comment]
MisplaysThey're faded, that's the problem

**Comment by Zamiell** [comment]
oh i think i see now

**Comment by Zamiell** [comment]
fixed
