### ISSUE TITLE
Hotkey for going back to live game from replay mode

### ISSUE THREAD

**Issue by Ape** [Zamiell/hanabi-live#543]
Thanks for implementing #527 (hotkey for replay mode). I now realized that maybe there should also be the complement hotkey for going back to the live game from the replay mode.

The key could be something like esc, space or maybe backspace.

**Comment by Zamiell** [comment]
it already is escape

**Comment by Ape** [comment]
Ah, thanks. I tried pressing esc, but seems like my browser config hijacked the event to itself. I was now able to configure my browser so that esc returns to the live game.
