### ISSUE TITLE
Content idea: Multinumber deck

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#545]
What about a deck that has cards that are touched by every number clue? Sort of like how every color clue touches rainbow.

**Comment by Zamiell** [comment]
duplicate of #448

**Comment by Zamiell** [comment]
or do you mean one specific suit?

**Comment by hanabirnoob** [comment]
Sorry. One specific suit. Sorry for duplicate.

**Comment by Zamiell** [comment]
if you mean one specific suit it isn't a duplicate

**Comment by hanabirnoob** [comment]
Sorry for confusion.

**Comment by Zamiell** [comment]
ok done
