### ISSUE TITLE
When a game gets bottom-decked by unique non-5, make the game feed announce that.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#547]
So when the message "[Players] finished a [variant] game with a score of 29 (bottom-decked by shuffle)" appears, the people in the lobby know that the players played the game well enough to achieve maximum score possible with that shuffle and non-perfect score was not their fault. Although if there was a bottom-deck shuffle and players still didn't play the game well enough to achieve highest possible score, what to do then?

**Comment by Zamiell** [comment]
announcements are meant to be brief and cursory, so this kind of detail seems superfluous
