### ISSUE TITLE
players inside abandoned unstarted tables don't get kicked back into the lobby

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#55]
When the table host abandons a table they created with players inside by clicking "Return to the Lobby" and then abandoning the table with the "Abandon" button, the players do not get kicked back into the lobby. Instead, they sit in the table as if it still existed, with the status "Pre-Game"; even though in the eyes of the server and table list, the table doesn't exist.

**Comment by RaKXeR** [comment]
turns out the fix to this bug is the same as #53 , which is to point `commandGameAbandon` to `commandGameLeave` inside the `if !g.Running` block

**Comment by Zamiell** [comment]
can you test to see if this still happens
