### ISSUE TITLE
Six cards seen in replay.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#556]
Evidence here:

https://imgoat.com/uploads/534b76d325/211171.png

Apparently, after some certain move, the redundant card disappeared. And if I am not mistaken, there are currently no variants in the game where everyone has different amount of cards.

**Comment by Zamiell** [comment]
are there any errors in the javascript console?

**Comment by hanabirnoob** [comment]
So far I didn't see any.

**Comment by Zamiell** [comment]
did refreshing the page fix it?

**Comment by hanabirnoob** [comment]
It seem to have worked. I watched the same replay again and now it is fine.

**Comment by Zamiell** [comment]
reopen the issue with the actual javascript error if it happens again
