### ISSUE TITLE
If pink card receives 2 different color clues, it currently doesn't turn pink.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#560]
[Edit: Corrected color to number]
When pink is the only non-standard suit and a pink card receives two different number clues, would it make sense if it would turn pink in player's hands because being touched by at least two different number clues means it is pink (assuming there are no other suits that can receive multiple number clues)?

**Comment by wjomlex** [comment]
Do you mean "number clues" in each place you say "color clues"? Pink is its own color.

**Comment by hanabirnoob** [comment]
Yup. I meant number clues. My bad again.

**Comment by Zamiell** [comment]
fixed
