### ISSUE TITLE
Idea: Different symbols for white, brown and pink suits

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#563]
Currently, for non-standard suits, only rainbow and dark rainbow have a custom. Since brown, pink, white, and their dark versions behave differently from standard suits, maybe it would be useful to have them also a custom suit symbol just like rainbow does. 

(I currently don't know if suit symbols on cards are unicode symbols or not so I don't know how easy it is to implement them)

**Comment by Zamiell** [comment]
what symbols? be more specific

**Comment by hanabirnoob** [comment]
Some of the ideas:

https://s3.amazonaws.com/files.thegamecrafter.com/5071cd3b3838569fdb27ef18129e75e3a0edce6c

O for brown

X for pink

http://clipart-library.com/images/8cA6x99Li.jpg

Shields for white

Also, should I prefer a symbol that is already present in unicode?

**Comment by Zamiell** [comment]
not a big fan of any of those personally

**Comment by Zamiell** [comment]
im not inherently opposed to adding more suit symbols, but i dont think O's and X's and weird shapes would look very good in the context of the existing ui.
