### ISSUE TITLE
for pink and brown, use ABCDE instead of 12345

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#566]

**Comment by aliblong** [comment]
This would help with the pips as well. For example, if you get clued 4 in brown suit, your other cards don't get neg 4, since you could have brown, but that changes when it's instead brown D.

**Comment by Zamiell** [comment]
actually i thought about this and changed my mind. it would be more confusing overall i think, plus it is hard to say "Pink E" without it sounding like "Pinky"
