### ISSUE TITLE
Finished the game with light and pink suit. White in-game, pink in replay

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#570]
If I played light pink variation, the deck was white when playing or when exiting and entering the game after it was being reviewed. However, when watching a reply, not only was the deck pink, but there was also a brown suit slot. I entered a dev mode and console showed no errors at all. Replay id: 31168

**Comment by Zamiell** [comment]
"light and pink suit" what does this mean

**Comment by hanabirnoob** [comment]
Light pink suit. Sorry for confusion.

**Comment by Zamiell** [comment]
fixed
