### ISSUE TITLE
new variant suggestion: prism

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#573]
We have rainbow: one suit is touched by all color clues
We have pink: one suit is touched by all rank clues
We have multi-fives: one rank is touched by all rank clues
So we need one more variant: one rank is touched by all color clues.

So here is my new variant suggestion. **Prism**: all color clues touch all 1s. 
I think having the rank 1 as the "multi"-cards probably makes it hardest, so that's why I chose it.

**Comment by Zamiell** [comment]
Do players have the ability to clue rank 1?

**Comment by fpvandoorn** [comment]
Yeah (then it works the same as pink, where you can still clue pink).

**Comment by Zamiell** [comment]
wouldn't a better name be rainbow 1's then rather than prism ones?

**Comment by Zamiell** [comment]
maybe we could rename multi 5s to "Pinkish 5s"

**Comment by fpvandoorn** [comment]
Maybe. Rainbow 1s sounds more like the name of a card (in the rainbow variant) than the name of a variant, but I'm fine with either.

**Comment by Zamiell** [comment]
should be implemented now
