### ISSUE TITLE
Variant suggestion: Dual discard pile

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#576]
Basically, a variant that has two discard piles. Let's use 4-suit version for an example: If you discard a blue or green card, it needs to go into discard pile 1. If you need to discard yellow or red card, it needs to go into discard pile 2. Discarding a card into wrong pile is counted as a misplay.

Would that variant change the strategies of Hanabi significantly?

**Comment by Zamiell** [comment]
it doesn't sound that interesting
