### ISSUE TITLE
Make the down arrow key exit replay during games

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#577]
Given the left and right arrow keys can be used to enter the replay without having to press the replay button, I would like to also be able to leave the replay without having to move all the way across the keyboard to the esc key. Since there's no behavior for the down arrow anyway, this seems like a logical decision. An alternative button would be the backspace button, which is still within reach, but I think it's a worse decision unless we decide to use the down arrow for something else.

**Comment by Zamiell** [comment]
done
