### ISSUE TITLE
Convention Training/Preview Mode

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#578]
I remember mentioning this idea quite a large time ago but apearently never made an issue about it, likely because of how complex it is.

For many people (myself included), it is difficult to look at the convention definition in the document, and understand just which scenarios it truly applies to. The conventions often have described examples to follow up on it, and sometimes screenshots. While this information surely helps, it still doesn't feel as alive as witnessing this convention in a real game.

My proposal is the creation of a training mode, where you select the convention you want to see in action and try to perform, and get booted into a randomly generated game situation that satisfies all of the criteria for the given convention to be applied. If the convention requires certain moves to be performed previously, they should be seen as if other players are performing them, until it reaches the player's turn to apply the convention.

The mode should look just like a normal untimed game for the player, except all player names would be fake (Alice, Bob, etc...). This means the player can look around as much as they want and do the clue they think works with the convention. If they applied the convention correctly, great, if not, we tell them that is not how the convention works. While it would be great to go into more detail here, coding such a response message and verification would be extremely difficult, so I'll leave that up to interpretation.

In the scenario where they did in fact do the expected move, they could see the resulting interpretations of the other players (aka discarding, playing, missplaying). Ideally, they'd also see "cm", "f", and similar notes, so that the player can see what the read is if there's no immediate action.

And that's it. after the scenario plays out they can just look at the replay, restart with a newly generated scenario for the same convention, or go back to the menu.

**Comment by Zamiell** [comment]
pretty hard to program this, submit a PR

**Comment by Zamiell** [comment]
gonna close this for now to clean up the issues
