### ISSUE TITLE
Making notes as a spectator

### ISSUE THREAD

**Issue by Ape** [Zamiell/hanabi-live#579]
Sometimes I would like to be able to make notes as a spectator. This would be useful for marking things that need to be discussed during the review.

**Comment by hanabirnoob** [comment]
Spectator notes would be better if the icon appears at the lower left side of a card to make it easier to distinguish from players' notes.

**Comment by Zamiell** [comment]
1) players agree to play with each other before the game starts, so there is an implicit contract: the combined notes of all the players will be combined and baked into the final game state that is stored in the database.

2) players do not agree to be spectated by a complete stranger. this feature would have the potential for abuse when a spectator can permanently mark pejorative words on cards, which would persist into the permanent game recording into the database.

3) it also does not scale well. what if 10 spectators all have notes on the same card, in a 5-player game where all 5 players have a note on the card. now there is a giant essay of information in the tooltip, most of which will be duplicated notes like "cm". there would need to be a system to priority player notes over spectator notes, or maybe have a cutoff after having 6 lines.

**Comment by Ape** [comment]
You could add some "Hide spectator notes" checkbox on the replay view if it becomes an issue.

**Comment by RaKXeR** [comment]
In the past, it was possible for spectators to edit notes. However, this only applied to the client and no other users could see such notes, given it was mostly just a bug. If what you want is to be able to keep track of this information for yourself, the javascript could probably be edited in a way where this is achievable. I do not agree however that the server should have any knowledge of spectator notes, mostly for the reasons @Zamiell mentioned.

I recommend you just open up notepad and write down the turn, player, slot, and information you want to keep track of, if you're a spectator that wants to point something out during the game. It's quite a special edge case and keeping track of it outside the game is not a deal breaker given you aren't actually a part of the game to begin with.

**Comment by Zamiell** [comment]
as a first step i could do spectator notes that are not shared with the players, and those are not written to database

**Comment by Zamiell** [comment]
ok i rewrote the note system and spectators can now make notes.
they are ephemeral though (notes will be deleted if spectator refreshes/leaves).
also spectator notes are not written to the database.
