### ISSUE TITLE
Confusing neg-info in Light Rainbow

### ISSUE THREAD

**Issue by hunt0r** [Zamiell/hanabi-live#582]
Playing light rainbow today, I clued 1's to a player who's holding a light rainbow card. From my perspective of his empathy, the rainbow card didn't get negative-one.

Which brings up a contradiction: If it's a light-rainbow 1, then a 1's clue doesn't touch it... but perhaps also it can't have negative-one?

Anyways, my expected behavior was to show the negative rank info as well as the rainbow possibility, and rely on the player to deduce that it could be a light-rainbow 1, despite having neg-1 info.

**Comment by Zamiell** [comment]
intended
