### ISSUE TITLE
Pink and Brown 3 Suits doesn't display the pink color clue button

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#593]
The pink color clue is current missing from the Pink and Brown (3 suits) variant. Did not check if the other versions with more suits are also bugged.

**Comment by Asddsa76** [comment]
Maybe refactor code? Currently, when making a new variant, you specify both the suits and clues in that variant. If instead clues were bound to suits, you would only have to include the suits, and then the code should work out what clues are required.

Might be harder to code ambiguous and dual variants, though.

**Comment by Zamiell** [comment]
refactoring the code would be bad for precisely the reasons you mentioned

**Comment by Zamiell** [comment]
fixed
