### ISSUE TITLE
Game variant descriptions and renames are inconsistent in documentation.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#595]
"Wild & Crazy" was renamed to "Dual-color mix" but Wild & Crazy in is still mentioned list of variants. Same goes to "African-American" being mentioned despite it being renamed "Ambiguous mix". Meanwhile, "Gay pride" did not get the same renaming treatment to make it more descriptive (e.g. special suit mix or something). Finally, the document lists "Prism-ones", a variant that is not currently in game.

**Comment by Zamiell** [comment]
good catch

**Comment by Zamiell** [comment]
should be fixed now
