### ISSUE TITLE
Prism-Ones Bugs

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#599]
1. There are p1 (slot 2) and p3 (slot 4) in bulbasaur's hand
![bug1](https://user-images.githubusercontent.com/50160641/57004369-200cfd00-6c01-11e9-9b07-fd1df7f9a0dd.png)
2. Squirtle wants to give purple clue to bulbasaur which touches his p1 and p3 before giving the clue, but it only touches p3 after giving the clue.
![bug2](https://user-images.githubusercontent.com/50160641/57004446-a1648f80-6c01-11e9-824a-3df38b31ca0f.png)
3. At the moment, if you left click bulbasaur's hand, p3 is becoming p1.
![bug3](https://user-images.githubusercontent.com/50160641/57004489-eb4d7580-6c01-11e9-9113-8aceac8185e8.png)
4. Now in charmander's turn, he can neither give clue (any type of the clues) nor see the replay (he can do it before clicking the button "Give Clue", but after that, the replay button is broken). In addition, there are still 8 clues in the bank but squirtle should have burnt 1 clue in his turn.
![bug4](https://user-images.githubusercontent.com/50160641/57004599-c9082780-6c02-11e9-8ca3-bf3b71a5fa44.png)

**Comment by Zamiell** [comment]
can you retest on latest version?

**Comment by Zamiell** [comment]
i think it is fixed now
