### ISSUE TITLE
empathy shows negative ranks in the "Number Blind" variant

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#603]

**Comment by hunt0r** [comment]
Is this the same bug reported by cyberholmes. Replay ID 36090, Turn 27: Jack's slot 3 obtains empathy-marking for "not a 4" but this seems to be a logical mistake. Is this the same bug?

**Comment by Zamiell** [comment]
no, it is not the same bug, because this issue is about the "Number Blind" variant

**Comment by Zamiell** [comment]
<cyberholmes> another bug: in this multi-five game, fives don't show any color information on the back of the card, before or after color clues
<cyberholmes> there are no pips showing at all
<cyberholmes> also, in multi-five, the description says that every rank clue touches the fives, not every color clue. So a red-clued five should actually be red
<cyberholmes> another: if I have a note that says 'p5', the card shows as a purple 5. But then, I receive a color clue that touches the card, and it switches to showing as clued purple and the negative info on the numbers, but retains the note showing 'p5'. Deleting the note and re-entering it causes the card to
<cyberholmes> sorry, that overflowed
<cyberholmes> essentially, colors clues cause the notes to stop showing on the back of the card even if the clue didn't invalidate it
<cyberholmes> and then retyping the note fixes that
<cyberholmes> actually, update on the colors not showing on the back of the 5
<cyberholmes> when he tried to play that card, he got the popup asking if he did want to play the card because it was known to be unplayable
<cyberholmes> even though that was false
<cyberholmes> he hit okay, and it played succesfully

**Comment by Zamiell** [comment]
@hunt0r I'm unable to reproduce. I go into that replay, go to turn 27, left click on jac's slot 3, and no X's show up

**Comment by hunt0r** [comment]
Sorry, I said that in a confusing way. The empathy is "obtained" on 27, so go to turn 28, I see the empathy there.

**Comment by Zamiell** [comment]
fixed both the Number Blind bug and the bug with the feature that draws X's

i will move the other bug to a new issue
