### ISSUE TITLE
Variant suggestion: Mixed special suit

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#604]
Basically, a variant where the suit slot that needs to be built from 1 to 5 is composed of ten cards randomly selected from rainbow, white, pink and brown suit.

So, for an example, special suit can consist of following: Two Pink 1s, white 1, brown 2, pink 2, rainbow 3, brown 3 and two white 4s. However, the rank 5 card is randomly either light pink or light rainbow.

Playing cards for the special suit works the same as in standard suits from ranks 1 to 5. So you can place brown 3 on white 2 etc.

**Comment by Zamiell** [comment]
sounds too complicated
