### ISSUE TITLE
Bug: Right-clicking user as a spectator makes the player's viewpoint sometimes glitches out.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#605]
https://i.imgur.com/k2ojRcL.jpg

As you can see, I spectated a game from kondain's point of view. However, at some point, new cards started to become fully visible to me despite them not supposed to be visible for spectators as well. Right-clicking on the user still put me on empathy mode though to see what the user should have seen. I went to dev mode and the bug persisted. Checking for errors, I found none.

Game: 34941

**Comment by Zamiell** [comment]
fixed thanks
