### ISSUE TITLE
Bug: Replay 27631 corrupted badly (everybody has the wrong cards and whatnot)

### ISSUE THREAD

**Issue by sjdrodge** [Zamiell/hanabi-live#606]

**Comment by hanabirnoob** [comment]
Dev mode shows no bugs either.

**Comment by Zamiell** [comment]
is it an old replay? if it was played before the variant refactor then having the wrong suits is normal, because i switched the order of the suits

**Comment by Zamiell** [comment]
yeah this is a game i was in and it is from march. so yeah this is intended because the refactor happened on april 20th
