### ISSUE TITLE
fixme card images

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#609]

**Comment by Zamiell** [comment]
@fpvandoorn i was thinking a big X over the card, any ideas?

**Comment by fpvandoorn** [comment]
I'm not sure what this is referring to. An image if you write the word `fixme` on a note? 
I would prefer that the card shows a nice small note-symbol in the top-right corner (just like if you write any other note).

**Comment by Zamiell** [comment]
done
