### ISSUE TITLE
Middle click cards to go to turn they were clued

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#613]
Because it's faster than finding it in the clue log.

**Comment by Zamiell** [comment]
done

**Comment by Asddsa76** [comment]
It goes to the turn it first appears in the clue log. Which includes negative clues. 

Example: A blue card is in my hand when I get a red clue. Later, I'ts clued blue. Even later, I middle click it. It goes back to the turn it got negative red, not positive blue.
