### ISSUE TITLE
Change viewpoint during replay

### ISSUE THREAD

**Issue by Asddsa76** [Zamiell/hanabi-live#615]
When I watch replay, I see myself at the bottom.

![image](https://user-images.githubusercontent.com/49531523/57489680-1184ac80-72b7-11e9-97db-0be990353aa4.png)

Some hotkey to get an out-of-body experience.
![image](https://user-images.githubusercontent.com/49531523/57489671-07fb4480-72b7-11e9-8fe4-913c1cdc149c.png)

**Comment by hanabirnoob** [comment]
Would it be better to do the "toggle empathy button" where, when turned on, empathy mode automatically switches between whose turn it is?

**Comment by Zamiell** [comment]
this is already implemented for spectators but not for shared replays

**Comment by Zamiell** [comment]
you can now right click to change perspectives
