### ISSUE TITLE
Notes duplicate/not appearing on post-view

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#618]
I was a spectator and made a note.  When the game ended, the notes became duplicates. I exited the post-game and re-entered it in dev mode and the notes were completely missing. No errors appeared on console.
 
https://i.imgur.com/DqFKI4Y.png

Game. 36768

**Comment by fpvandoorn** [comment]
Oh yes, I've also seen those duplicated notes once.

**Comment by Zamiell** [comment]
not able to reproduce. closing for now unless you can post more specific steps to reproduce
