### ISSUE TITLE
Colorblind mode is not functioning.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#626]
At least in spectator mode. I set this to "on" just to test. Still no letters appearing on cards. Dev log showed no errors.

**Comment by hanabirnoob** [comment]
Update.

https://imgur.com/7ebc9648-142e-444a-9b9c-6d031fbdd98a

That's how colorblind mode is seen in dual-color variant.

**Comment by Zamiell** [comment]
fixed
