### ISSUE TITLE
don't parse note with `g|2`

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#627]
I wrote `g|2` (in duck) and got the error message that my card cannot possibly be `g2`. Please disable error in this case.

**Comment by Zamiell** [comment]
what does g|2 mean? green or number two?

**Comment by fpvandoorn** [comment]
yes. I'm pretty inconsistent with that notation so far, sometimes I use `g|2`, sometimes `g/2`

**Comment by Zamiell** [comment]
isn't the typical convention to use `g, 2`?

**Comment by fpvandoorn** [comment]
yeah, I could use other notation. Feel free to close (though I don't see how `g|2` is used to say that I have green 2)

**Comment by Zamiell** [comment]
fixed

**Comment by Zamiell** [comment]
the code now just looks at all of the text to the right of the rightmost pipe
