### ISSUE TITLE
global find and replace nuked a lot of comments

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#634]
can you fix all the comments that you changed?
like this:
```
// Decrease the maximum score possible for this table
```
it should read game, not table.

**Comment by Zamiell** [comment]
also stuff like this should read in-game, not in-table
```
In-table notify functions
```

**Comment by Zamiell** [comment]
another example:
```
// For example, a yellow clue will not touch a green card in a normal table,
```

**Comment by Zamiell** [comment]
there's a lot, not going to list any more

**Comment by aliblong** [comment]
Hard to tell if I got them all, so reopen if you find any
