### ISSUE TITLE
tableLobbyInfo.go needs to exist because you renamed the associated command

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#635]

**Comment by Zamiell** [comment]
also why not leave it as just "table"? tableLobbyInfo seems needlessly verbose

**Comment by aliblong** [comment]
It's the subset of table information that's viewable from the lobby. Some verbosity is necessary to distinguish it from the `tableGame` (previously `game`) message, which sends a different subset of the table info to the players who actually attend the table. Or, the two commands could be condensed into one, but I'm not motivated to redesign the messaging story.
