### ISSUE TITLE
Double right-click on a card hides all notes form the game until a refresh

### ISSUE THREAD

**Issue by Sucubis** [Zamiell/hanabi-live#638]
Steps to reproduce:
1. Go in a game
2. Write a note on some card
3. Double right-click on any card (essentially cancelling the note window)
4. All notes are now gone

**Comment by Zamiell** [comment]
cannot reproduce, provide more detailed steps

**Comment by Zamiell** [comment]
nevermind i figured it out

**Comment by Zamiell** [comment]
fixed
