### ISSUE TITLE
Cannot read property 'canClue' of null

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#640]
Transient error. I have only seen it occasionally while pressing the down arrow while rewinding a live game. It might also repro on the un-minified source.
> Uncaught TypeError: Cannot read property 'canClue' of null
>    at Object.a.handleAction (main.min.js:2920)
>    at Object.n [as exit] (main.min.js:2902)
>    at HTMLDocument.q (main.min.js:2878)
>    at HTMLDocument.dispatch (main.min.js:145)
>    at HTMLDocument.n.handle (main.min.js:141)

**Comment by Zamiell** [comment]
you should play in /dev so that you get better error messages

**Comment by Zamiell** [comment]
closing for now
