### ISSUE TITLE
Un-needed card not faded

### ISSUE THREAD

**Issue by wjomlex** [Zamiell/hanabi-live#652]
<img width="1174" alt="Screen Shot 2019-06-14 at 10 31 19 PM" src="https://user-images.githubusercontent.com/6496674/59654664-13f6e380-914c-11e9-85e0-f8e51b26301d.png">

b2 should be faded.

**Comment by Zamiell** [comment]
what was the game ID

**Comment by wjomlex** [comment]
Verily I have not a clue -- will include in the future though

**Comment by Zamiell** [comment]
gonna close for now then since just a screenshot isn't really helpful

**Comment by sjdrodge** [comment]
Replay ID is #42093, but the bug looks fixed.
