### ISSUE TITLE
Sometimes notes don't want to disappear

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#656]
https://imgoat.com/uploads/0e190d8267/218972.png

What happened here, I don't know. I forgot to check the error log as well. Moving the cursor into and away from the note didn't make the note disappear either. Is it something related to duplicate notes?

**Comment by hanabirnoob** [comment]
Update. When I I complete/abandon game, then any notes that haven't disappeared won't.

**Comment by hanabirnoob** [comment]
Update: It randomly disappears during replay.

**Comment by fpvandoorn** [comment]
This is a known issue. I think it happens when the note appears at the same time as that the card moves, or something.

You can make the note disappear by hovering your mouse over the card that made the note appear in the first place (which might now be in the trash/play area)

**Comment by Zamiell** [comment]
just press esc to close any note tooltips
