### ISSUE TITLE
Up or down variant – suggestions

### ISSUE THREAD

**Issue by beri2** [Zamiell/hanabi-live#658]
I just tried the up-or-down variant, which is great.
I noticed it was tough to have a clear mind about what’s going up or down, despite the "Up"  "Finished" and "Down" indications under the stacks.

Could you maybe either:
- shift up or down by a few pixels the stacks that are played respectively up or down
- under the stacks, display the next card numbers to play, in order
- spread (why not upwards or downwards as well) the stacks slightly so that all played cards can be at least partly seen

The latest option might be the one that makes it easiest (and might be useful in other modes/variants). Ideally, 5s would always be at the top and 1s at the bottom.

Also, could there be a "START" clue? Or include START cards in the 1 and 5 clues.

**Comment by Zamiell** [comment]
> Also, could there be a "START" clue? Or include START cards in the 1 and 5 clues.

We've been able to get a perfect score a fair amount of the time in this variant, so making the variant arbitrarily easier isn't something that most people would probably like.

**Comment by Zamiell** [comment]
https://cdn.discordapp.com/attachments/478615084134957057/608365028667555873/Up_or_down.png

**Comment by beri2** [comment]
The above image was wrong, so I corrected it:

![Up or down](https://user-images.githubusercontent.com/52741407/62571177-067af180-b891-11e9-8288-de1927c6800e.png)

**Comment by Zamiell** [comment]
i dont know if there is enough room for that

**Comment by beri2** [comment]
Maybe something that adapts to the screen?
I spaced cards a lot here just to be clear.

**Comment by beri2** [comment]
Plan B (obviously not as good)
![Up or down 2](https://user-images.githubusercontent.com/52741407/62572708-a6864a00-b894-11e9-8508-f69b34c86cbe.png)

**Comment by Zamiell** [comment]
submit a PR

**Comment by Zamiell** [comment]
probably don't need this anymore with the new arrow features that were implemented
