### ISSUE TITLE
Feature suggestion: Add a password recovery feature

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#660]
After accidentally logging out and not remembering my password, I cannot log in anymore and I cannot recover the password either as there is no password recovery feature. I'm locked from my account. Suggestion: Add a password recovery feature.

EDIT: Fortunately, I remembered my password as it was written down on a physical medium. But yea. Cautionary tale.

**Comment by Zamiell** [comment]
password recovery implies that the website collects your email address, which i dont want to do
