### ISSUE TITLE
Suggestion: Make efficiency number account for number of cards that cannot be played (endgame)

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#662]
Basically, should efficiency number be reduced when the amount of cards that need to be played is lower than the amount of clued cards. It's more important in the endgame.

For an example, in game 46194, 15 cards were played with 9 clues. That means that its efficiency should be about 1.67. However, current efficiency calculator considers unplayed but clued in the endgame as well, inflating the efficiency number shows 2.44.

**Comment by Zamiell** [comment]
nah
