### ISSUE TITLE
Pink mode: numbers not marked

### ISSUE THREAD

**Issue by beri2** [Zamiell/hanabi-live#664]
Several times did we make mistakes due to the fact number clues are represented only by a yellow outline around the cards, which may look untouched if you don’t notice the outline.
And you need to mouse over the card to know what number touched it.

I can think of two things that would ease visibility:
- display some character (question mark / hash* / infinity) in the box corresponding to the number clued and/or colour the box in pink
- make the other boxes lighter-coloured

*I support a suggestion I read somewhere: change the "infinity" symbol for a # symbol, since # means "number".

Thanks a bunch.

**Comment by Zamiell** [comment]
the rank pip corresponding to a positive rank clue will now turn yellow
