### ISSUE TITLE
In-game chat stopped working

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#672]
https://i.imgur.com/fjaWekl.png
That's what happened. No errors in console despite dev mode.

**Comment by Zamiell** [comment]
provide steps to reproduce

**Comment by hanabirnoob** [comment]
But the error happened every time I pressed enter on in-game chat. Even exiting replay and re-entering it did not fix it.

**Comment by hanabirnoob** [comment]
Could it be because I tried opening null variant table before?

**Comment by Zamiell** [comment]
should work now
