### ISSUE TITLE
chatread is broken

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#675]

**Comment by hanabirnoob** [comment]
The "Table # doesn't exist bug"

**Comment by hanabirnoob** [comment]
That happened again. It's so annoying especially when I'm asked about my decisions and me not being able to answer.

**Comment by Zamiell** [comment]
provide steps to reproduce

**Comment by hanabirnoob** [comment]
1. Chat for a bit in-game.
2. Suddenly, chat doesn't work and instead, says "Table # does not exist"

**Comment by Zamiell** [comment]
i think i fixed it, open another issue if it is still broken after updating to the latest code

**Comment by hanabirnoob** [comment]
Now it's "This is an invalid room".

https://i.imgur.com/JWCatqd.png

**Comment by Zamiell** [comment]
```
open another issue if it is still broken after updating to the latest code
```

**Comment by Zamiell** [comment]
fixed chatread
