### ISSUE TITLE
make trash card symbol for "trash" note

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#682]

**Comment by fpvandoorn** [comment]
It might be useful to also put this symbol on visible trash cards of other players, instead of fading them. It's easy to overlook faded cards.

**Comment by efaust** [comment]
There's also a difference between a "not useful" card (currently faded) and known trash, which we could also mark in other people's hands after some "kt" note, or something.

Not sure other people's hands are that relevant. Big fan of a morph in-hand for KT.

**Comment by Zamiell** [comment]
done
