### ISSUE TITLE
Total games calculation is wrong on global statistic for variants

### ISSUE THREAD

**Issue by zsole2** [Zamiell/hanabi-live#697]
Great new feature to provide global statistics!
A just came across a possible bug: see e.g. [Global Statistics for Black & Omni (6 Suits)](https://hanabi.live/variant/186).

```
Total games played (in non-speedruns): 29
.....
Total perfect scores: 1 / 29  (11.1%)
Total strikeouts: 8 / 29  (88.9%)
```

There were only 9 games played, but 29 is shown, apparently summed for all players' total number of games. On the other hand, percentage calculation seems to be OK for 9 games.

Is there a specific reason to show only recent games? Scanning the database might be time consuming, though. 
However, full game history apparently lists all games for a player. With the added benefit to be able to sort by column headers...making it easier e.g. to list all perfect games on the top of the page.

**Comment by Zamiell** [comment]
the reason is because i dont want to program pagination

**Comment by zsole2** [comment]
Yeah, pagination might be complex. But still, being able to find the perfect games to review would be helpful. Or games played by the experts. 
Some kind of filtering, like the one is already done for missing games, maybe? I'm not a programmer, so cannot judge the difficulty...

**Comment by Zamiell** [comment]
if you want to find a game played by an expert, you can go to their profile and then click on "Full Game History"

**Comment by Zamiell** [comment]
The bug should be fixed now thabks
