### ISSUE TITLE
Alternating clues - new variant suggestion

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#699]
First clue may be whatever. After that every clue must be the opposite type of the clue before it. E.g. Turn 1 Alice clues 5 to Cathy. The next person to give a clue will be forced into giving a color clue. After that, the next person to give a clue must give a number clue. Etc.

It's basically an alternate take on color mute/number mute that would probably end up a bit easier than either. But hopefully fun.

You can obviously rename it as you like.

**Comment by Zamiell** [comment]
done
