### ISSUE TITLE
Swap out 🔻 with 🔍 (createGameTooltip search box)

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#703]
The dropdown arrow on the UI element that lets you select a variant should change to a magnifying glass icon. While combo boxes that work as search bars exist, they don't behave like the current one (like omitting non-matches from the list). The easiest workaround is swapping the icon so people think of it as a search bar (which is essentially what it is now, not a combo box) . An alternate solution would be a rollback of the tooltip.

**Comment by Zamiell** [comment]
yeah i dont know how to do this. submit a pull request

**Comment by Zamiell** [comment]
someone can submit a PR if they know how to do this
