### ISSUE TITLE
Rainbow&dark rainbow, white&grey,brown&chocolate,pink&dark ink - Variant

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#715]
Are these not present because these would be harder to implement? And because that would mean that pink & dark pink (and brown & chocolate) need to have separate color clues?

**Comment by Zamiell** [comment]
i dont want to implement ambiguous colors outside of an ambiguous variant

**Comment by hanabirnoob** [comment]
Pink& Dark Pink. And Brown & Chocolate can have separate color clues.

**Comment by Zamiell** [comment]
that would be confusing
