### ISSUE TITLE
Throw It In A Hole mode: empathy in replay

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#726]
Should using empathy mode in Throw it in a Hole cause the 'hole' to appear or not during replays?

**Comment by Zamiell** [comment]
what

**Comment by hanabirnoob** [comment]
Basically, should activating empathy mode during replay cause played cards to not appear when replaying 'throw it in the hole' game?

**Comment by Zamiell** [comment]
i dont think that is necessary
