### ISSUE TITLE
Incremental spectator notes lack formatting

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#73]
When first connecting to a game as a spectator, all notes are sent in a large batch. This includes formatting in the notes so that new lines start each note on the same card, with the author's name in bold, etc.

This is also the case when connecting to a replay.

However, when the server sends an individual note update to a spectator, the formatting is not sent. This makes them hard to read.

**Comment by Zamiell** [comment]
can u show a screenshot

**Comment by rogers-j** [comment]
It is deterministic and always repros.

Create game. Join as a spectator. Let it finish loading. Pick a card. As both players, make a note on the card. Examine the note as a spectator after each note.

**Comment by Zamiell** [comment]
your mom is deterministic
