### ISSUE TITLE
variant idea: Backwards suit

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#740]
Basically this is a backwards/inverted/upside down suit. It could be implemented one of two ways (or others):

Option A) This suit must be played to the stacks backwards (5 then 4 then 3 then 2 then 1). This option is simple enough, but has the problem of having only one starting card, and it may be hard to code. You could change the card distribution to three 5s, two 4s 3s 2s, and one 1 with this option if desired.

Option B) The only rank clue that touches the inverted suit's 5 is "1", 4 is touched by "2", 3 is normal, 2 is touched by "4" and 1 is touched by "5". This option is harder to explain and makes for more difficult empathy

I prefer option A if it's workable.

**Comment by Zamiell** [comment]
i dont think that this makes the game harder in a meaningful way. i imagine that it would play extremely similarly to just a normal six suits game.
