### ISSUE TITLE
Please change the 'CM' functionality

### ISSUE THREAD

**Issue by invarse** [Zamiell/hanabi-live#753]
if you write CM, there's a nice halo that goes around the card. I like this. However, this disappears under many conditions and the card goes back to looking like an untouched card (with a note, I'll admit).  That said, getting used to it being there as a marker for a cm and then having it disappear is awful, as human brains are wired to get used to signal triggers like that.

 Can it please either not appear in the first place, or stay permanently (my preference).

**Comment by Zamiell** [comment]
yeah ill fix this eventually

**Comment by Zamiell** [comment]
fixed
