### ISSUE TITLE
right click efficiency to add counter

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#774]

**Comment by padiwik** [comment]
What exactly does this mean, add a certain number of cards to the numerator? Why do you want to spend time fiddling with the efficiency counter in a game when it can be done automatically through notes?

**Comment by Zamiell** [comment]
because i want efficiency to be synchronous

**Comment by timotree3** [comment]
Why do you want that?

**Comment by Zamiell** [comment]
propose how it works with notes in a shared review

**Comment by timotree3** [comment]
Clued trash cards do not count towards efficiency in shared review (even if they are unknown trash)

Useful clued cards count towards efficiency in shared review.

Unclued cards with an `f` note by the player holding them or an identity note by the player holding them both count towards efficiency in a shared review.

**Comment by timotree3** [comment]
Hmm. Then cards with an `f` note will act like they're gotten even when viewing a turn before they were.

**Comment by timotree3** [comment]
So then either we ignore in shared review or we keep track of when a note was written.

**Comment by Zamiell** [comment]
we are not keeping track of when a note was written, as previously discussed

and i'd rather have it work the same in shared review as it does in a normal game for consistency (and it makes the code simpler)

**Comment by timotree3** [comment]
Is the review leader really gonna take the time to fiddle with adding and subtracting from the efficiency during the review? It seems like no, and if not, the efficiency displayed during review will not be the same as the efficiency displayed during player's turns.

If we are picking a solution where the efficiency displayed during review is not the same as the efficiency displayed during player's turns, then a note-based solution would be much more user-friendly.

**Comment by Zamiell** [comment]
> Is the review leader really gonna take the time to fiddle with adding and subtracting from the efficiency during the review?

yes, to find the real eff for a specific turn
furthermore, you will have to ability to do +-N yourself in a game by right clicking eff

**Comment by timotree3** [comment]
Well, using information from notes during the game and using a manual control during replay are not mutually exclusive.

To make this proposal feel easy to use, I propose the following automatic rules for when the player's manual adjustments should be undone.

- Whenever a clued trash (or duplicate) that previously counted towards `cardsGotten` is discarded, if the player has touched the manual counter this game, then add one to the manual counter
- Whenever an unclued card is successfully played, if the player has touched the manual counter this game, then subtract one from the manual counter

**Comment by Zamiell** [comment]
the idea is that cards aren't tied to the feature

you just modify it for a specific turn, and then it ends when the turn changes

**Comment by timotree3** [comment]
what if it stuck around when the turn changed and we implemented my proposed automatic adjustments? I think that that would be nicer to use.

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
timo open a new issue and/or for the improvements that you want
