### ISSUE TITLE
make stale = kt

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#777]

**Comment by Romain672** [comment]
If I understood correctly : why?
A stale card can totally be a g4 who seem useless at first, but finish by being good.

**Comment by Zamiell** [comment]
typically stale cards are trash though

**Comment by Romain672** [comment]
Or could be two players who have the same card on a row too...
Or perhaps it would be possible to make the trash of kt card transparent at ~20%.

**Comment by Romain672** [comment]
Or like, your hand is x-g1-x-g4, we don't clue you that, so you write g4 as stale.
Then someone clue you green as a focus inversion, you play g1, but your g4 is still writed as trash, but your teammates except you to save that card.

**Comment by Zamiell** [comment]
done
