### ISSUE TITLE
hide Clues + Strikes, hide Cards Gotten

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#78]
put them in a tooltip if you over over efficiency

**Comment by Zamiell** [comment]
now put them in a tooltip

**Comment by aliblong** [comment]
My original idea was to make it depend on user notes, which would reinforce using a certain notation style. Like writing "p1" on a finessed p1 would count it as gotten. I didn't mind that, but really I just didn't want to bother doing anything but the simplest implementation until seeing what everyone thought.

**Comment by Zamiell** [comment]
yeah have it do that, either "p3" or "f" for finessed
