### ISSUE TITLE
Variant rules changes should be in the variants.json file

### ISSUE THREAD

**Issue by jeep** [Zamiell/hanabi-live#781]
Stuff like this isn't very maintainable. Special rules imposed by the variant (not specific to the suit) should be in the variants.json file. Multi-fives should probably have something special for ranks similar to suits, but unless there are many of them, it could be in the variants.json.

		if strings.HasPrefix(variant, "Number Blind") || strings.HasPrefix(variant, "Number Mute") {
			return false
		}
		if strings.HasPrefix(variant, "Multi-Fives") && card.Rank == 5 {
			return true
		}

**Comment by Zamiell** [comment]
duplicate issues aren't very maintainable

**Comment by jeep** [comment]
They are distinct issues with different possible solutions. It's likely that the solution is to move the info to the variants.json, but not certain.

**Comment by Zamiell** [comment]
i thought they were duplicate issues, so i guess my joke fell flat

**Comment by Zamiell** [comment]
>Special rules imposed by the variant (not specific to the suit) should be in the variants.json file.

what is the proposed fix here? for example, do you want me to add `"numberBlind": true` in the variants.json file to all of the number blind variants, and then change:
`if strings.HasPrefix(variant, "Number Blind")`
to
`if variant.NumberBlind`
in the golang code?
such a change strikes me as worthless, adding more total lines of code and not providing any extra insight into how the code works

**Comment by Zamiell** [comment]
additionally: if there were two variants that had number clues that touched no cards, then I think it **would** make sense to create a "rankCluesTouchNoCards: true" property in the variants.json file.
however, there is exactly 1 variant that has this property, so i am not sure that there is a benefit in expanding the scope of total possible variant parameters in the variants.json file

**Comment by alercah** [comment]
It leads to cleaner separation of concerns; for instance if someone wanted to write a bot which tried to play, if it wants to be able to read from variants.json to understand the variants, all the information should be there.

It could also mean that it's easier to make combination variants. For instance, if you wanted to combine Number Blind and Multi-Fives (I know this doesn't make sense but I don't want to look through for other variants that use this type of logic) you can't, because you need your string to have two different prefixes. Or if someone tries to add "Rainbow Number Blind", that won't work either. Then someone has to go update the Go code in addition to modifying the JSON file.

**Comment by jeep** [comment]
Well, it looks like Number blind uses special suits already, so can this ever resolve as true?
    if strings.HasPrefix(variant, "Number Blind") ||  (variants.go about line 312)
And Number mute can't even give number clues, right? So... can lines 312-314 just be removed?
Lines 260-266 can just be reading the ranks form the json file.

Probably the same for color blind/mute.  

That just leaves multi 5s and prism 1s? While not ideal, with one exception for each, it is probably okay... but when you want to add a combo (as alercah mentioned) or another similar variant, it should be refactored away.

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/0a46a38d98533554f67c33cb3d45048e4f7274bb

prism 1s and multi 5s will be revamped in the future
other than that, open a new issue if there is more stuff remaining not handled by this commit
