### ISSUE TITLE
Variant Idea: "Precise Rainbow"

### ISSUE THREAD

**Issue by alercah** [Zamiell/hanabi-live#782]
Feel free to change the name.

In this variant, the rainbow cards are not multi-coloured, but instead form a rainbow. m1 is red, m2 is yellow, m3 is green, and so on. This means that there's no way to clue multiple rainbow cards in one clue, nor to distinguish them from the natural cards of their suit by clues alone.

**Comment by rogers-j** [comment]
Perhaps 'Prism'

**Comment by jakestiles** [comment]
I'd want them to be blue/green/yellow/red/purple for 1/2/3/4/5 to match the stack's left to right to make it easier to remember.

**Comment by jeep** [comment]
This requires at least 5 suits, so the validation is easier if they are in order, since the colors are just ints. It would just be "card.rank == clue.color" or whatever the actual fields are called.

**Comment by alercah** [comment]
Yes, I forgot that the stacks are not in rainbow order when I was writing this. 100% agree.

**Comment by iamwhoiamhahaha** [comment]
i had a similar idea few weeks ago (but more complicated than yours) and decided not to propose it here

**Comment by Zamiell** [comment]
the stacks are in rainbow order now

**Comment by Zamiell** [comment]
Prism is a good name for the suit I guess
what would be the name for the number analog?

**Comment by jakestiles** [comment]
What even does “number analog” mean?

Prism - The number clues of this suit are normal. Each of the 5 ranks of this suit is a distinct color. 
Number Analog? - The color clues of this suit are normal.  Each of the 5 colors of this suit is a distinct number. (This sounds like nonsense)

**Comment by Zamiell** [comment]
you are right, i think the analog would just be a teal suit. that is confusing

**Comment by Zamiell** [comment]
this would be easy to program.
need a pip for this though, as it is a new suit.
@SashaIr any ideas?
maybe a colored version of this?
https://en.wikipedia.org/wiki/Penrose_triangle#/media/File:Penrose-dreieck.svg

**Comment by SashaIr** [comment]
Might work! I put the instructions to create new pips in the notes.txt file, I hope they're exhaustive enough, but feel free to ask for help!

**Comment by Zamiell** [comment]
done
