### ISSUE TITLE
Variant Idea: Shared Hand

### ISSUE THREAD

**Issue by joshkopen** [Zamiell/hanabi-live#785]
(As a preface, I recognize that this would probably be a bitch to code and would be really hard to create with the UI. However, I thought it was an interesting concept so I wanted to document it.)

In between each set of consecutive players, there is a shared card. This card is blind to both players who own the card and anyone else can clue it. Either player who the card belongs to can on their turn choose to either play/discard the card. When the card is played/discarded, a card is drawn from the deck to replace that individual card. Anytime a clue touches either players hand, it also touches the shared card.

For example, there are 3 players, Alice, Bob and Cathy. Alice and Bob share a card. Bob and Cathy share a card. Cathy and Alice share a card.

If there were 4 players (Alice, Bob, Cathy, and Donald), Alice and Bob share a card, Bob and Cathy share a card, Cathy and Donald share a card, and Donald and Alice share a card.

**Comment by rogers-j** [comment]
If we made no UI changes at all, the server would just need to specify 'that card' was included in the hands of both players, and would need to tell neither of them what it is when they drew it.

**Comment by Zamiell** [comment]
instant that would mess with the card possibilities feature, because it would see two blue 2s and then assume that all the blue 2s are visible

**Comment by Zamiell** [comment]
too hard to program, submit a pull request
