### ISSUE TITLE
Variant Proposal: NUMBER Suits & COLOR Suits

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#795]
### NUMBER Suits

- A **colorless** suit, each card shares with the **same number**. It can/must be played in any "order".

- It can be defined as a critical suit, which means there are only 5 **NUMBER** cards.

- There are 10 kinds of **NUMBER suits**:

1. NUMBER ONE suit (I call it _"CrazyOne_ suit")
2. NUMBER TWO suit (I call it _"CrazyTwo_ suit")
3. NUMBER THREE suit (I call it _"CrazyThree_ suit")
4. NUMBER FOUR suit (I call it _"CrazyFour_ suit")
5. NUMBER FIVE suit (I call it _"CrazyFive_ suit")
6. Dark NUMBER ONE suit (I call it _"Dark CrazyOne_ suit")
7. Dark NUMBER TWO suit (I call it _"Dark CrazyTwo_ suit")
8. Dark NUMBER THREE suit (I call it _"Dark CrazyThree_ suit")
9. Dark NUMBER FOUR suit (I call it _"Dark CrazyFour_ suit")
10. Dark NUMBER FIVE suit (I call it _"Dark CrazyFive_ suit")

- For example, the components of the variant _"CrazyTwo suit (4 suits)"_:

> Blue suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> Green suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> Yellow suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> CrazyTwo suit: 2, 2, 2, 2, 2, 2, 2, 2, 2, 2

- One interesting part of this variant: some of the current conventions might fail or look weird while playing CrazyNumber variants, like _Trash Chop Move_ (with a 1), _Self Finesse_ (with a 2), _Self 3 Bluff_, _Self 4 Double Bluff_, _5 Pull_, and so for.

### COLOR Suits

- A **rankless** suit, each card shares with the **same color**. It can/must be played in any "order".

- It can be defined as a critical suit, which means there are only 5 **COLOR** cards.

- There are 4 kinds of **COLOR suits**:

1. COLOR BLUE suit (I call it _"CrazyBlue_ suit")
2. COLOR BLACK suit (I call it _"CrazyBlack_ suit")
3. Dark COLOR BLUE suit (I call it _"Dark CrazyBlue_ suit")
4. Dark COLOR BLACK suit (I call it _"Dark CrazyBlack_ suit")

- For example, the components of the variant _"CrazyBlack suit (6 suits)"_:

> Blue suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> Green suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> Yellow suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> Red suit: 1, 1, 1, 2, 2, 3, 3, 4, 4, 5
> Black suit: 1, 2, 3, 4, 5
> CrazyBlack suit: k, k, k, k, k, k, k, k, k, k

- One interesting part of this variant: **_Black_** is a critical suit, while **_CrazyBlack_** is **NOT** a critical suit. Both of them are touched by a black clue. Might be fun to play.

**Comment by Zamiell** [comment]
>  It can/must be played in any "order".

sounds too easy

**Comment by iamwhoiamhahaha** [comment]
I don't think they are easy
