### ISSUE TITLE
remove the clues part of the status message

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#800]

**Comment by Zamiell** [comment]
@robertos can i close this now?

**Comment by robertos** [comment]
We haven't been using the clues for a little while. Maybe we need to test more edge cases like detrimental chars before nixing this

**Comment by Zamiell** [comment]
done

**Comment by robertos** [comment]
Nope, not done yet... https://github.com/Zamiell/hanabi-live/blob/card-reducer/server/src/table_notify.go#L142

**Comment by Zamiell** [comment]
closing this in favor of #710
