### ISSUE TITLE
Max score global stats are incorrect

### ISSUE THREAD

**Issue by jwngr** [Zamiell/hanabi-live#807]
First, just wanna say thanks for maintaining this thing! My friends and I play using it each week and it's a fun way for us all to stay in touch. So thanks again for your efforts!

I found an issue as I was looking at [the global stats page](https://hanabi.live/stats) earlier today. I just couldn't make sense of the max scores:

<img width="458" alt="Screen Shot 2019-11-25 at 10 06 16 PM" src="https://user-images.githubusercontent.com/4149793/69603520-d1291980-0fcf-11ea-86cd-0828f53336a1.png">

I was confused as to why "Total max scores achieved" was a fraction instead of an integer. And how is it possible all the player size variants have the exact same denominator? After digging into the code, I found [the] [problematic](https://github.com/Zamiell/hanabi-live/blob/39742b364b1ada9f3e185057e3484a0684d2ee7c/src/views/stats.tmpl#L44-L67) [files](https://github.com/Zamiell/hanabi-live/blob/39742b364b1ada9f3e185057e3484a0684d2ee7c/src/httpScores.go#L21-L24) and put together PR #808 for you to look at.

I apologize in advance for not following all of your setup instructions and getting things running locally. I've never used Go and honestly don't have the time right now to learn how to get it all set up on my machine and learn how to code properly in it. But hopefully the code is a useful starting point and someone can take it to the finish line.

Thanks again!

**Comment by Zamiell** [comment]
thanks ill take a look at it later

**Comment by Zamiell** [comment]
> I was confused as to why "Total max scores achieved" was a fraction instead of an integer. 

its not a fraction, it is just displaying to the user their total max scores and the "denominator" is the total possible max scores, so you can see how far you have to go

**Comment by Zamiell** [comment]
i feel that seeing the total amount of max scores achieved is worth having it on there. would you like it better if the data was just displayed on a different way?

**Comment by Zamiell** [comment]
e.g. how about instead of

> Total max scores achieved:     635 / 1490

it says:

> Total max scores achieved:     635 of 1490

or maybe:

> Max scores achieved:     635 of 1490 total

**Comment by Zamiell** [comment]
or maybe "635 (of 1490 total)"

**Comment by Zamiell** [comment]
or maybe "635 (of 1490 possible)"

**Comment by jwngr** [comment]
> it is not a fraction, it is just displaying to the user their total max scores and the "denominator" is the total possible max scores, so you can see how far you have to go

Ohh I think I understand now. This means the 298 denominator (and the 1490 for that matter) actually represent something meaningful. Are there 298 variants of the game, each which can be played with 2-6 players and each of which can have its own max score? If so, I think saying "635 of 1490 variants" or "635 of 1490 possible" would be clearer.

I ultimately got confused where the 298 number comes from. I think the text format for this data is not ideal (not enough info density) and a simple table may work better. Adding percentages also provides a bit more context between the two values:

|     | 2-player | 3-player | 4-player | 5-player | 6-player | Total |
|---|---------|----------|---------|----------|---------|-------|
| Possible max scores (all variants) | 298 | 298 | 298 | 298 | 298 | 1490 |
| Max scores achieved | 209 (70%) | 183 (61%) | 178 (60%) | 46  (15%) | 22 (7%) | 638 (43%) |

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/59fcea3213c85e9d40fdb446f95b529c79114381

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/commit/b3b913c4b4d08053b3525301877efd1c593fdbcc

**Comment by Zamiell** [comment]
i think this accomplishes what you want, so i will close this for now
