### ISSUE TITLE
Feature request: Display game time more accurately

### ISSUE THREAD

**Issue by fpvandoorn** [Zamiell/hanabi-live#816]
In speedruns, it would be nice to have a more accurate measurement of time in the game log. Showing 1-3 digits behind the decimal period would be good.

There was a time when 2 scores were tied for WR in 2p dark rainbow, and currently, there are 2 categories with only 1 second between 1st and 2nd place.

**Comment by aliblong** [comment]
I think the uncertainty on the actual time given server-client communication and load lag is greater than a second, so IMHO it's fine to round to the second and have tied records. Tenths of a second might also be ok, but any finer granularity than that would just be noise.

**Comment by Zamiell** [comment]
> I think the uncertainty on the actual time given server-client communication and load lag is greater than a second, so IMHO it's fine to round to the second and have tied records. 

i agree
