### ISSUE TITLE
Feature request: hidden vote to terminate

### ISSUE THREAD

**Issue by aliblong** [Zamiell/hanabi-live#818]
I think it would be valuable to be able to express one's desire to terminate a game in such a way that it is not communicated to the team unless a supermajority (say >=60%) agrees.

Basically, each player would have a "vote to terminate" switch that they could toggle on and off as they wish. If a supermajority ever have the switch toggled on, the game is terminated. This means information about the game state is not leaked when a player states a desire to terminate. Furthermore, this empowers us to move to a paradigm where players will not unilaterally terminate games (the nuclear option) against the will of the team. The nuclear option can and probably should still exist, since ultimately, a game's continuance relies on omnilateral participation; however, I think it will become socially unacceptable to use for reasons other than an emergency or "restart because someone else just showed up and wants to play".

**Comment by aliblong** [comment]
@jakestiles

**Comment by jakestiles** [comment]
In favor. :) Sometimes the majority of players wish to terminate but there’s currently no way to tell unless someone wants to so much that they are willing to speak up about it.

**Comment by Zamiell** [comment]
> click = VTK, possibly with timer, control + click = instant termination?

unfortunately, there is not room on the UI to add a separate button for VTK, so this suggestion seems reasonable to me.

**Comment by timotree3** [comment]
I would suggest that clicking the skull triggers the vote, and adds a visual indicator to the skull (e.g. a bright outline), and clicking subsequently triggers instant termination (coupled with the confirmation message for players with <1000 games)

**Comment by Zamiell** [comment]
agree with that

**Comment by DrAnax** [comment]
> I would suggest that clicking the skull triggers the vote, and adds a visual indicator to the skull (e.g. a bright outline), and clicking subsequently triggers instant termination (coupled with the confirmation message for players with <1000 games)

That's tricky given that the dialog will be a modal and clicking outside will either cancel the dialog (if it's cancellable) or do nothing (if it isn't).

how about showing something like:

![image](https://user-images.githubusercontent.com/2622043/143892542-76831a23-dc70-4398-b3db-84fa0dd8a706.png)

**Comment by Zamiell** [comment]
> That's tricky given that the dialog will be a modal

do we need to have a dialog for a VTK?
i dont think so.
by default, just have clicking it start a VTK.
reason: misclicking on the button in this case is far less destructive than a misclick causing a termination

**Comment by DrAnax** [comment]
Clicking will send a command to the server and in turn everybody will get a screen modal, similar to the paused dialog. How will the player be able to click again the skull and terminate immediately?

**Comment by Zamiell** [comment]
> Clicking will send a command to the server and in turn everybody will get a screen modal, similar to the paused dialog.

why does the player who clicked the button need to get a dialog? they already voted, so i presume that nothing further should show

**Comment by DrAnax** [comment]
So there won't be any immediate game termination anymore?

**Comment by timotree3** [comment]
I think there's a misunderstanding here. It sounds like you're saying that when you trigger a Vote To Kill, every player is asked to vote yes or no in that moment. My understanding was that during the game, each player can secretly declare that they want to kill, and if enough players do that, the game ends instantly.

**Comment by DrAnax** [comment]
> I think there's a misunderstanding here. It sounds like you're saying that when you trigger a Vote To Kill, every player is asked to vote yes or no in that moment. My understanding was that during the game, each player can secretly declare that they want to kill, and if enough players do that, the game ends instantly.

Now it makes sense

**Comment by Zamiell** [comment]
> hmm.. I guess what's missing in that proposal is that you can't cancel your vote

right click on a red skull icon to cancel

**Comment by DrAnax** [comment]
So what about the votes required? Is 50% or better ok? i.e. 1/2/2/3/3 for 2/3/4/5/6 people?

**Comment by Zamiell** [comment]
>= 50% seems fine

**Comment by DrAnax** [comment]
So the final proposal is:

- clicking on skull casts a vote, turns skull red (possibly with percentage indicator)
- right clicking on skull cancels the vote, turns back black (but retains the indicator if there are still votes)
- if votes reach or exceed 50% of people present, the game terminates

is that all?

**Comment by Zamiell** [comment]
> (possibly with percentage indicator)

i think better to show no percentage indicator

> right clicking on skull cancels the vote, turns back black (but retains the indicator if there are still votes)

no, that conveys information.
once you submit a vote, it should not be undone for the remainder of the game

**Comment by DrAnax** [comment]
> > hmm.. I guess what's missing in that proposal is that you can't cancel your vote
> 
> right click on a red skull icon to cancel

What about this then?

**Comment by timotree3** [comment]
We should definitely not display an indicators that other players have voted to kill unless the game is terminated. The whole point of the feature is to not leak information. 

> > right clicking on skull cancels the vote, turns back black (but retains the indicator if there are still votes)
>
> no, that conveys information.
> once you submit a vote, it should not be undone for the remainder of the game

Given that players have no way of telling who else is voting to kill, I don't see how cancelling a vote is a problem or conveys information. Is there some misunderstanding @Zamiell?

**Comment by Zamiell** [comment]
you're right, i guess it only conveys information if there is an indicator

**Comment by DrAnax** [comment]
By the way, why "right click to cancel" and not have it function as a toggle? Click to vote, click to un-vote

**Comment by Zamiell** [comment]
yea click to toggle seems fine

**Comment by Zamiell** [comment]
on second thought, right click has to be cancel, because left clicking again should force-terminate the game

**Comment by DrAnax** [comment]
> on second thought, right click has to be cancel, because left clicking again should force-terminate the game

Need a solution for mobiles as well; maybe right click to terminate (safer) and tap to change vote / dbl tap to terminate?

**Comment by DrAnax** [comment]
That's what I think as well: click / tap to change vote state, right click / dbl tap to terminate

**Comment by timotree3** [comment]
Seems good. We can have a tooltip on hover explaining this, right?

**Comment by Zamiell** [comment]
yeah, tooltip should explain both options

**Comment by DrAnax** [comment]
CLosed by #2310
