### ISSUE TITLE
Number Blind Number Clues Remove Card Possibilities

### ISSUE THREAD

**Issue by cvb2009** [Zamiell/hanabi-live#819]
Played a round of Number Blind (6 suits).  Every time a number was clued, the black square indicating that card was potentially that number was incorrectly removed.  If a card was hinted to not be four numbers, it came up as the fifth.  Multiple times, I attempted to make a correct play, and the pop-up came up that claimed I should know the card is not playable.

**Comment by Zamiell** [comment]
fixed, thanks
