### ISSUE TITLE
Bug: Spectators, under certain circumstances, are able to give clue during the game.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#823]
https://i.imgur.com/pDt5yP3.png

I was a spectator. Checked the console. No errors. This happened when I clicked "shared reply" while clue giver was not able to give clues.

I decided to did not give clues.

**Comment by hanabirnoob** [comment]
Update: Fortunately, the game still prevents non-players from giving clues. However, the HUD still remains.

**Comment by Zamiell** [comment]
fixed thanks
