### ISSUE TITLE
Alter the appearance of chiaroscuro pink and cocoa rainbow

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#827]
Currently, chiaroscuro pink looks exactly like light pink. And cocoa rainbow looks exactly like muddy rainbow.

Suggestion: Make chiaroscuro pink light pink/dark pink gradient. And cocoa rainbow a bit darker version of muddy rainbow.

Although currently it does not matter since chiaroscuro pink, light pink, muddy rainbow and cocoa rainbow do not appear with other special suits.

[edit: Whoops. Typo in title.]

**Comment by Zamiell** [comment]
done thanks to sasha
