### ISSUE TITLE
Variant Proposal: Invisible Suit

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#831]
Variant Proposal: Invisible Suit

A colorless suit, where the identity of the card cannot be seen until the rank clue which matches the rank of card is given.

**Comment by jakemrtz** [comment]
What are the differences between this and white?

**Comment by iamwhoiamhahaha** [comment]
The main difference is the rank of the card cannot be seen by all players until it is touched accidentally

**Comment by Zamiell** [comment]
sounds not fun because you would have to save every card like a 5, or something
