### ISSUE TITLE
Lobby continues updating behind game canvas

### ISSUE THREAD

**Issue by jthemphill** [Zamiell/hanabi-live#834]
I felt like my battery drain while playing Hanabi was higher than it needed to be. I opened the Developer tools and saw messages like

```
Received table:
{id: 271, name: "Shared replay for game #72587", password: false, joined: false, numPlayers: 5, …}
```

appearing every second in my console.

I also ran a performance profile while waiting for my dad to make a move (and therefore while I was looking at a static screen), and found that quite a lot of time was being spent mucking around with the `#lobby-games-table-tbody` HTML element. Some grepping revealed that this is the original hot code:

https://github.com/Zamiell/hanabi-live/blob/62313a090c403e5db8714c9a03d085f0d1ffd814/public/js/src/lobby/tablesDraw.ts#L10

Based on what I've seen, I believe we're spending a fair amount of CPU time (and therefore battery life) updating information in the lobby even when we're in game. Hopefully this fix is as easy as adding a boolean to disable these lobby redraws when we're in game :smile:

Anyway, thanks for reading this bug report, and thanks for taking this project on! This site's UI is, bar none, the most user-friendly UI I've seen for any board game ever.

**Comment by Zamiell** [comment]
fixed in commit https://github.com/Zamiell/hanabi-live/commit/534f04f9e4394c7fc8828653f5bd82fcbc91ee35
