### ISSUE TITLE
Mousedown on teammate's card doesn't always cross off known public info

### ISSUE THREAD

**Issue by jthemphill** [Zamiell/hanabi-live#835]
In this screenshot, I'm currently holding the mouse down on lilbugger's cards. Note that the red suit is not crossed off on either of lilbugger's 5s, even though the red 5 has already been played.

<img width="1680" alt="hanabi-bug" src="https://user-images.githubusercontent.com/887446/71434543-e611cf00-2699-11ea-8f76-330a78b0a9fc.png">

**Comment by Zamiell** [comment]
What is the game id

**Comment by jthemphill** [comment]
Game ID 72589

**Comment by Zamiell** [comment]
fixed
