### ISSUE TITLE
Variant Proposal: Special Mix

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#836]
### Special Mix (7 Suits)
A variant with Black, Rainbow, Pink, White, Brown, Omni, and Null Suits.

### Special Mix 2 (6 Suits)
A variant with Rainbow, Pink, White, Brown, Omni, and Null Suits.

**Comment by hanabirnoob** [comment]
Does the game currently support more than 6 suits? If not, how easy it is to implement it?

**Comment by Zamiell** [comment]
no it doesn't support 7 suits, its hard to implement because i have to recode a bunch of bullshit in the ui

**Comment by Zamiell** [comment]
wont implement Special Mix (7 Suits)

Special Mix 2 (6 Suits) is probably too similar to the other special mix
