### ISSUE TITLE
Variant proposal: Hard to Clue Hands

### ISSUE THREAD

**Issue by jakestiles** [Zamiell/hanabi-live#850]
Variant 1 - Invisible Slot 1: Slot 1 is not part of a player's hand for the purposes of cluing. E.g. If Alice has a green 5 in slot 1 and no other 5s, then 5 may not be clued to Alice, and if green is clued to Alice touching other green cards in Alice's hand, then green 5 will not be touched. Perhaps there could be a bit of space or a divider between slot 1 and the other slots to help show this.

Variant 2 - Double Handed: A player's hand is divided in half (or as close to possible for odd numbers of cards) into two hands shown right next to each other (with a small space or divider between). When a clue is given, it can be given to only one "hand" of a particular player at a time. So if Alice has: G4 B5 G1 Y2, then green/blue/four/five could be clued to Alice's left hand and the green clue would not touch the G1 in Alice's other hand.

**Comment by Zamiell** [comment]
how does variant 2 work in 5 card hands / 3 card hands

**Comment by jakestiles** [comment]
Divide as evenly as possible. So 2/3 cards and 1/2 card. RE the only other obvious solution: I don’t think having one of the cards in both hands makes sense with the name/concept “double handed.”

**Comment by Zamiell** [comment]
i think im going to veto this due to it not sounding very fun
