### ISSUE TITLE
Discard area can stack a suit too closely in colorblind mode

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#854]
Sample game: 84181
![image](https://user-images.githubusercontent.com/5349111/75955552-eb924f00-5e6a-11ea-907c-a5b9af4da172.png)

**Comment by ddugovic** [comment]
For example game 84181 - demonstrated at https://clips.twitch.tv/EasyPluckyVanillaKappaRoss

**Comment by Zamiell** [comment]
how to fix it though

**Comment by Zamiell** [comment]
i guess i'll reverse the order, e.g. B2 --> 2B
