### ISSUE TITLE
Optional disable cross-out UI

### ISSUE THREAD

**Issue by squidgetx** [Zamiell/hanabi-live#859]
It would be cool to have a mode that disables the cross-out UI that appears when all copies of a card/number are visible, requiring the players to card count on their own. Even though it's a relatively trivial task I find the extra mental step of card counting leads to more satisfying game-play when you're able to utilize it when playing hanabi with the actual cards/tokens.

I'm happy to implement it and submit a PR depending on the best way people feel like it should be implemented (eg, is it necessary to make it a separate variant for stat-keeping purposes (heavy) or is it fine to just have a checkbox when setting up the game)

**Comment by Zamiell** [comment]
this already exists, enable "Real life mode" in the options
