### ISSUE TITLE
feature request: allow shading of unplayable cards in clued hands

### ISSUE THREAD

**Issue by tsvikas** [Zamiell/hanabi-live#865]
Currently, when looking and another player's cards, the UI automatically shadows unplayable cards and gives a golden border to clued cards.
Clued unplayable cards have a golden border and are unshadowed.
I would expect such cards to have a golden border and still be shadowed. Personally, it'll help me recognize cases of "need to un-hint about a card somehow".
It seems that the current UI is aimed at players who use the "good touch principle", but players might be hindered from trying other methods by this visualization.

Could it be possible to add a toggle option for this, in the player settings?

**Comment by Zamiell** [comment]
it is a reasonable request, but every checkbox in the lobby options has a cost associated with it, and i don't want to bloat the website with options that not a lot of people are going to use.

if you enable "Real Life Mode" in the options, then no cards will be faded (or "shadowed", as you put it).
i recommend that you enable that option if you consider the current behavior to be confusing or detrimental

**Comment by tsvikas** [comment]
Thanks for the reply. I understand the bloating cost.
(I find the idea if shading comfortable, so your solution is not what I wanted.)
Can I suggest leaving this issue open, and tracking how many users will find this option needed? If it'll be useful to many, maybe you could re-consider it.

And again, thanks for the reply, and the great server:).

**Comment by Zamiell** [comment]
yes you can leave it open

**Comment by tsvikas** [comment]
(BTW, I'm also OK with using the UI suggested above for everyone, without any option to toggle it off. But I guess it's been like that for a reason)

**Comment by Zamiell** [comment]
when fading was first implemented, there was no exception for clued cards, but it caused lots of misplays and lots of general confusion, so we fixed it shortly thereafter

**Comment by Zamiell** [comment]
no other users seem to be interested in this, so i'll close the issue now
