### ISSUE TITLE
feature request: different color for the "most recent clue" for each player

### ISSUE THREAD

**Issue by tsvikas** [Zamiell/hanabi-live#866]
Would it be possible to add a toggle in the player-settings that will make the UI use a slightly different color for the border of cards who were part of the most recent clue each player got?

I find it comfortable to highlight the most recent clue, in my hand, and other players' hands

**Comment by Zamiell** [comment]
that's what the coloring of the arrows is for

**Comment by tsvikas** [comment]
Don't the arrows disappear after the next turn? I meant for something more lasting. (But I understand if it's not the most needed enhancement)

**Comment by Zamiell** [comment]
why do you need something more long lasting? so that you know they are going to play the card, or something?

**Comment by Zamiell** [comment]
closing this since tsvikas isn't responding
