### ISSUE TITLE
Hanabi Competitive Mode

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#879]
### Setups

- Can only be played with 4 (or 6) players. The players are divided into two teams and each player is sitting opposite his partner.

- Place two decks with same components on the table. Given one deck to each team.

- Each player draws 5 cards (4 in 6 player) from the deck at the start of the game.

- Given 4 clue tokens to each team.

- No _strike tokens_ bank.

- Only one stack for each color.

### Rules

- Successfully play a matching card: **Your team gains 2 points**

- Misplay a card: Nothing happens

- Give a clue to your _"partner"_: **The opponent gains 1 point**

- Give a clue to your _"opponent"_: Nothing happens

- Discard a card: **Your team gains 0.5 clue tokens**

### End Game

- The first team who draws the last card triggers the end game.

- The team who gains the most point at the end of the game wins.

**Comment by iamwhoiamhahaha** [comment]
### Hanabi Competitive Mode (version 2)

### Setups

- Can only be played with 4 players. The players are divided into two teams and each player is sitting opposite his partner.

- Place two decks with same components on the table. Given one deck to each team.

- Given 4 clue tokens to each team.

- No strikes bank.

- Only one stack for each color.

### Rules

- Successfully play a matching card: **Your team gain 3 points**

- Give clues to your _partner_: **The opponent gain 1 point**

- Discard: **Your team gain 1 clue token**

- The first team who draws the last card triggers the end game.

- The team who gains the most point at the end of the game wins.

**Comment by Zamiell** [comment]
too hard to program
