### ISSUE TITLE
Unify waiting list and Discord notification systems

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#88]
We have two systems that do not complement each other:
 * Users join and check the waiting list and get notified when others make tables. This is not always perfect because different groups use the same server and use the same queues, tables.
 * Users mention everyone `@here` on Discord, then decide what kind of table to make depending on who shows up.

Proposed new system:

`/here` commands the bot to send `@here` into the general channel if it hasn't been used recently, and also directly mention the people on the list regardless.

  - The person who uses the command knows who might join because of the individual mentions
  - Users have the option to suppress `@here` in the channel
  - This is always always a single message, so some people might be mentioned once implicitly and once explicitly, but that does not make Discord do anything exceptional

This *replaces* the messages when new tables are made, so this command should empty the waiting list.

Proposed message, optimized for the users receiving the notification:
`{name} wants to play. Anyone @here? @Ahming @bradz @cubegoldberg @Doge`
or, if the last use is recent, omit the `@` before here.

- [ ] The command can be used from the server chat, where users might not be able to determine when the last `@here` was sent (and making anyone do that seems wasteful)
- [ ] Remove the ability of most users from using `@here` in the general channel afterwards

**Comment by Zamiell** [comment]
i think this is done?
