### ISSUE TITLE
Pink and light pink have the same letter notation in colorblind mode.

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#882]
They also have the same symbol.

**Comment by SashaIr** [comment]
I guess the same happens for Rainbow & Muddy Rainbow.

**Comment by Zamiell** [comment]
@iamwhoiamhaha

**Comment by Zamiell** [comment]
i dont want to change the abbreviation. get fucked if you are colorblind i guess

**Comment by iamwhoiamhahaha** [comment]
im fine without adding those variants now. at least there are thousands of variants can be hunt. but i'll propose it again after finishing all the other scores in 2p
