### ISSUE TITLE
empathy sucks in Null-Ones & Pink

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#883]
The card on my slot 4 is negative red from previous clue; however, the empathy shows it could be a red card.
![empathy sucks 1](https://user-images.githubusercontent.com/50160641/77760333-1ee28b00-7071-11ea-9b93-3a76b5c6f3c2.png)

![empathy sucks 2](https://user-images.githubusercontent.com/50160641/77760446-52bdb080-7071-11ea-8310-0ab56b133f97.png)

I'm not sure which variants have the same problem.

**Comment by Zamiell** [comment]
should be fixed now
