### ISSUE TITLE
Limit default variant list to standard suits

### ISSUE THREAD

**Issue by rogers-j** [Zamiell/hanabi-live#889]
The standard suits are: the base five colors, rainbow, and black.

There should be a setting to show any variants with suits other than these.

(By this construction, the variants with more/fewer suits total are defaults, rather than hidden.)

The 'random variant' option should respect this setting.

**Comment by hanabirnoob** [comment]
Alternatively, have two dice symbols: One with standard variants and one with all variants.

**Comment by rogers-j** [comment]
The point isn't the random behavior; that's a consequence. The point is for most people to not be bewildered.

**Comment by Zamiell** [comment]
i rewrote the variant dropdown (again)
play around with it and let me know if you find any bugs
