### ISSUE TITLE
Empathy in Muddy-Rainbow-Fives & Brown is broken

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#890]
Look at my brown 4 it has negative 4
![brown empathy sucks](https://user-images.githubusercontent.com/50160641/77816401-6a427b00-70fd-11ea-990b-179e81b57d00.png)
![brown empathy sucks 2](https://user-images.githubusercontent.com/50160641/77816404-6c0c3e80-70fd-11ea-8154-12002210ea1c.png)

**Comment by Zamiell** [comment]
fixed

**Comment by Zamiell** [comment]
id is 99551
