### ISSUE TITLE
Spectators view empty notes for un-noted players when any note is available

### ISSUE THREAD

**Issue by Tempus** [Zamiell/hanabi-live#9]
Severity: Moderate
Encounter rate: Common

Issue:

On mousing over any note, a spectator sees empty note entries for all players who have not entered a note. ie.

Instantiation:
Zamiel: I am the only one who has made a note
Libster:

Repro:

1. Begin any game of Hanabi
2. Have a third party spectate
3. Have any player create a note on any card
4. Spectator mouses over note

Expected:

Notes only show the relevant players who have left notes

ie.
Zamiel: I am the only one who has made a note

Issue does not occur while spectating reviews as of yesterday.

**Comment by Zamiell** [comment]
fixed thanks
