### ISSUE TITLE
Note box is not dismissed by left-click in some cases

### ISSUE THREAD

**Issue by erinboyle** [Zamiell/hanabi-live#905]
sometimes this box shows up and we can't get rid of it!  any tips? or is it an actual issue?

![image](https://user-images.githubusercontent.com/12789116/78104858-bcf19080-73a4-11ea-9abb-9e0931958676.png)

**Comment by rogers-j** [comment]
The note box. Are you unable to click away to dismiss it?

**Comment by rogers-j** [comment]
What about the escape key?

**Comment by erinboyle** [comment]
Ok : reporting from my sister who actually experienced it, but nowhere she clicked made it go away. She didn't try escape!

**Comment by rogers-j** [comment]
The bug is easier to repro than I thought:

1. open a note
2. rewind back to an earlier turn
3. observe how clicking takes focus from but does not hide the box
4. right-clicking another note closes the lingering one, as does the escape key

**Comment by erinboyle** [comment]
Ok! Sounds like we can fix this with right click and escape. Want me to close the issue or do you plan on working on left click?  Thanks for the help! :)

**Comment by rogers-j** [comment]
Leave the issue; it is a real bug.

**Comment by Zamiell** [comment]
is this really a bug? if you open a note box, partially type something in, and then decide to go back in time to do some further investigation before finishing the note that you were typing in, then it seems to me that you would want the note box to 1) stay open and 2) not delete your partially typed note.

**Comment by rogers-j** [comment]
If the user is clicking on something, like the replay UI or viewing a card, that's one thing. But clicking the background doesn't do anything else. It seems like that's the handler that's being unregistered.

**Comment by Zamiell** [comment]
i guess i could register a handler on the background. seems like kind of a weird "solution" though

**Comment by rogers-j** [comment]
Isn't there something already?

**Comment by rogers-j** [comment]
Alternatively, we could say that clicking out of the box never dismisses it, and it always needs a key to leave (or starting to edit a different note)

**Comment by Zamiell** [comment]
> Alternatively, we could say that clicking out of the box never dismisses it, and it always needs a key to leave (or starting to edit a different note)

well, that is the way it currently works, afaik.

> sometimes this box shows up 

well, it is not supposed to just "show up". it is supposed to show up when you deliberately right click on a card. @erinboyle were you accidentally right clicking on a card, or something? i dont think it is possible for the note box to appear otherwise.

**Comment by rogers-j** [comment]
Oh, you're right, that is how that works. I take back what I said about background.

**Comment by erinboyle** [comment]
> well, it is not supposed to just "show up". it is supposed to show up when you deliberately right click on a card. @erinboyle did your sister accidentally right clicking on a card? i dont think it is possible for the note box to appear otherwise.

she says yes it was a click, and she thinks it could have been a right click since there's a two-finger tap shortcut on the mouse trackpad that's feasible. but she's not positive.

**Comment by Zamiell** [comment]
background now listens on master
