### ISSUE TITLE
Access all game histories

### ISSUE THREAD

**Issue by aalok-sathe** [Zamiell/hanabi-live#908]
Is there a way to access all game histories of all games played online (or however many that are stored in your database)? I'm a board games enthusiast and this would be for small-time research as a college project towards building a baseline Hanabi AI. Could be integrated into this project someday.

**Comment by Zamiell** [comment]
easily? no

but database ids are sequential. so you can just send a replayCreate command for IDs 1 through N

**Comment by Zamiell** [comment]
and make sure to throttle it quite a bit so that you dont kill my web server = )

**Comment by aalok-sathe** [comment]
of course! i will take care of that. how do i send that command?

**Comment by Zamiell** [comment]
you'll have to write a script to emulate a browser client, login to the websocket server, etc

**Comment by Zamiell** [comment]
closing this as access to the database won't be officially supported
