### ISSUE TITLE
Replays of the certain variants break the client

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#910]
107035 Is Throw it In a hole & white variant. When trying to watch the replay of this (using replay finder), it doesn't let me. In fact, attempting to view it makes me unable to watch any other replays and it also breaks the lobby chat. Seems that throw it in a hole&white breaks something.

Also, this variant has an issue that score counter is a bit off when the game is complete (but it fixes itself in replay)

**Comment by iamwhoiamhahaha** [comment]
i cant even see it in show history

**Comment by Zamiell** [comment]
fixed thanks

**Comment by Zamiell** [comment]
definitely fixed now
