### ISSUE TITLE
Move termination button away from chat, lobby buttons

### ISSUE THREAD

**Issue by hedgepiggy** [Zamiell/hanabi-live#912]
I fat fingered it a few times on my desktop, ending the game immediately instead of opening chat lol

possibly an additional confirmation prompt might work at the expense of an extra click

**Comment by Zamiell** [comment]
telling me to "move it away" is unhelpful
where specifically are you proposing that it gets moved to

**Comment by padiwik** [comment]
I think the best solution is an option for a confirmation prompt which is on either by default or in all non-speedrun games. I have accidentally hit the restart button when reviewing, which is a similar issue to accidentally terminating a game. If there's enough interest, I might submit a PR.

**Comment by iamwhoiamhahaha** [comment]
same here. both terminating a game accidentally and restarting a game while review

**Comment by Zamiell** [comment]
added confirmation box, i will delete it if it gets annoying though
