### ISSUE TITLE
Sometimes clicking on played cards in hypothetical mode causes the game go nuts

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#920]
![image](https://user-images.githubusercontent.com/49693470/78651633-43d4ca80-78c9-11ea-90fa-cff6a662060c.png)

Especially when back button is pressed. I can't do it consistently though.

**Comment by Zamiell** [comment]
what do you mean "Sometimes clicking on played cards", like getting empathy on played cards?

**Comment by hanabirnoob** [comment]
Well, clicking on cards in the stacks that are supposed to rewind the game..

Seems it happens if you've dragged a card into a play when it doesn't connect (For an exmple, when you've dragged yellow 1 on yellow 4).

**Comment by Zamiell** [comment]
oh i see

**Comment by Zamiell** [comment]
should be fixed now after server restart
