### ISSUE TITLE
game chat

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#925]
i started typing in pre-game chat. should i see this?
![2020-04-08_23-11-43](https://user-images.githubusercontent.com/46625461/78919733-02941480-7a9b-11ea-8ef8-4bbeebd43c20.png)

**Comment by Zamiell** [comment]
did you start typing at the exact same time valetta did?

**Comment by iamwhoiamhahaha** [comment]
have the same issue but not a big problem for me to bring it up here

it happens if someone is typing and you leave the game joining another game

**Comment by Zamiell** [comment]
chat.mp4

**Comment by Zamiell** [comment]
should be fixed now
