### ISSUE TITLE
White-Fives and Cocoa Rainbow

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#926]
Broken empathy, the same problem as in pink-ones and brown
![2020-04-08_23-29-47](https://user-images.githubusercontent.com/46625461/78920039-7cc49900-7a9b-11ea-9e23-6406c3ef87af.png)

**Comment by Aigul9** [comment]
![2020-04-09_21-42-06](https://user-images.githubusercontent.com/46625461/78929489-27908380-7aab-11ea-95ce-7eb9e3f42229.png)
![2020-04-09_21-40-51](https://user-images.githubusercontent.com/46625461/78929505-2e1efb00-7aab-11ea-974c-43897b18fb7d.png)

**Comment by Zamiell** [comment]
should be fixed on next restart
