### ISSUE TITLE
Hypothetical clue giving: Rightmost player corresponds to uppermost one on BGA layout

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#928]
For giving clues in hypothetical in BGA layout,

Rightmost player in clue giving interface corresponds to uppermost one.
Leftmost one corresponds to second uppermost one.
And so on until second-to-last player corresponds to lowermost one.

Should it be changed so leftmost player corresponds to uppermost one and so on until rightmost player's name corresponds to lowermost one?

**Comment by Zamiell** [comment]
fixed after next restart
