### ISSUE TITLE
special sound effects

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#933]
1) Special sound effect when discarding in a double discard situation (not implemented yet)
2) Special sound effect when discarding a clued card (not implemented yet)
3) Special sound effect when playing a 1 out of order (not implemented yet)

**Comment by Zamiell** [comment]
4. Special sound effect for when a double discard situation is initiated

**Comment by efaust** [comment]
These look like great options! Are you gonna hide them behind the hyphenated options flag, or do you have another plan? I think, now, with the amount of hyphenated features, it might make sense to start giving users some configurability, as a long term goal? What do you think?

**Comment by Zamiell** [comment]
> Are you gonna hide them behind the hyphenated options flag, or do you have another plan?

yes they are all gated behind that checkbox

> it might make sense to start giving users some configurability, as a long term goal?

not sure what you are specifically suggesting

**Comment by Zamiell** [comment]
done
