### ISSUE TITLE
Suggestion on Discord Categories

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#936]
So I've noticed some players who have more than 1+ years experience not listed as a purple player on Discord.  I've also seen some players, Fireheart for example, who accumulated 3k+ games in 3 months, so I feel it's safe to say there are some players who have more experience than players who have been playing for 1+ years.  

From my understanding, Purple players are considered "staff."  I assume this because purple players have extra privileges, such as being able to move players in the voice channels.   

Proposal:  
1. Make a separate category for just staff.
2. Change the category to "# of games played," instead of what we have now.  We probably could go further and set it to "# of total max scores," as this would indicate how proficient a player is at playing other variants.  

The category can be changed depending on what players feel would separate one player from another.  For Example:
- Novice/Beginner 
We can change "Some Experience" to be "100+ games." 
- Intermediate 
Next Category would be "1k+ games," for example.
- Expert
2nd Category for "2k+ games," etc.
- Professional.  

The added benefit is that it would make it easier to find players who have a certain experience level to game with.  This would also make it easier for players to request to be bumped up in rank.  Right now it's sort of Gray because asking to be bumped up to purple is the same as asking for staff, when the player really just wants to be recognized as a higher level player than where they are currently at.

I'm not really sure how staff privileges work, but it would be nice to give staff the option to move players to separate categories so that 1 person isn't organizing all the players.

**Comment by Zamiell** [comment]
> So I've noticed some players who have more than 1+ years experience not listed as a purple player on Discord.

who?

> From my understanding, Purple players are considered "staff."

purple players have administrative privs in the discord server, yes

> The added benefit is that it would make it easier to find players who have a certain experience level to game with.

the current discord ranking system is a compromise between having no ranks at all (what I prefer) and having 3 ranks (what libster prefers). thus, I am currently not in favor of making it any less egalitarian than it already is.

typically, if you want to play a game with the hyphen-ated group, the flow is as follows:

1) there is usually a voice channel filled with hyphen-ated group members that are already playing
2) you join the voice channel alongside them and wait for the current review/game to end
3a) if there are 5 or less players remaining, then you hop into the next game with the remaining players, regardless of the current skill level of those players.
3b) if there are 6 or more players remaining, then you split into two groups based on either skill level or if certain specific people want to play together.

more rank granularity would not help with 3a. it would help with 3b if you were not already familiar with the skill level of all of the players in the group. on the other hand, the size of the group is quite small, and most people have a general understanding of the skill level of where everybody is at, so it may not be necessary.

**Comment by Aigul9** [comment]
i know that Jeff joined in february, 2019.

**Comment by Zamiell** [comment]
jeff has purple role now

**Comment by Zamiell** [comment]
closing since kakashi isn't replying
