### ISSUE TITLE
Broken detrimental characters

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#937]
![2020-04-12_20-33-32](https://user-images.githubusercontent.com/46625461/79076632-57869380-7d04-11ea-8fce-ce41d8399353.png)
The character with palette gives a clue after playing a card (9 clues???). 
Also when i tried to watch the game again, i had an error (index 0, 1 and 3), my screen became green, and all characters were changed:
![2020-04-12_21-24-53](https://user-images.githubusercontent.com/46625461/79076700-e72c4200-7d04-11ea-9eb2-d11f4c1b3936.png)
There is some strange arrow (quack):
<img width="958" alt="2020-04-12_21-07-40" src="https://user-images.githubusercontent.com/46625461/79076790-7df8fe80-7d05-11ea-9a2d-a8363c867813.png">

**Comment by Zamiell** [comment]
> There is some strange arrow (quack):

thats intended, quacks don't tell color or rank information

**Comment by Aigul9** [comment]
arrows in a regular duck game don't show any numbers

**Comment by Aigul9** [comment]
P.S. all played games end on turn 1-3

**Comment by Zamiell** [comment]
> arrows in a regular duck game don't show any numbers

right, so the arrows are supposed to be like the arrows in a normal duck game

**Comment by Zamiell** [comment]
should be fixed after next server restart, reopen if not fixed
