### ISSUE TITLE
Logo Proposal for Hanabi-live

### ISSUE THREAD

**Issue by Jeims01** [Zamiell/hanabi-live#94]
Hellow @Zamiell 
 I would like to help you to do your project, I can create a logo that represents your repository or company.

I like to collaborate with open source projects and polish my skills

**Comment by Zamiell** [comment]
Our logo is here:
https://raw.githubusercontent.com/Zamiell/hanabi-live/master/public/img/hanabi-logo-full.png

If you think you can do better than that, by all means.

**Comment by Zamiell** [comment]
The project is about a card game. You can read the [README file](https://github.com/Zamiell/hanabi-live/blob/master/README.md) to learn about it.

We don't need a specific color, but as you can see, the background is green, so it would be nice to look good on a green background.

**Comment by Jeims01** [comment]
ok perfect soon I will be presenting my proposal

**Comment by Jeims01** [comment]
Hi @Zamiell 
sorry for the delay, here is my proposal.
You can modify anything you want.
![logotipo hanabi live 2018](https://user-images.githubusercontent.com/41645441/43607994-fc6fcf58-966d-11e8-9206-dfce56c14c12.png)

**Comment by Zamiell** [comment]
Holy shit, I really like #2.
What does @RaKXeR @rogers-j @fpvandoorn @aliblong think?

**Comment by Jeims01** [comment]
@Zamiell   let me know which one you like the most to perform the pull requests

**Comment by fpvandoorn** [comment]
I also really like 2.

**Comment by Zamiell** [comment]
@Jeims01 It sounds like we like #2 the best. Thank you so much for your work!!! It is very nicely done. You can post the original, high resolution versions of the logos in this thread, or you can make a pull request yourself, it is up to you.

**Comment by Jeims01** [comment]
ok @Zamiell   soon I'll pull requests and add a drive with the editable files
