### ISSUE TITLE
Alert for "my turn"

### ISSUE THREAD

**Issue by lybeck** [Zamiell/hanabi-live#942]
It would be nice to have some kind of feature to remind the player that it is their turn. At least in casual games people sometimes forget to follow the flow of the game and don't realize that it is their turn. Some kind of setting to toggle visual and audio clues for the players when their turn starts would be useful.

**Comment by Zamiell** [comment]
there is already an audio notification for when it is your turn, right?

**Comment by NoAnni** [comment]
To be honest, I have been asking myself for several days why sometimes there were different sounds, and I discovered that it was a "your turn alert" just a few hours ago (by reading the file's name); so it probably isn't common knowledge.

**Comment by rogers-j** [comment]
There is a setting to 'play a sound when a move is made', and one of the sounds is unique to it being your turn. However, this makes _a_ sound on every turn, not just yours.

**Comment by Zamiell** [comment]
@lybeck i added a new setting called "Show a desktop notification when it reaches your turn"
does that solve your issue?

**Comment by lybeck** [comment]
I think it sounds great! I haven't tested it myself yet, but I assume it works as described.

**Comment by Zamiell** [comment]
ok reopen a new issue if this doesn't solve the issue
