### ISSUE TITLE
!replay command crashes when used and turn argument doesn't do anything

### ISSUE THREAD

**Issue by RaKXeR** [Zamiell/hanabi-live#945]
Games started with the "!replay" command crash the client, forcing a refresh. The table is indeed created with the correct seed, however, regardless of which turn was specified on the 2nd argument, it always starts with no actions taken.

**Comment by Zamiell** [comment]
what game id / turn did you use

**Comment by Zamiell** [comment]
nevermind, should be fixed now (after the server restarts).
