### ISSUE TITLE
6-card rewind error

### ISSUE THREAD

**Issue by hanabirnoob** [Zamiell/hanabi-live#949]
![image](https://user-images.githubusercontent.com/49693470/79278752-0d90df80-7eb5-11ea-99f7-97c692e79fea.png)

Started spectating and then holding down the rewind key. This happened.

**Comment by Zamiell** [comment]
> and then holding down the rewind key

what does that mean?

**Comment by hanabirnoob** [comment]
Basically, I held down left arrow key.

**Comment by Zamiell** [comment]
im holding down the left arrow key and then spectating games, and im not able to reproduce

**Comment by Zamiell** [comment]
are you?

**Comment by hanabirnoob** [comment]
Seems it was a rare one-time thing.

**Comment by Zamiell** [comment]
can't reproduce
