### ISSUE TITLE
public/css/main.min.css and js/dist/main.2989.min.js

### ISSUE THREAD

**Issue by hengyuan-hu** [Zamiell/hanabi-live#951]
Hey thanks for open sourcing this repo. I am trying to set up a server on my own linux machine. When I access the web from a cline through http, the login page is messed up and chrome shows that `js/dist/main.2989.min.js` and `js/dist/main.2989.min.js` are not found. I attached a screen shot here.

<img width="1674" alt="Screen Shot 2020-04-14 at 6 11 26 PM" src="https://user-images.githubusercontent.com/4728165/79288405-7ce9dd80-7e7b-11ea-840a-99b7946a70d0.png">

Any help would be greatly appreciated!

**Comment by Zamiell** [comment]
did you make min.min.css and main.min.js?

**Comment by hengyuan-hu** [comment]
Ah thanks for the pointer. The build process for the client code failed for a machine specific problem. Will check it on a different machine and re-open if the problem persists.
