### ISSUE TITLE
Bug Detrimental Characters

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#955]
![2020-04-17_0700_001](https://user-images.githubusercontent.com/48993588/79582660-e5ee7280-8080-11ea-90d9-5b111f2fdc5c.png)
![2020-04-17_0711](https://user-images.githubusercontent.com/48993588/79582572-ceaf8500-8080-11ea-9dee-b5fbf6eceb3a.png)
![2020-04-17_0711_001](https://user-images.githubusercontent.com/48993588/79582584-d2430c00-8080-11ea-8a83-4a5948bd5661.png)

So this bug is with #25 - Synesthetic
Whenever this character is chosen when players discard it adds a clue.  When the Synesthetic player discards it adds 2 clues.
Whenever Synesthetic plays a card it adds a clue.

**Comment by Zamiell** [comment]
char 25 was removed, so ill close this now
