### ISSUE TITLE
Bug with Cycling Cards

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#956]
![2020-04-17_0801](https://user-images.githubusercontent.com/48993588/79583299-c9066f00-8081-11ea-89ab-9262be80123a.png)
![2020-04-17_0801_001](https://user-images.githubusercontent.com/48993588/79583303-cad03280-8081-11ea-8cdc-c954f81b9601.png)

Edit: Sorry for not stating the issue.  It's with Floriman's hand.  It looks like it didn't cycle properly after his turn.

**Comment by Zamiell** [comment]
you opened an issue that says "bug with cycling cards".
what is the bug

**Comment by SashaIr** [comment]
I guess B4 moved on slot 2 instead of slot 1?

**Comment by iamwhoiamhahaha** [comment]
I believe it's because Floriman is Synesthetic (Must clue both a number and a color of the same value (uses 1 clue)). It looks like he gave two clues by spending only one token.

**Comment by Zamiell** [comment]
Synesthetic character is removed, reopen a new issue if you see it happen again
