### ISSUE TITLE
New Variant: 7 Pile 

### ISSUE THREAD

**Issue by Dr-Kakashi** [Zamiell/hanabi-live#965]
https://en.boardgamearena.com/group?id=2487062

So some players brought over this variant.  I was wondering if you would be interested in adding this?  Technically, it doesn't need to be because we can manually do it, but it would be awesome to have on this site officially.  

The variant works like this.  For 6 suit we will set the trash as the 7th pile, where teal must be discarded in the order of 11234.

In a 6 pile variants, it's 5 suit where trash is the 6th pile. Purple needs to be discarded in the order of 11234.

**Comment by Zamiell** [comment]
just do it manually for now

**Comment by iamwhoiamhahaha** [comment]
i've told you kakashi, zamiel wont approve it
