### ISSUE TITLE
label on color clues

### ISSUE THREAD

**Issue by tyrcho** [Zamiell/hanabi-live#975]
Hi,

First time on the site today. Really well done ! (I'm a regular on BGA).

One small improvement would be to label the clues with the same icons. I'm color-blind and it took me some time to figure out which color clue to give !

And maybe to mark clearly when it's my turn to play. For the first game I kept looking for this information, I only saw it when it was the other player's turn.

**Comment by Zamiell** [comment]
> One small improvement would be to label the clues with the same icons. 

i dont understand this request, you mean inside of the circles?

note that on hanabi live, colors are distinct from suits. this is because we regularly play with various dual-color variants, where one suit is touched by two separate colors. give it a try and see what i mean.

> I'm color-blind and it took me some time to figure out which color clue to give !

do you have the color blind mode enabled?

> And maybe to mark clearly when it's my turn to play.

what specifically do you suggest

**Comment by tyrcho** [comment]
about the clues :

![image](https://user-images.githubusercontent.com/700260/80138161-b1a91380-85a4-11ea-87ca-655857caae68.png)

it took me some time to make the link between which clue I can give and which zone cards are to be played.

Maybe you could put the same symbols on the clues ? Or align the clues with the play area ?

**Comment by tyrcho** [comment]
now I have enable color-blind mode !

![image](https://user-images.githubusercontent.com/700260/80138389-0b114280-85a5-11ea-9292-16624284d2b5.png)

It's still not obvious to me that R clue has something to do with the first 'o' playing area.

**Comment by tyrcho** [comment]
about marking that it's my turn, maybe some text in this area
![image](https://user-images.githubusercontent.com/700260/80138623-5af00980-85a5-11ea-9b2f-a9fe1662dd49.png)

similar to this one
![image](https://user-images.githubusercontent.com/700260/80138643-63484480-85a5-11ea-9afe-613dc9b3e310.png)

again, it's pretty obvious after the first game, but it would help a complete newcomer

**Comment by Zamiell** [comment]
> about marking that it's my turn, maybe some text in this area

the area in the screenshot is covered by the clue ui.
maybe text that appears on top and fades out?

**Comment by tyrcho** [comment]
maybe some text under "give clue" ? the point is sometimes you are busy looking some rule, convention ... and you miss the animation. Then you look at the site and wonder who's turn it is.

**Comment by Zamiell** [comment]
theres no room for that in keldon mode, as you can see:

![image](https://user-images.githubusercontent.com/5511220/80142107-9fb17b80-8578-11ea-89b2-d22db8bc0f3d.png)

**Comment by rogers-j** [comment]
(Try not to have two issues in your issue. They are free.)

With colorblind mode on, every red card has its letter, right? So your only problem in this screenshot is that the *base* stack does not have a letter? That seems like something it would be easy for colorblind mode to change.

**Comment by rogers-j** [comment]
On the other hand, I am still not sure if this additional information would help. If there are no red cards played, then you would be able to verify this by seeing that none of the played cards have the letter R on them.

**Comment by Zamiell** [comment]
i think for simplicity ill just make the suit color match the color letter for non-dualcolor games

**Comment by rogers-j** [comment]
Don't they match? That doesn't seem like the problem here

**Comment by rogers-j** [comment]
My way seems far simpler. You just have to remove the special case that stops the colorblind letter appearing on stack bases.

**Comment by Zamiell** [comment]
@tyrcho what about this:

![image](https://user-images.githubusercontent.com/5511220/80821818-7a8bc100-8ba7-11ea-9eff-96b84702ba51.png)

**Comment by Zamiell** [comment]
or would you prefer that they are filled in with white

**Comment by tyrcho** [comment]
that would help a lot ! (pictogram + color)

**Comment by Zamiell** [comment]
they are kinda hard to see, but ok

**Comment by tyrcho** [comment]
What could help also, is to shift the colors and symbols since some are more similar than others.

For example:
1 - yellow triangle
2 - blue square
3 - red "Pi"
4 - green cross
5 - purple circle

**Comment by Zamiell** [comment]
the colors are in the order of the colors in the rainbow, i dont want to rearrange them

**Comment by Zamiell** [comment]
the symbols roughly match the suits in the vanilla edition of hanabi, so i dont want to arbitrarily reassign those either

**Comment by tyrcho** [comment]
for me it's actually very visible (black over color), but I'm also fine with white background or filling

**Comment by tyrcho** [comment]
well, in vanilla Hanabi there was White color which has different meaning here ...

**Comment by tyrcho** [comment]
anyways symbols in the clues would really help me !

**Comment by Zamiell** [comment]
indeed, white is just remapped to purple

**Comment by tyrcho** [comment]
a suggestion is to use more light and dark tones on similar colors (there are good resources on "color blind palette" on internet). 
For instance on hanabi.live : lighter yellow, darker green, lighter blue (purple already quite dark)

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-live/blob/master/public/js/src/data/colors.json

you need to specify exactly what you want

**Comment by rogers-j** [comment]
If you're going to the trouble of putting the suits there, why even have the background rounded rectangles?

e.g.
![image](https://user-images.githubusercontent.com/5349111/80852401-1388ff00-8bdd-11ea-8f89-af4726e40ace.png)

**Comment by Zamiell** [comment]
i filled them as white instead so that they match the numbers

**Comment by rogers-j** [comment]
Isn't that also what I did? 🙃

**Comment by Zamiell** [comment]
the opposite

**Comment by rogers-j** [comment]
Not a fan.
![color_suit_clue](https://user-images.githubusercontent.com/5349111/80852476-b80b4100-8bdd-11ea-8ef2-575f3cf46769.png)

**Comment by Zamiell** [comment]
@tyrcho what do you like better

**Comment by tyrcho** [comment]
I prefer the simplest one:

![image](https://user-images.githubusercontent.com/700260/80859698-03b3fe00-8c63-11ea-9a73-95cb23c7fc1e.png)

You could even simplify by removing the (brown ?) outline with rounded borders outside the color clue and make it all red, yellow ...

**Comment by tyrcho** [comment]
color suggestion to make them stand out more :

https://coolors.co/e60000-e6e600-00aa00-0055ff-8800aa

I checked on their color blind mode (the glasses) and for other kind of color blindness it looks fine too.

**Comment by tyrcho** [comment]
about removing the brown outline ... color blindness is related to the relative area of color spots, so making the spot slightly bigger with the relevant color also helps !

**Comment by Zamiell** [comment]
619b527e2a6d0cb4520c0db92c2e65ff0301c97b
those colors will be in the next update (wont be for a few days)

> about removing the brown outline ... color blindness is related to the relative area of color spots, so making the spot slightly bigger with the relevant color also helps !

i dont know what this means

**Comment by tyrcho** [comment]
thanks for the colors update !

sorry about my english ...
What I mean is that it's easier for me to see a larger spot of the same color. So replacing the brown outline
![image](https://user-images.githubusercontent.com/700260/81046668-30f9e980-8eb9-11ea-83fc-d3ad2c79a4e2.png)

with a full red clue would make it easier to see.

**Comment by Zamiell** [comment]
i can't remove the outline because then there is no indication of which button you have selected

**Comment by Zamiell** [comment]
going to close this now, open a new issue with any other suggestions beyond what is currently implemented
