### ISSUE TITLE
Turns Left Broken

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Zamiell/hanabi-live#978]
- **Case 1: Turns left does not count down while playing the last card**
Turn 72 (Turns left: 2)
![t72](https://user-images.githubusercontent.com/50160641/80169758-e35bc200-8618-11ea-9c7f-abb2ed9b1466.png)
Turn 73 (Turns left: 1)
![t73](https://user-images.githubusercontent.com/50160641/80169776-efe01a80-8618-11ea-892a-32b33d6b1d8a.png)
Turn 74 (Turns left: 1)
![t74](https://user-images.githubusercontent.com/50160641/80169790-f5d5fb80-8618-11ea-9560-52f18f54cc44.png)

- **Case 2: Incorrect turns left**
How can there be 4 turns left in 3p after drawing the last card?
![4 turns left in 3p](https://user-images.githubusercontent.com/50160641/80169916-464d5900-8619-11ea-8e08-ac8e4d93947d.png)

**Comment by Zamiell** [comment]
should be fixed on next server restart
