### ISSUE TITLE
a replay got buggy after I blindplayed bottom of the deck

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#980]

**Comment by padiwik** [comment]
do u mean a hypo?

**Comment by Zamiell** [comment]
https://discordapp.com/channels/140016142600241152/140016142600241152/703456302340374539

**Comment by padiwik** [comment]
Yeah now it's a slightly more helpful error in hypo:
> You cannot perform a game action in a shared replay.

**Comment by Zamiell** [comment]
padi can i close this? not sure how to repro

**Comment by Zamiell** [comment]
i think this should be fixed now
